### ISSUE TITLE
Duplicati 2 asks for a password for unencrypted backups

### ISSUE THREAD

**Issue by lucatrv** [duplicati/duplicati#1098]
I'm using Duplicati 2.0.0.60 on Windows 7 64-bit.
If I run commands such as "test" or "find" or "restore" on unencrypted backups, Duplicati asks for the password and I if I press "enter" I get "Empty passphrases are not allowed", the only way around is to explicitly pass the option "--no-encryption=true".
In my opinion empty password should be allowed and have the same effect as "--no-encryption=true". The same behavior (empty password = "--no-encryption=true") could be convenient also when performing a backup.
##

**Comment by dhobi** [comment]
:+1: 
Just stumbled across this one...thanks @lucatrv for the --no-encryption=true hint

**Comment by kenkendk** [comment]
This happens because the backup does not know what data you have in the store.

Duplicati defaults to encrypted backups, and it requires you to supply a passphrase to avoid accidentally storing unencrypted backups.

If I defer asking for the passphrase, you could get hanging scripts when running a scheduled backup task.

**Comment by dhobi** [comment]
I see your point and it makes completely sense but only in the context of  a backup imho. In a "restore" context I would at least expect a more detailed error message than just "not allowed". 
Thanks anyway! :)
Daniel

**Comment by olfMombach** [comment]
I just stumbled across this same issue. The error message is still the same, just as confusing...
