### ISSUE TITLE
Gentoo Ebuild

### ISSUE THREAD

**Issue by necrose99** [duplicati/duplicati#1141]
http://sources.gentoo.org/cgi-bin/viewvc.cgi/gentoo-x86/dev-dotnet/mono-zeroconf/mono-zeroconf-0.9.0.ebuild?view=log
I reported the bug for duplicati to gentoo , however using the ebuild above (template)  I may be able to create an alpha ebuild --- it may not work but the devs @ Gentoo might be able to patch it and get duplicati   on repos sooner.....

I just need to know Linux build /Run-time depends...  
typically one can take Debian or red-hat and with some searching eliminate or find ones with Gentoo parity....
##

**Comment by fritteli** [comment]
I have created an ebuild for version 1.3.4 and one for version 2.0.1.11, to be found in my gentoo-overlay either at https://gittr.ch/linux/gentoo-overlay/tree/master/app-backup/duplicati or on github at https://github.com/fritteli/gentoo-overlay/tree/master/app-backup/duplicati

The 1.3.4 gives me errors at runtime, and I haven't really tested the 2.0 version, because it's experimental anyway.

If anyone is interested, you can send be pull requests to improve the ebuilds.

**Comment by fritteli** [comment]
Just for future reference: This is the link to the Gentoo Bugzilla bug: https://bugs.gentoo.org/show_bug.cgi?id=522374
