### ISSUE TITLE
large backups slow way down partway through (with new duplicati)

### ISSUE THREAD

**Issue by angelic** [duplicati/duplicati#1215]
I have a backup that's about 2.21 TB and 530,000 files. I'm backing up from one Debian server to another on a local LAN over a gigabit line, using the command line, 7z, dblock-size of 200 mb, and ssh. It seems to go fine until it gets down to about 1.2 TB (taking a few days to get there). Now it's going super slow and has taken a couple weeks to get down to 1.02 TB (308,000 files left). It seems like it's going to take another 2 or 3 months to finish. I'm using Duplicati 2.0.0.73 and Mono 3.10.0.
##

**Comment by rocifier** [comment]
angelic, is this on a continuous run?

**Comment by angelic** [comment]
This is on my initial backup.

**Comment by kenkendk** [comment]
Are you using an SSD disk or a spinning disk for storing the SQLite database?

I would expect the SQLite database to perform fine even for large datasets, but a spinning disk might introduce some lookup delays.

A quick-fix would be to use a larger blocksize, as that reduces the pressure on the database and works better if most files are larger than the blocksize. You could probably go from the default --blocksize=10kb to --blocksize=1mb, that should reduce the number of records in the SQLite database significantly.

Unfortunately, you need to start over to make that change.

**Comment by agrajaghh** [comment]
@kenkendk just a quick idea for the future: What do you think about adapting the blocksize automatically at the creation of a backup job? It could be done by looking at the overall size of the backup (quite easy to implement I guess) or scanning all the files and calculate the overhead to chose a blocksize which limits the overhead to < 1% (don't know which number makes sense) (probably harder to implement). Should I open another ticket for that or do you think thats not a good idea?

I know this adapting doesn't produce good results when you add (or remove) sigificantly data to the backup later, but I guess for most users the size of the backup doesn't change that much. It should produce better results than a standard value for all users I guess...

**Comment by kenkendk** [comment]
@agrajaghh The problem is that there is no correlation between hashes for blocks of different sizes.
That means that if you have a 20kb file, and record the hashes for two 10kb block, those hashes are useless if you only have the hash for a 20kb block.

You can analyze the current data and make a good guess, but this helps very little if the user adds a large folder to the backup sources after you have determined the size. It is possible to use multiple blocksizes, but the code is not written to handle it. Also, with multiple blocksizes, some deduplication may be missed.

For the "adaptive blocksize" you can choose individual block sizes for each file, possibly based on the file size. If you decide to change the block size for a file, you can upload a new copy of the file, and thus be fully flexible.

**Comment by rocifier** [comment]
I don't know if you realize, but the block size default would be overridden to be 1mb in Duplicati.Main.Options:BlockSize()

**Comment by rocifier** [comment]
Nevermind, that's VolumeSize() was looking at the wrong method.

**Comment by agrajaghh** [comment]
@kenkendk you're right, calculating the overhead doesn't make sense. The relative amout stays the same anyway, not depending on the backup size.
But I still think it might be a good idea to improve the backup speed by increasing the blocksize at job creation time if the backup size is already large. I know this doesn't help if you add a large folder afterwards. But it makes sense to use a differnet blocksize for a 5GB backup then for a 500GB backup job...

**Comment by angelic** [comment]
@kenkendk This is on spinning disks in a ReadyNas 516, spinning disks in a RAID array.  I have a blocksize of 200mb, with a mixture of large files and small files.

**Comment by kenkendk** [comment]
There is another discussion of this issue here:
https://groups.google.com/forum/#!topic/duplicati/06GNieZ6Em8

The suggestion there is to set --old-lookup-memory-defaults="1", so there is an in-memory cache of the database lookup tables. This has no measureable speed effects in my test setup with an SSD disk. But it is possible that the SQLite implementation is too conservative when storing the lookup tree in memory and this causes the slowdown on spinning disks when it has to load the lookup data.

**Comment by ironjohn** [comment]
In my experience with other backup software we have seen slowdowns with destination folders containing thousands of individual files.  One preventative step take is to store backed up data in subfolders, creating a new one every XXXX number of files.  This could be adjusted with a command line option, but really just setting the number of files per subfolder to 1000 in code would get the job done.  I'll repost this comment as an enhancement suggestion.
