### ISSUE TITLE
Support for Office365 OneDrive accounts

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#1244]
The Office365 accounts with OneDrive needs a special OAuth flow, going through Azure AD.

**Comment by TimoD** [comment]
Hello,

I receive an exception trying to backup on OneDrive:

Failed: Der Remoteserver hat einen Fehler zurückgegeben: (413) Request Entity Too Large.
Details: System.Net.WebException: Der Remoteserver hat einen Fehler zurückgegeben: (413) Request Entity Too Large.
   bei Duplicati.Library.Main.Operation.BackupHandler.HandleFilesystemEntry(String path, FileAttributes attributes)
   bei Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
   bei Duplicati.Library.Main.Controller.<Backup>c__AnonStorey0.<>m__0(BackupResults result)
   bei Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, Action`1 method)

Is this because of the mentioned OAuth-handling for Office365-accounts? I thought about, because the error occured when my free space is full and only 1 TB is left on my OneDrive now. If so, when will there be a solution?

Thanks,
Timo

**Comment by TimoD** [comment]
Hm, after I read elsewhere that OneDrive has a 100 MB file size limit, I tested with 99 MB file size instead of 100 MB which I choose first. The backup is working now.

**Comment by wadami** [comment]
I'm also interested in the support for Office365 accounts, since the company I work for is providing OneDrive for Business (OD4B) account to store backups.

**Comment by m1r4c** [comment]
Also voting for this feature, especially now that microsoft is offering unlimited storage for office365 customers.

**Comment by FootStark** [comment]
A OneDrive for Business backend has now been added and is available to test in build [Canary_v2.1.0.9](https://github.com/duplicati/duplicati/releases/tag/v2.0.1.9-2.0.1.9_canary_2016-03-26).
