### ISSUE TITLE
VSS on Windows 8.1, Duplicati 2.0.0.73

### ISSUE THREAD

**Issue by go-vegan** [duplicati/duplicati#1248]
First, I've read similar reports, but they all indicate that the problem is resolved in the latest Duplicati, but for me it isn't.

Here is the error:

Failed to create a snapshot: Alphaleonis.Win32.Vss.VssUnexpectedProviderErrorException: The provider returned an unexpected error code.
at Alphaleonis.Win32.Vss.VssBackupComponents.IsVolumeSupported(String volumeName)
at Duplicati.Library.Snapshots.WindowsSnapshot..ctor(String[] sourcepaths, Dictionary'2 options)
at Duplicati.Library.Main.Operation.BackupHandler.GetSnapshot(String[] sources, Options options, ILogWriter log) => Alphaleonis.Win32.Vss.VssUnexpectedProviderErrorException: The provider returned an unexpected error code.
at Alphaleonis.Win32.Vss.VssBackupComponents.IsVolumeSupported(String volumeName)
at Duplicati.Library.Snapshots.WindowsSnapshot..ctor(String[] sourcepaths, Dictionary'2 options)
at Duplicati.Library.Main.Operation.BackupHandler.GetSnapshot(String[] sources, Options options, ILogWriter log)]
Errors: []

I have the following Microsoft Visual C++ Redistributables installed (both x86 and x64 versions)
8.0.61001
8.0.59193
8.0.59192
8.0.61000
9.0.30729.4148
9.0.30729.6161
10.0.40219
11.0.61030.0

I'm running Duplicati through the Task Scheduler with elevated privileges.
##

**Comment by David-Pa** [comment]
A hint that may shed some light on the problem. I'm currently running 4 backups, all of them use the VSS switch. I noticed that the first backup that it run after starting the computer does not report this problem, but all subsequent backups do. Perhaps the first backup does not properly close the handle, so subsequent backups fails to obtain it?

**Comment by David-Pa** [comment]
I don't want to sound pushy, but is there a chance this issue is being worked on?
Currently I can't backup my Firefox profile directory, because the files are locked and VSS isn't working... (Duplicati 2.0.0.82)


Warnings: [Failed to create a snapshot: Alphaleonis.Win32.Vss.VssSnapshotSetInProgressException: The creation of a shadow copy is already in progress.
at Alphaleonis.Win32.Vss.VssBackupComponents.StartSnapshotSet()
at Duplicati.Library.Snapshots.WindowsSnapshot..ctor(String[] sourcepaths, Dictionary`2 options)
at Duplicati.Library.Main.Operation.BackupHandler.GetSnapshot(String[] sources, Options options, ILogWriter log) => Alphaleonis.Win32.Vss.VssSnapshotSetInProgressException: The creation of a shadow copy is already in progress.
at Alphaleonis.Win32.Vss.VssBackupComponents.StartSnapshotSet()
at Duplicati.Library.Snapshots.WindowsSnapshot..ctor(String[] sourcepaths, Dictionary`2 options)
at Duplicati.Library.Main.Operation.BackupHandler.GetSnapshot(String[] sources, Options options, ILogWriter log)

**Comment by haweig** [comment]
I face the same issue with Duplicati 2.0.0.85 on Windows 8.1 when running duplicati.server from task scheduler with administrator permissions. It seems that the first run after a reboot is fine but all subsequest runs cannot create shadow copies.

The error message in the log is:

Warnings: [Failed to create a snapshot: Alphaleonis.Win32.Vss.VssSnapshotSetInProgressException: The creation of a shadow copy is already in progress.
bei Alphaleonis.Win32.Vss.VssBackupComponents.StartSnapshotSet()
bei Duplicati.Library.Snapshots.WindowsSnapshot..ctor(String[] sourcepaths, Dictionary`2 options)
bei Duplicati.Library.Main.Operation.BackupHandler.GetSnapshot(String[] sources, Options options, ILogWriter log) => The creation of a shadow copy is already in progress., Failed to process path: c:\users\Harald\ntuser.dat.LOG2 => Der Prozess kann nicht auf die Datei "c:\users\Harald\ntuser.dat.LOG2" zugreifen, da sie von einem anderen Prozess verwendet wird.

**Comment by David-Pa** [comment]
Thank you Duplicati... (NOT!)
Today I had to restore my Firefox profile directory, and it was only partially restored, because some files were locked during the backup, and Duplicati didn't use VSS :(

I can live with the awful interface, but what is it worth if you can't trust it to restore your files when you need them?

**Comment by ts678** [comment]
I'm looking mainly at the original issue here, because "The creation of a shadow copy is already in progress." is a different thing, sometimes entirely proper if it is accurate. It does potentially connect to the original issue if the interference was from Duplicati.

Probably the thing to do for either would have been a `vssadmin list shadows` before, during, and after the Duplicati backup. Current behavior is that the Duplicati snapshot only exists while Duplicati needs it in order to do the backup. It goes away later.

I considered seeing if I could put 2.0.0.73 on Windows 11 to see how reproducible this is, but [2.0.0.73_preview_2014-11-11](https://github.com/duplicati/duplicati/releases/tag/v2.0.0.73-2.0.0.73_preview_2014-11-11) is seemingly no longer available as a binary. The changelog goes back that far, but has no note obviously connected to run-once.

I looked through the source commit history for some relevant files. I am not a VSS expert, but the developer in 2015 time was presumably quite practiced at it, as the original Duplicati prior to Duplicati 2 had also supported VSS using very similar facilities.

Issue seems to have gone away fairly fast. I looked through all of the open and closed issues with titles about VSS or snapshot. There's another 2015 sighting in the link above with a bit more information. Storage Spaces seemed implicated then disproven.

[IsVolumeSupported(String)](https://alphavss.alphaleonis.com/api/Alphaleonis.Win32.Vss.IVssBackupComponents.html#Alphaleonis_Win32_Vss_IVssBackupComponents_IsVolumeSupported_System_String_) as seen in some stacks does suggest that VSS dislikes something about a specific volume, but what?
Sometimes the event log (most likely Application) gets VSS information, but we're not likely to be to get those old records now.

I don't think this issue is actionable now. VSS these days works well repeatedly. I was doing hourly VSS backups for a long time.

This interesting mystery will probably never get solved, but it seems gone. This issue will close unless further posts keep it open.
