### ISSUE TITLE
Trying to create throttle settings in 2.0

### ISSUE THREAD

**Issue by rocifier** [duplicati/duplicati#1261]
Hi, I've got a nice dialog for throttle settings showing and submitting the following json data to the server:

"data": {
    "max-upload-speed": "50"
}

That seems to come in and serialize fine, but of course it's not throttling. I don't really know if this is the correct settings variable or not, and what's happening behind the serialization. It seems that the variable doesn't just need to be set in a class, but ApplicationSettings.m_values needs its max-upload-speed item set. This is only done once when the server starts. How can I properly set the m_values dictionary item when calling SetServerOptions?
##

**Comment by rocifier** [comment]
Javascript code:

    $('#throttle-dialog').dialog({
        autoOpen: false,
        width: $('body').width > 320 ? 320 : 600,
        height: 250, 
        modal: true,
        closeOnEscape: true,
        buttons: [
            { text: 'Cancel', click: function(event, ui) {
                $(this).dialog('close');
            }},
            { text: 'submit', click: function(event, ui) {
			
				var maxuploadPerSecond = $('input[name=max-upload-speed]:checked', '#throttle-dialog-form').val();
				var data = {};
				data['max-upload-speed'] = maxuploadPerSecond;

                var dlg = $(this);
                APP_DATA.callServer(
                    {'action': 'set-server-options', 'data': JSON.stringify(data), 'HTTP_METHOD': 'POST'},
                    function() {
                        dlg.dialog('close');
                    },
                    function(a,b,msg) {
                        alert('Failed to save throttle data: ' + msg);
                    }
                );
				
            }}
        ]
    });

**Comment by rocifier** [comment]
Nevermind, that code is all correct. It was because I had commented some other code out in the server. Please close this issue :)

**Comment by rocifier** [comment]
Actually, 'max-upload-speed' seems to be a red-herring. It's an option that's not used anywhere. I commented it out in favor of the setting 'throttle-upload'.

**Comment by rocifier** [comment]
@kenkendk able to offer any insights here?

**Comment by kenkendk** [comment]
Yes, there are multiple things going on here.

I agree there is some name confusion going on, the call to set "ApplicationSettings" should not be called "set-server-options".

ApplicationSettings are system-wide settings. Some of these system-wide settings are applied to the backup/restore/list tasks, others (such as the server passphrase) are used elsewhere.
See: https://github.com/duplicati/duplicati/blob/master/Duplicati/Server/Runner.cs#L339

As for the crash, it should not happen because the m_values dictionary is filled with nulls during initialization. Can you reproduce the crash somehow?

The max-upload-speed and corresponding property DownloadSpeedLimit is used in the LiveControls class:
https://github.com/duplicati/duplicati/blob/master/Duplicati/Server/LiveControls.cs#L187

This means that if you write the upload speed, this will be applied to tasks started AFTER you apply the changes.

Some logic is required to get the values set DURING the run.

First thing to decide is how the speed should be persisted. Should there be one single upload speed that you set, and then it just stays that way? Or should there be a "basic" and "current" speed selector, where current is only active until restart?

If you want to go with a single value, then it could be as simple as adding some code to update the LiveControl instance after saving here:
https://github.com/duplicati/duplicati/blob/master/Duplicati/Server/Database/ApplicationSettings.cs#L96

ie (not tested):
```
private void SaveSettings()
{
    m_connection.SetSettings(
        from n in m_values
        select (Duplicati.Server.Serialization.Interface.ISetting)new Setting() {
            Filter = "",
            Name = n.Key,
            Value = n.Value
        }, Database.Connection.APP_SETTINGS_ID);

    long? uploadSpeed = null;
    try 
    { 
        if (!string.IsNullOrWhiteSpace(this.UploadSpeedLimit))
            uploadSpeed = Library.Utility.Sizeparser.ParseSize(this.UploadSpeedLimit);
    } 
    catch 
    {
    }

    Server.Program.LiveControl.UploadLimit = uploadSpeed;
}
```

**Comment by kenkendk** [comment]
Sorry, it is applied to LiveControls during startup, so any changes only take affect AFTER restart, not when starting a new task as I wrote.

**Comment by rocifier** [comment]
But how do I access Program.LiveControl from the ThrottledStream? It needs to be able to fetch the current upload throttle in realtime

**Comment by kenkendk** [comment]
It appears that the infrastructure for this is not in place.

When you set the UploadLimit as noted above, it will trigger the ThrottleSpeedChanged event here:
https://github.com/duplicati/duplicati/blob/master/Duplicati/Server/Program.cs#L512

Then you can do something like:
```
var task = Program.WorkThread.CurrentTask as IRunnerData;
if (task != null) {
    task.SetSpeedLimit(Program.LiveControl.UploadLimit ?? 0, Program.LiveControl.DownloadLimit ?? 0);
}
```

You need to add the method to IRunnerData and RunnerData:
https://github.com/duplicati/duplicati/blob/master/Duplicati/Server/Runner.cs#L27

It could look like:
```
public void SetSpeedLimit(long uploadlimit, long downloadlimit)
{
    var c = Controller;
    if (c != null)
       c.SetSpeedLimit(uploadlimit, downloadlimit);
}
```

Then you need to add the method in the controller:
https://github.com/duplicati/duplicati/blob/master/Duplicati/Library/Main/Controller.cs#L599

It could look like:
```
public void SetSpeedLimit(long uploadLimit, long downloadLimit)
{
    var ct = m_currentTask;
    if (ct != null && m_options != null)
    {
        m_options.MaxDownloadPrSecond = downloadLimit;
        m_options.MaxUploadPrSecond = uploadLimit;
        ct.UpdateSpeedLimit();
    }
}
```

You need to add this to the ITaskControl interface and the implementation:
https://github.com/duplicati/duplicati/blob/master/Duplicati/Library/Main/ResultClasses.cs#L167
and
https://github.com/duplicati/duplicati/blob/master/Duplicati/Library/Main/ResultClasses.cs#L504

I suggest adding a new event in the BasicResults class, and then subscribing to that in the BackendManager Put/Get events, because you can then get a reference to the current ThrottledStream instance such that you can change the ReadSpeed and WriteSpeed on it.

**Comment by rocifier** [comment]
Wow thanks for that, I don't think I would have figured any of that out. So the idea at the end of that calling chain is to modify the throttled steam.. would that work because the event that goes in BasicResults would be called from another thread, which would be able to go in and change the ThrottledStream in spite of the BackendManager code being frozen by the synchronous upload or download thread?

**Comment by rocifier** [comment]
@kenkendk  I've almost got this working. I'm just trying to figure out how to access the results class from the DoGet() and DoPut() methods so I can handle the event that's in the BasicResults class. It seems to pass in the stats writer to the backend, but not the results parent object.

**Comment by rocifier** [comment]
Cool well this seems to be working. I have to be careful with the way that it calculates speed, because if you throttle from one speed to another, it takes the past transfer history for that file into account to calculate the current speed. Really it needs to calculate it as a moving window. However, I've got a bit of a hack for it. Will post all my code sometime in the next few days.

**Comment by kenkendk** [comment]
Yes, all my "window code" is a bit too crude.
The right way would be to use "exponential weighted moving average" to compute the current speed.
It would also be very simple to reset if this was done with EWMA.

I am looking very much forward to the post.

**Comment by rocifier** [comment]
You can see my commercial fork here https://github.com/rocifier/duplicati
Sorry that I've butchered your project so much.
I haven't completed your recommendation for pause refactoring yet.
Throttle works but is pretty hacked, and the dialog box is near useless if you're not on standard ADSL uploading to the cloud.
I missed some of your recent changes in the last couple of days. But I tried to include everything I consider important to my version.
