### ISSUE TITLE
feature request: "Dismiss All"

### ISSUE THREAD

**Issue by David-Pa** [duplicati/duplicati#1268]
I have several backups set, all of them using the "--snapshot-policy=on" switch, which currently emits a warning (#1248). So once a day I have to manually dismiss all the warning notifications. A single "Dismiss All" button would be helpful in this situation.
Thanks!
##

**Comment by ts678** [comment]
[added a dismiss-all button to the notification area #3158](https://github.com/duplicati/duplicati/pull/3158)
[made dismiss all option only show up with 2 or more notifications #3164](https://github.com/duplicati/duplicati/pull/3164)

Tested with some warnings made from backup of Duplicati's `control_dir_v2\lock_v2` file. After two runs of that, it looks like this:

![image](https://user-images.githubusercontent.com/40771998/102828850-b8965900-43b3-11eb-9908-cb9be1a5122a.png)

A `Dismiss all` click clears all three popups. This issue seems resolved.

**Comment by warwickmm** [comment]
Thanks @ts678.
