### ISSUE TITLE
Much slower files scanning with 2.0.0.81

### ISSUE THREAD

**Issue by David-Pa** [duplicati/duplicati#1288]
Not only it now takes ages to just _scan_ the files on my local drive to determine which has changed, the CPU is at 100% during the entire process...

This was not the case with 2.0.0.79.
##

**Comment by David-Pa** [comment]
Unfortunately I cannot go back to 2.0.0.79, I get this error:

System.Exception:
The database has version 2 but the largest supported version is 1.
This is likely caused by upgrading to a newer version and then downgrading.

Please can you issue a fix quickly? I cannot perform backups at this state... :(

**Comment by kenkendk** [comment]
Hi.

The first run is slower, because the new timestamp storage needs to be updated. 
After this, speed should be the same as for 2.0.0.79 (it is in my tests).

If you wish to go back to 2.0.0.79, look into the ~/.config/Duplicati folder where you should see the backup of the database as it was before the upgrade.
