### ISSUE TITLE
Problems with the options not being taken into account

### ISSUE THREAD

**Issue by marcal** [duplicati/duplicati#1343]
Hello,

I have tried to use some options in the advanced options (in the program, not in the job) (they are put in the options of the program so I guess they must be filled there.
--7z-compression-fast-algorithm=True
--7z-compression-level=1
--snapshot-policy=required

In the job I have put the option 
--compression-module=7z

When I launch the job, the 3 options are not used (my job works with a very low speedin the local network).
I have started the GUI icon normally (not as Administrator) and the job has no problem starting.
If I put the 3 options in the options of the job, the job can't start (it is normal as the GUI is not started as Administrator). If I start the job as Administrator, the job will start normally (so a snapshot can start).
When the job is started it will be a lot faster (so the option compression -level and algorithm are used).
Perhaps you could say when an option is not used correctly (for example when it will be ignored).

MArc
##

**Comment by ltGuillaume** [comment]
Same here, global advanced options seem to be discarded (sometimes?). It would be a good idea to put the actually used options inside the log. This will probably be the case already when enabling the debug/verbose switch, but I think it would be best to include it in the normal output, in order to get some confirmation that the options are actually "activated".
