### ISSUE TITLE
.config folder too large, can it be moved?

### ISSUE THREAD

**Issue by gfalgiano** [duplicati/duplicati#1352]
I'm running Duplicati 2 on a Synology NAS and before I can backup a full 1TB, I fill up the root directory in the system with what I assume is the Duplicati database. I've read that it is really difficult to expand the root volume on a Synology, so I was wondering if the .config folder for Duplicati could be moved to another location, just like what was recommended for the temp directory?

Really excited for a Synology Duplicati app in the future :)
##

**Comment by kenkendk** [comment]
Yes.

You can use the commandline option --dbpath to point to the right database.

If you are using the server/gui, then there is a database as well (which should be small).
That database can be moved by setting the environment variable "DUPLICATI_HOME" to the folder you want to use. The database used by the GUI may contain paths pointing to the .config folder, so you need to edit it, or use the --dbpath option inside the job config.

**Comment by cbi78** [comment]
Hi, I was running into the same issue. Wasn't it possible to configure the default path for all backup database files at a single place instead of using the job config? Also, especially for the case it's running on a Synology, it would be good to have at least a warning during installation to change the path.
Thanks
