### ISSUE TITLE
Duplicati self cannibalism

### ISSUE THREAD

**Issue by David-Pa** [duplicati/duplicati#1362]
Once a few weeks, Duplicati decides that some of the valid backup files are redundant, and deletes them from the server.

As a result, the backup becomes corrupt, and Duplicati attempt to repair it.

Repair fails with messages such as:
'''Failed to perform cleanup for missing file: duplicati-b5fd7367ee13f43a9a359dcaf616670c6.dblock.7z.aes, message: Repair not possible, missing 32 blocks!!!'''

It then gets stuck for hours on 100% CPU until the process is killed or the computer is shut down.

The only way to bypass this problem is to delete the backup files from the remote server, then delete the local database, and perform the backup from scratch.

This has many disadvantages, such as losing the entire backup history, for example when keeping files for 30 days. For big backups it means remaining vulnerable for a long period of time until the backup is fully uploaded again. Not to mention the manual work involved, and that I have to periodically launch the visual interface in order to even detect such failures.

As a backup software I am expecting more reliability.
##

**Comment by ulicky** [comment]
I experienced this problem to, what helped me was to turn off autocompact. During autocompact some files are deleted and as result backup is corrupted. With autocompact turned off it is not happening.

**Comment by David-Pa** [comment]
Thanks, I will give it a try!

**Comment by kenkendk** [comment]
I agree that it should not break itself. The idea is to have a setup-and-forget approach that "just works".
But since 2.0 has some issues reported, I am reluctant to recommend using it for production. On the other hand, I cannot work on both 2.0 and 1.3, leaving things in an in-between state.

Are you using zip or 7z? I know there are some issues with 7z creating too small files.

**Comment by David-Pa** [comment]
Yes, I'm using 7zip.

**Comment by ulicky** [comment]
Me too.

**Comment by realrs** [comment]
@kenkendk did you know the reason?

**Comment by kenkendk** [comment]
@realrs: Yes, the issue is that the LZMA2 engine needs large buffers (50mb) to utilize multicore.
There is no way of knowing what on-disk size the buffer data will be. To ensure that 7z does not exceed the volume size limit, it stops processing prematurely.

In some cases this causes small files to be written, which makes the compacting procedure think that it can improve the storage space.

Unfortunately, when the compacting process rewrites the 7z files, they do not become smaller.

I recommend either turning off compacting or not using 7z for now.

**Comment by ulicky** [comment]
So please when 7z and compacting is selected for backup, throw error, or inform on gui, that this combination could lead in special cases to backup corruption - to protect other users from this issue.

**Comment by robsonsobral** [comment]
Or at least says that 7z is experimental and should be used only for tests.

**Comment by robsonsobral** [comment]
(well, the 2.0 version should be only for tests, I guess...)
