### ISSUE TITLE
Failed to restore a file

### ISSUE THREAD

**Issue by PMassicotte** [duplicati/duplicati#1373]
This morning I was trying to restore a file named "simul_2015-01-22_16:57:55.Rdata"

For some reasons, Duplicati 2.0.0.85- 2.0.0.85_preview_2015-03-07 was giving me a positive message saying the file was restored. However, I could not find it. I tried on other files and it works perfectly fine. Hence, I suspect it is related to the "weird" file name I'm using.
##

**Comment by kenkendk** [comment]
Is this on Windows?
If yes, I suspect that the file is named "simul_2015-01-22_16" but i zero bytes, because the data is written as an alternate data stream: http://blogs.technet.com/b/askcore/archive/2013/03/24/alternate-data-streams-in-ntfs.aspx

**Comment by Persican** [comment]
Sorry, I forgot to mention I'm using mint 17.



Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=ta&cv=6.3.14&pv=5.1]

On Mon, May 11, 2015 at 1:01 PM, Kenneth Skovhede < notifications@github.com [notifications@github.com] > wrote:
Is this on Windows?
If yes, I suspect that the file is named "simul_2015-01-22_16" but i zero bytes,
because the data is written as an alternate data stream: 
http://blogs.technet.com/b/askcore/archive/2013/03/24/alternate-data-streams-in-ntfs.aspx
[http://blogs.technet.com/b/askcore/archive/2013/03/24/alternate-data-streams-in-ntfs.aspx]

—
Reply to this email directly or view it on GitHub
[https://github.com/duplicati/duplicati/issues/1373#issuecomment-100869107] .[https://github.com/notifications/beacon/AET1NRZPD5uNQnTuQmaM4nDqplxYEV9cks5oIIN0gaJpZM4ESGkK.gif]

**Comment by Persican** [comment]
I forgot to mention its a ntfsa partition



Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=ta&cv=6.3.14&pv=5.1]

On Mon, May 11, 2015 at 1:01 PM, Kenneth Skovhede < notifications@github.com [notifications@github.com] > wrote:
Is this on Windows?
If yes, I suspect that the file is named "simul_2015-01-22_16" but i zero bytes,
because the data is written as an alternate data stream: 
http://blogs.technet.com/b/askcore/archive/2013/03/24/alternate-data-streams-in-ntfs.aspx
[http://blogs.technet.com/b/askcore/archive/2013/03/24/alternate-data-streams-in-ntfs.aspx]

—
Reply to this email directly or view it on GitHub
[https://github.com/duplicati/duplicati/issues/1373#issuecomment-100869107] .[https://github.com/notifications/beacon/AET1NRZPD5uNQnTuQmaM4nDqplxYEV9cks5oIIN0gaJpZM4ESGkK.gif]
