### ISSUE TITLE
Duplicati fails to back up due to "The process cannot access the file because it is being used by another process" error

### ISSUE THREAD

**Issue by jarmo** [duplicati/duplicati#1388]
I've been using Duplicati commandline for a while now (version 2.0.0.85- 2.0.0.85_preview_2015-03-07), but it started to fail at one point with the following error message:

```
Failed: database is locked
database is locked
Details: System.Data.SQLite.SQLiteException (0x80004005): database is locked
database is locked
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at Duplicati.Library.Main.Database.LocalDatabase.LogRemoteOperation(String operation, String path, String data, IDbTransaction transaction)
   at Duplicati.Library.Main.BackendManager.DatabaseCollector.FlushDbMessages(LocalDatabase db, IDbTransaction transaction)
   at Duplicati.Library.Main.Operation.FilelistProcessor.RemoteListAnalysis(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log)
   at Duplicati.Library.Main.Operation.FilelistProcessor.VerifyRemoteList(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log)
   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
   at Duplicati.Library.Main.Controller.<Backup>c__AnonStorey0.<>m__0(BackupResults result)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, Action`1 method)
```

Restarting duplicati or even OS didn't make a difference. After i deleted local duplicati db file and tried again, i'm getting this error every time:

```
Failed: The process cannot access the file because it is being used by another process.
Details: System.IO.IOException: The process cannot access the file because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at Duplicati.Library.Main.Operation.RepairHandler.Run()
   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
   at Duplicati.Library.Main.Controller.<Backup>c__AnonStorey0.<>m__0(BackupResults result)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, Action`1 method)
```

OS is Windows 8.1.
##

**Comment by chicco27** [comment]
I'have the same problem on version 2.0.0.87- 2.0.0.87_preview_2015-07-03. OS is Windows 7 Pro.

**Comment by kenkendk** [comment]
Can you find out which process locked the file?

Try this:
http://superuser.com/questions/117902/easy-way-to-find-out-which-process-is-locking-a-file-or-folder-in-windows

**Comment by chicco27** [comment]
If you mean the process that use the file System.Data.SQLite are that:
- DBRCrawler.exe
- explorer.exe
- procexp64.exe
- Duplicati.GUI.TrayIcon.exe

**Comment by jarmo** [comment]
In my case it had to be duplicati itself, because problem persisted even after system restart. Although I can't prove it anymore because I've not had this problem anymore.

**Comment by kenkendk** [comment]
The file DBRCrawler.exe seems to be a Dell Backup component:
http://systemexplorer.net/file-database/file/dbrcrawler-exe

If that process is trying to make a backup, I think that could cause the problem.

**Comment by jarmo** [comment]
I've started getting `database is locked` exception again. No process has any handles open to database after Duplicati is closed. It doesn't matter if I restart OS or Duplicati - it's always locked.

**Comment by jarmo** [comment]
In addition repair command doesn't help and if I remove the local database and start backup again, then I will get that `The process cannot access the file because it is being used by another process.` error although there's no other process accessing according to `Process Explorer`.

In other words, when this problem occurs, it is reproducible and the only solution is to create full backup from scratch.

**Comment by solemgar** [comment]
I am having the same issue as well.

**Comment by CONSULitAS** [comment]
me too :-(

**Comment by ute-arbeit** [comment]
Same for me on Firefox / Windows 10. I never achieved to upload one backup to Google Drive nor MS OneDrive. The messages are:
```
Failed to process path: C:\Users\xxx\AppData\Roaming\Thunderbird\Profiles\ngf7tlvk.default\parent.lock
System.IO.IOException: Der Prozess kann nicht auf die Datei "C:\Users\xxx\AppData\Roaming\Thunderbird\Profiles\ngf7tlvk.default\parent.lock" zugreifen, da sie von einem anderen Prozess verwendet wird.
bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
bei System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
bei System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
bei Duplicati.Library.Snapshots.SystemIOWindows.FileOpenRead(String path)
bei Duplicati.Library.Main.Operation.BackupHandler.HandleFilesystemEntry(ISnapshotService snapshot, BackendManager backend, String path, FileAttributes attributes)
```

Then two other identical messages with two other files
`Failed to process path: C:\Users\xxx\AppData\Roaming\Mozilla\Firefox\Profiles\iuj1j2ki.default\parent.lock`
and
`Failed to process path: C:\Users\xxx\AppData\Roaming\Duplicati\control_dir_v2\lock_v2`
The two `parent.lock` files are locked by FireFox and ThunderBird respectively, the `lock_v2` file is locked by the only instance of `Duplicati.GUI.TrayIcon.exe`.
Duplicati version is 2.0.1.9- 2.0.1.9_canary_2016-03-26.

Using Chrome instead of FireFox yields the same message about `lock_v2` being locked by another process.
System reboot did not help - same exception.

**Comment by ute-arbeit** [comment]
Same for me on Firefox / Windows 10. I never achieved to upload one backup to Google Drive nor MS OneDrive. The messages are:
```
Failed to process path: C:\Users\xxx\AppData\Roaming\Thunderbird\Profiles\ngf7tlvk.default\parent.lock
System.IO.IOException: Der Prozess kann nicht auf die Datei "C:\Users\xxx\AppData\Roaming\Thunderbird\Profiles\ngf7tlvk.default\parent.lock" zugreifen, da sie von einem anderen Prozess verwendet wird.
bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
bei System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
bei System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
bei Duplicati.Library.Snapshots.SystemIOWindows.FileOpenRead(String path)
bei Duplicati.Library.Main.Operation.BackupHandler.HandleFilesystemEntry(ISnapshotService snapshot, BackendManager backend, String path, FileAttributes attributes)
```

Then two other identical messages with two other files
`Failed to process path: C:\Users\xxx\AppData\Roaming\Mozilla\Firefox\Profiles\iuj1j2ki.default\parent.lock`
and
`Failed to process path: C:\Users\xxx\AppData\Roaming\Duplicati\control_dir_v2\lock_v2`
The two `parent.lock` files are locked by FireFox and ThunderBird respectively, the `lock_v2` file is locked by the only instance of `Duplicati.GUI.TrayIcon.exe`.
Duplicati version is 2.0.1.9- 2.0.1.9_canary_2016-03-26.

Using Chrome instead of FireFox yields the same message about `lock_v2` being locked by another process.
System reboot did not help - same exception.

**Comment by kenkendk** [comment]
@ute-arbeit your errors occur because something has locked the files and they cannot be read by Duplicati. The fix to this is to use VSS, which requires Duplicati to run as administrator.

The other issues are about Duplicati locking its own database, and then failing to run at all because it is locked.

**Comment by jarmo** [comment]
Closing this issue since haven't seen it recently.
