### ISSUE TITLE
Restore files & folders cannot handle UNC pathnames

### ISSUE THREAD

**Issue by haweig** [duplicati/duplicati#1401]
Hi,

I use Duplicati to save a network ressource. Unfortunately the restore dialog cannot handle UNC pathnames correctly. The directory structure is not recogniced and displayed correctly.

See attached image for an example:

![image](https://cloud.githubusercontent.com/assets/11524671/8402125/5880c31c-1e38-11e5-8a19-5e95e7c07234.png)

Hope this can be fixed.

Harald
##

**Comment by kenkendk** [comment]
What is this mounted as ? 
Is it a network drive that you mount?
Normally you cannot see network paths here.

**Comment by haweig** [comment]
Hi,

this is not mounted as network drive. I actually specified it as network 
UNC path in the backup configuration.

Backup works fine, but the restore does not recognice the directory 
structure in this case.

Regards,
Harald


Am 3. Juli 2015 20:30:42 schrieb Kenneth Skovhede <notifications@github.com>:

**Comment by ipitcher** [comment]
I'm not sure if this is necessarily that same issue, but since it's close enough and this issue is still open, I'll contribute my experience. Backups with more than one UNC path seem to work insofar as the files are backed up, but I get an error when I try to view the file tree when restoring.

The backup source data config:

![image](https://cloud.githubusercontent.com/assets/835717/21619243/d7236f42-d1bc-11e6-9b3c-ba9ac882203e.png)

The error:

![image](https://cloud.githubusercontent.com/assets/835717/21619183/9162473a-d1bc-11e6-824a-4475e9115274.png)

Chrome console after error is raised:

![image](https://cloud.githubusercontent.com/assets/835717/21619698/d60c3ed4-d1be-11e6-92fd-67063946507c.png)

When I click 'OK' I am presented with a single unnamed folder node, which produces the same error when the expand arrow is clicked. Interestingly, here is what happens when I search for files in that backup:

![image](https://cloud.githubusercontent.com/assets/835717/21619529/1310bec8-d1be-11e6-92b5-e118fe5e1eb3.png)

If I delete one of the UNC paths from the backup and run it again, I see the correct tree on the restore page, without any error, like so:

![image](https://cloud.githubusercontent.com/assets/835717/21619601/69d2a60e-d1be-11e6-9b96-cfe72b586354.png)

**Comment by kenkendk** [comment]
I did not check if this particular case was fixed, but I did improve the handling of UNC paths in the latest canary. Could you see if it is fixed:
https://github.com/duplicati/duplicati/releases/tag/v2.0.1.39-2.0.1.39_canary_2017-01-08

**Comment by ipitcher** [comment]
Yes, it is fixed for my particular case. Thank you very much!

**Comment by agrajaghh** [comment]
@haweig could you please check if your problem is solved with 2.0.1.39 as well? Thanks!

**Comment by kenkendk** [comment]
Closing for lack of feedback
