### ISSUE TITLE
dlist file name inconsistency

### ISSUE THREAD

**Issue by thekrugers** [duplicati/duplicati#1444]
Hi,

I just had an interesting one, here are two log entries:

2015/08/25, 11:07:51 PM
Message
scheduling missing file for deletion, currently listed as Uploading: duplicati-20150824T210010Z.dlist.zip.aes

2015/08/25, 11:39:42 PM
Message
Extra unknown file: duplicati-20150824T210011Z.dlist.zip.aes

So it seems the file was uploaded with a name based on a timestamp one second later than what the data in the local database records. Perhaps the timestamp is being recalculated instead of reused?

I've renamed duplicati-20150824T210011Z.dlist.zip.aes to 20150824T210010Z.dlist.zip.aes in my storage, I want to see tomorrow if my backup still fails.
##

**Comment by kenkendk** [comment]
The +1 second is a renaming rule. If an upload fails, Duplicati will always upload with a different filename. For dindex and dblock the names are random and have no meaning, so they just get a new name.
The dlist files are named by the time they were used, so new files get +1 second added to the name.

To get to the situation you have, I think there was an upload that failed (...10Z), so a new file was created as (...11Z) and uploaded. Since the database knows ...10Z but not ...11Z, there has to be some kind of rollback with the database.

The rollback usually happens if an error occurs, or the backup is terminated for some reason.
