### ISSUE TITLE
Can't browse a restore in the NGAX UI on Windows

### ISSUE THREAD

**Issue by nilayp** [duplicati/duplicati#1527]
I am backing up 100,000 files (30GB) to the Backblaze B2 service. The backup goes fine, but when I try to browse the restore - it doesn't list the individual files. (I tried this with a smaller backup set of 8,000 files - same error.)

My storage-url is: b2://b2demo/duplicati100k?auth-username=xxxx&auth-password=xxxx. I'm not using encryption.

<img width="776" alt="inner-windows-10" src="https://cloud.githubusercontent.com/assets/744246/12004256/d023ca7e-aafe-11e5-9a2c-99eb28e4c369.png">

I've also tried to list the files in the restore via the command line tool. It gives me an error: Cannot read while writing.

C:\Program Files\duplicati-2>Duplicati.CommandLine.exe find "b2://b2demo/duplicati100k?auth-username=xxxx&auth-password=xxxx" *

Enter encryption passphrase: 
No local database, accessing remote store
  Listing remote folder ...
  Downloading file (7.11 MB) ...

Cannot read while writing

**Comment by ingul-buz** [comment]
I noticed the UI problem, too. On the "Restore files" page you can't browse to file level or even into subfolders. It seems to be a glitch with the new NgAx theme, since the browsing works as expected with the old Greeno interface.

So, until that gets fixed, you can use the old interface as a workaround. Click the link "Change theme" on the bottom left corner, then select Greeno (either "Use as default" or "View now", whichever you like), and on that inteface you should be able to browse your backup down to file level again.

Your other problem I haven't come across, so can't help.

**Comment by nilayp** [comment]
Thanks for the tip! Browse restores via greeno works great.

**Comment by ingul-buz** [comment]
It seems that part of the file picker problem in "Restore files" dialog still seems to exist in NgAx, despite Kenneth's commit above. Now you can browse down to the file level, but you still can't **select** any of the files or even subfolders. The only thing you can select is the whole backup, so no partial restore is possible.

It doesn't seem to be a browser issue either, since you can make perfect file/folder selections when you create new backups or edit existing ones.

**Comment by kenkendk** [comment]
Is the error still on Windows ?

**Comment by ingul-buz** [comment]
Yes, Windows 7 and Duplicati 2.0.1.8.

**Comment by kenkendk** [comment]
Ok, I am re-opening and changing the title a bit

**Comment by ingul-buz** [comment]
I think I found the reason for not being able to select files or subfolders in the restore dialog. I tested another backup of mine, and to my surprise I was able to select anything with that one. The difference is that this backup only consists of files from a single drive/partition, whereas in my problem backup there are files from several drives.

![select](https://cloud.githubusercontent.com/assets/10701768/13998819/e1ad9494-f141-11e5-9c5c-aff1e11a7930.png)

So in Windows the "root node" doesn't get any name in case of a multi-drive backup, and that seems to prevent the selection of children nodes altogether. Unfortunately I'm not skilled enough in JavaScript in order to try and fix this myself.

**Comment by saviodsouza** [comment]
I use  Duplicati 2.0.1.7 greeno and file level listing takes very long.

To browse to a particular file in a sub sub directory the pie progress bar goes on and on for hours and sometimes I get a error like 'database is locked'. i then kill duplicati and start again.

i backup a local drive to a NAS Box in my LAN.
Source : 102 GB
Backup ; 65 GB.

Core 2 Duo 2.x Ghz
2 GB RAM.
Backups are running since late December 2015 till date.

Does the number of incremental backup cause delay in file listing? Because in the first few incremental backups it was fast but as the database size is growing day by day its getting bad.

Thanks and keep up the great work going. :+1:

**Comment by agrajaghh** [comment]
@saviodsouza is it working better with the ngax GUI?
