### ISSUE TITLE
Kernelbase.dll crashing Win10, Server 2012 R2

### ISSUE THREAD

**Issue by CCARDELEIN** [duplicati/duplicati#1528]
Awesome program, except I am having trouble getting this to work on Server 2012 R2 and Win10.  Both 64 bit, both have .net 4.5 and .net 2.0-3.5 installed.

I tried a few different version and each one give me the Faulting module name: KERNELBASE.dll

This is from my Win10 machine, same error on Server 2012 R2 might have some different version numbers.  I can post if needed.

This comes first. 

Application: Duplicati.GUI.TrayIcon.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.Serialization.SerializationException
Stack:
   at System.AppDomain.ExecuteAssemblyByName(System.String, System.String[])
   at Duplicati.Library.AutoUpdater.UpdaterManager.RunFromMostRecent(System.Reflection.MethodInfo, System.String[], Duplicati.Library.AutoUpdater.AutoUpdateStrategy)
   at Duplicati.GUI.TrayIcon.Program.Main(System.String[])

Then followed by

Faulting application name: Duplicati.GUI.TrayIcon.exe, version: 2.0.0.91, time stamp: 0x00000000
Faulting module name: KERNELBASE.dll, version: 10.0.10240.16384, time stamp: 0x559f38c3
Exception code: 0xe0434352
Fault offset: 0x000000000002a1c8
Faulting process id: 0x1850
Faulting application start time: 0x01d13d8a745cdbef

Faulting module path: C:\Windows\system32\KERNELBASE.dll
Report Id: 0af8daab-1513-4310-ba91-b1874b31915f
Faulting package full name: 
Faulting package-relative application ID: 

Am I missing a step in getting this to work?  I have tried searching but I cant seem to find an answer.   Any help would be great !!

Thanks!!!!!!!
##

**Comment by jimrob** [comment]
Was this ever resolved.

I'm getting this exact error as well, on a Windows 7 64bit machine. I've tried the latest experimental version v2.0.1.22-2.0.1.22_experimental_2016-09-12, and the latest canary v2.0.1.25-2.0.1.25_canary_2016-09-26, both are the same. Duplicati.GUI.Trayicon.exe crashes as soon as it is run.

There are 2 error events in the log, they are:

Application: Duplicati.GUI.TrayIcon.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.Serialization.SerializationException
   at System.AppDomain.ExecuteAssemblyByName(System.String, System.String[])
   at Duplicati.Library.AutoUpdater.UpdaterManager.RunFromMostRecent(System.Reflection.MethodInfo, System.String[], Duplicati.Library.AutoUpdater.AutoUpdateStrategy)
   at Duplicati.GUI.TrayIcon.Program.Main(System.String[])


Faulting application name: Duplicati.GUI.TrayIcon.exe, version: 2.0.1.25, time stamp: 0x00000000
Faulting module name: KERNELBASE.dll, version: 6.1.7601.23539, time stamp: 0x57c99bd4
Exception code: 0xe0434352
Fault offset: 0x000000000001a06d
Faulting process id: 0xc7c
Faulting application start time: 0x01d218ab0ec7c3d2
Faulting application path: C:\Program Files\Duplicati 2\Duplicati.GUI.TrayIcon.exe
Faulting module path: C:\Windows\system32\KERNELBASE.dll
Report Id: 4e593cd4-849e-11e6-90f5-a0a8cd3e9a67

**Comment by kenkendk** [comment]
No, it has not been resolved.

The crash message points to AutoUpdater, so you can try to disable it by setting the environment variable:
```
C:\> set AUTOUPDATER_Duplicati_SKIP_UPDATE=1
C:\> C:\Duplicati\Duplicati.GUI.TrayIcon.exe
```

**Comment by jimrob** [comment]
Thanks for the suggestion I now get a different error. There is still something about the AutoUpdater, but there is now an error about opening the database. Is there something I might be doing wrong? Thanks for any suggestions.

The new error is below.

Application: Duplicati.GUI.TrayIcon.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Data.SQLite.SQLiteException
   at System.Data.SQLite.SQLite3.Open(System.String, System.Data.SQLite.SQLiteConnectionFlags, System.Data.SQLite.SQLiteOpenFlagsEnum, Int32, Boolean)
   at System.Data.SQLite.SQLiteConnection.Open()
   at Duplicati.Server.Program.OpenDatabase(System.Data.IDbConnection)
   at Duplicati.Server.Program.RealMain(System.String[])

Exception Info: System.Exception
   at Duplicati.Server.Program.RealMain(System.String[])

Exception Info: System.Exception
   at Duplicati.Library.AutoUpdater.UpdaterManager.RunMethod(System.Reflection.MethodInfo, System.String[])
   at Duplicati.Library.AutoUpdater.UpdaterManager.RunFromMostRecent(System.Reflection.MethodInfo, System.String[], Duplicati.Library.AutoUpdater.AutoUpdateStrategy)
   at Duplicati.GUI.TrayIcon.Program.Main(System.String[])

**Comment by kenkendk** [comment]
That indicates that the SQLite database for the server configuration cannot be opened/created.

The database is stored in `%APP_DATA%Duplicati\Duplicati-server.sqlite`
Can you check that the path resolves to something write-able on your machine?

You can also set the environment variable `DUPLICATI_HOME=C:\somewhere\else` to have the database stored elsewhere.

**Comment by tomneto** [comment]
I fix my error by adding a user at the logon settings on services.msc > right-click on the target service > properties > Logon tab;

Hope it fixes someone else's too.

Dont forget to take a look at my repo's 🗡️

**Comment by ts678** [comment]
> I fix my error by adding a user at the logon settings

@tomneto Which error? That sounds more likely to be the database opening problem than original TrayIcon startup crash.

From original post:

> Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.Serialization.SerializationException
Stack:
at System.AppDomain.ExecuteAssemblyByName(System.String, System.String[])

[2.0.3.3_beta_2018-04-02](https://github.com/duplicati/duplicati/releases/tag/v2.0.3.3-2.0.3.3_beta_2018-04-02)

> Updated the auto-updater, such that new installs will spawn an extra process instead of using the AppDomain method as previously done.

which means ExecuteAssemblyByName is no longer used by default. To anybody, is problem still of interest and happening?

If nothing more need be said, this issue will eventually close, as it appears to no longer happen (and I did search for awhile).

Note that 0xe0434352 is an extremely generic code (feel free to web search it) so it's possible we'll get some more someday.
