### ISSUE TITLE
lose DBlbock file ,repair didnot work.

### ISSUE THREAD

**Issue by HITSUN2015** [duplicati/duplicati#1552]
Hi,I am develop with Duplicati ~
##

**Comment by HITSUN2015** [comment]
sorry for ctrl and entry to comment before.
1.how about if we lose the Dblock file on remote storage,but it still in the local filesyetem?
it report missing file ,and I run the repair operation,but it can't send the dblock to the remote(cant run backend.put)
2.is the repair operation just work for repair the database ,or it can recreate dbock file and restore to remote file system again?
3.im trying to recreate the missing dblock in remote storage or checking if the local left dbock file is right.then put it again,is i can make it in a right way?

**Comment by kenkendk** [comment]
If all the data needed for the dblock file is on the local machine, the repair process will re-create the dblock file and upload it again. Most often this is not possible because a timestamp or other minor detail has changed.

If the dblock file is missing, there is currently no way to make the backup continue. It theory, it would be possible to just mark the affected files as "broken" and then continue making new backups, but this has not been implemented.

You can restore from the data though.

**Comment by kenkendk** [comment]
This will be fixed with #1337
