### ISSUE TITLE
Piping output of list-current-files

### ISSUE THREAD

**Issue by achalddave** [duplicati/duplicati#1576]
Running

```
Duplicati.CommandLine.exe list-current-files <file_path>
```

results in Duplicati asking for the passphrase for the folder, followed by listing all the files. If the backup is large, this list is very long, and needs to be piped into a file to be managed properly. However, piping the output of this command line to a file results in the passphrase prompt also being piped to the file. Perhaps it would be nice to have a "output" flag for the command line?
##

**Comment by kenkendk** [comment]
How would the `output` flag work?

You can supply the passphrase on the commandline with `--passphrase`.
If you are on a multi-user system, you may want to set the environment variable `PASSPHRASE=...` so others cannot read it from the commandline.

**Comment by achalddave** [comment]
I would imagine like the output flag of, e.g., `wget`.

`Duplicati.CommandLine.exe list-current-files <file_path> -o output_path`

Both methods of specifying the passphrase seem to be less than ideal, in my opinion. Environment variables can be read by other processes as well, which seems to be rather undesirable. Being able to enter the password on the command line is what most command line tools seem to do, and it would be nice to have that option even when the output is large and needs to be output to a file.

**Comment by Bummibaer** [comment]
Where is the command and what is it doing?
> Duplicati.CommandLine.exe list-current-files D:/test
Command not supported: list-current-files

**Comment by kenkendk** [comment]
@Bummibaer: That is for the 1.3.x version, and it lists the files changed in the last incremental backup.
The closest match would be `compare` in 2.0.

**Comment by Bummibaer** [comment]
Thanks.

**Comment by ts678** [comment]
> That is for the 1.3.x version, and it lists the files changed in the last incremental backup.
> The closest match would be compare in 2.0.

`list-current-files` did not exist in any Duplicati 2.0 Beta, 1.3.x is no longer maintained, and

The [compare](https://duplicati.readthedocs.io/en/latest/04-using-duplicati-from-the-command-line/#the-compare-command) command in Duplicati 2.0 does not seem to need a password, presumably because it has all the info it needs in its DB.
I verified with Process Monitor on Windows that it wasn't reading the `.aes` files from CLI when I ran`compare` without a password.

It seems like both these points make the request no longer relevant, so it can be closed.
