### ISSUE TITLE
distorted display of the tray icons on windows

### ISSUE THREAD

**Issue by agrajaghh** [duplicati/duplicati#1646]
since #1630 is closed (and has a different topic)

quote from there:
hmm, nitpick but the ico I created looks like that (1600%)
![ico](https://cloud.githubusercontent.com/assets/5296073/13905907/f3bce9e0-eecc-11e5-833c-1a0563171f1e.png)

but its displayed for me on windows 10 like that:
![tray](https://cloud.githubusercontent.com/assets/5296073/13905909/f8467ad0-eecc-11e5-843e-23c82309e2b2.png)

It's displayed as exactly 16x16px for me in the taskbar. And there is a 16x16 version included in the ico file. Maybe windows is using 24x24 (or another version) and is resizing it, but that wouldn't make sense :grin:

I'm using version 2.0.1.8

**Comment by FootStark** [comment]
I think the tray icon must be loaded with an explicit size, otherwise it defaults to 32px:
`new Icon(..., System.Windows.Forms.SystemInformation.SmallIconSize)`
But I'm not sure if adding a ref to `System.Windows.Forms` will break somthing in Mono on Linux... Fixing it at 16px might not be good for hi-res system, says MS...

**Comment by FootStark** [comment]
Nevermind, I saw the ref is available. I can fix this later.
