### ISSUE TITLE
UI: "keep backups: custom" not possible

### ISSUE THREAD

**Issue by agrajaghh** [duplicati/duplicati#1651]
It's currently (2.0.1.8) not possible to enter a custom string in the UI for *keep backups*. Just numbers are allowed:
![custom](https://cloud.githubusercontent.com/assets/5296073/13971454/af2a7304-f090-11e5-923e-e53279740d63.png)

also please reduce the size of the second field, so that all three fit in one line :blush:

**Comment by renestach** [comment]
1. What value would you like to enter?
2. Have you seen the dropdown the line below? (a small bug in the layout)

**Comment by agrajaghh** [comment]
1: I don't need the "custom" option, I would be fine with removing it completetly 

2: Of course I saw it, I selected "custom" there. But as soon as you enter a letter in the second field, the third one gets cleared.

possible solutions:
* remove "custom" as an option
* allow full strings instead of just numbers as soon as "custom" is selected

**Comment by renestach** [comment]
I think we should remove "custom" from that list. If someone thinks, "days" is too long, we could add "Hours" instead of custom.

**Comment by agrajaghh** [comment]
yes, I agree, that would be enough.

a bit OT, but what do you have to enter to not keep older versions at all? "a specific number" 1 or 0?

There are these round blue "i"'s next to "Max backup file size" and "Keep backups". Should they show a help text when hovering? For me nothing is displayed.. Should I open a new issue for that?

**Comment by renestach** [comment]
Good question. I think you say "1". I am not sure if that really keeps just 1 version or "one additional to the last successful backup".

The (i) buttons should show helping text. We have that on our todo list already.

**Comment by kenkendk** [comment]
IIRC "0" means "keep all" and "1" means "delete all but the last".

**Comment by kenkendk** [comment]
I fixed this with bc55763339a44a26c9714b8ad2af03fe97c230e6 by setting the type of the field to text.

A follow up on some of the other items here:

* You cannot set "not keep older versions at all" as you would need at least one versions (otherwise, what is the point of having a backup run, if you delete it afterwards), so the number "1" is correct
* The blue (i)'s ... we have not really moved on that. Should we create an issue and put effort into getting that ready?
* We can reduce the list to not have custom, but it is problematic if the user imports a backup, or somehow gets a backup in with a non-standard retention, as we cannot display it then, and it will be something weird that happens.

**Comment by agrajaghh** [comment]
> The blue (i)'s ... we have not really moved on that. Should we create an issue and put effort into getting that ready?

the (i)'s are currently removed, so its not confusing anymore. IMHO the options are pretty self-explanatory, but it might be helpful for beginners etc. I opened a new issue #2010, not sure about the priority though ;)
