### ISSUE TITLE
Trojan Win32/Fethar.B!d detected by Windows Defender

### ISSUE THREAD

**Issue by barbushin** [duplicati/duplicati#1658]
Just downloaded http://updates.duplicati.com/experimental/latest.zip and received critical alert from Windows Defender that there is Trojan Win32/Fethar.B!d in archive. File was automatically deleted.

OS: Windows 10 x64

**Comment by renestach** [comment]
.. and that is our fault?

**Comment by renestach** [comment]
When you get the file checked online, all services say it is a clean file. This includes Google Malware, Kaspersky, Sophos, Bitdefener, Avira and 60 more. Only Windows Defender thinks that file is bad. So what can we do about it?

**Comment by barbushin** [comment]
Guys, I don't know what you can do about it, but definitely it's not very good issue and should be fixed.

Funny thing is that now I downloaded https://github.com/duplicati/duplicati/releases/tag/v2.0.1.8-2.0.1.8_canary_2016-03-20 and Windows Defender did not detected any trojan inside.

**Comment by renestach** [comment]
We do not know what we can do about false alarms in other software either.

**Comment by agrajaghh** [comment]
@renestach you can report false positives here:
https://www.microsoft.com/en-us/security/portal/submission/submit.aspx

**Comment by renestach** [comment]
Just tried to submit a report there
1) I cannot download the file because Defender deletes it immediately. (Turn off defender)
2) I cannot submit a report because they only accept files up to 10MB.
3) I cannot provide them with a download URL

This really sucks.

**Comment by renestach** [comment]
OK, I extracted the file in question and could submit it. Support case MMPC16032594679630

Now let's see what happens.

**Comment by renestach** [comment]
Submission ID MMPC16032594679630
  Submitted Files
  =============================================
  Duplicati.Library.AutoUpdater.exe [**Not Malware**]
Your submission was scanned using antimalware definition version **1.215.2980.0**.


I guess this should be solved soon.

**Comment by coxd** [comment]
FYI downloaded latest.zip on April 25 and Windows defender is still treating it as a virus.

**Comment by renestach** [comment]
Submitted again under MMPC16042519066237

**Comment by renestach** [comment]
Submission ID MMPC16042519066237

  Submitted Files
  =============================================
  Duplicati.Library.AutoUpdater.exe [Not Malware]


Your submission was scanned using antimalware definition version 1.217.2369.0.
========

The detections listed above are included in the latest pre-release definition available for download. For more information please visit the pre-release definition update download page available at:

http://www.microsoft.com/security/portal/Shared/PreReleaseSignatures.aspx

Alternatively, detections listed above will be available for users who subscribe to the automatic definition update mechanism in the next regularly scheduled release, as well as users who choose to manually update their definition library available via the MMPC Portal available on:

http://www.microsoft.com/security/portal/Definitions/ADL.aspx

**Comment by jvook** [comment]
I used the following work around for this error.  Instructions are for Windows 10 but should be similar for earlier OS.  Might work with other Antivirus programs as well:

We can take advantage of the fact that Duplicati uses names the executable as .TrayIcon.exe by setting a Windows Defender exclusion of that extension so that it will stop deleting the file.

Open "Windows Defender" from Start Menu.
Select Settings in upper-right corner.
Scroll down to "Exclusion" settings and select "Add an Exclusion".
Choose "Exclude a file extension".
When prompted, enter ".TrayIcon.exe".
Redownload the latest.zip

From now on, don't download any virus with extension of .Trayicon.exe ;)  (should never happen).
Windows Defender should stop deleting your files.

**Comment by jvook** [comment]
@renestach 

Just re-reading this thread and noticed that you are submitting the autoupdater.  That file has not been giving me a false-positive -- it is in fact the Duplicati.GUI.TrayIcon.exe file that gives the error in the lastest release.

**Comment by jvook** [comment]
FYI

Analysis of the file(s) in Submission ID MMPC16050521710459 is now complete.

This is the final email that you will receive regarding this submission.

The Microsoft Malware Protection Center (MMPC) has investigated the following file(s) which we received on 5/5/2016 10:14:55 AM Pacific Time.
Below is the determination for your submission.

========
Submission ID MMPC16050521710459

  Submitted Files
  =============================================
  Duplicati.GUI.TrayIcon.exe [Not Malware]


Analyst Comments
================
**-- 5/5/2016 10:17:38 AM --
Thanks _____,

We've addressed the incorrect detection on our side and the file will no longer be detected. No signature update is required for it to take effect since it is part of our cloud protection technology. It should take effect starting in the next hour or two.

Apologies for any inconvenience this caused,**

-_____




Your submission was scanned using antimalware definition version 1.219.883.0.
