### ISSUE TITLE
SFTP fails to connect to OpenSSH_7.2

### ISSUE THREAD

**Issue by sovapatr** [duplicati/duplicati#1687]
Duplicati version: 2.0.1.7_experimental_2016-03-19

When trying to create a new backup to a FreeNAS server using SFTP I receive a Failed to connect error.

Server log:
`freenas sshd[23957]: fatal: mm_answer_moduli: bad parameters: 2048 2048 1024`

Duplicati log:
`Renci.SshNet.Common.SshConnectionException: An established connection was aborted by the software in your host machine.
   at Renci.SshNet.Session.WaitHandle(WaitHandle waitHandle)
   at Renci.SshNet.Session.Connect()
   at Renci.SshNet.BaseClient.Connect()
   at Duplicati.Library.Backend.SSHv2.CreateConnection(Boolean changeDir)
   at Duplicati.Library.Backend.SSHv2.List()
   at Duplicati.Server.WebServer.RESTMethods.RemoteOperation.TestConnection(String url, RequestInfo info)
   at Duplicati.Server.WebServer.RESTHandler.DoProcess(RequestInfo info, String method, String module, String key)`

I am able to successfully connect if I use the 2014.4.6-beta2 version of the SshNet .Net 4.0 dll instead of the Renci.SshNet.dll supplied. 

[https://sshnet.codeplex.com/releases/view/120565](https://sshnet.codeplex.com/releases/view/120565)

**Comment by KshitijAgrawal** [comment]
Yeah, same with me! Did you find an answer? Is there a way to make the previous version work with openSSh 7.2?

Maybe because of this?
https://launchpad.net/ubuntu/xenial/+source/openssh/+changelog 

•	- This release disables a number of legacy cryptographic algorithms by
•	      default in ssh:
•	      + Several ciphers blowfish-cbc, cast128-cbc, all arcfour variants and
•	        the rijndael-cbc aliases for AES.
•	      + MD5-based and truncated HMAC algorithms.

**Comment by kenkendk** [comment]
I think the updated sshd increases the minimum key sizes, and that breaks the Renci.SSH library.

**Comment by kenkendk** [comment]
Yes, that is the issue:
https://sshnet.codeplex.com/workitem/1973

**Comment by kenkendk** [comment]
I updated to the beta of Renci.SSH, so this should be fixed in the next canary build 730a134b802fe5b2d1e756628aea46bca468f202
