### ISSUE TITLE
ctrl-c on linux doesn't cancel

### ISSUE THREAD

**Issue by utdrmac** [duplicati/duplicati#1703]
When operations are failing, as demo'd below, pressing ctrl-c repeatedly does nothing. However, when operations are proceeding normally, ctrl-c works just fine.

```
root@gasgiant:~# duplicati-cli --auth-username="centos" --ssh-keyfile="/home/dude/.ssh/id_rsa" --skip-metadata=True --backup-test-samples=2 backup ssh://52.132.26.116/opt/timemachine/ /data/.timemachine/ReadyNAS/
Backup started at 4/16/2016 3:19:22 PM

Enter encryption passphrase:

Confirm encryption passphrase:
Checking remote backup ...
  Listing remote folder ...
Operation List with file  attempt 1 of 5 failed with message: No suitable authentication method found to complete authentication. => No suitable authentication method found to complete authentication.
=====!! CTRL-C x10 here. No effect. !!====
  Listing remote folder ...
Operation List with file  attempt 2 of 5 failed with message: No suitable authentication method found to complete authentication. => No suitable authentication method found to complete authentication.
=====!! CTRL-C x10 here. No effect. !!====
  Listing remote folder ...
Operation List with file  attempt 3 of 5 failed with message: No suitable authentication method found to complete authentication. => No suitable authentication method found to complete authentication.
=====!! CTRL-C x10 here. No effect. !!====
etc...etc..
```
##

**Comment by ts678** [comment]
Not reproducible on Linux unless it's very operation-specific even though it claims a general issue.

I think original case is an authentication mismatch per [Frequently experienced SSH.NET exceptions](https://github.com/sshnet/SSH.NET/wiki/Troubleshooting-SSH.NET#frequently-experienced-sshnet-exceptions).
I just used a vacant IP address for my SFTP server to get my error. Control-C works fine with that.
To make things a little more visible, I added `--console-log-level=retry` and tested a few spots.

> duplicati-cli --auth-username="centos" --auth-password="password" backup ssh://192.168.0.250/dest/ /home/ --console-log-level=retry --no-encryption

I'm not expecting a tidy cancel. I'm expecting sudden death due to a signal, and I seem to get one.
The `$?` variable in bash is 130 which I think says it was SIGINT which seems right for a Control-C.

The Duplicati process structure might be different than it was before. It's now a parent and a child.
Parent launches the child with its latest version. Both are in the same process group for the signal.
I was watching Duplicati process action from another tab using `ps -t pts/2 -o tpgid,pgid,args`

Windows Control-C is different, but this issue is about Linux. Anyway, is problem still reproducible?
