### ISSUE TITLE
Exponential backup expiry

### ISSUE THREAD

**Issue by mach-o** [duplicati/duplicati#1732]
For many use cases, it's more storage-efficient to keep backups on an exponential rather than linear timeframe. For example, rather than storing rolling daily backups over the last seven days, it's usually more helpful to store seven backups, each being 1, 2, 4, 8, 16, 32, and 64 old, so that if you want to restore a file to the way it was last month, it's remains possible.

The BackupPC software allows very granular configuration of the intervals at which backups are stored. You set a backup interval (e.g. it can be one day or one week), and then list the multipliers of that interval at which you want to store backups (e.g. 10, 100, 1000, 10000). I think granular control (by having the person provide this kind of list of intervals) would be better than having a hard-coded exponential function. I'm not sure whether the backup interval would be necessary as well, but could be considered.
##

**Comment by kenkendk** [comment]
Yes, I agree. A list is better because it is more fine-grained and otherwise you need at least: 

  * minimum
  * exponential factor
  * maximum

By supplying a list like `1D,2D,1W,1M,1Y` it is very intuitive that the oldest backup will be a year old. A potential problem would be that the user could provide it un-sorted. It is easy to sort, but may confuse the user.

@renestach: Thoughts?

**Comment by warwickmm** [comment]
Does the "new" retention policy take care of this issue?

**Comment by Pectojin** [comment]
I would argue it does.
