### ISSUE TITLE
Restore doesn't resume after the computer wakes up from sleep.

### ISSUE THREAD

**Issue by stanimirivanovde** [duplicati/duplicati#1747]
If the computer goes to sleep in the middle of a restore, the restore doesn't resume when the computer  wakes up from sleep. I am running this on Windows 7. It looks like the restore is working, but using the Resource Monitor in Windows 7 it shows no signs of activity in the Network or Disk. Before the computer going to sleep it showed a healthy activity on the Network and Disk. The restore is from an SFTP source on the local network. The SFTP server is always on.
##

**Comment by ts678** [comment]
I couldn't find any other reports in open and closed Issues, and I also can't reproduce this on Windows 10 with local SFTP server. Tested with sleep and hibernate. I had to tell Duplicati to resume, because Settings had `Pause after startup or hibernation`.

Unless this is still of interest and still happening, this issue will eventually close.

**Comment by ts678** [comment]
[Tray icon didn't show unpause on computer wake, while GUI icon did #5186](https://github.com/duplicati/duplicati/issues/5186) is slightly similar, except it seemingly was just a TrayIcon display glitch of unknown origin, that was studied deeply but hasn't come back, which maybe is the case here too?

There is also a chance that the SFTP activity stalled, meaning it wasn't a Resume problem in the sense of Duplicati's "Pause".
Regardless, this isn't very actionable now. There have also been lots of changes since 2016, and it might simply be resolved.
