### ISSUE TITLE
Windows Service installer with parameters

### ISSUE THREAD

**Issue by mnaiman** [duplicati/duplicati#1768]
Hi, I just found, you added Windows Service. Could you make it self installable? Like in this article?
http://www.codeproject.com/Articles/21405/Windows-Services-Can-Install-Themselves
Ideally with ability to pass arguments like "--portable-mode" during install. So commandline for install should looklike Duplicati.WindowsService.exe --install --portable-mode and for uninstall Duplicati.WindowsService.exe --uninstall --portable-mode . Thanks

**Comment by kenkendk** [comment]
That sounds like a nice idea.

The reason that the service is not currently installing itself is that we have been discussing how to best expose the feature. When Duplicati is running as a service, it does not have a user context, but instead runs as a system account. This is great because it can then run VSS and do backups of locked files.

But it is also something that should be done with care, as any user on the system can connect to the process and thus obtain access to all files on the system. It also means that the "My Documents" folder is not related to the user viewing it.

When we have a good plan for how to convey these issues to the user, the service will be installed by the msi package. And I think we can make the `--install` flag as described.

**Comment by ulicky** [comment]
Yeah, I understand. I think under service mode there is no "My documents" only C:\users\<user>\...\My documents. 
Many service installs are great on servers, because "unattended" mode and it is fine running as LOCALSYSTEM. On desktop I manually changed service to run as user to impersonate user and access network recources (dont want to include windows password in duplicati config). For that im protecting web interface with password, thats why i suggested #1198 

I like portable software, thats why installer is not good option for me :)

**Comment by HRomie** [comment]
@kenkendk
It would be a crap load of work, but what if duplicati running as system service, uses windows authentication to authenticate users? Here's (in my mind), how the process will go:

1- The user opens the web UI, and provides his local user/pass for his windows account
2- duplicati spawns a new process running as that account
3- from there that account will be used for all further activities (backups/restores/etc)

That should solve all the issues that you've mentioned. But I'm not sure how easy it is to implement.

**Comment by BrianLakstins** [comment]
I have it running as a service.
Since I'm running it on a system that I have full management of, then it's fine to run it as the system user context.
With multiple users, then the different possible use cases might need to come into play.  How much should a non-administrator be able to do when accessing / running Duplicati?  Maybe the answer is nothing.
The web access would need to be limited to Administrators only.

Locking it down with a password seems just almost as good though.  Maybe the "service install" just makes sure that the web interface is locked down with a password.  Perhaps it's set during service install or reported during service install.  Maybe the install procedure allows it to be left blank if it's a single user or administrators only system anyway.

**Comment by mnaiman** [comment]
It is really necessary to implement multi user support? Most users will not be able to install and configure software like this, some admin will install and setup things like remote storage for them. 

For example I switched to duplicati from cobian backup, when its development was stopped and logic there was, that service could backup everything (run as system), but when user didnt (couldnt) install as service and only runs backup software after login - only user context backup engine was started. But it is already implemented - trayicon.

**Comment by HRomie** [comment]
Even though it would be super cool to have that, i have to admit that supporting multi user doesn't seem like a priority to me either. unless you are using the software in an enterprise environment that is.

**Comment by kenkendk** [comment]
I have now implemented the installation part, so you can run:
```
Duplicati.WindowsService.exe install --webservice-interface=loopback --log-retention=3M
```

That should solve the original request.

For the other ideas, they should be moved to #1739.

@HRomie and @mnaiman: I had a look at the NTLM authentication, and it is not impossible to do via the webserver, but not an easy task either.

When running as a service, we cannot rely on the trayicon to pass the user context, because there is no guarantee that whoever requested the web-page is the same that runs the tray-icon.
But for small systems (i.e. single user) it might make sense to have the trayicon send the user context, so there is just a single context. 

This could perhaps be done via the installer instead, such that the server always knows what context to use.

Correct multi-user is quite a large topic (each user needs their own backups only, etc).

@BrianLakstins : I like the idea, but I am not sure how to implement it.

**Comment by mnaiman** [comment]
Hi, thanks I'm fine with that, because until now, I used [NSSM](https://nssm.cc/) to start Duplicati Server.
With this commit it will be possible to use just Duplicati itself.
