### ISSUE TITLE
Automatically Resume After Restart / Other Failure

### ISSUE THREAD

**Issue by thomaskonrad** [duplicati/duplicati#1772]
I started my first backup from a Windows machine, and after some time, Windows automatically rebooted due to Windows updates. The backup did not resume after restart. I had to manually start the backup process again so that it would continue.

One thing that is not at all clear to me is what is happening behind the scenes in this case. Does it start all over? Does it continue where it left off? Why is it shown as an extra backup process in the list if it just continues? Why are the interrupted backup processes shown as a red question sign in the list although there seem to be files backed up? What if the next incremental backup date approaches? Will it continue with the old one or start over because it's seeing that the first one did not finish?

The setup:
- Only incremental backup every 2 weeks
- First time, so full backup
- Windows
- Duplicati 1.3.4

From an end-user perspective, I'd expect the tool to just continue after a reboot.
##

**Comment by jvook** [comment]
I was just wondering the same.  I'm currently using Duplicati on a stable desktop but I was considering running it on my laptop, but for various reasons it might go to sleep or hibernate, or need to be restarted.  Is backup resume an existing feature or is this a new request?

**Comment by SARG04** [comment]
Duplicati 1.3 is not maintained any more.
https://github.com/duplicati/duplicati/wiki/FAQ

And in 2.0 (experimental) the backup is kind of continued and a new one is created at the same time.
http://www.duplicati.com/news/majorupdatecoming

There are no traditional incremental or full backup any more. Each backup is a full backup in this case that you can delete all old backup and still restore all file from the resent backup.
But they are as well incremental backup that only changed data will be added for each backup.
Parts which haven't changed will be referenced in files from old backup and belong to both backups.

So is a backup is incomplete because of a interruption, the next one will use all unchanged files from the old unfinished backup and add all changed and files not in the new backup.

As far as I can tell the unfinished will not restart automatic. You either have to start it yourselves or wait for the next scheduled run.

**Comment by ts678** [comment]
> Duplicati 1.3.4

This is likely going to eventually close unless changed to a Duplicati 2 issue. Some of the same design decisions probably apply.

> I'd expect the tool to just continue after a reboot.

It's not going to continue at boot if it's started at login. If set up as a Windows service, it starts at boot, and runs jobs that have missed their scheduled time. I think it will resume jobs interrupted by a restart, but it would be best to test if it's still of concern.

Sleep or hibernate should get continue after wake (just like everything else). If no further activity here, issue will eventually close.
