### ISSUE TITLE
"Invalid File Format" with Synology Installation Package

### ISSUE THREAD

**Issue by RKB1923** [duplicati/duplicati#1777]
1. Tried manual install of Synology package duplicati-2.0.1.17_canary_2016-05-14.spk
2. Received "Invalid File Format" error.
3. Using DSM 5.0-4528 on DS1511+

![screen shot 2016-05-19 at 5 30 32 pm](https://cloud.githubusercontent.com/assets/1047643/15412824/34c58a7e-1de8-11e6-8c64-80ec3ffaba1c.png)
##

**Comment by martva** [comment]
Hi I'm experiencing the same issue. I have Mono installed and running, but when trying to install the most recent package: duplicati-2.0.1.22_experimental_2016-09-12.spk I get the "Invalid File Format" message. 

the synosys.log says the following:
err	2016/09/16 11:01:21	uat531:	Failed to install package [Duplicati].

/var/log/messages says this:
Sep 16 11:01:21 Bignasventi entry.cgi_SYNO.Core.Package.Installation[1].install[12700]: pkginstall.cpp:385 Failed to unpack package.tgz, /bin/tar zxf /volume1/@tmp/pkginstall/package.tgz -C /volume1/@tmp/pkginstall/package

This can be true, because there is no package.tgz in /volume1/@tmp/pkginstall.

**Comment by Ch3k0ch** [comment]
Hi,

got the same problem here.

Any suggesstion for a solution?

Greetz

**Comment by meffect** [comment]
i notice you can cancel at this point and still load gitlab... i havent tried it out yet behind that tho

**Comment by kenkendk** [comment]
I have made an updated .spk, is this still an issue?

**Comment by warwickmm** [comment]
I'm assuming this has been fixed. If not, please reopen with new details.
