### ISSUE TITLE
Duplicati incremental restore

### ISSUE THREAD

**Issue by saviodsouza** [duplicati/duplicati#1780]
Incremental restore does not seem to work in command line at least.

If I hit ctrl + c in middle of a restore operation, (50 GB to restore) then run the same command again it start all over again. (102 GB to restore)

Incremental restore would be great in case systems cannot run 24 hours. Restore operation can resume like say the next day.
##

**Comment by saviodsouza** [comment]
I am running version 2.xx.11 experimental.

**Comment by renestach** [comment]
Is this a single file or many files?

**Comment by saviodsouza** [comment]
It's complete restore. Using * sign.

**Comment by ts678** [comment]
I suspect the size report works like the backup size report, in giving a large value, then decreasing as it finds what's really needed. Backup checks source files for changes needing uploading, while restore checks files in restore area for changes needing applying. Backup and restore are incremental. One way to test this is to look at the restored files statistic after the restore finishes, such as

```
Verifying restored files ...
Restored 3 (95 bytes) files to C:\backup restore
Duration of restore: 00:00:01
```

When a second restore (which I suggest is incremental) is run after a partial restore which is interrupted, it should do less than a restore that has to start from empty `--restore-path` instead of a partially restored one. You should see partial files sitting in it.

Can you see a difference? If you want details, set up a verbose log and look for `Target file exists and is correct version:`
