### ISSUE TITLE
When backup is deleted option remain in db

### ISSUE THREAD

**Issue by mnaiman** [duplicati/duplicati#1828]
When I deleted backup in web UI, options for that backup remain in server db Options table (not consistent db). Maybe when new backup is created it inherits same settings, which is not intended.

**Comment by 4m1g0** [comment]
Hello.

The problem is that the backup id is not autoincremental, so when you delete the last backup and add a new one, it obtains the same id and all the configuration is attached to it magically :)

http://www.sqlite.org/faq.html#q1

> Note that the integer key is one greater than the largest key that was in the table just prior to the insert. The new key will be unique over all keys currently in the table, but it might overlap with keys that have been previously deleted from the table. To create keys that are unique over the lifetime of the table, add the AUTOINCREMENT keyword to the INTEGER PRIMARY KEY declaration.

I added the AUTOINCREMENT manually in the database and works perfectly, the problem is that when I try to add it to the Schema.sql so that duplicate makes it autoincremental on creation, the adapter crashes...

It seems that the version of the sqlite library we are using does not support autoincrement, at least I've tried upgrading to version 1.0.102.0 and it works... but I'm new with this and I'm not very sure if this is the actual problem...

If I can do something to help with this, tell me, I want to contribute to the project.

Btw, this is somehow related: https://github.com/duplicati/duplicati/issues/1201

**Comment by 4m1g0** [comment]
It was my fault, autoincrement is supported by our version of sqlite.

So #1856 fix the problem, but I'm not sure if that's the way you handle db updates.

Tell me If I should do it in another way. 

Thanks

**Comment by kenkendk** [comment]
This was closed with d63430e
