### ISSUE TITLE
List seems to not honor retries setting

### ISSUE THREAD

**Issue by hcjehg** [duplicati/duplicati#1831]
It seems List does not honor the Retries setting, here set to 3, but only one retry is logged it seems.

Webdav target on Synology (OpenDrive)

HC

v2.0.1.17-2.0.1.17_canary_2016-05-14 on Synology

2016-06-28 08:37: Failed to create folder: The folder /Duplicati/fs02-jehg-dk/ was not found, message: The remote server returned an error: (404) Not Found.
{"ClassName":"System.Net.WebException","Message":"The remote server returned an error: (403) Forbidden.","InnerException":null,"HelpURL":null,"StackTraceString":"  at Duplicati.Library.Utility.AsyncHttpRequest+AsyncWrapper.GetResponseOrStream () <0x40d8d560 + 0x000fb> in <filename unknown>:0 \n  at Duplicati.Library.Utility.AsyncHttpRequest.GetResponse () <0x40dd4c30 + 0x00157> in <filename unknown>:0 \n  at Duplicati.Library.Backend.WEBDAV.CreateFolder () <0x40e9c820 + 0x00097> in <filename unknown>:0 \n  at Duplicati.Library.Main.BackendManager.ThreadRun () <0x40dfde60 + 0x008f1> in <filename unknown>:0 ","RemoteStackTraceString":null,"RemoteStackIndex":0,"HResult":-2146233079,"Source":"Duplicati.Library.Utility","ExceptionMethod":null,"Data":null}
**2016-06-28 08:37: Backend event: List - Retrying: ()**
2016-06-28 08:37: Operation List with file attempt **1 of 3** failed with message: The folder /Duplicati/fs02-jehg-dk/ was not found, message: The remote server returned an error: (404) Not Found.
{"ClassName":"Duplicati.Library.Interface.FolderMissingException","Message":"The folder /Duplicati/fs02-jehg-dk/ was not found, message: The remote server returned an error: (404) Not Found.","InnerException":{"ClassName":"System.Net.WebException","Message":"The remote server returned an error: (404) Not Found.","InnerException":null,"HelpURL":null,"StackTraceString":"  at Duplicati.Library.Utility.AsyncHttpRequest+AsyncWrapper.GetResponseOrStream () <0x40d8d560 + 0x000fb> in <filename unknown>:0 \n  at Duplicati.Library.Utility.AsyncHttpRequest.GetResponse () <0x40dd4c30 + 0x00157> in <filename unknown>:0 \n  at Duplicati.Library.Backend.WEBDAV.List () <0x40e17ca0 + 0x00273> in <filename unknown>:0 ","RemoteStackTraceString":null,"RemoteStackIndex":0,"HResult":-2146233079,"Source":"Duplicati.Library.Utility","ExceptionMethod":null,"Data":null},"HelpURL":null,"StackTraceString":"  at Duplicati.Library.Backend.WEBDAV.List () <0x40e17ca0 + 0x011eb> in <filename unknown>:0 \n  at Duplicati.Library.Main.BackendManager.DoList (Duplicati.Library.Main.FileEntryItem item) <0x40e16ad0 + 0x00070> in <filename unknown>:0 \n  at Duplicati.Library.Main.BackendManager.ThreadRun () <0x40dfde60 + 0x00353> in <filename unknown>:0 ","RemoteStackTraceString":null,"RemoteStackIndex":0,"HResult":-2146233088,"Source":"Duplicati.Library.Backend.WEBDAV","ExceptionMethod":null,"Data":null}
**2016-06-28 08:36: Backend event: List - Started: ()**
##

**Comment by kenkendk** [comment]
The "404" errors stop the retry system, because that indicates that the folder is missing, so repeatedly asking for the folder would just cause a delay.

Do you think this should be handled differently?

**Comment by Xavron** [comment]
However you look at it, stopping all backup retries is **never** a good idea for a backup system. The backup system is broken if it ever does that.

I just ran into this FolderMissingException and no backups have been running. Not an expected result. Because of that I may have to switch backup applications or spend time on hacking/fixing Duplicati.

I believe local backups might not be officially supported with Duplicati which is how I use it (I am new to Duplicati), but the idea is the exact same. If the remote service is offline or the internet connection is offline for whatever reason, no backups could spring upon people. They would expect it to retry automatically after it came online.

For my case, if X:/ is down, obviously we know that the drive is offline and retries should continue. Anything else is incorrect.

**Comment by Xavron** [comment]
I'm going to double check if this is definitely still an issue all these years later and try hourly.

Daily might not be enough and it simply may not have code to deal with knowing when the drive goes online to deal with daily in a good way.

**Comment by Xavron** [comment]
_Note, I really don't know if this is the correct issue or not to post this. Am just posting it because it seems relevant to here as well since backups are failing to retry plus few are open and I don't want to open a new one at this time. It is Duplicati's responsibility to keep the backups going regardless. Not do a full stop manual start._ 

However you look at it, stopping all backup retries is **never** a good idea for a backup system. The **automatic** backup system is broken if it ever does that.

I just ran into this FolderMissingException and no backups have been running. Not an expected result. Because of that I may have to switch backup applications or spend time on hacking/fixing Duplicati.

The idea for local is the exact same as an online service. If the remote service is offline or the internet connection is offline for whatever reason, no backups could spring upon people. They would expect it to retry automatically after it came online.

_For my case, if X:/ is down, obviously we know that the drive is offline and retries should continue. Anything else is incorrect._

_Even if a required folder is not found on the remote side, perhaps a full new backup should be created instead of full stop. That way everything required would be known and obtainable._

_One could argue if there's eg 1TB of data to transfer that would be a problem. This could have a section in the setup wizard and a box to select it and/or a box to set the maximum transfer size allowed should it ever exceed that and then fail is acceptable along with an email or some other notice._

_There's always something better than outright stopping all backups. **Never stop the retry system.** I don't get what people are thinking. This isn't a mobile device and we do not need to keep from using the battery if nothing has been detected for eg a month._

I apologize but its the 2nd backup application to piss me off with something stupid :-)

Looks like I will have to come through here and whack out a few problems asap. Running into other old problems while trying to reproduce this on another system.

**Comment by Xavron** [comment]
So some additional info here.

The retry count doesn't work on the time (eg backup 1 per hour or day) but instead appears to be fairly immediate as in retry connection attempt up to this many times.

So if you set eg 1000 retries it will keep retrying constantly without really any pause. If the remote destination is offline or disconnected, this idea completely fails.

**Comment by Xavron** [comment]
Have an implemented solution for local drive failure which looks to be working correctly now. Test phase.

Need to decide how to do WebDav and solve this issue here as I expect it should also to be not really related to a folder missing. There's some code failure that makes drive failure look like folder failure.

Will only update next when I have well tested release code for all of this. If it is actual folder failure here, I might not fix that as I have less interest in it.

**Comment by Xavron** [comment]
Alright, so the retry issue should be correct here. The real issue is should be the (404) Not Found. Doing more retries shouldn't make it found unless there was a connection issue.

**Comment by ts678** [comment]
> It seems List does not honor the Retries setting

@hcjehg 

Is the provided explanation sufficient to close this?

**Comment by hcjehg** [comment]
Yes, please close the issue :-)
