### ISSUE TITLE
can't restore

### ISSUE THREAD

**Issue by jvook** [duplicati/duplicati#1875]
I have a OneDrive backup and a local hard disk backup.  When I try to restore from local HDD the process runs but the files never appear in their correct location:  C:\Users\<name>\Desktop, C:\Users\<name>\Documents, C:\Users\<name>\AppData

I used default restore options (restore to same place as original location) and from what I can see in logs Duplicati finds and verifies the files, but they never appear in the location and aren't actually restored.

I imported the backup from json.
I then repaired local database before restoring as I saw in another thread. (I received an error when trying to restore without repair, something about Local File Already Exists or something)

After running a while with scanning local disk etc. it goes back to "No Scheduled Tasks" but files are not restored.

I also tried with option --no-local-blocks as suggested in another thread since data was local.

Using latest experimental.

ETA:  When restoring from a Macrium Reflect image I made, I saw that one single file was restored but no others. (C:\Users\<name>\Documents\Dolphin Emulator\MemCard.raw)

**Comment by jvook** [comment]
I tried to decrypt the AES file and just restore manually but the files are full of random characters and I can't make heads or tails of them.

This seems to run counter to this quote from the Duplicati homepage:

> Duplicati is built using standard tools and formats. Un-encrypted archives are simple .zip archives. Encrypted archives are .zip archives that can be decrypted with AES Crypt. So, even without Duplicati all your data are belong to you :-)

I can't restore these from standard tools at all.

**Comment by jvook** [comment]
WinRAR could not extract the duplicati zip files.  THe following appeared ad nauseum:

```
    J:\backup\1\duplicati-b8fcd5b5a34c44492801d8ea39e375ccf.dblock.zip: Cannot create J:\backup\1\1\KhqlmCGHttLssyd998T8hM24HZGr64oByTCiW-nUjKA=
!   The directory or file cannot be created.
    J:\backup\1\duplicati-b8fcd5b5a34c44492801d8ea39e375ccf.dblock.zip: Cannot create J:\backup\1\1\ODOnvsdEnNxaW_W30AZzpEYuqCzlnXdDR8dsqrsBjfM=
!   The directory or file cannot be created.
    J:\backup\1\duplicati-b8fcd5b5a34c44492801d8ea39e375ccf.dblock.zip: Cannot create J:\backup\1\1\R0FyFlBZ9uyY5kDb2MUDZbbcr2QCbtDJPaWWpRN3OVI=
!   The directory or file cannot be created.
    J:\backup\1\duplicati-b8fcd5b5a34c44492801d8ea39e375ccf.dblock.zip: Cannot create J:\backup\1\1\EN9RPvxqVtln20E8PwhERXHIFlYYLLvS_HHqaEre1X4=
!   The directory or file cannot be created.
    J:\backup\1\duplicati-b8fcd5b5a34c44492801d8ea39e375ccf.dblock.zip: Cannot create J:\backup\1\1\o-sb9TsA6RCqSzpW2vyZnCn-QXRidqE0-bLzQSCuaXU=
!   The directory or file cannot be created.
    J:\backup\1\duplicati-b8fcd5b5a34c44492801d8ea39e375ccf.dblock.zip: Cannot create J:\backup\1\1\wm4UiszFDMTE-2iUTXNhSqY4EUuqSN6SnWH-jiOmH18=
!   The directory or file cannot be created.
```

**Comment by tedbeer** [comment]
+1
Running Duplicati - 2.0.1.17_canary_2016-05-14 on x64 Windows 8.1
It does not restore files and folders.
I made backup of a simple test folder to a flash drive. I deleted some files and folders and try to restore them. When I run "restore files" it reports success but nothing is restored. If I choose a folder where to restore files it puts files there. But even in this case it does not restore folders.
In logs I see suspicious 'null' instead of drive/folders:
2016-08-07 11:24: Patching metadata with remote data: null\row-enhancer.js

**Comment by thirschbuechler** [comment]
Similar issue when running the prerelease [v2.0.1.18-2.0.1.18_canary_2016-08-10](https://github.com/duplicati/duplicati/releases/tag/v2.0.1.18-2.0.1.18_canary_2016-08-10) on Ubuntu 16.04 x64:
Can't restore a backup using AES-Crypt (tried local / googleDrive backups), it only works when using the duplicati-gui.

Does duplicati alter the passphrase before encrypting??

My first guess what that some special characters glitched somehow, but setting up a testing backup with a very weak password strength, a useless password without said characters ("asdfghjkl"), doesn't seem to generate AES-Crypt decryptable files either.

**Comment by kenkendk** [comment]
The strange names inside the zip files are explained here: https://github.com/duplicati/duplicati/wiki/Developer-Documentation#core-algorithm

For the unpack with WinRAR, it seems that Window does not like files with a `=` character in them?

For 2.0.1.18 there is a bug that prevents pretty much all file operations from working.

@tedbeer and @jvook : the "null" issue should be fixed in 2.0.1.19, but you should see your files in a "null" folder.

If you choose a target folder instead of the "restore to original" it works.

Please let me know if 2.0.1.19 does not fix the restore/null issue.

@thirschbuechler: I think you have something different. The passphrase is not modified before being passed to AESCrypt, and all my tests indicate that you can use any AESCrypt tool to decrypt them, including the provided SharpAESCrypt.exe. Also @jvook seems to have success with decryption, but fails elsewhere.

**Comment by tedbeer** [comment]
> If you choose a target folder instead of the "restore to original" it works.
It does not restore the folder structure. All files go to the selected folder. I'll try 2.0.1.19 ASAP.

**Comment by tedbeer** [comment]
I have quickly tested version 2.0.1.19 on Windows 8.1 x64. It works successfully with backup to a flash drive. Tested the following:
- creating backups
- updating backups
- restoring all files to another folder
- restoring missing(deleted) files to the original folder
- restoring old files without overwriting if files were changed
- ignore files bigger than specified size

Result:
- all tasks were successful
- no strange error messages in logs
- there was a warning message in logs and it was not shown in UI:
Warnings: [Failed to apply metadata to file: "C:\Dev\_temp\BackupTest\", message: The process cannot access the file 'C:\Dev\_temp\BackupTest' because it is being used by another process. => The process cannot access the file 'C:\Dev\_temp\BackupTest' because it is being used by another process.]
Errors: []

**Comment by jvook** [comment]
Hey Kenken, thanks for your support on this issue.  I downloaded latest canary (previously running on April latest.zip) but I'm unable to test your solution.  Basically, after the last issue i reported, my duplicati backup was broken.  Since then, I've been unable to restore or repair database.  If I try to run a backup, I get an error that db is not correct please repair blahblahblah.  So I try repair, and I get an error that it cannot complete because it will alter remote files and result in loss of data.  So I try delete and repair, and it runs a while but ultimately i get this:
Aug 27, 2016 4:37 PM: Message
Processing all of the 38 volumes for blocklists
Aug 27, 2016 4:37 PM: Message
Remote file referenced as duplicati-b1ff7e56d2f8a4aa9b180e2c288134e1c.dblock.zip.aes, but not found in list, registering a missing remote file
...tons of these errors.

So my Duplicati remote backup is pretty broke at the moment and I'm unsure how to fix it.  Can you help me repair or should I open another issue or follow up at another forum?  Thanks.

**Comment by kenkendk** [comment]
@tedbeer : Great to hear that it is now working for you!

@jvook:
It is problematic if you cannot repair the local database.
Is there something special with the file being mentioned: `duplicati-b1deb80e5e19842ad9a28a8c018732093.dblock.zip.aes`

The error message indicates that this file should be present, but it is not?
Can you perhaps create a bug-report from the UI, so I can see where this file is seen from and what operations are causing it?

**Comment by jvook** [comment]
No it is multiple files including that one.  It is also in all backup jobs
but I only attempted restore operation on the first one so far.

I don't think this is relevant to the error, but at one point I switched
location on the job from onedrive to local backup (because I knew I would
do immediate restore and wanted to minimize bandwidth use).  Then switched
back.  That is why duplicati finds files in the db that are not in remote
location so I can't restore and need to repair.  But I'm not sure why I
can't repair.

Bugreport.zip emailed to you at duplicati.com address.

**Comment by kenkendk** [comment]
@jvook: I checked the bug report that you sent, and I can see that the remote folder listing returns only a single dlist file and 38 dindex files. This indicates that all the dblock files are somehow removed.

Are the dblock files present at the remote location?

**Comment by jvook** [comment]
@kenkendk Indeed it must have been a late night when I was working on the config because I had an errant underscore in that path.  I have been able to recreate database for that backup job. 

However, I have come across a disturbing behavior in this process.  As I was attempting to repair my other two backup jobs, my remote storage was erased.  For example, in my Minecraft_Folder backup, it was about 1 gigabyte remote data.  I verified this prior to attempting repair.  I attempted a Repair, and the system hung up indefinitely (over an hour, compared to the User Folder backup job which recreated and deleted in less than an hour and is significantly larger).  This backup job should have had no data changes or only minor changes since previous job completion.  I force stopped the data job because it appeared to be hung, and when I checked the remote data at this time, it only had 447 KB of data.  

I found the old files in the recycle bin and they were deleted at 4:22-4:23 PM EST (This may be when I force stopped the job, maybe not).  I will send you a bugreport from that job for analysis.

**Comment by jvook** [comment]
Moving back to the original issue, I have tried to restore a backup and I'm still unsuccessful.

To repair the Minecraft_Folder backup job, I deleted the remote directory and deleted local database, then ran the backup.  So essentially starting fresh.

When I try to restore, either to original location or to a new location, I get the following output in information log.  I have verified remote file is 49 MB.


```
Sep 1, 2016 6:59 PM: Operation Get with file duplicati-ba550e05fc7e248858d3603e0b0322f04.dblock.zip attempt 4 of 5 failed with message: The file duplicati-ba550e05fc7e248858d3603e0b0322f04.dblock.zip was downloaded and had size 6830 but the size was expected to be 52405810
{"ClassName":"System.Exception","Message":"The file duplicati-ba550e05fc7e248858d3603e0b0322f04.dblock.zip was downloaded and had size 6830 but the size was expected to be 52405810","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at Duplicati.Library.Main.BackendManager.DoGet(FileEntryItem item)\r\n   at Duplicati.Library.Main.BackendManager.ThreadRun()","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":"8\nDoGet\nDuplicati.Library.Main, Version=2.0.1.19, Culture=neutral, PublicKeyToken=null\nDuplicati.Library.Main.BackendManager\nVoid DoGet(FileEntryItem)","HResult":-2146233088,"Source":"Duplicati.Library.Main","WatsonBuckets":null}
Sep 1, 2016 6:59 PM: Backend event: Get - Completed: duplicati-ba550e05fc7e248858d3603e0b0322f04.dblock.zip (6.67 KB)
Sep 1, 2016 6:59 PM: Backend event: Get - Started: duplicati-ba550e05fc7e248858d3603e0b0322f04.dblock.zip (49.98 MB)
Sep 1, 2016 6:58 PM: Backend event: Get - Retrying: duplicati-ba550e05fc7e248858d3603e0b0322f04.dblock.zip (49.98 MB)
```

**Comment by kenkendk** [comment]
Regarding the delete problem, Duplicati attempts to sync the local database with the remote. In previous versions of Duplicati, this could cause it to think that all the remote files should be removed (as there was no local files are registered), but this has been fixed a few versions back.

For the transfer failure, that is much harder to debug. Somewhere the connection gets closed and Duplicati is stuck with half-a-file and complains. Can you see the server log, or any server indication of why the connection is closed?

Otherwise, you can use the network trace support to dump all communication with the server to a file:
https://msdn.microsoft.com/en-us/library/ty48b824(v=vs.110).aspx

Simply take the "example" from there and save it as Duplicati.GUI.TrayIcon.exe.config (temporarily replace the existing one), then run Duplicati again, and it should create a `network.log` file you can examine.

**Comment by kenkendk** [comment]
@jvook : For the problematic file, can you try to download it and check that the downloaded file is 49MB ?

Also, there is a `Duplicati.CommandLine.BackendTool.exe`, which you can try to download the file, something like:
```
Duplicati.CommandLine.BackendTool.exe GET onedrive://folder/duplicati-ba550e05fc7e248858d3603e0b0322f04.dblock.zip --authid=xxxxxx
```

If the BackendTool returns a 6kb file, and the normal OneDrive returns a 49MB file, there is a bug in the OneDrive download function.

**Comment by jvook** [comment]
> Regarding the delete problem, Duplicati attempts to sync the local database with the remote. In previous versions of Duplicati, this could cause it to think that all the remote files should be removed (as there was no local files are registered), but this has been fixed a few versions back.
> 
This was using the 2.0.1.19 version you mentioned above.

> For the transfer failure, that is much harder to debug. Somewhere the connection gets closed and Duplicati is stuck with half-a-file and complains. Can you see the server log, or any server indication of why the connection is closed?
> 
> Otherwise, you can use the network trace support to dump all communication with the server to a file:
> https://msdn.microsoft.com/en-us/library/ty48b824(v=vs.110).aspx
> 
> Simply take the "example" from there and save it as Duplicati.GUI.TrayIcon.exe.config (temporarily replace the existing one), then run Duplicati again, and it should create a network.log file you can examine.

I can't see the server log.  The example XML from that site just causes TrayIcon.exe to crash.

> kenkendk commented 18 hours ago
> @jvook : For the problematic file, can you try to download it and check that the downloaded file is 49MB ?
> 
> Also, there is a Duplicati.CommandLine.BackendTool.exe, which you can try to download the file, something like:
> 
> Duplicati.CommandLine.BackendTool.exe GET onedrive://folder/duplicati-ba550e05fc7e248858d3603e0b0322f04.dblock.zip --authid=xxxxxx
> If the BackendTool returns a 6kb file, and the normal OneDrive returns a 49MB file, there is a bug in the OneDrive download function.

I downloaded the file through chrome and it is 49MB.  The Backendtool only returns Command failed: Backend not supported.  I tried a couple variations but it doesn't seem to like onedrive protocol.
```
Usage: <command> <protocol>://<username>:<password>@<path> [filename]
Example: LIST ftp://user:pass@server/folder
```

**Comment by jvook** [comment]
OK I was able to get BackendTool.exe to work with v. 2.0.1.22 and it downloads a 6KB file.

The TrayIcon.exe also ran with the network trace XML but it didn't create a trace.log file.  I also tried adding ```
<trace autoflush="true" indentsize="4">
    <listeners>
      <add name="file" type="System.Diagnostics.TextWriterTraceListener" initializeData="trace.log"/>
    </listeners> 
  </trace>
```
but no log was generated.

**Comment by jvook** [comment]
hey @kenkendk , If it's alright with you, I am going to close this issue and create a new one specific to OneDrive download function, for clarity.
