### ISSUE TITLE
SecureChannelFailure again

### ISSUE THREAD

**Issue by glannes31** [duplicati/duplicati#1882]
Hello , i tested the new version .... I have SecureChannelFailure on a macbook again ....

**Comment by agrajaghh** [comment]
can you be a bit more precise? What version? Do you have a log?

**Comment by glannes31** [comment]
in the last version of duplicati. the problem is due TLS. our owncloud server accept tls 1.2 with specify cipher.  duplicati send paquet with tlsv1 with basic cipher suites. i have posted a similar issue a few months ago and the team says me that a knew problem. i thinked that its solved in the last version.

**Comment by glannes31** [comment]
I forget to download the lateste Mono Framework 4.7  .

**Comment by agrajaghh** [comment]
so its working now?

**Comment by glannes31** [comment]
No... I don't know if you have used this new Mono package in the latest version

**Comment by mnaiman** [comment]
Mono package is not included in Duplicati as far as I know. 

You have to install it separately, perhaps compile from source, because there is no 4.6 binaries. As written in #1836 you have to wait of Mono 4.6 to become released. [https://github.com/mono/website/blob/gh-pages/docs/about-mono/releases/4.6.0.md](https://github.com/mono/website/blob/gh-pages/docs/about-mono/releases/4.6.0.md)

There is nothing to be done in Duplicati, it makes no sense to open bug again with every version.
