### ISSUE TITLE
"Source: 0 bytes" - Empty backups with VSS snapshots - 2.0.1.19

### ISSUE THREAD

**Issue by NickPyz** [duplicati/duplicati#1905]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info
**Duplicati Version:** 2.0.1.19
**Operating System: Windows 10 - 64 bit
**Backend - Amazon S3:**

### Bug description

Seeing "Source: 0 bytes" after a backup job

Not sure if this is a cosmetic bug or a real malfunction. This was introduced with 2.0.1.18, and it went away when I downgraded to 2.0.1.17. Now, it's back again.

![2016-08-27_16-55-32](https://cloud.githubusercontent.com/assets/7215081/18030103/1b667d42-6c79-11e6-88f1-2599612150c8.png)

**Comment by martin54** [comment]
I've the same problem, but not sure if it's 100% caused by my update (from 2.0.1.17 to 2.0.1.19).
Also with an downgrade I didn't got it working again (Win7 64).
In my case it's a real real malfunction: if trying to restore files from a new backup, it shows that it's empty.

I was able to narrow down my problem to Volume Shadow Copy: if removing the option "**--snapshot-policy**=On" it's working again (at least 2.0.1.17 is now working again w/o snapshots).

Really very strange: the log does not contain any information that there was a problem with snapshots. Even if running without admin privileges, it works w/o any warning and creates an empty backup (w/o admin privileges there should be something like "missing permissions to ...").

Using vshadow64.exe I removed all existing snapshots, but that didn't helped.
I tested another backup app which uses vshadow64.exe, and that's still working.

**Comment by martin54** [comment]
I was able to reproduce the problem:

1. Fresh installation of 2.0.1.17 on Win7-64bit.
2. Started Duplicati via context menu "Run as Admin".
3. Configured and executed a backup job to Google Drive for one folder,
    with  option "--snapshot-policy=Required"
    => Success with "Source: 10 KBbytes"
4. Performed Update via the Webpage popup.
5. Executed the same backup job again with unchanged parameters
   => "Success" with "Source: 0 bytes", i.e. empty backup, and no warnings or errors.

**This bug is quite dangerous, as the user does not get any notification/warning/error message that only empty backups are generated! Probably he will only detect it when trying to restore something :-(**

FYI: via the config GUI (web gui, config job step #2: source data/folders), the directories + files are still visible, i.e. not related to the earlier bug in sub-version 18.

**Comment by NickPyz** [comment]
Thanks @martin54 for your follow up tests. My experience with 2.0.1.19 is exactly the same as yours. The only difference in my experience is that "--snapshot-policy=On" works perfectly when I downgrade to 2.0.1.17. Not sure about the 2 later releases since nothing was backed up at all.

*.18 and *.19 are somewhat different as you noted. In the later release, users can browse through the source hard drive when creating a job. This wasn't possible in *.18.

However, the end result is the same. The UI reports "Source: 0 bytes" after running the job, nothing is actually backed up, and there is no warning of the failure.

It's a bug of course, **but is this affecting 100% of users, or only some?** Would be helpful to know the answer to this question. Meanwhile, I am going back to *.17 and I will wait patiently for the next new release.

**Comment by martin54** [comment]
I guess my first try to downgrade was unsuccessful because I didn't deleted  C:\ProgramData\Duplicati.
@NickPyz : are you able to change the title to something like:
"Source: 0 bytes" empty backups with snapshots / Volume Shadow Copy Services (VSS) - 2.0.1.19

**Comment by huste** [comment]
I have one backup with snapshot-policy=Off and it lists "0 bytes" as source data. That's with 2.0.1.19

**Comment by NickPyz** [comment]
@huste This implies the failure to backup in version 2.0.1.19 is **not** connected to use of VSS. 

OK - I don't understand why we're not seeing a flood of feedback here. Is it possible that this problem is only affecting a small % of those running 2.0.1.19? Or maybe few are noticing it - because the application  isn't issuing an error pop-up?

**Comment by lucwuyts** [comment]
It seems ok on my PC's
![2016-08-29_155356](https://cloud.githubusercontent.com/assets/198423/18053696/0bfc1112-6e01-11e6-91cf-7a1c285190e1.png)
![2016-08-29_155616](https://cloud.githubusercontent.com/assets/198423/18053713/29f27d14-6e01-11e6-86c9-7519d4d6c0f5.png)
![2016-08-29_155630](https://cloud.githubusercontent.com/assets/198423/18053714/29f62630-6e01-11e6-8af5-fa0d5493a3e0.png)
![2016-08-29_155745](https://cloud.githubusercontent.com/assets/198423/18053768/5820a27e-6e01-11e6-997c-9f74dee91f8b.png)

Backup destination is google storage

**Comment by dsferruzza** [comment]
Hi!

I add the same "0 bytes" problem described here (on *.18 and *.19). Disabling VSS fixes it.
I don't have more information that were not already said, but as you expected more feedback/flood, here it is ^^

Have a nice day!

**Comment by huste** [comment]
@NickPyz yes, it seems so. No connection to VSS. At least not to a specific setting. Maybe it's the existence of the VSS-option at all? [...] nope, one backup does not have the option set at all.

I just noticed: I have mixed displays: Some show 0 bytes at the source. Some at the target. Some at both locations...
[...]
One thing: Does anyone have the "no-backend-verifcation" option set? I noticed that removing this option shows file sizes...

**Comment by martin54** [comment]
@lucwuyts : can you please provide the information, if you used Volume Shadow Copy Service (VSS) for your successful backups, i.e. a Windows system with "--snapshot-policy=On" or =Required?

**Comment by lucwuyts** [comment]
No, I didn't use VSS

Van: martin54 [mailto:notifications@github.com]
Verzonden: maandag 29 augustus 2016 18:02
Aan: duplicati/duplicati <duplicati@noreply.github.com>
CC: Luc Wuyts <luc.wuyts@a-d-e.net>; Mention <mention@noreply.github.com>
Onderwerp: Re: [duplicati/duplicati] "Source: 0 bytes" - Empty backups with VSS snapshots - 2.0.1.19 (#1905)


@lucwuyts<https://github.com/lucwuyts> : can you please provide the information, if you used Volume Shadow Copy Service (VSS) for your successful backups, i.e. a Windows system with "--snapshot-policy=On" or =Required?

**Comment by NickPyz** [comment]
@martin54 

Based on the variety of comments, I don't think the connection between the backup failure and "--snapshot-policy=on" is proven. The feedback from @huste indicated a failed backup (source: 0 bytes) with "--snapshot-policy=off".

Is there a pattern here we're missing? 

Another thought is that there are 2 ways to employ the snapshot-policy option. One is at the individual backup job level. Also, there is another method where it is done as a global default option. I never use the global option - now I wonder if it matters in relation to these backup failures.

**Comment by martin54** [comment]
@NickPyz : There are several users who reported that snapshot-policy=on caused empty backups, and removing that option makes it working again. So we absolutely know that there's a problem with snapshots in v.19 (which was not there in v.17).

Regarding huste: until now that's the only one who reported that there are also problems without snapshots. Maybe that's a second independent problem (as he also has jobs with 0 bytes only at target), or maybe that's no problem at all (maybe huste's backups already were empty before the upgrade). I suggest to tread it independently, i.e. @huste should open a 2nd issue with a detailed description of the problem, system setting, test results, situation after downgrade, etc.).

Regarding global default option: I don't know if they have any effect at all. Maybe they will be only used as default parameters when setting up new backup jobs? Found no documentation :-(

I've just detected this one: https://usage-reporter.duplicati.com/
![usage-reporter duplicati com](https://cloud.githubusercontent.com/assets/21290778/18072591/d09db49a-6e5f-11e6-980a-2e89a55484a0.PNG)

Isn't it possible for s.o. from the project to filter these statistics on Version=2.0.1.19 and jobs with option "snapshots" turned on, in order to see if there's a significant drop compared with v.17 (measured in avg. MB per Job)?

**Comment by huste** [comment]
@NickPyz yes, there's something you're missing: Could you check if you use the no-backend-verification option. If so, remove it for once.

**Comment by mbrum** [comment]
I am using 2.0.1.19 on Windows 10 with administrator rights:
My default options under Settings are:
```
--usn-policy=Auto
--snapshot-policy=Auto
--auto-cleanup=true
--threshold=15
--symlink-policy=Store
```

A job without any advanced option configured runs without problems.
As soon as I add "`--snapshot-policy=On`" to the job, the job fails and shows "Source: 0 bytes".

After removing this option everything works well again.

**Comment by kenkendk** [comment]
I think this was caused by upgrading AlphaVSS, there is probably something changed in AlphaVSS, but the change does not cause the snapshot creation to fail, and thus there are no error messages.

I will check now on a Windows machine to see if I can fix it.

**Comment by kenkendk** [comment]
Ok, found the problem.

AlphaVSS does not return paths with the correct UNC prefix (`\?\\\`), so some string substitution fails, cutting 4 characters of the path and then giving an error on each file.

**Comment by kenkendk** [comment]
There is a new bug report in #1916.
Can some of you who had the "size = 0" problem report if the problem was fixed in 2.0.1.20, so I can rule out that VSS generally does not work in 2.0.1.20?

**Comment by huste** [comment]
Things are intertwined, it seems.
I modified one backup job that already ran successfully today. It had snapshot-policy=off. I changed it to "on" and manually started the job again. 

Here's the warning at the end of the job:
```
Warnings: [Failed to create a snapshot: System.UnauthorizedAccessException: Es wurde versucht, einen nicht autorisierten Vorgang auszuführen. bei Alphaleonis.Win32.Vss.VssBackupComponents..ctor() bei Alphaleonis.Win32.Vss.VssImplementation.CreateVssBackupComponents() bei Duplicati.Library.Snapshots.WindowsSnapshot..ctor(String[] sourcepaths, Dictionary`2 options) bei Duplicati.Library.Snapshots.SnapshotUtility.CreateSnapshot(String[] folders, Dictionary`2 options) bei Duplicati.Library.Main.Operation.BackupHandler.GetSnapshot(String[] sources, Options options, ILogWriter log) => Es wurde versucht, einen nicht autorisierten Vorgang auszuführen.] 
```
(Trying to execute an unauthorized process)
The source and target sizes are as reported properly.

Can this have something to do with the fact that I don't install duplicati, but unzip it to C:\Progs\duplicati? My Windows user has administrative rights.

**Comment by mbrum** [comment]
When I start duplicati.library.snapshots.exe or a job with the option `snapshot-policy=on`, then I get the following warning:
```
C:\Program Files\Duplicati 2>duplicati.library.snapshots.exe
Creating file C:\Program Files\Duplicati 2\testfile.bin
Attempting to read locked file C:\Program Files\Duplicati 2\testfile.bin
The file C:\Program Files\Duplicati 2\testfile.bin was correctly locked, message: Der Prozess kann nicht auf die Datei "C:\Program Files\Duplicati 2\testfile.bin" zugreifen, da sie von einem anderen Prozess verwendet wird.
Creating snapshot for folder: C:\Program Files\Duplicati 2
If this fails, try to run as Administrator
The snapshot tester failed: Alphaleonis.Win32.Vss.VssSnapshotSetInProgressException: The creation of a shadow copy is already in progress.
   bei Alphaleonis.Win32.Vss.VssBackupComponents.StartSnapshotSet()
   bei Duplicati.Library.Snapshots.WindowsSnapshot..ctor(String[] sourcepaths, Dictionary`2 options)
   bei Duplicati.Library.Snapshots.SnapshotUtility.CreateSnapshot(String[] folders, Dictionary`2 options)
   bei Duplicati.Library.Snapshots.Program.Main(String[] _args)
* Test failed
```
But the job is finished. The "size=0" problem doesn't occur anymore.

**Comment by huste** [comment]
@mbrum:  I find the message about testfile.bin interesting: It was locked correctly but access was denied?
And you already have a VSS running? Maybe your Windows is currently making updates?

**Comment by mbrum** [comment]
Sorry, seems that it was my fault.
The service VSS was set to manual (don't know why) and it was running constantly.
I stopped it and set it to automatic. Now it works well: 
```
Could open locked file C:\Program Files\Duplicati 2\testfile.bin, through snapshot
* Test passed
```

**Comment by kenkendk** [comment]
@huste: there is no difference between unzipping and using the MSI.
The MSI has some of the non-Windows icons etc removed, but otherwise it is just a copy of the zip file.

I don't know why you get permission denied if the user has administrative rights.

@mbrum : thanks for reporting, that means that at least some installs have a working VSS now.

**Comment by huste** [comment]
@kenkendk: Can I do something to help find the issue?

**Comment by kenkendk** [comment]
@huste : does the snapshot tool work for you?
That could indicate that the GUI.exe is running with limited powers.
This should be another issue, as comments on closed issues tend to go out of sight quickly.

**Comment by huste** [comment]
No. Running C:\Progs\duplicati\Duplicati.Library.Snapshots.exe gives me an error message:

```
Creating file C:\Progs\duplicati\testfile.bin
Attempting to read locked file C:\Progs\duplicati\testfile.bin
The file C:\Progs\duplicati\testfile.bin was correctly locked, message: Der Prozess kann nicht auf die Datei "C:\Progs\duplicati\testfile.bin" zugreifen, da sie von einem anderen Prozess verwendet wird.
Creating snapshot for folder: C:\Progs\duplicati
If this fails, try to run as Administrator
The snapshot tester failed: System.UnauthorizedAccessException: Es wurde versucht, einen nicht autorisierten Vorgang auszufhren.
   bei Alphaleonis.Win32.Vss.VssBackupComponents..ctor()
   bei Alphaleonis.Win32.Vss.VssImplementation.CreateVssBackupComponents()
   bei Duplicati.Library.Snapshots.WindowsSnapshot..ctor(String[] sourcepaths, Dictionary`2 options)
   bei Duplicati.Library.Snapshots.SnapshotUtility.CreateSnapshot(String[] folders, Dictionary`2 options)
   bei Duplicati.Library.Snapshots.Program.Main(String[] _args)
* Test failed
```

**Comment by huste** [comment]
There already is an issue #1701 , I'll repost there if necessary

**Comment by agrajaghh** [comment]
@huste did you run `Duplicati.Library.Snapshots.exe` with adminsitrator priviliges?

**Comment by martin54** [comment]
I don't have currently access to the PC with Duplicati, so I cannot test the new version, sorry.

**Comment by huste** [comment]
How much I hate Windows' cracked user model. It works when I create a batch file with a pause at the end to read the output and run it as administrator. Why is it not sufficient to run it as a user from the administrator group? And how do I start Duplicati with administrative rights from a batch file that doesn't run with administrative rights? runas.exe doesn't work, as it requires a password, which "run as administrator" doesn't.

**Comment by NickPyz** [comment]
2.0.1.20 is working for me. (Win 10 - 64bit)

I am no longer seeing the "Source=0" bug while running jobs where --snapshot-policy=on

I ran  Duplicati.Library.Snapshots.exe as admin, and received "could open locked file" ... which I assume means the test created a snapshot and was a pass.
