### ISSUE TITLE
HELP - How to disable software update notifications...

### ISSUE THREAD

**Issue by mcmastertek** [duplicati/duplicati#1986]
Duplicati Version: 2
Operating System: Windows 7 Pro

Need info on how to disable new update notifications or notifications in general for Duplicati version 2.

Thanks!!!

### Version info

**Duplicati Version:** 0.0.0.0
**Operating System:**
**Backend:**

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

**Comment by agrajaghh** [comment]
you can use `--auto-update = false` or set the environment variable `AUTOUPDATER_Duplicati_SKIP_UPDATE=1` to disable auto updates

If you don't want any notifications of the tray icon, just run `Duplicati.Server.exe` instead of `Duplicati.GUI.TrayIcon`

**Comment by AndrewDavis** [comment]
No offense, but I'd really like to be able to disable auto-updates as well. I would prefer to have my backup computer not accessing the internet at all to having it auto-update to any potential fixes. Also, it makes me uncomfortable that I have to set a more temporary variable/string in order to accomplish this (even environment variables get lost or reset from time to time). Could this become a more integral option for Duplicati, i.e. as one of the advanced options, so that the option is stored permanently in a file?

By the way, I think I'm getting this error when I launch the browser console and auto-updates are disabled: "Missing XSRF Token".
