### ISSUE TITLE
Feature request: Specify source by drive label

### ISSUE THREAD

**Issue by tophee** [duplicati/duplicati#2036]
In order to be able to backup external drives consistently, it is necessary for duplicati to detect these based on their drive labels rather than the drive letter since the latter can change.
##

**Comment by tophee** [comment]
To anyone who is facing the same problem: you can use USBDLM (USB Drive Letter Manager for Windows)  by Uwe Sieber ([http://www.uwe-sieber.de/usbdlm_e.html](http://www.uwe-sieber.de/usbdlm_e.html)) as a workaround). It allows you to reliably assign the same drive letter to drives based on their label.

**Comment by kenkendk** [comment]
You can use the option --alternate-target-path="*:\folder" and --alternate-destination-marker="markerfile.txt".
Then create an empty file in the destination folder called "markerfile.txt".

Duplicati will then scan all drive letters to find the file, and use the drive where the file is found.

Does that solve your issue?

**Comment by tophee** [comment]
As I understand it, this only looks at the path, not the label of the drive. It could be a workaround, though, if I I created a folder with a unique name on the external drives and put everything on the drive under that  folder. But in that case I think prefer my own workaround posted above cause I'd be artificially making my paths on that drive longer than necessary.

**Comment by kenkendk** [comment]
You specify the target drive as normal, but use `--alternate-target-path=*:\folder` to give the path without the real drive.
Then you put a file (with a name you choose) in the target folder and supply that name as `--alternate-destination-marker`.
This means there is no change in your setup, apart from an extra file.

But this relates to the _destination_ and your request is for the _source_.
A similar scheme could be used for source folders though.

**Comment by kenkendk** [comment]
@tophee Is the fix in #2707 sufficient to support your use case?

**Comment by tophee** [comment]
I'm not sure what exactly the fix includes. @tygill says that 

> it attempts to back up all drives rather than providing a better specification for the specific drive to backup

but I'm not sure what that means in practice. Does it mean that it checks all drives for relevant paths and if it finds them it assumes it is backing up the correct drive? That would sound a bit risky to me. (e.g. what if I have two drives with a similar folder structure?)

**Comment by tygill** [comment]
> Does it mean that it checks all drives for relevant paths and if it finds them it assumes it is backing up the correct drive?

That is what it does, so this behavior does have the possibility of backing up from multiple drives if they have the same file structure. (Whether or not this is a 'risk' depends on your point of view and use case.)

In my own experience, having multiple drives with the same file structure usually means that either the folders are copies / snapshots of one another (e.g., Y:\Photos is an older snapshot of X:\Photos), or are at least going to have similar backup patterns (if I want to backup C:\Projects, I'll probably want to backup D:\Projects as well).

In the first case, since most of the files should have the same (or similar) contents, the actual data backed up should be minimal, thanks to Duplicati's de-dup logic. In the second case, this behavior causes Duplicati to err on the side of backing up too much, rather than potentially missing something that should be backed up if a drive is assigned a new letter.

That said, I understand this behavior may not be ideal for some use cases - and I for those cases, I still think allowing sources to be keyed off of the drive label / ID would be valuable. And it's possible that the logic I added for handling * as the drive could be extended to also map an ID of the drive to the letter.
 (Possibly the `VolumeName` in the format `\\?\Volume{XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX}`, from [here](https://superuser.com/questions/465730/access-to-a-disk-drive-using-volume-id-instead-of-a-drive-letter-in-windows)? It would require System.Management , and I'm not sure how that would affect running under Mono on Mac / Linux.).

**Comment by tygill** [comment]
I actually took a look at prototyping this using the idea above, and it seems to be working. I'll try to get the pull request published once I get the documentation updated.

**Comment by tygill** [comment]
PR #2723 has been merged - is that enough to close this issue?

**Comment by warwickmm** [comment]
I think pull request #2723 closes this.
