### ISSUE TITLE
Wrong information about last successful run

### ISSUE THREAD

**Issue by cdrfun** [duplicati/duplicati#2070]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info
**Duplicati Version:** 2.0.1.28_canary_2016-10-19
**Operating System:** Windows NT 6.2.9200.0
**Backend:** Local Filesystem

### Bug description
Last successful run states "Yesterday at 7:14 PM". Today is 31.10.2016 but no restore is available for 30.10.2016. Also no files have been created for 30.10.2016. Also the Log seems wrong regarding times and doesn't list a hint why the backup is missing. This may be correlated with #2069. 

### Steps to reproduce
- not shure how to reproduce, maybe due to switch of summer/winter time? (see #2069)

**Actual result:** 
- Now backup was created for 30.10.2016
- Information about last successsfulll run indicates, that backup was created for 30.10.2016
- No Information about unsuccessfull run in Log
- EndTime seems to be wrong in Log (always 01.01.0001 00:00:00)
- BeginTime seems to be wrong in Log (different from information you see in "Last successful run")

**Expected result:** Backup for 30.10.2016.

### Screenshots
![000023-](https://cloud.githubusercontent.com/assets/146877/19852480/cf44a8c6-9f63-11e6-91fb-774712a7a0a2.png)

### debug log

> Oct 30, 2016 7:13 PM: Result
DeletedFiles: 0
DeletedFolders: 0
ModifiedFiles: 0
ExaminedFiles: 365135
OpenedFiles: 0
AddedFiles: 0
SizeOfModifiedFiles: 0
SizeOfAddedFiles: 0
SizeOfExaminedFiles: 132797409650
SizeOfOpenedFiles: 0
NotProcessedFiles: 0
AddedFolders: 0
TooLargeFiles: 0
FilesWithError: 0
ModifiedFolders: 0
ModifiedSymlinks: 0
AddedSymlinks: 0
DeletedSymlinks: 0
PartialBackup: False
Dryrun: False
MainOperation: Backup
CompactResults: null
DeleteResults:
    DeletedSets: []
    Dryrun: False
    MainOperation: Delete
    CompactResults: null
    VerboseOutput: False
    VerboseErrors: False
    EndTime: 01.01.0001 00:00:00
    BeginTime: 30.10.2016 18:12:41
    Duration: -736266.18:12:41.3110113
    BackendStatistics:
        RemoteCalls: 5
        BytesUploaded: 0
        BytesDownloaded: 235319847
        FilesUploaded: 0
        FilesDownloaded: 3
        FilesDeleted: 0
        FoldersCreated: 0
        RetryAttempts: 0
        UnknownFileSize: 0
        UnknownFileCount: 0
        KnownFileCount: 433
        KnownFileSize: 44113935165
        LastBackupDate: 29.10.2016 20:00:00
        BackupListCount: 5
        TotalQuotaSpace: 5991332573184
        FreeQuotaSpace: 3595406487552
        AssignedQuotaSpace: -1
        MainOperation: Backup
        VerboseOutput: False
        VerboseErrors: False
        EndTime: 01.01.0001 00:00:00
        BeginTime: 30.10.2016 18:00:00
        Duration: -736266.18:00:00.0105661
RepairResults: null
TestResults:
    MainOperation: Test
    Changes: []
    VerboseOutput: False
    VerboseErrors: False
    EndTime: 01.01.0001 00:00:00
    BeginTime: 30.10.2016 18:13:36
    Duration: -736266.18:13:36.8950549
VerboseOutput: False
VerboseErrors: False
EndTime: 01.01.0001 00:00:00
BeginTime: 30.10.2016 18:00:00
Duration: -736266.18:00:00.0105661
Messages: [
    No remote filesets were deleted,
    removing file listed as Temporary: duplicati-b936055900fea4db09ec7c41472262d6a.dblock.zip.aes,
    removing file listed as Temporary: duplicati-i28def09990404093915341b4cf44e58c.dindex.zip.aes
]
Warnings: []
Errors: []

**Comment by ts678** [comment]
2.0.5.1 Beta behavior is home screen `Last successful backup` is updated on backup, a log entry is created, both times are correct even if no new version for that time is created, due to no changes, which is how the original post looks -- check out all the 0 values.

One inconsistency that exists (not sure if it's a bug or a feature) is that version times on the dropdown are the start times, while the end time goes to "Last successful run", Regardless, many of the oddities here might be due to no change so no new backup version.

[upload-unchanged-backups](https://duplicati.readthedocs.io/en/latest/06-advanced-options/#upload-unchanged-backups) was available at least as far back as 2.0.2.1 Beta to create a new version even if no source files changed.

> If no files have changed, Duplicati will not upload a backup set.

Assuming there are a few typos in original post (which contradicts itself), I think all of this is either explainable or has now been fixed.

Should this be closed?

**Comment by warwickmm** [comment]
Yes, thanks @ts678.
