### ISSUE TITLE
Migrate Backup jobs from 1.3.4 to Duplicati 2

### ISSUE THREAD

**Issue by ThomasHeinrichSchmidt** [duplicati/duplicati#2093]
I wonder if there will be a migration path from version 1.3.4 to the new Duplicati.
I understand that the old backups are no longer usable by Duplicati 2, and this has a reason, i.e. to be able to use better technology for backup creation.
But what about the 17 backup jobs that I've created using version 1.3.4? 
I needed to split up my backup into different portions due to size, file and upload limitations on my cloud storage.
When switching to the new Duplicati I would not like to re-create all this jobs manually again.
Will there be a tool that helps me to migrate my version 1.3.4 backup jobs to Duplicati 2?

**Comment by kenkendk** [comment]
This is also discussed here: https://forum.duplicati.com/t/migrate-backup-configuration-from-1-3-4-to-2-0/1160

**Comment by peterschmidt01** [comment]
There is a very simple solution to this problem. Just install version 1,3.4 on the newer machine and you are in business! At least it worked for me.

**Comment by warwickmm** [comment]
Unfortunately, this is not possible since 1.3.4 didn't have the ability to export configurations.

**Comment by ThomasHeinrichSchmidt** [comment]
Why would you need to "export configurations"? 
All the Backup jobs are stored in "c:\Users\<User>\AppData\Roaming\Duplicati\Duplicati.sqlite". This DB is encrypted but can be decrypted and the content reviewed. 
All you need to migrate Backup jobs from 1.3.4 to Duplicati 2 is the knowledge about Duplicati.sqlite and the will to implement this in Duplicati 2.

**Comment by warwickmm** [comment]
Sorry, I closed this not because it is impossible, but simply because the ticket is so old and low priority that we don't have the resources to consider addressing this.

You're correct in that all we need is a way to extract configuration settings from the database into a form that can be consumed by Duplicati 2 (e.g., json).  The settings might not all map nicely, so there are some decisions to be made there.

I'll reopen this in case someone wants to take on this task.

**Comment by ThomasHeinrichSchmidt** [comment]
Thanks for your feedback, I do understand.
For me this means to stay with version 1.3.4 because it's too much effort to migrate to version 2.

**Comment by ThomasHeinrichSchmidt** [comment]
Thanks for reopening the issue.
I still wonder why I should be the only one having this requirement. Maybe they just don't show?
Is there a way to vote for issues?

**Comment by warwickmm** [comment]
I see the following ways of sorting issues, so users can comment, or give it thumbs up to indicate their interest.

![image](https://user-images.githubusercontent.com/17345532/92650238-12f62880-f2a1-11ea-9225-90eb7eb26677.png)

I only became aware of Duplicati a few years ago, so unfortunately I have zero knowledge about the 1.x versions.

**Comment by ThomasHeinrichSchmidt** [comment]
Let's see what's happening. If nothing, then close again please.

**Comment by ts678** [comment]
> Just install version 1,3.4 on the newer machine and you are in business!

[Download links for 1.3.4 are dead #5079](https://github.com/duplicati/duplicati/issues/5079) hit a snag where the old web link to old `sites.google.com` no longer works (site went away), had Linux dependency issues from a newer Linux, but wound up doing a `.zip` file install (likely works with Windows too).

> For me this means to stay with version 1.3.4 because it's too much effort to migrate to version 2.

Or maybe there's no reinstall, but hardware does eventually break, so need some replacement OS. Some people may need mono.

> Let's see what's happening. If nothing, then close again please.

That's about all I know of that's happening with this lately. Devs are fully occupied fixing Duplicati 2, and AFAIK, none know 1.3.4.
Last call, if anything more must be said, otherwise this will close after awhile.

**Comment by ThomasHeinrichSchmidt** [comment]
Finally, I installed Duplicati 2 and entered all my 25 backup jobs manually.
Since some of the jobs were quite similar, I exported the backup configuration for one of them. Then I created all the corresponding JSON configuration files with an AWK script like this one.
```# create Duplicati config files for all Fotos using Fotos+20xx-duplicati-config.json 
# C:\> FOR /L %y IN (2004,1,2022) DO gawk -f Fotos.awk -v year=%y Fotos+20xx-duplicati-config.json > Fotos+%y-duplicati-config.json

/"ID": x,/        { print A "    \"ID\": " year-2002 ","; next }
/      "ID=x"/    { print B "      \"ID=" year-2002 "\""; next }
/    "ID": "x",/  { print C "    \"ID\": \"" year-2002 "\","; next }
/20xx/            { gsub(/20xx/, year); print; next }

// { print}
```
It took me some time to get everything up and running, but now Duplicati 2 is doing its job and the issue is solved for me.

**Comment by ts678** [comment]
Thanks for the response and the conversion idea to help any others who have not yet migrated.
That would have been tough for the current developers to have come up with without research.
