### ISSUE TITLE
Broken tray icon on resume from suspend on Ubuntu 16.10

### ISSUE THREAD

**Issue by orschiro** [duplicati/duplicati#2177]
Dear all, 

I installed version 2.0.1.35 on Ubuntu 16.10.

On resume from suspend, the tray icon is broken. 

Can anyone help me resolve this problem?

Yours,

-Robert

![image](https://cloud.githubusercontent.com/assets/170947/21180818/fd258eea-c1fa-11e6-907c-202ced3b1e00.png)

**Comment by ts678** [comment]
[Red tray icon #3126](https://github.com/duplicati/duplicati/issues/3126) analyzed a red tray icon problem fixed in [2.0.3.5_canary_2018-04-13](https://github.com/duplicati/duplicati/releases/tag/v2.0.3.5-2.0.3.5_canary_2018-04-13), but I don't know if it's related to this.
That icon image doesn't look like the usual Duplicati one, even ignoring the red. Have you seen this shape before? Do you now?
I couldn't find that picture or any similar reports in Issues or Forum.
