### ISSUE TITLE
Translation issues

### ISSUE THREAD

**Issue by kees-z** [duplicati/duplicati#2190]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.35

### Bug description
During making a translation to Dutch with Poedit, I stumled upon some issues. 
Because of there is no reference to where in the user interface an entry is used, it is not always clear which Dutch word is the correct translation.
This is expecially the case with single-word entries. An amount of English words are the same for a noun or a verb.
Example:
The word "import" has to be translated to "import" if it's a noun (as in: The import completed successfully") and to "importeren" if it's a verb (for example: "you have to import the settings first").
In Poedit I only see the word "import" without any reference to what context it is used in the user interface, so I have to guess in these cases what would be the correct translation.

**Comment by agrajaghh** [comment]
I don't think we can do something about that. Transifex is displaying the occurences of the string, so its e.g. displaying:

> Occurrences:
templates/advancedoptionseditor.html:48

you can then open this file and maybe get some more info where the string is used. At least for the localization_webroot.pot you might find something usefull. Most of the strings from localization.pot are just coming from a strings.cs file which doesn't show you directly where its used. You need to search for the string ID or use an IDE to find out more I guess...

But if you are unsure where a specific string is used, you can open an issue at transifex and we we'll try to clarify it. 😊 

Btw, you also mentioned problems about specific strings including variables you couldn't translate because of the grammar used in english. Could you tell us which strings are causing problems? Maybe we can fix them so they are translatable...

**Comment by kees-z** [comment]
I'm not 100% sure about which strings were hard to translate. I guess "Exclude directories whose names contain" was one of them, but I've found a workaround for all of them.
