### ISSUE TITLE
Is my backup broken? 

### ISSUE THREAD

**Issue by plarner30** [duplicati/duplicati#2196]
Is something wrong here, what action should i take?

Source:256.00 GB
Backup:320.01 GB / 19 Versions

Actual total size of backup destination folder: 285GB

Duplicati - 2.0.1.35_experimental_2016-12-13

**Comment by agrajaghh** [comment]
What backend are you using?

**Comment by bunion** [comment]
SFTP to my web hosting

**Comment by bunion** [comment]
More info: I emptied the destination folder and cleared the local database and ran it again, dont know why its saying 19 versions

**Comment by bunion** [comment]
I am stuck in this cycle:

Run backup - > Found 1 remote files that are not recorded in local storage, please run repair
Run Repair - > 
Run Backup -> upload again
Make no changes to files
Run backup - > Found 1 remote files that are not recorded in local storage, please run repair
...

Backup GB does not match GB in destination

This is the problem i had before so i deleted all files on the target and started again, including recreating database.

I am backing up one 256GB image file. 

Source:256.00 GB
Backup:320.01 GB / 19 Versions

Actual backed up in destination 285GB 

There is no way there is 19 versions there as i tried to start again. How can i get out of this loop and start afresh.

**Comment by agrajaghh** [comment]
> There is no way there is 19 versions there as i tried to start again. How can i get out of this loop, does it entail starting afresh and how do i do that 100% completely.

I think the problem is that you just deleted the files at the destination folder and didn't delete the local database.

To start fresh, you should click on the backup name, than click on delete and check **Delete the local database** and **Delete remote files** like this:

![delete2](https://cloud.githubusercontent.com/assets/5296073/21749017/d3ce08ee-d594-11e6-82f0-fa7ffd1097cc.png)
