### ISSUE TITLE
Possibility of backing up OS

### ISSUE THREAD

**Issue by abpostelnicu** [duplicati/duplicati#2204]
Hello,

I'm running Duplicati on Debian server and i want to to backup my OS. I was wondering if this is possible.

**Comment by kenkendk** [comment]
Mostly no.

Duplicati can backup all the files in your OS, and will ignore all the special descriptors.

But when you need to restore, it is not so simple, because files need to be placed correctly on the disk. For a real OS backup, you need a "block level backup" and Duplicati is a "file level backup" system.

So you can restore all the files, but you need a real installation first, and then you can replace the files in the installation with a restore.
Since most of the OS is just installed from an image anyway, I see little benefit from making a backup of the entire system.
