### ISSUE TITLE
There is no easy way to import an existing backup

### ISSUE THREAD

**Issue by lucatrv** [duplicati/duplicati#2282]
Hi, I made a clean installation of Duplicati, deleting all previous local data. I still have all my destination backup folders, but I cannot find an easy way to import all previous backups. Maybe I should add new backups using the old backup folder as destination folder? But in this case I should remember all the old backups configuration settings...
There should be a link "Import backup" (just underneath "Add backup") which easily restores all settings (including the source folder) from the existing backup folder, or am I missing anything?
Thanks

**Comment by gorbiWTF** [comment]
You can export the configuration beforehand and later import the configuration. You import it under "Add backup", there are three dots on the right hand site. I can post a screenshot later, if you don't find it (it's not really obvious).

**Comment by agrajaghh** [comment]
> You import it under "Add backup", there are three dots on the right hand site. I can post a screenshot later,

yes, that should work.

> it's not really obvious

hm, I hoped it was obvious enough. Do you have an idea how we could better "hide" these advanced options?

**Comment by lucatrv** [comment]
Well... what if one did not export the backups configuration beforehand, for instance because he lost his AppData/Roaming/Duplicati folder?
IMHO there should be an "Import backup" link, just underneath the "Add backup" link. From there it should be possible to select either "Import backup from folder" or "Import backup configuration from file". Of course the backup configuration data should be stored on the backup destination folder upon every successful backup.

**Comment by gorbiWTF** [comment]
The configuration file contains the passwords (for encryption and if you use an online account) and other sensitive information. You would have to encrypt the configuration file (already possible) and then upload it at the same destination as the backup - maybe asking the question if the user wants this while creating a backup at step 5: "Backup the configuration file? Yes | No" and "Password to encrypt the configuration file:"

And then this:
> IMHO there should be an "Import backup" link, just underneath the "Add backup" link. From there it should be possible to select either "Import backup from folder" or "Import backup configuration from file". Of course the backup configuration data should be stored on the backup destination folder upon every successful backup.

This also solves the "problem" with the not so obvious three dots:
> hm, I hoped it was obvious enough. Do you have an idea how we could better "hide" these advanced options?


So I guess this could work, could it?

**Comment by kenkendk** [comment]
It could work, but I worry that we get a too large menu on the right.
I just added two new items there (Home and About), adding a new "Import backup" would expand this more.

Perhaps a sub-menu, like the one for "Pause" would do the trick, so you get an extra click, but keep the menu small. The sub menu would then have:

  - From scratch
  - From a configuration file
  - From a remote destination

Would that work?

**Comment by kenkendk** [comment]
We could also consider putting "log", "settings" and "about" into a "more" menu with sub-items?

Btw, the pause menu does not work on small screens as it pops out to the right, but we should fix that anyway.

**Comment by kenkendk** [comment]
There is support for storing the backup configuration on the remote destination, using the option `--control-file`, which can be used to inject files, such as the configuration file, into the backup. It is not currently being done, but that is easy to fix.

The hard(er) part is the restore, because it is likely that you restore to somewhere else. In this case you do not want the backup to run immediately after importing it. There could be settings, such as source folders, temporary folders, etc. that needs to change.

This could be solved by either letting the user edit the backup configuration after importing it, or marking the backup "frozen" or "inactive" after import.

**Comment by gorbiWTF** [comment]
> Perhaps a sub-menu, like the one for "Pause" would do the trick, so you get an extra click, but keep the menu small. 


> We could also consider putting "log", "settings" and "about" into a "more" menu with sub-items?

> Btw, the pause menu does not work on small screens as it pops out to the right, but we should fix that anyway.

Sounds good to me! Maybe you can change the menu on mobile like at https://download.lineageos.org/ where the menu just expands if you click on something.


> This could be solved by either letting the user edit the backup configuration after importing it, or marking the backup "frozen" or "inactive" after import.

I guess both works, editing it right after import seems better to me.

**Comment by lucatrv** [comment]
I agree to add the three sub menus to the "Add backup" link! (good idea)

IMHO once imported, the "From a configuration file" and "From a remote destination" commands should behave exactly like the "From scratch" command, so they should just add the backup without running it. The user can edit the configuration afterwards if he wants to. All these three commands should **add** the backup, if instead you want to restore a backup you would click on the "Restore backup" link.

Note: I just wonder... if one does not encrypt his backup (for instance because it includes only non sensitive data) whether his online account password is encrypted both locally and remotely...

**Comment by kees-z** [comment]
> It could work, but I worry that we get a too large menu on the right.

I cannot agree more about this.
The menu should be as short as possible, containing only the primary tasks of Duplicati, which are:
Add backup, Restore backup, Settings and Show log.
The other menu options are shortcuts to external sites and program functions that do not perform an operation that is directly related to making or restoring a backup. These icons can be placed in the header.

If the Menu button in the upper right corner moves to the upper left corner, the best location for these icons is the upper right corner. The word MENU should be removed, so the Menu icon can be placed at the left side of the word Duplicati.

The main screen could look something like this:

![duplicati ui](https://cloud.githubusercontent.com/assets/24669568/22388071/fddd13b0-e4de-11e6-9b32-3a2a888fa3b1.PNG)

Of course the Logout button should only be displayed if a password is set to the user interface.
The @ Icon could show a dropdown menu (with links to Facebook, Google+ etc), or can be combined with the About button, so again one icon can be removed.

Placing the menu in the upper left corner also solves issue #2286 (section 2).
If the Pause option stays in the main menu instead of an icon in the header, the "submenu problem" Kenneth mentioned will also be solved.

I don't see much sense in an import-backup option, unless I'm overlooking something. It doesn't add anything useful to the "Restore backup" menu option.
If you loose your configuration or want to restore to a different machine, with the "import config from backup" you have to specify all settings for making a connection to the backend. Also the encryption passphrase has to be specified manually (I suppose the configuration file will be encrypted, otherwise encryption will be useless!).
In the Restore backup wizard, you have to enter this information:
- URL and credentials to connect to the backend: this must also be entered manually if you want to downoad a config file from the backend
- Encryption passphrase: also this must be entered manually to be able to decrypt the downloaded config file.
- File / folder tree: this is displayed in the Restore wizard after entering Backend URL/credentials and passphrase.

So: in which specific situation will an "import config from backend" add any value to the "Restore backup" option?

**Comment by lucatrv** [comment]
The "Import backup" command is to add an existing backup in order to run it again, while the "Restore backup" command is to restore the backup data. It is useful when for whatever reason you lose your `AppData\Roaming\Duplicati` folder, for instance because you made a clean new installation, or you accidentally deleted it, or you lost your hard drive and did not back it up, or you upgrade your hard drive and forget to keep the `AppData\Roaming\Duplicati` folder, etc. Without the "Import backup" feature for each destination folder you would need to remember all configuration settings (source data, filters, timing schedule, advanced settings, etc).

**Comment by kees-z** [comment]
In some cases it can indeed be useful to import a backup configuration from the backend.
Note that you **always** need the URL and credentials for logging in to the backend, as well as the passphrase used for encryption to get access to the config. So if you forget the passphrase for encryption, the config as well as the backup itself are lost.
This is why exporting the config to a file and storing it somewhere else is the preferred way IMHO.

This feature should be needed very occasionally, especially if there is a .json file available, but in some situations it can be handy that you can recover from a situation that there is a backup, but the configuration is lost.

In my opinion the best location for this feature is at the same place as where the "import a backup configuration from file" is. A second item "import a backup configuration from backend" could be added to the "three-dots-menu" in the Add backup-wizard. Asking for protocol, url, credentials and passphrase should be enough to import the configuration from the most recent backup.

Probably the config can be added automatically with each backup to a dlist file when completing a backup? When using a dlist file, no extra files need to be created at the backend. When importing a backup, Duplicati could simply open the most recent dlist file and extract the configuration from it.

**Comment by lucatrv** [comment]
Actually I would prefer Kenneth's proposal to add a sub-menu to the "Add backup" menu, like the one for "Pause", which could be detailed as follows:

- Create new backup
- Import backup from configuration file
- Import backup from back-end folder

No password / passphrase need to be saved remotely, because in any case you would need to know them in order to reach the remote folder and to access an encrypted backup. So only the backup configuration should be saved in the back-end folder without password / passphrase.

**Comment by kees-z** [comment]
Sounds like a logical way to implement importnig backups, but adds items to the menu structure that are not frequently used. I like to see the main menu as short/simple as possible.

I agree that the "three-dots" button in the Add backup-wizard is overlooked easily. How about adding a link to importing backups in the Add backup-wizard link this:

![importbackup1](https://cloud.githubusercontent.com/assets/24669568/22438860/c963f88c-e72d-11e6-94ed-97341caf0229.png)

When clicking "Import a backup configuration", a menu like this could be displayed:

![importbackup2](https://cloud.githubusercontent.com/assets/24669568/22438903/f04afd38-e72d-11e6-89a3-2df30da8e7e0.png)

When "From Remote Destination" is selected, of course the lower part of the window should ask for protocol, url, credentials and passphrase to access the backup location.
 
Clicking the Import button returns to the Add backup-wizard to optionally change one or more settings.

**Comment by kenkendk** [comment]
I think this now fixed with the new add/import menu

**Comment by mkatsevVR** [comment]
So how exactly does "Load a configuration from a storage provider" work? It asks for the configuration file - what does it mean and where do I get one?

**Comment by kenkendk** [comment]
@mkatsevVR If your storage provider supports Duplicati, they can add a button or similar that provides the configuration file. I am not aware of any publicly available providers that supports this.

If you want to make one, the easiest is to configure a backup, export it to an unencrypted file and edit it (removing the source folders etc).

**Comment by mkatsevVR** [comment]
wouldn't it make sense for Duplicati to automatically store the configuration (sans passwords) alongside the backup and allow importing it on a new computer using the interface similar to the "Direct restore from backup files" feature?

the comments on this issue were requesting this functionality as far as I can tell, but it's closed now without that functionality actually existing...

**Comment by 13dimitar** [comment]
Would be nice if this functionality was available via cli, what would happen if one needs to configure backup on 200+ servers (at least I wasn't able to find a solution for Duplicati)?

**Comment by Hoffenbar** [comment]
I have created a backup with the command line tool. It´s not visible within the gui. Found no way to import it. Don't know that the *configuration file* is - the sqlite DB isn't it.
