### ISSUE TITLE
Request: duplicati official dockerhub images

### ISSUE THREAD

**Issue by cguentherTUChemnitz** [duplicati/duplicati#2309]
I have:
- [ x] searched open and closed issues for duplicates
----------------------------------------

Duplicati targets especially the market of server based backup systems. It seems to be a big project, which is good maintained, up to date and widely used. So it surprises me that there is no official duplicati image on dockerhub, where a lot of people, like me, are looking for easy maintainable server services.

There are some guys who are providing good looking images like this one:
https://hub.docker.com/r/intersoftlab/duplicati/

But nevertheless, they are not officially maintained and they are not in sync the the duplicati release cycle. E.g. there latest one is not the latest duplicati release.

So i would vote to use the image as good starting point and use the dockerhub github integration / hooks to automatically rebuild the dockerimages on github changes or tags.
https://github.com/dmitryint/docker-duplicati

I think an available official dockerhub image would even further push the distribution of the duplicati service into server systems.

**Comment by kenkendk** [comment]
Nice!

I would like that to be integrated into the build script so it generates Docker images on build.

The build script is here: https://github.com/duplicati/duplicati/blob/master/build-release.sh

**Comment by fkrull** [comment]
Any update on this? Because if not, I'll work on it -- I'm gonna need some Duplicati Docker images anyway, so I might as well do it properly.

**Comment by kenkendk** [comment]
@fkrull I have not looked at it yet

**Comment by fkrull** [comment]
Okay, I've some images for preliminary review.
Dockerfile: https://github.com/fkrull/duplicati-docker
Test builds: https://hub.docker.com/r/fkrull/duplicati/

These download the builds for a specific version for now; for build script purposes, that part would be replaced with just copying the build from a local directory, but I haven't done that yet.

Some discussion of design decisions:

* I added tini, a "tiny but valid init"; without it, Duplicati doesn't handle signals correctly and at least Ctrl-C to stop the container doesn't work (there's some special-casing where PID 1 processes don't get default signal handlers and other things in the kernel). Docker since 1.13 has the `--init` flag that has the same effect (it actually uses tini internally), but I didn't want to rely on a relatively obscure flag for Ctrl-C to work.
* I've settled on running duplicati as root inside the container. That's generally not recommended, but otherwise the permissions get tricky because the duplicati user needs access to all files that should be backed up. 
* All files get written into `/data` which can be mounted as a volume to persist state.
* The image for amd64 is 278 MB which is reasonable, I feel.

The shortest useful invocation is

```
docker run -p 8200:8200 fkrull/duplicati:linux-amd64-2.0.2.12_canary_2017-10-20
```

More commonly, something like  this:

```
docker run -p 8200:8200 -v duplicati-data:/data -v /my/stuff:/my/stuff fkrull/duplicati:linux-amd64-2.0.2.12_canary_2017-10-20
```

In practice the image would probably be called `duplicati/duplicati` and would be used without a tag or with a channel, rather than the full version.

---

Open questions, as of yet:
* Integrating this into the build scripts. Shouldn't be too hard.
* Multi-architecture support. The Dockerfile, as it stands, build on any platform that [the base image exists for](https://hub.docker.com/_/mono/), but docker doesn't support cross-building across architectures in any useful way. But I absolutely want an image for my Raspberry Pi now :D I do have an idea that I'll investigate about how to do that without leaving behind any artifacts in the final image.
* Re: Raspberry Pi, the mono image only supports armv7, which is fine for the Pi 2 and 3, but not the original Pi or the Zeros which only go up to armv6. I do have a Pi Zero coming in so I'll try it. Also, see if I can get them to add an image for that.

**Comment by JonMikelV** [comment]
Does this release satisfy this ticket?
https://forum.duplicati.com/t/release-2-0-2-20-canary-2018-02-27/2671

**Comment by ts678** [comment]
[https://hub.docker.com/r/duplicati/duplicati](https://hub.docker.com/r/duplicati/duplicati)
has duplicati official dockerhub images from 2.0.2.20_canary_2018-02-27 through 2.0.5.103_canary_2020-02-18, though I'm asking whether a later build change lost 2.0.5.104_canary_2020-03-25. Ignoring a possible new issue, is the ticket satisfied?

**Comment by warwickmm** [comment]
Docker images are being published.
