### ISSUE TITLE
Temporary files left behind

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#2415]
On some connection errors, it appears that temporary files are left behind.

**Comment by warwickmm** [comment]
@kenkendk, is this the same as issue #2465?  It sounds like that issue was fixed in 2.0.3.8.

**Comment by warwickmm** [comment]
I think this was [fixed](https://github.com/duplicati/duplicati/commit/be6093b7a61eca8152cb4babcc61011461be66fb)  in version 2.0.3.8. If someone finds that this issue has not been resolved, we can re-open this.

**Comment by kmwoley** [comment]
I am consistently getting one additional temporary file left behind with each backup run. My temp directory has a dup- file for each and every backup run on one of my sets since December 3rd of this past year and continues to this date.

Currently on 2.0.4.5_beta_2018-11-28
(via "linuxserver/duplicati" Docker container on an UnRaid Linux server.)

One thing I've noticed in testing - the temp files appear to only be left behind when the backup runs against a data set with no changes. If there are changed files, the dup-* temp files created are removed after the backup runs.

It also appears to be the dup-* files created during the backup. The temp files created during verification are always deleted correctly.
