### ISSUE TITLE
Unknown header: 1930147637

### ISSUE THREAD

**Issue by Aconitasi** [duplicati/duplicati#2444]
I have:
- [X ] searched open and closed issues for duplicates

----------------------------------------

### Version info
**Duplicati Version:** 2.0.1.53_experimental_2017-03-1
**Operating System:** Windows 10

### Bug description
When I'm trying to restore files from encripted backup, I come across the following problem:
 Failed to patch with remote file: "duplicati-bfbf49f03fc3a40258abf22171384c998.dblock.zip.aes", message: Unknown header: 1930147637 => Unknown header: 1930147637
I reported below the complete debug log results.

### Steps to reproduce
- do a backup
- restore a file from the backup

### complete debug log results
FilesRestored: 0
SizeOfRestoredFiles: 0
FoldersRestored: 0
SymlinksRestored: 0
FilesPatched: 0
FilesDeleted: 0
FoldersDeleted: 0
SymlinksDeleted: 0
MainOperation: Restore
RecreateDatabaseResults: null
ParsedResult: Error
EndTime: 26/04/2017 16:16:54
BeginTime: 26/04/2017 15:27:34
Duration: 00:49:19.0750787
Messages: [
    Searching backup 0 (10/04/2017 13:30:05) ...,
    1 remote files are required to restore,
    Failed to restore 1 files, additionally the following files failed to download, which may be the cause:
duplicati-bfbf49f03fc3a40258abf22171384c998.dblock.zip.aes
]
Warnings: [
    Impossibile trovare il file 'C:\Users\manenti.fabio\Desktop\Restore\topi elenco KPC eco e MR.xlsx'. => Impossibile trovare il file 'C:\Users\manenti.fabio\Desktop\Restore\topi elenco KPC eco e MR.xlsx'.
]
Errors: [
    Failed to patch with remote file: "duplicati-bfbf49f03fc3a40258abf22171384c998.dblock.zip.aes", message: Unknown header: 1930147637 => Unknown header: 1930147637
]
BackendStatistics:
    RemoteCalls: 2
    BytesUploaded: 0
    BytesDownloaded: 75316816813
    FilesUploaded: 0
    FilesDownloaded: 1
    FilesDeleted: 0
    FoldersCreated: 0
    RetryAttempts: 0
    UnknownFileSize: 0
    UnknownFileCount: 0
    KnownFileCount: 99
    KnownFileSize: 80885102711
    LastBackupDate: 26/04/2017 16:10:28
    BackupListCount: 33
    TotalQuotaSpace: 11401682743296
    FreeQuotaSpace: 10827560595456
    AssignedQuotaSpace: -1
    ParsedResult: Success

If you need more details, I'll send you
In apptempting to your quickly reply, best regards
Fabio Manenti

**Comment by Aconitasi** [comment]
Update: By decrypting some backup files, I found that the decrypted zip does not open, giving the following error: Cannot open file: it does not appear to be a valid archive.
Seems to be a problem as to how zip files are generated, as you wrote in other similar issues. However from what I understood the problem had to be corrected with the March update!

**Comment by Aconitasi** [comment]
Update: Error found in another pc using Duplicati:

> 27 apr 2017 09:58: Failed while executing "Backup" with id: 1
System.NotSupportedException: Unknown header: 466721199
   at SharpCompress.Common.Zip.ZipHeaderFactory.ReadHeader(UInt32 headerBytes, BinaryReader reader, Boolean zip64)
   at SharpCompress.Common.Zip.SeekableZipHeaderFactory.<ReadSeekableHeader>d__3.MoveNext()
   at SharpCompress.Archives.Zip.ZipArchive.<LoadEntries>d__16.MoveNext()
   at SharpCompress.LazyReadOnlyCollection`1.LazyLoader.MoveNext()
   at Duplicati.Library.Compression.FileArchiveZip.GetEntry(String file)
   at Duplicati.Library.Compression.FileArchiveZip.OpenRead(String file)
   at Duplicati.Library.Main.Volumes.VolumeReaderBase..ctor(ICompression compression, Options options)
   at Duplicati.Library.Main.Volumes.BlockVolumeReader..ctor(String compressor, String file, Options options)
   at Duplicati.Library.Main.Operation.CompactHandler.DoCompact(LocalDeleteDatabase db, Boolean hasVerifiedBackend, IDbTransaction& transaction)
   at Duplicati.Library.Main.Operation.DeleteHandler.DoRun(LocalDeleteDatabase db, IDbTransaction& transaction, Boolean hasVerifiedBacked, Boolean forceCompact)
   at Duplicati.Library.Main.Operation.BackupHandler.CompactIfRequired(BackendManager backend, Int64 lastVolumeSize)
   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
   at Duplicati.Library.Main.Controller.<Backup>c__AnonStorey0.<>m__0(BackupResults result)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)
   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)

**Comment by kenkendk** [comment]
Are the files larger than 4GiB ?

There is a problem with the current experimental (and all versions before it) that it overflows if the zip file is larger than 4GiB.

This has been fixed in the latest canary, and it has a fallback mechanism that can recover data from some of the defect 4GiB files+ .

You can grab the latest canary build here:
https://github.com/duplicati/duplicati/releases

This is likely a duplicate of #1877

**Comment by boeffi** [comment]
copy-and-paste from http://127.0.0.1:8200/ngax/index.html#/:

Name: "share to local 2 TB b"
Last successful run:Today at 9:20 AM (took 00:00:27)Run now
Source:1,22 TB
Backup:1,07 TB / 5 Versions

Hello,
I get a variant of previous posts. What is recommend as a "repair" strategy ?

There are dozens of files to backup with file sizes > 4 GByte. If possible I don't want to full backup all the files due to source size 1,22 TB.

Best regards

**Version info**

Duplicati Version: 2.0.1.64_canary_2017-06-02

previous same issue with
- 2.0.1.60_canary_2017-05-23
- 2.0.1.53_experimental_2017-03-1
Operating System: Windows 10 64-bit

**Bug description**

after backup I get the error "Failed: Unknown header: 3356609520"

**Steps to reproduce**

do a backup

**complete debug log results**

email/log step 1:
subject: [Fatal] DC Backup for share to local 2 TB b

Failed: Unknown header: 3356609520
Details: System.NotSupportedException: Unknown header: 3356609520
   bei SharpCompress.Common.Zip.ZipHeaderFactory.ReadHeader(UInt32 headerBytes, BinaryReader reader, Boolean zip64)
   bei SharpCompress.Common.Zip.SeekableZipHeaderFactory.GetLocalHeader(Stream stream, DirectoryEntryHeader directoryEntryHeader)
   bei SharpCompress.Common.Zip.SeekableZipFilePart.LoadLocalHeader()
   bei SharpCompress.Common.Zip.SeekableZipFilePart.GetCompressedStream()
   bei Duplicati.Library.Compression.FileArchiveZip.OpenRead(String file)
   bei Duplicati.Library.Main.Volumes.BlockVolumeReader.ReadBlock(String hash, Byte[] blockbuffer)
   bei Duplicati.Library.Main.Operation.CompactHandler.DoCompact(LocalDeleteDatabase db, Boolean hasVerifiedBackend, IDbTransaction& transaction)
   bei Duplicati.Library.Main.Operation.DeleteHandler.DoRun(LocalDeleteDatabase db, IDbTransaction& transaction, Boolean hasVerifiedBacked, Boolean forceCompact)
   bei Duplicati.Library.Main.Operation.BackupHandler.CompactIfRequired(BackendManager backend, Int64 lastVolumeSize)
   bei Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
   bei Duplicati.Library.Main.Controller.<>c__DisplayClass16_0.<Backup>b__0(BackupResults result)
   bei Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)

email/log step 2
subject: [] DC Compact for share to local 2 TB b

Failed: Unknown header: 3356609520
Details: System.NotSupportedException: Unknown header: 3356609520
   bei SharpCompress.Common.Zip.ZipHeaderFactory.ReadHeader(UInt32 headerBytes, BinaryReader reader, Boolean zip64)
   bei SharpCompress.Common.Zip.SeekableZipHeaderFactory.GetLocalHeader(Stream stream, DirectoryEntryHeader directoryEntryHeader)
   bei SharpCompress.Common.Zip.SeekableZipFilePart.LoadLocalHeader()
   bei SharpCompress.Common.Zip.SeekableZipFilePart.GetCompressedStream()
   bei Duplicati.Library.Compression.FileArchiveZip.OpenRead(String file)
   bei Duplicati.Library.Main.Volumes.BlockVolumeReader.ReadBlock(String hash, Byte[] blockbuffer)
   bei Duplicati.Library.Main.Operation.CompactHandler.DoCompact(LocalDeleteDatabase db, Boolean hasVerifiedBackend, IDbTransaction& transaction)
   bei Duplicati.Library.Main.Operation.CompactHandler.Run()
   bei Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)

email/log step 3
subject: [] DC Test for share to local 2 TB b

MainOperation: Test
Verifications: [
    Key: duplicati-20170603T074122Z.dlist.zip.aes
    Value: [],
    Key: duplicati-i998c2126298141209d70a70c8bfc0b70.dindex.zip.aes
    Value: [],
    Key: duplicati-b5ef2235460594d0e8cb915be495c23cc.dblock.zip.aes
    Value: []
]
VerboseOutput: False
VerboseErrors: False
ParsedResult: Success
EndTime: 03.06.2017 08:19:09
BeginTime: 03.06.2017 08:16:40
Duration: 00:02:29.5878623
Messages: [
    removing file listed as Temporary: duplicati-b59555ea5f2924234bf963122622e2354.dblock.zip.aes,
    removing file listed as Temporary: duplicati-i174733d2699246f0adb6631f23f2bfda.dindex.zip.aes
]
Warnings: []
Errors: []

email/log step 4
subject: [] DC Compact for share to local 2 TB b

Failed: Unknown header: 3356609520
Details: System.NotSupportedException: Unknown header: 3356609520
   bei SharpCompress.Common.Zip.ZipHeaderFactory.ReadHeader(UInt32 headerBytes, BinaryReader reader, Boolean zip64)
   bei SharpCompress.Common.Zip.SeekableZipHeaderFactory.GetLocalHeader(Stream stream, DirectoryEntryHeader directoryEntryHeader)
   bei SharpCompress.Common.Zip.SeekableZipFilePart.LoadLocalHeader()
   bei SharpCompress.Common.Zip.SeekableZipFilePart.GetCompressedStream()
   bei Duplicati.Library.Compression.FileArchiveZip.OpenRead(String file)
   bei Duplicati.Library.Main.Volumes.BlockVolumeReader.ReadBlock(String hash, Byte[] blockbuffer)
   bei Duplicati.Library.Main.Operation.CompactHandler.DoCompact(LocalDeleteDatabase db, Boolean hasVerifiedBackend, IDbTransaction& transaction)
   bei Duplicati.Library.Main.Operation.CompactHandler.Run()
   bei Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)

email/log step 5
subject: [] DC Repair for share to local 2 TB b

MainOperation: Repair
VerboseOutput: False
VerboseErrors: False
ParsedResult: Success
EndTime: 03.06.2017 09:23:10
BeginTime: 03.06.2017 09:22:42
Duration: 00:00:27.8245385
Messages: [
    removing file listed as Temporary: duplicati-b96355047253843a39815cd661a5ba922.dblock.zip.aes,
    removing file listed as Temporary: duplicati-i8cb73b97103f4afbb1da9c1921987c31.dindex.zip.aes,
    Destination and database are synchronized, not making any changes
]
Warnings: []
Errors: []

**Comment by ts678** [comment]
> There is a problem with the current experimental (and all versions before it) that it overflows if the zip file is larger than 4GiB.

> There are dozens of files to backup with file sizes > 4 GByte.

> This is likely a duplicate of https://github.com/duplicati/duplicati/issues/1877

which was fixed and closed in 2017. This will close unless there's something more.
