### ISSUE TITLE
Found X remote files that are not recorded in local storage, please run repair

### ISSUE THREAD

**Issue by mmiat** [duplicati/duplicati#2449]
I've this error persecuting me...
in 2 server, I've configured to backup to Amazon Cloud Drive and after every backup I've this error, and repair doesn't fix, I've to delete and rebuild entire db

**Comment by saviodsouza** [comment]
D.commandline.exe has two more options that helped me when I faced the same issue but a different backend.

list-broken-files
purge-broken-files

Duplicati.Cammandline.exe help list-broken-files
Duplicati.Cammandline.exe help purge-broken-files

See the help options and try first with --dry-run

**Comment by mmiat** [comment]
ok, thanks, I've tried:

with
`Duplicati.CommandLine.exe list-broken-files --dry-run amzcd://REMOTE_FOLDER --dbpath=C:\Windo
ws\System32\config\systemprofile\AppData\Roaming\Duplicati\NGPASSJGNJ.sqlite --authid="MY_ACD_ID"  --no-encryption`

I've this message:

> No broken filesets found in database, checking for missing remote files
  Listing remote folder ...
Skipping operation because no files were found to be missing, and no filesets were recorded as broken.

and with purge-broken-files I've same message

**Comment by TeeKay2000** [comment]
I've had this problem as well. Also tried it from two different servers.

At a closer inspection of the remote folder in ACD it seems that there are some dindex files that are missing.
If I'm not mistaken, there should be a dindex file for each dblock file uploaded. But for some reason they aren't uploaded to ACD.

As stated, by the original poster, the repair function doesn't seem to fix this issue. 
The log shows the following:

```
30 apr 2017 11:36: RemoteOperationDelete took 00:00:15.682
30 apr 2017 11:36: Backend event: Delete - Completed: duplicati-b3216f196c367482f92c1971c89416a18.dblock.zip.aes (499,99 MB)
30 apr 2017 11:36: ExecuteScalarInt64: INSERT INTO "Remotevolume" ("OperationID", "Name", "Type", "State", "Size", "VerificationCount", "DeleteGraceTime") VALUES (?, ?, ?, ?, ?, ?, ?); SELECT last_insert_rowid(); took 00:00:00.000
30 apr 2017 11:36: Starting - ExecuteScalarInt64: INSERT INTO "Remotevolume" ("OperationID", "Name", "Type", "State", "Size", "VerificationCount", "DeleteGraceTime") VALUES (?, ?, ?, ?, ?, ?, ?); SELECT last_insert_rowid();
30 apr 2017 11:36: Backend event: Delete - Started: duplicati-b3216f196c367482f92c1971c89416a18.dblock.zip.aes (499,99 MB)
30 apr 2017 11:36: Starting - RemoteOperationDelete

```
The remote folder in ACD, however, still has all the files. Nothing gets deleted.

I also tried to remove the backup entirely by selecteing "Delete remote files" with no effect.
So if you want to delete files on the remote storage you have to do it manually it seems.

Any insight to what the cause might be on this issue?

I'm using v2.0.1.56-2.0.1.56_canary_2017-04-21.

**Comment by sjonez** [comment]
I've seen this issue with ACD too, the log clearly shows it's deleting remote files but they're still present on the server afterwards. Is there an issue deleting files in ACD?

**Comment by sjonez** [comment]
To answer my own question yes there is, I added some logging to the Delete function in AmzCD.cs and the the try-catch block doesn't have any handling in it, but it appears every time for me it's catching and swallowing this exception:

"When performing a write operation with AllowWriteStreamBuffering set to false, you must either set ContentLength to a non-negative number or set SendChunked to true"

**Comment by mmiat** [comment]
ACD has some limitations, but they are not known (max upload speed for example)
maybe setting some timeout can fix the problem?

**Comment by mmiat** [comment]
can #1893 be related?

**Comment by TeeKay2000** [comment]
I have tried the setting "amzcd-consistency-delay" with 15 seconds without results.
Don't know if the setting affects deletes though.

As for speed limitations i've found that the amazon server you're connecting to can be a big factor.
Results can look as following:
```
52.1.18.102		300+ Mbit/s
54.86.248.15		5 Mbit/s
54.210.111.186		170-290 Mbit/s
54.210.205.230		10-90 Mbit/s		Unstable
```
I've used dblock sizes ranging from 50MB, 500MB and 2GB.

The thing is that i don't remember having this problem on older releases of duplicati.

The problem I was facing then was the "out of memory" error, where I would try to do a big backup and after a while windows would get the "out of memory error" for Duplicati consuming lots of memory (almost 10GB RAM).
Then I had to close and restart the program, make a repair and continue the backup. It did continue after repair but eventually run into the "out of memory" error again.
Never got a full backup done.

The "out of memory error" is now fixed with this latest version of Duplicati, it draws practically nothing now, but now there is the problem of missing uploads of dindex files, and failiure to repair it and/or deleting.

Don't know if there was a change in the ACD backend or Duplicati.
All the large dblock files seem to be uploading fine.

**Comment by mmiat** [comment]
at this point, I suspect ACD is not reliable
probably, using its own client can fix issues about different servers, but other clients like rclone or duplicati can't
maybe it's better to use another cloud storage like dropbox or box (that have unlimited plan too)

**Comment by sjonez** [comment]
The exception I'm seeing is coming from .NET before any comms has taken place, it's basically saying the function is being used incorrectly. It's not an error from ACD. I've still got some files in my trash back before I moved to the canary update channel so it's possibly something that changed between 2.0.1.53 and 2.0.1.56

I've got it to work myself by changing the following line in AmzCD.cs (function Delete)

`using (m_oauth.GetResponse(string.Format("{0}/trash/{1}", MetadataUrl, fileID), null, "PUT"))`

to

`using (m_oauth.GetResponse(string.Format("{0}/trash/{1}", MetadataUrl, fileID), new System.IO.MemoryStream(), "PUT"))`

I suppose this works because it forces the ContentLength to be 0 as I'm now passing in an empty stream instead of null. Regardless this works for me and now files are being deleted (and running a repair on my backup job works again) but I'm unsure what the "proper" fix should be, as I suspect the issue is somewhere in the JSON or oAuth helpers, and there could be other requests that are failing in the same way when sending a request such as PUT without a payload.

**Comment by mmiat** [comment]
@sjonez 
do you suggest to try a downgrade to versione 2.0.1.53 ?

**Comment by mmiat** [comment]
I downgraded to 2.0.1.52

server A) deleted and recreated db, relaunched, it's now running
server B) only repaired db, relaunched, it's now running

stay tuned

PS in server B, web interface tell me that I'm running 2.0.1.55, but the versione is 2.0.1.52

**Comment by sjonez** [comment]
You need to confirm that files can be deleted, which doesn't need to happen right away on a new backup. I'd suggest configuring the backup to only keep 1 version of each file, change a few files then backup again. This should force some deletions on the server side.

You can check your trash folder in ACD to see if files are being deleted.

**Comment by Vaporizer8** [comment]
I can confirm that the issue started with 2.0.1.56. I upgraded to 2.0.1.56 from 2.0.1.55 on one system and from 2.0.1.54 on another. Both systems had failing backups since the 28th of April and no deleted items appeared in the ACD trash folder since then. I reverted to 2.0.1.55, the ACD trash folder started getting filled and all backups were immediately running okay again.
I suspect it is caused by 015a92343fa0dc092511e24936ddbc2a8db467ad as that is the only commit between .55 and .56 that affects ACD.

**Comment by sjonez** [comment]
actually, I'm pretty sure it's [f9e5eea](https://github.com/duplicati/duplicati/commit/f9e5eeae0caa3ca238fe1df768b5999b455df024) as it changes AllowWriteStreamBuffering to false which corresponds exactly with the exception I see during deleting of `When performing a write operation with **AllowWriteStreamBuffering set to false**, you must either set ContentLength to a non-negative number or set SendChunked to true`

**Comment by TeeKay2000** [comment]
Could this also be the cause that some of the small dindex files not getting uploaded? Because that seems to why the repair wants to delete lots of files in the first place?

**Comment by mmiat** [comment]
after downgrade my backup was completed, but one of them with some warnings: #2453

**Comment by kenkendk** [comment]
@sjonez Yes, good catch, I was not aware of this. I need to go through all calls that use the async-wrapper and check that they set the content length explicitly now.

**Comment by sjonez** [comment]
Good stuff. It might also be a nice idea to add some throws in some of the empty exception handlers. Without my extra logging you wouldn't even know the Deletes were failing without checking the ACD trash folder.

**Comment by kenkendk** [comment]
I rewrote the handling code with 28ecfc90527a7bccdf3ff671a7bfb6d4e4ae59ea.

This is part of the 2.0.1.57 canary build.

Not sure if this fixes the original issue, but it at least should fix the problem identified by @sjonez

**Comment by mmiat** [comment]
seems ok with v59

**Comment by mmiat** [comment]
noooo
again.... :(
I've added a new folder to my source data and I've: "Failed: Found 1 files that are missing from the remote storage, please run repair"

**Comment by sjonez** [comment]
That's slightly different to the original issue, it's saying its found a file missing from remote that *should* be there, i.e. it's not an issue with deleting.

I've seen this error too after a backup job and from investigating it myself I find that the file that is supposedly missing (by checking the logs) is not actually missing from remote storage at all. Running a repair also confirms that nothing is wrong and both local/remote are in sync.

What I think is happening is that straight after the upload Duplicati is almost immediately performing a Directory List operation and sometimes finding that the file isn't showing up there in time (due to server side caching or similar) and therefore throwing this error.

First perform a repair and check the result message in the log, if that confirms that nothing needed fixing then try increasing your amzcd-consistency-delay option to 30 seconds or more, which should add enough delay between the Put and the List for Amazon to have updated itself.

**Comment by mmiat** [comment]
tried even with 1m and error occurs
I explain: I've selected disk E: as source, excluding some subfolders.
I run backup and it's ok
Then I add one of the excluded subfolders and I've the error ""Failed: Found 1 files that are missing from the remote storage, please run repair"
Can I try to find this file?

**Comment by sjonez** [comment]
If you go to the web interface and click the "Show Log" option next to your backup job, then expand the last few message log lines prior to the last result. You should see something like:

"Missing file: duplicati-20170518T013000Z.dlist.zip.aes"

Then go to amazon cloud drive and see if that file does really exist or not. If it does then it's the consistency/caching problem I've seen myself. If the file really isn't there then that's something else entirely.

As I mentioned before, you can also check by performing a repair then checking the log. If the missing files do exist it will tell you that everything was on sync (nothing needed repairing)

**Comment by mmiat** [comment]
last 2 backups were fine, so I think this issue is solved

**Comment by njfox** [comment]
I am experiencing this issue on a fresh install on Arch Linux. I installed via AUR.
Version: Duplicati - 2.0.2.1_beta_2017-08-01

I haven't been able to successfully run a backup yet--I'm getting the "Found 1 files that are missing from remote storage" error, but running DB repair shows no issues.

**Comment by njfox** [comment]
Some additional info: The remote file Duplicati complains is missing changes every time I run the backup. In every case, after the backup finishes with an error, the remote file does not actually appear to be present in ACD.

**Comment by Oxyrhynchos** [comment]
I had the same problem, but found finally the reason:
My mistake was to save two backups (a daily and a monthly one) in the same directory.
When I changed the destination directory of the second backup, the error messages disappeared.
