### ISSUE TITLE
SSH backend stop to work suddenly. Renci.SshNet.Common.SshOperationTimeoutException: Connection failed to establish within 30000 milliseconds.

### ISSUE THREAD

**Issue by icterine** [duplicati/duplicati#2458]
I have:
- [ ] searched open and closed issues for duplicates

----------------------------------------

### Version info
**Duplicati - 2.0.1.53_experimental_2017-03-13 
Fist discovered on 2.0.1.48_canary_2017-02-23
CentOS Linux release 7
SSH (SFTP)

### Bug description
Suddenly my SFTP backup backups stop to work as commands end up with error

Operation List with file  attempt 5 of 5 failed with message: Connection failed to establish within 30000 milliseconds.
Renci.SshNet.Common.SshOperationTimeoutException: Connection failed to establish within 30000 milliseconds.
  at Duplicati.Library.Main.BackendManager.List () [0x00041] in <ea7138a2c6a14507b2af9033acbce077>:0 
  at Duplicati.Library.Main.Operation.FilelistProcessor.RemoteListAnalysis (Duplicati.Library.Main.BackendManager backend, Duplicati.Library.Main.Options options, Duplicati.Library.Main.Database.LocalDatabase database, Duplicati.Library.Main.IBackendWriter log, System.String protectedfile) [0x0000d] in <ea7138a2c6a14507b2af9033acbce077>:0 
  at Duplicati.Library.Main.Operation.FilelistProcessor.VerifyRemoteList (Duplicati.Library.Main.BackendManager backend, Duplicati.Library.Main.Options options, Duplicati.Library.Main.Database.LocalDatabase database, Duplicati.Library.Main.IBackendWriter log, System.String protectedfile) [0x00000] in <ea7138a2c6a14507b2af9033acbce077>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.PreBackupVerify (Duplicati.Library.Main.BackendManager backend, System.String protectedfile) [0x0006c] in <ea7138a2c6a14507b2af9033acbce077>:0 

### Steps to reproduce
- I am not sure as it was working fine and appear without pattern. Target SFTP server is up for 160 days along with SSHD daemon

Normal linux ssh works fine. Test connectivity from backup config also woking. Test backup can complete successfully.

Only backup operations fails.

**Comment by Luto73** [comment]
I habe the same issue since this morning. Strange: a similar backup configuration with the same server works flawless?!

> 23. Okt. 2017 15:32: Message
> Fatal error
> Renci.SshNet.Common.SshOperationTimeoutException: Socket read operation has timed out after -1 milliseconds.
>    bei Renci.SshNet.Session.WaitOnHandle(WaitHandle waitHandle, TimeSpan timeout)
>    bei Renci.SshNet.Channels.Channel.Close(Boolean wait)
>    bei Renci.SshNet.Channels.ChannelSession.Close(Boolean wait)
>    bei Renci.SshNet.SubsystemSession.Disconnect()
>    bei Renci.SshNet.SftpClient.OnDisconnecting()
>    bei Renci.SshNet.BaseClient.Disconnect()
>    bei Renci.SshNet.BaseClient.Dispose(Boolean disposing)
>    bei Renci.SshNet.SftpClient.Dispose(Boolean disposing)
>    bei Duplicati.Library.Backend.SSHv2.Dispose()
>    bei Duplicati.Library.Main.BackendManager.Dispose()
>    bei Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)

**Comment by gopinathrimc** [comment]
any update on how the issue was resolve? facing similar issue.

**Comment by ts678** [comment]
There is a distinct lack of information about this problem Fortunately I found no other reports in issues or forum.
Possibly whatever this mystery issue was somehow went away, but I'll add some speculations about it regardless.

For original post on its long-uptime server, I wonder if a restart would have helped. Sometimes software needs it.
Second report actually had a different timeout (-1) which (at least currently) means infinite to the SSH.NET library.

[Added extra options to SSH that exposes the operation timeout and keep-alive properties.](https://github.com/duplicati/duplicati/commit/81d5b77c8ee9e447a18652cb036c6b942676371e)
was added in [2.0.2.2_canary_2017-08-30](https://github.com/duplicati/duplicati/releases/tag/v2.0.2.2-2.0.2.2_canary_2017-08-30) so that's an option that can be played with to see if it can change error.

> Added options to SSH library that allows configuring the timeout values

Sometimes one may need to turn on some sort of logging at the sshd to get a better look at what's going wrong.
If that's impossible, packet traces and expertise can help, but the real experts are at the [SSH.NET](https://github.com/sshnet/ssh.net) development site.

Their [2023.0.1 release](https://github.com/sshnet/SSH.NET/releases/tag/2023.0.1) (which Duplicati might grab soon) has a fix for a similar problem, and a ton of other reports.

> Send the client key exchange init in Connect

We have other reasons to update the library, but I don't know if it will help here. Mainly due to lack of new reports:

Last call for any new information. If nothing comes, issue will close. These weird ones need lots of active debugging.
