### ISSUE TITLE
[Security Improvement] Login using POST requests

### ISSUE THREAD

**Issue by flexbrane** [duplicati/duplicati#2511]
Why did you choose to perform login requests using HTTP GET parameters?

W3Schools provide a table to explain the main differences between GET and POST parameters: https://www.w3schools.com/tags/ref_httpmethods.asp

To do some login requests, use a POST requests can provide a better security (from w3school):
+ Cannot be bookmarked
+ Not cached
+ Parameters are not saved in browser history
+ parameters are not stored in browser history

----------------------------------------

### Version info
**Duplicati Version:** Duplicati - 2.0.1.58_canary_2017-05-19
**Operating System:** Docker image `intersoftlab/duplicati:canary`
**Backend:** Docker image `intersoftlab/duplicati:canary`

### Steps to reproduce
- Intercept all http requests using a proxy
- Find the login url

OR

- Try to login using a bad password
- See the browser console

**Actual result:**
```
GET https://backup.mydomain.com/login.cgi?password=AAAaaaBBBbDDdEEE1%2FFF8GGGhIIIIIjKK5lMnn82OP%3D 401 ()
```
(hash changed)

**Comment by sjonez** [comment]
It looks like the browser makes an ajax call containing a one-time hash of the password in the query string and then uses the resulting 401 or 200 response to indicate whether the login was successful. 

The hash is different for every login as it's based on a random value retrieved from the server, however I agree that this should be sent in a POST request to prevent those hashes showing up in server side or proxy logs (though ajax calls shouldn't be stored in the browser history)

**Comment by flexbrane** [comment]
> The hash is different for every login

Absolutely, I notice it.

> however I agree that this should be sent in a POST request to prevent those hashes showing up in server side or proxy logs

This is how I see that login use GET parameters.

**Comment by kenkendk** [comment]
The login _does_ use `POST`:
https://github.com/duplicati/duplicati/blob/master/Duplicati/Server/webroot/login.html

The request you have captured is from the hosted tray-icon:
https://github.com/duplicati/duplicati/blob/master/Duplicati/GUI/Duplicati.GUI.TrayIcon/HttpServerConnection.cs#L223

Since the request happens entirely outside of the browser, there are no issues with bookmarks, caches, etc.

The request here is actually a valid `GET` request, in that it fetches a cookie value. The server can cache the response, as it should return the same cookie for the same query.

But, it might create problems if there is a proxy involved as it could cache a stale response instead of returning a 401.

So I think we _should_ change it, but I don't see it as a security issue. While we are in there, we should change the nonce generator to a `POST` as well to make sure that does not get changed either:
https://github.com/duplicati/duplicati/blob/master/Duplicati/GUI/Duplicati.GUI.TrayIcon/HttpServerConnection.cs#L212

**Comment by sjonez** [comment]
Hi @kenkendk, just to make sure we're on the same page the request I saw to verify his claims was logging into the server via Chrome (and using developer tools) which is where I saw the ajax request.

I believe this is the the javascript that does it: https://github.com/duplicati/duplicati/blob/274d1cfeadc85181e9af80624a7abf1d7f9cf0b2/Duplicati/Server/webroot/login/login.js

I don't know Duplicati's internals nearly well enough though so could be wrong, but I definitely saw that call within the browser.

**Comment by flexbrane** [comment]
>  I don't see it as a security issue

This is why I don't named this issue `security issue` but `Security Improvement`. Maybe I should have named it `Improvement` only.

Anyway, according to the @sjonez answer, in the `login.js` file, there is the following code:

```javascript
            $.ajax({
                url: '/login.cgi',
                type: 'GET',
                dataType: 'json',
                data: {'password': noncedpwd }
            })
```

It is definitely a `GET` request.

**Comment by kenkendk** [comment]
Arh, I did not see that. So if you have JS enabled, it actually sends a `GET`.
I probably just copied the TrayIcon code without thinking too much :).

That should be fixed.
