### ISSUE TITLE
Backup Fails: Unsupported compression module: zip

### ISSUE THREAD

**Issue by SamiLehtinen** [duplicati/duplicati#2514]
I have:
- [ ] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.61
**Operating System:** Windows
**Backend:** FTPS

### Bug description
Duplicati won't run a backup at all, because of this error message:
"Fatal error => Unsupported compression module: zip", even if zip is default compression algorithm.

### Steps to reproduce
- It's enough just to try running a normal backup, even without the --compression-module parameter.

**Actual result:** Backup fails with error message
**Expected result:** Well, backup should run with zip compression

**Comment by SamiLehtinen** [comment]
Yes, after 54 -> 61 update. Also downgrade back to 54 left system without essential .exe files in Duplicati 2 binary directory. Which is kind of strange. .config files are there, but exe's are missing.

**Comment by SamiLehtinen** [comment]
Reboot and reinstall fixed the missing binaries issue. But the unsupported compression module issue remains. But this is probably due the fact that the SharpCompress.dll was (now) missing. It was present after 53 (re)install. Now I restored the file back to duplicati 2 directory, which was strangely missing after 61 installation. And now even if the SharpCompress.dll is present, the issue still remains. Quite curious issue. Any pro-tips?

**Comment by NTWarrior** [comment]
I upgraded from and to the same versions the same way on Windows 10 x64 and have the same issue now. I would have used the integrated​ update but it wouldn't let me since I had a backup scheduled, and then I quit Duplicati and ran the MSI rather than turn off the schedule.

**Comment by kenkendk** [comment]
I have no idea why this happens. As I wrote i issue #2425, the SharpCompress.dll file _is_ in the msi and zip files, so it _should_ be installed.

The only vague clue I have is that the build is a custom version, because I needed fixes faster than the official build, so the current SharpCompress.dll has my signing key, and not the official one. Maybe that flags it for virus checking or similar.

@SamiLehtinen There is a tool that tells why it cannot load a particular file:
https://msdn.microsoft.com/en-us/library/e74a18c4(v=vs.110).aspx

If you can figure out how to use it, maybe that can shed some light on the problem?

**Comment by SamiLehtinen** [comment]
Now in early morning I could restart the system without upsetting anyone too much. Complete uninstall, reboot, reinstall and now everything is working again. Yet I don't know what the root cause is. Afaik, this was duplicate and the original issue should go on with this problem.
