### ISSUE TITLE
Support Team Drive targets in Google Drive [$515]

### ISSUE THREAD

**Issue by thirtythreeforty** [duplicati/duplicati#2515]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info
**Duplicati Version:** 2.0.1.61_experimental_2017-05-30
**Operating System:** CentOS 7.3
**Backend:** Google Drive

### Bug description
I would like to be able to select a Team Drive (from G Suite for Business) as a backup target.  Currently I can only use my personal Google Drive.

I think this mainly involves setting the relevant Team Drive request parameters (see the [list API call](https://developers.google.com/drive/v3/reference/files/list), for example).

I'd be happy to help test or even implement this if someone can guide me.

**Comment by kenkendk** [comment]
I do not have a Team Drive to test with, but the `list` call is made here:
https://github.com/duplicati/duplicati/blob/master/Duplicati/Library/Backend/GoogleServices/GoogleDrive.cs#L459

You can perhaps just add `includeTeamDriveItems=true` to the url here:
https://github.com/duplicati/duplicati/blob/master/Duplicati/Library/Backend/GoogleServices/GoogleDrive.cs#L467

If there is some downside to including Team Drive results, you can add an option here:
https://github.com/duplicati/duplicati/blob/master/Duplicati/Library/Backend/GoogleServices/GoogleDrive.cs#L302

Instructions for building are here:
https://github.com/duplicati/duplicati/wiki/How-to-build-from-source

**Comment by gfrewqpoiu** [comment]
I would love to see this included in Duplicati. Not sure if it is helpful but Rclone has implemented this with the following changes:
[Link to commit](https://github.com/ncw/rclone/commit/2b0f8a8a924ef82e9c6620013fc707a268364ec1)
I can provide a team drive for testing if needed.
On the frontend it probably needs some kind of selector for the user which team drive to use (because Team drive IDs aren't visible in the Drive UI).

**Comment by yukoarts** [comment]
@kenkendk 
I have Team Drive not in use at all. I can invite you while the development.
If you're interested, please send me a private message me so that I can add your email which is associated to your Google Drive.
Another place you can get your own Team Drive in budget is [ebay](https://www.ebay.com/sch/i.html?_from=R40&_trksid=p2050601.m570.l1313.TR0.TRC0.H0.XGoogle+drive+unlimited.TRS0&_nkw=Google+drive+unlimited&_sacat=0).
When they say "Google Drive Unlimited", it means that they will give you a team drive with their domain.
I bought the space for my encrypted backup files, but I couldn't access to it with the most of the backup apps, because its API is different from that of My Drive.
Anyways, I'd love to see this feature in Duplicati, too!

**Comment by pymenow** [comment]
Hello ,
I am using the latest beta 2.0.3.3 but still cannot get the Team Drive as backup destination folder.
It seems to only look for folders in my drive.

**Comment by methanoid** [comment]
The absence of team drive (Filestream) support is what puts me off using Duplicati :-(

**Comment by SPDurkee** [comment]
This doesn't make any sense. There is an option to disable team drives but no where does it state how to set a correct path to a team drive. Whomever created the option to disable team drives should be able to describe the correct paths to the team drives.

**Comment by CristianCantoro** [comment]
I would also like this feature and I could help with testing.

**Comment by sandymac** [comment]
I want this enough to put a bounty on it
https://www.bountysource.com/issues/45769777-support-team-drive-targets-in-google-drive

I will also create a shared Team Drive to aid in development.

**Comment by denim2x** [comment]
I'm interested in implementing this feature; there's a new bounty goal on Bountysource

**Comment by mukut1994** [comment]
> This doesn't make any sense. There is an option to disable team drives but no where does it state how to set a correct path to a team drive. Whomever created the option to disable team drives should be able to describe the correct paths to the team drives.
> 
> I am happy to add a team drive to anyone's google account so they can test this and find the correct path syntax.

It looks like the original dev didn't finish implementing team drive support but did initially intend to which is why there are some hints on the UI and the backend about it, but the missing team drive id option.
I've added a new option called googledrive-teamdrive-id (and removed the disable-team-drive) in my pull request.
Team drive ID is the last part from the url. Should look something like this https://drive.google.com/drive/folders/<TEAM DRIVE ID>

**Comment by ts678** [comment]
As a workaround, would anyone care to see whether Duplicati rclone backend + rclone Team Drive works?
[This](https://forum.duplicati.com/t/duplicati-and-google-drive-paths/1967/20?u=ts678) describes the idea, and some of the drawbacks.

**Comment by sandymac** [comment]
> As a workaround, would anyone care to see whether Duplicati rclone backend + rclone Team Drive works?
> [This](https://forum.duplicati.com/t/duplicati-and-google-drive-paths/1967/20?u=ts678) describes the idea, and some of the drawbacks.

My understanding of the rclone option is it needs a local disk staging area before the rclone sync which I'm hoping to avoid.

**Comment by TimetravelerDD** [comment]
I see the issue is closed – does that mean that it was sucessfully implemented?

**Comment by mukut1994** [comment]
Yea this was implemented. 
Select Google Drive and put your team drive ID into the textbox that shows up.
If I remember it correctly, you can get the team drive ID from the last few characters in the url when you browse to it.
