### ISSUE TITLE
losed my backup jobs after update

### ISSUE THREAD

**Issue by WalidLej** [duplicati/duplicati#2538]
I losed my backup jobs after an update from **Duplicati - 2.0.1.53_experimental_2017-03-13**  to **Duplicati - 2.0.1.61_experimental_2017-05-30**, what should i do? (i forgot to make a backup of configuration)

**Comment by sjonez** [comment]
You forgot to make a backup of your backup jobs?

If you at least saved the passphrases I think you can probably just manually recreate the jobs and then tell Duplicati to regenerate the database from the remote location. Not 100% though.

**Comment by kenkendk** [comment]
Not sure how you lost the backup configurations.
They are stored in `%APPDATA%\Duplicati\Duplicati-server.sqlite` (assuming Windows) and not touched by the installer (it leaves them behind, even after uninstall).

As @sjonez  says, you can just create the backup jobs again (assuming you know the passphrase), and run the "Repair" command to have Duplicati rebuild the local database.

**Comment by sjonez** [comment]
Ah, that's a thought. If you're on windows check that you're not running Duplicati as a different user to before the upgrade as the %APPDATA% path is per user. I guess the same will happen if you move to running it as a service too

**Comment by Germs2004** [comment]
I had this problem today and have a good guess about what is causing it.  It's a serious and scary bug because it could result in someone losing all access to their backups if they don't figure out how to fix it, and it stops all backups until it's solved.

I usually run Duplicati as a service, which means its sqlite file is stored here: "C:\WINDOWS\System32\config\systemprofile\AppData\Local\Duplicati\".  In the web GUI last week, I clicked the link to install a Duplicati update.  Today, when I went into the web GUI again, it acted like a brand new install (and it was using port 8300 instead of the usual 8200).  I found that it had switched to using a new sqlite file stored in "C:\Users\myusername\AppData\Local\Duplicati\".  When I copied the files from the systemprofile to the user profile and restarted the service, it all worked right again.  I since cleaned it all up and reinstalled Duplicati to be safe.  It looks like the Duplicati updater has some bug with detecting that a previous install is running and is configured as a Windows Service, and it fails to use the service's sqlite file.

Here are other similar tickets about this issue:
https://github.com/duplicati/duplicati/issues/2793
https://github.com/duplicati/duplicati/issues/3004
https://github.com/duplicati/duplicati/issues/1950
https://github.com/duplicati/duplicati/issues/2538 (this one)

I think Duplicati should always, service and non-service, store all of its config in "C:\ProgramData\Duplicati" to fix all 4 of these tickets.

Thank you

**Comment by lingwooc** [comment]
Just installed 1803 and it lost my settings too. I am running duplicati as a service.

Windows evidently cannot be trusted to maintain `C:\WINDOWS\System32\config\systemprofile\AppData\Local\Duplicati` across major versions. My duplicati db was still there in `windows.old` but was gone from `windows`.

@Germs2004 is right. You can't use that folder, it isn't safe.

**Comment by Germs2004** [comment]
This just happened to me again.  I randomly decided to check on my backups and logged into the web GUI and realized that my backup jobs were completely missing.  Please make this an urgent priority to fix.  Either move the database to a safe location or let us use registry entries to specify a custom location (or both).

**Comment by typoworx-de** [comment]
Btw just checked where Duplicati is storing its settings on Linux:
~/.config/Duplicati/

There are still files present from my previous instance/backups! Why are they not recogniced?!

**Comment by Germs2004** [comment]
> Same here... running Duplicati from deb-installation on linux! After reboot and some work I noticed duplicati was not running anymore. After starting Duplicati-Service & GUI it was asking me inital-setup questions!!!
> 
> This should never happen for a software I have to trust my private data to! Can I somehow restore my previous backup-tasks or even access backup-data after loosing my client-configuration?!
> 
> There really should be some option restoring client-settings from duplicati server by some URL or credentials being able to connecto to a duplicati-server providing a duplicati-settings backup for each client!!!

I'd guess that your problem is different that the one this thread is about, though it has a similar result.  In Windows, the config folder that Duplicati uses gets deleted every time Microsoft releases a major OS update.  If your config is getting lost in Linux, it's likely a different cause.  You might want a different thread to help troubleshoot the problem you found.

**Comment by ts678** [comment]
> There are still files present from my previous instance/backups! Why are they not recogniced?!

Be sure your Duplicati is running as the same user. If the service ran as root, `~` will point it to a folder different than it was in when it ran as a non-root user. See [Web GUI lost all backup configurations on Linux, even though db is present](https://forum.duplicati.com/t/web-gui-lost-all-backup-configurations-on-linux-even-though-db-is-present/8821/10?u=ts678) for troubleshooting steps to solve your issue, which _might_ be similar.
