### ISSUE TITLE
How to backup with the original file name into google drive?

### ISSUE THREAD

**Issue by masums** [duplicati/duplicati#2545]
How to configure a backup so that it uploads all files with the original name? Is it possible or not?

----------------------------------------

**Comment by sjonez** [comment]
That wouldn't make sense unless all files were uploaded individually. Duplicati uploads multiple files together inside volumes (configurable, but by default 50MB each) for compression, encryption, upload efficiency and versioning purposes. Also depending on the content of some files, they might not even get uploaded at all if they manage to get de-duplicated (apart from the metadata). Finally, because of the encryption (among other things) I'm not sure what use seeing the files under their original names would even have.

If you want to store files "as they are" then it sounds like you're just after the standard sync capabilities of most cloud storage provider clients (e.g. Dropbox, Box, OneDrive)

**Comment by kenkendk** [comment]
Yes, that is not supported. You are probably looking for a sync/mirror tool:
https://github.com/duplicati/duplicati/wiki/FAQ
