### ISSUE TITLE
Feature request: Duplicati to autostart as admin in Windows 10

### ISSUE THREAD

**Issue by zappeee** [duplicati/duplicati#2591]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info
**Duplicati Version:** 2.0.1.61_experimental_2017-05-30
**Operating System:** Windows 10
**Backend:**

### Bug description
Related to https://github.com/duplicati/duplicati/issues/2223
VSS/Snapshot warnings/errors due to not running as admin

### Steps to reproduce
- Install Duplicati in Windows 10
- Restart computer
- Run a backup

**Actual result:** 
VSS/Snapshot warnings/errors

**Expected result:** 
No warnings/errors as you get if I start it manually as admin

**Comment by kenkendk** [comment]
You can install Duplicati as a service, as described here (look for the `Service component`):
https://www.duplicati.com/articles/Way-To-Make-A-Backup/#server-component

This should be an option in the installer as requested in #1738.

**Comment by zappeee** [comment]
Thanks!
Any way I can attach that service to the current instance of Duplicati?
Or do I need to export the config and set it up again?

**Comment by adamlis** [comment]
Well, proposed solution do not solve original problem.

Current status - also regarding #1738 is:

* Duplicati places itself in Start Menu (you know, in Windows 10 maybe it has different name) and application placed is GUI.Tray - which even when service is already running, will run next copy of Server.exe (listening on next port, e.g. if service uses 8200, GUI.Tray would use 8300)

* Duplicati running as a service using local system account (started from WindowsService.exe program) uses different configuration as the one started by user - but this is just to mention, minor issue

* Duplicati running as a service using local system account (started from WindowsService.exe program) after importing valid configuration export file (due to above mentioned minor issue) can see properly all Resource data - e.g. source, destination, schedule and of course existing Versions, etc. - but it is unable to start backup - the problem is some resource error is raised - I may try to reproduce this and put error here. Anyway while importing Resource into Server.exe running as local system, everything (incl. remote location verification which is SSH) is going OK, but then actual backup run fails.

**Comment by mayerwin** [comment]
Same issue here, I am logged in as an administrator but VSS won't work. It is not intuitive at all.

**Comment by l3d00m** [comment]
Yeah same here, needing it for VSS

**Comment by mayerwin** [comment]
Can't believe this is still not fixed. Still trying to find a solution to make VSS work with Windows 10 at startup.

**Comment by wolfcry0** [comment]
Having the same problem here, VSS fails when trying to backup because the installer is not properly setting it up to run with the right permissions.

**Comment by alexisindesign** [comment]
Issue isn't fixed yet.

**Comment by ts678** [comment]
To those who won't use a Windows service, and want an Administrator account to launch Duplicati as Administrator without question, please read [How User Account Control works](https://docs.microsoft.com/en-us/windows/security/identity-protection/user-account-control/how-user-account-control-works) which explains how even an Administrator account does not ordinarily run its programs with Administrator privilege, which is what VSS requires. I'm not sure there are any not-too-ugly ways to silently bypass UAC security.

If you're willing to answer the prompt, it doesn't matter whether you're in an Administrator account or not. You can right-click on the shortcut, click Advanced, check the `Run as administrator` box, and answer the UAC prompt when it comes up. Any other methods?

![image](https://user-images.githubusercontent.com/40771998/108565327-7bc2e180-72d2-11eb-9294-6f61a50f0bf7.png)

[How to Open the Command Prompt as Administrator in Windows 8 or 10](https://www.howtogeek.com/194041/how-to-open-the-command-prompt-as-administrator-in-windows-8.1/) illustrates the UAC prompt and security challenge that the Command Prompt faces. Duplicati when launched manually (i.e. not a service) faces the same problem of getting from medium to high integrity level. Windows programs have an autoElevate trick, but that's not available. So it's probably either a service or a UAC prompt.

If there are any Windows experts out there who know of a prompt-free way to do this without help from a service, please describe it.

[Use the Windows Task Scheduler to run apps without UAC prompts and admin rights](https://www.digitalcitizen.life/use-task-scheduler-launch-programs-without-uac-prompts/) is one kind of ugly approach. Any better ones?

[Duplicati Tutorial 02 Install Duplicati as a Service](https://www.youtube.com/watch?v=fZ_ukxbEyG0) is a somewhat old video.
[Duplicati.WindowsService.exe](https://duplicati.readthedocs.io/en/latest/07-other-command-line-utilities/#duplicatiwindowsserviceexe) installs and uninstalls the service.
[Duplicati.GUI.TrayIcon.exe](https://duplicati.readthedocs.io/en/latest/07-other-command-line-utilities/#duplicatiguitrayiconexe) mentions --no-hosted-server.
[Migrating from User to Service install on Windows](https://forum.duplicati.com/t/migrating-from-user-to-service-install-on-windows/660) is a too-long topic which could also be used to better understand initial installation.

The documentation is not as well integrated as it ideally should be, and the same is true for the code, thus #1738 is open. Volunteers?
