### ISSUE TITLE
Deal with the tilde character

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#2619]
The tilde character is used to denote "home folder" on Linux, and is used for the same purpose on Windows by Duplicati.

Unfortunately, `~` is also a valid character in paths, causing some issues.

We should review all the places that the tilde is being expanded and see if we can make some sane logic rule that determines when to expand and when not to expand.
This is a bit tricky as people might have backups set up that depends on the expansion, which we will now remove.

**Comment by DragonFlux** [comment]
I ran into this same issue on CherryTree backup files on Windows that end in a tilde. I think a sensible strategy would be:
1 - If a tilde is at the very start of a path AND is followed by a slash, expand it (home folder)
2 - Tildes elsewhere are kept as is

Of course it would be even better if the code can determine which OS it is running on and only do the expansion in Linux.

Are there not functions/libraries to handle expansion in an OS sensitive way? You'll need other expansions as well like for example %temp% on Windows. There has to be an elegant way of handling this...

**Comment by warwickmm** [comment]
I may be missing some cases, but as of revision 6c921ab3ec878a99262150b80b7f29713700c11e, I can only find the following instances where `~` is explicitly used to denote the home directory in the source code:
* `BasicSetupHelper.cs:32`
* `GeneralBlackBoxTesting.cs:32`
* `SVNCheckoutsTest.cs:105`
* `Utility.cs:986`
* `Utility.cs:1016`

The `Utility` class has a private field `HOME_PATH` that represents the path to the user's home directory.  If we were to use this instead of `~` in the code, then would we be able to avoid performing the expansion on Windows?

**Comment by kenkendk** [comment]
It sounds correct to me. I think only the `BasicSetupHelper` is using the `~`. If we can change that to use `%HOME%` then we should be able to remove the `~` expansion?

Not sure if `~` is saved in the configuration though, but we could make an upgrade script that fixes this.

With tilde expansion away, we would need to re-enable it on Linux? Or is it just too annoying to deal with inside Duplicati so we disable it completely?

**Comment by DragonFlux** [comment]
How about you make the expansion an option on the job? That way Linux users can enable it as needed and the rest can have filenames containing tildes.

But even on Linux, this should surely only be expanded if it is used as a directory name (ie: does not apply to file names and does not apply if it is not the whole directory name).

**Comment by kenkendk** [comment]
I agree on the "only as start of path" idea, but I don't see many issues with pure paths.
The problem is more in filters, that could look like:
```
--exclude=~/.config/
--exclude=[~/abc]
--exclude=[(~|/home)/abc]
```

The first and second should be simple enough to fix with the "only as start of path" idea, but the last one is not. Does it make sense to simply say that tilde expansion in this version is not supported?

**Comment by warwickmm** [comment]
Are you suggesting that `~/.config` could be supported but `[(~|/home)/abc]` is not?  Or, that no tilde expansion will be supported?

I wonder if partial support for tilde expansion will be frustrating for users, as it may give them the expectation that it should work everywhere.  It might simplify things for everyone if tilde expansion is just dropped completely?

**Comment by kenkendk** [comment]
I don't feel strongly for any particular solution. It is more important to me that the user finds it intuitive whatever we choose. That includes having a simple explanation, and I am leaning on not supporting tilde expansions, as that seems to be the simplest to explain.

As a side not, I have used the `%ENV%` notation in many places, but that really is a Windows-ism. Should we change that to use  `$(ENV)` which is more Linux-like ?

**Comment by DragonFlux** [comment]
both %ENV% and $(ENV) use characters allowed in file/folder names and therefore might appear in actual file paths (in which case they should not be expanded). A safer approach would be something like ?<ENV> that can't appear in a normal path. It does not have to resemble one platform or the other since the application is cross platform.

In the above case you could use ?<~> or ?<HOME>, which also takes care of the tilde expansion problem.

**Comment by warwickmm** [comment]
I think `?`, `<`, and `>` are still valid on many filesystems?  For example, I can create a file named `?<HOME>` on EXT4 (where the only invalid characters are `NUL` and `/`).  I would vote for not supporting tilde expansions to make everyone's lives easier.

Regarding `%ENV%` and `$ENV`, is this only used internally in the code as a token for replacement, rather than referring to an environment variable?  If so, then I think either one is fine, as long as it's consistent throughout the codebase.

**Comment by kenkendk** [comment]
Closing this as we removed tilde expansion some time ago.
