### ISSUE TITLE
Not keeping multiple versions of backup.

### ISSUE THREAD

**Issue by marioolivier** [duplicati/duplicati#2622]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.73_experimental_2017-07-15 
**Operating System:** Win 7 x64
**Backend:**

### Bug description
I have configured my backup job to run every day and to keep 3 versions of the backup. When I try to do a restore however I only have one backup that is from a few weeks ago. I get an email report every morning to say that the backup ran as scheduled.

### Steps to reproduce
- configured a backup using the wizard
- set it to run every day and to keep 3 backups
- try to restore files

### Screenshots

![3 versions](https://user-images.githubusercontent.com/30689572/28916429-17cf7148-783a-11e7-8366-fd4f50c65bee.JPG)
![restore](https://user-images.githubusercontent.com/30689572/28916431-17d48692-783a-11e7-9e23-63a87f565c01.JPG)
![schedule](https://user-images.githubusercontent.com/30689572/28916430-17d1f062-783a-11e7-95d5-54dfe5be3c48.JPG)

**Comment by kees-z** [comment]
If nothing has been changed to your source files since 21 july, this is normal. In that case, no new blocks are uploaded and a new snapshot doesn't have to be created at the remote end. After you change/add/delete something that is included in the backup task, a new restore point should be created.

Why choosing such a low value for your number of backups? Usually, the used storage at the backend grows very slow, especially for folders with lots of photos and other static data. In my setup I use a retention time of 1 year and run backup tasks daily. For most backup tasks, the storage used for all backups (about 100 restore points) is still less than the storage used by the source files.
If you delete a very large amount of files and want to delete these files from the backup also, you can use the command line tools to do this.

**Comment by marioolivier** [comment]
@kees-z 
I was wondering about that (that if the files dont change that no new restore point will be created) but its nice to have confirmation of this. I havent added any photos to this catalog recently.

As for the number of backups... I am just backing up to a small external HDD at the moment so wasnt sure how much space would be needed. I will take your advice and increase this now that I understand more how Duplicati works. 

Thank you very much for taking the time to reply. It is much appreciated.

**Comment by kenkendk** [comment]
You can set `--upload-unchanged-backup` and it will create new backup files even if there are no changes.

**Comment by marioolivier** [comment]
@kenkendk  Thats great. I will definitely make use of this option.

Thank you for your reply and for an awesome project.
