### ISSUE TITLE
Update -> not starting anymore

### ISSUE THREAD

**Issue by black-snow** [duplicati/duplicati#2624]
I have:
- [x ] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.61 (from file infos)
**Operating System:** Win10 x64, Creator's
**Backend:** ?

### Bug description

I updated duplicati from within the web frontend. I wondered why it didn't restart automatically so I checked the task manager - no duplicati. I fired it up again but it just quits without showing the tray icon or any message.

### Steps to reproduce
- download version prior to 2.0.1.61
- update duplicati from within the web gui

I haven't yet checked if it's reproducable (for me).

### debug log

No debug/error log in AppData or duplicati dir.

**Comment by lotekjunky** [comment]
I'm having the same issue. Inside the windows event viewer, I can see a .NET runtime error:

<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
<System>
  <Provider Name=".NET Runtime" /> 
  <EventID Qualifiers="0">1026</EventID> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2017-08-04T14:29:02.246113400Z" /> 
  <EventRecordID>1214370</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>redacted</Computer> 
  <Security /> 
  </System>
<EventData>
  <Data>Application: Duplicati.GUI.TrayIcon.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: System.IO.FileLoadException Exception Info: System.IO.FileLoadException at Duplicati.Library.AutoUpdater.UpdaterManager..cctor() Exception Info: System.TypeInitializationException at Duplicati.Library.AutoUpdater.UpdaterManager.set_RequiresRespawn(Boolean value) at Duplicati.GUI.TrayIcon.Program.Main(String[] args) at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args) at System.AppDomain.ExecuteAssemblyByName(String assemblyName, String[] args) at System.AppDomain.ExecuteAssemblyByName(System.String, System.String[]) at Duplicati.Library.AutoUpdater.UpdaterManager.RunFromMostRecent(System.Reflection.MethodInfo, System.String[], Duplicati.Library.AutoUpdater.AutoUpdateStrategy) at Duplicati.GUI.TrayIcon.Program.Main(System.String[])</Data> 
  </EventData>
  </Event>

**Followed by a duplicati application error:**

<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
<System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2017-08-04T14:29:02.284238900Z" /> 
  <EventRecordID>1214371</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>VEIN</Computer> 
  <Security /> 
  </System>
<EventData>
  <Data>Duplicati.GUI.TrayIcon.exe</Data> 
  <Data>2.0.1.61</Data> 
  <Data>592d5a4e</Data> 
  <Data>KERNELBASE.dll</Data> 
  <Data>10.0.15063.483</Data> 
  <Data>aa6457d1</Data> 
  <Data>e0434352</Data> 
  <Data>0000000000069e08</Data> 
  <Data>29d4</Data> 
  <Data>01d30d2e021fe2da</Data> 
  <Data>C:\Program Files\Duplicati 2\Duplicati.GUI.TrayIcon.exe</Data> 
  <Data>C:\WINDOWS\System32\KERNELBASE.dll</Data> 
  <Data>3bac416e-7428-4a5e-9cd2-ec7bab73e18a</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>

**Comment by aptitude** [comment]
I can confirm this issues on Windows 10 (Version 10.0.15063 Build 15063) and I see the same errors as lotekjunky.

**Comment by sunwayru** [comment]
I can confirm too. I updated duplicati2 from within the web frontend, and then it not starting anymore. I tried uninstall-reboot-install duplicati-2.0.2.1_beta_2017-08-01-x64.msi (downloaded from official site), but does not matter duplicati2 doens work now :(

**Comment by jidea** [comment]
you should download new version and install it manually. ( https://github.com/duplicati/duplicati/issues/2560 )

**Comment by kenkendk** [comment]
This should be fixed in the beta (and .72 and .73 versions).
As @jidea suggests, download the new version and use that.

The error from @lotekjunky (and maybe @sunwayru) could be caused by the `%APPDATA%Duplicati/updates` folder containing some unwanted stuff. Try removing the folder and install the updated version.

**Comment by sunwayru** [comment]
Sorry, where I can get beta? On https://github.com/duplicati/duplicati/releases I found only old version from 1.08.2017.

**Comment by black-snow** [comment]
@sunwayru it's the first item on that page ...

Closing this as it'll probably not be fixed / is already fixed plus I already installed the latest beta.
