### ISSUE TITLE
Moving Files Between Locations Prevents Future Backups

### ISSUE THREAD

**Issue by GBT-CCW** [duplicati/duplicati#2648]
I have:
- [x ] searched open and closed issues for duplicates

----------------------------------------
First off, I just want to say thank you very much for this lovely piece of software. I have always respected open source software developers. Keep up the great work, it's very appreciated from the community. 

### Version info
**Duplicati Version:** 2.0.1.53_experimental_2017-03-13
**Operating System:** Windows 10 Pro
**Backend:** Local Storage Moved Files to SFTP Server

### Bug description
I created a test environment for something that I need to do in the future. I created a backup of a 1GB set of files and stored it on my local hard drive. After I upload the files Duplicati creates to an SFTP server, I tried to run the backup again. Duplicati says it's missing all the files, like I never copied them there. 

### Steps To Recreate
- Create Local Backup using Duplicati
- Move Files Created to SFTP Location
- Try to Backup to New Location
     - Changed the backup location using GUI options.
- Backup Fails

- Added bonus, those files I move prevent me from creating new backups in the same folder. I'm assuming this isn't really a bug, I believe I've actually seen this in other posts as normal behavior. 

I've done a lot of searching around to see if this is even possible. I can't really find any results. I have tried repairing the database. I have tried deleting and recreating the database. I have also tried completely removing the database (on my own and with the GUI button). Duplicati recreated the database when I removed it, then instead of 5 files missing it said I had 2 files missing. 

The reason I am trying to do the backup this way, the server running Duplicati seems to have a problem preventing any backups of any kind. I'm trying to copy the contents to an external, then upload them to an SFTP server. I'm hoping not having to do a full backup of a very full hard drive will help the backup along. I apologize in advance if this isn't a feature of if this is a duplicate.

**Comment by kenkendk** [comment]
This should certainly work.

Not sure why it does not work, but I am thinking that the destination path is wrong somehow.
When you use SFTP, you can sometimes get another folder than you expect, because the working folder is applied, so sometimes you get a relative path and sometimes not.

**Comment by GBT-CCW** [comment]
Well, I thought that as well. However; it actually breaks any backups to that sftp user. I was putting the files on the root server. With those files I put there from the first backup, it just refuses to run any backups to that folder period.

**Comment by GBT-CCW** [comment]
@kenkendk could you tell me if this is an actual bug or if I am doing something incorrectly please?

**Comment by ttr** [comment]
Not tried this but I've found that paths in exported configs are absolute (which caused some problems for me on migrating local database), possibly in database are also. If this is a case this will fail.
Also - in web UI, sftp remote path is relative to login dir and IIRC it should not have leading slash.

You could try to run "repair" so it will try to fix DB - it should at least allow you to use this backup destination, as it will (re-)add remote unlisted files, *BUT* this means it does not recognize them (again, my money is on mixed up paths)

My rule of thumb (not only to duplicati) is that If I need to change backup destination, I'll let application to re-upload whole data - yes, this means that I'll loose old versions, but for most of time I can live w/ this.

**Comment by GBT-CCW** [comment]
My problem is, duplicati already isn't working on a computer. I am currently trying to find a work around for this by backing up the files from an external hard drive, uploading it to a server, then starting the backup on the actual computer in hopes that the file size or some file is just messing it up. I have tried deleteing the DB, running the repair on the DB, deleting files that seemed associated with it. I never exported the configurations either. It is a local install of duplicati that I am testing with. What you mentioned also did not take into affect that the situation I've described actually has broken any duplicati backups to this location. Also the \ in sftp location shouldn't really matter. Either it's the root of the directly, or it's the root of the directly. Usually software require a \ as no destination is considered null. I wouldn't think this has anything to do with the \ as the files end up in the correct location.

**Comment by ts678** [comment]
This issue is mystifying, partly because descriptions of failures lack detail. Starting with a broken Duplicati also adds questions.
If there are updates, it would be best to hear where the story of the "isn't working" Duplicati and SFTP workaround try ended.

> Moving Files Between Locations Prevents Future Backups

[Creating a new backup job](https://duplicati.readthedocs.io/en/latest/03-using-the-graphical-user-interface/) (likely newer than this issue) says:

> Never store multiple backups in the same remote location. Backup data files from multiple backup jobs will interfere with each other and will result in failed backup operations. Always create a new remote folder for each backup job that you set up.

If I [export](https://duplicati.readthedocs.io/en/latest/03-using-the-graphical-user-interface/#exporting-a-backup-job-configuration) a backup job, then import it as a clone, then run it, the new backup knows nothing of old backup files, so complains:

> Found 3 remote files that are not recorded in local storage, please run repair

If that's how "it just refuses to run any backups to that folder period" stopped, that's meant to prevent corruption of the folder.

If I want to see what it saw, I go to Show log --> Remote, find only the `list` line, click on it, and it shows files of older backup.
New backup ends there because each backup should have either its own folder (safest plan), or maybe a different backup [prefix](https://duplicati.readthedocs.io/en/latest/06-advanced-options/#prefix).

If I rename folder to hide the original backup's files, attempting to run that says

> Found 3 files that are missing from the remote storage, please run repair

The `list` line is empty, so I know something's wrong. That might be as far as yours got, but if you want to actually see names,
About --> Show log --> Live --> Warning will give a more complete display.  GUI had these lines in reverse chronological order:

```
Dec 18, 2020 5:36 PM: Found 3 files that are missing from the remote storage, please run repair
Dec 18, 2020 5:36 PM: Missing file: duplicati-i62daaa5b06e3455b9f8bd40b619d829a.dindex.zip
Dec 18, 2020 5:36 PM: Missing file: duplicati-b4f5c8c4d9e0842309de55225ab561a31.dblock.zip
Dec 18, 2020 5:36 PM: Missing file: duplicati-20201218T221220Z.dlist.zip
```

If I now run the cloned new backup, it seeing no files is just what it expects, so it happily creates the folder and fills it with its files.

> Added bonus, those files I move prevent me from creating new backups in the same folder. I'm assuming this isn't really a bug, I believe I've actually seen this in other posts as normal behavior.

Correct, so does this close on the basis of the subject line being about that? Original Duplicati break has basically no description, however I can see how a workaround attempt of moving the backup to a different location might still have the broken Duplicati.

**Comment by ts678** [comment]
Still trying to get feedback, however I'm not sure this is going anywhere, given that there are zero specific error messages that might help understand what went wrong or allow people to say they got the same thing. This is also not reproducible in my test which may or may not be similar to the original issue which began with some sort of undescribed issue that led to a workaround that then failed.

Starting from an initial "problem preventing any backups of any kind" and "duplicati already isn't working on a computer" to debug a problem with the workaround is hard, and "backing up the files from an external hard drive" leaves me wondering if the external hard drive is the backup source or the backup destination (original post sounds like destination). A "very full hard drive" could factor in too.

**Comment by ts678** [comment]
Closing due to lack of clarity, lack of feedback, and not being reproducible.
