### ISSUE TITLE
zip64 should be enabled by default

### ISSUE THREAD

**Issue by rkarlsba** [duplicati/duplicati#2691]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- Duplicati version: 2.0.2.1_beta_2017-08-01
- Operating system: Linux, Debian Stretch
- Backend: Jotta

## Description

Files larger than 4GB are pretty common these days, so IMHO zip64 should be enabled by default unless it may break other things. This is particularly important for new users. If I understand correctly, not using it will effectively corrupt or truncate larger files, silently, which is bad indeed. I'm not sure about this, though, so I may be wrong.

## Steps to reproduce

1. Install Duplicati

- **Actual result:** 
zip64 enabled
- **Expected result:**
zip64 not enabled

**Comment by rkarlsba** [comment]
And btw… How can I check the content of what's backed up to see if anything's corrupted or truncated because of lack of zip64?

**Comment by kees-z** [comment]
Since Duplicati creates 50 MB volumes by default, it doesn't make a difference what kind of zip files are created, it only becomes an issue when choosing an upload volume size of 4GB or more. In almost all situations, this is not recommended, because a 4GB archive needs to be downloaded to be able to restore a single file.
Furthermore, after every backup a random volume is downloaded to check the integrity of the files, which would be 4GB.

OTOH, I'm not aware of any backdraws of using Zip64 by default, so why not? Maybe there are issues with using it on 32 bit OS's? I don't know.

**Comment by kees-z** [comment]
> And btw… How can I check the content of what's backed up to see if anything's corrupted or truncated because of lack of zip64?

Use `Duplicati.CommandLine.exe test` to download one or more samples from the backend and test the integrity of that file(s). This verification is performed automatically after each backup job (unless you disable it).
Other Command line options like `list`, `find` or `affected` can help with viewing/testing what's on the backend.
Ultimate check of course is restoring some files and verify if it completes without issues.

**Comment by rkarlsba** [comment]
I thought zip was used also to split the files into smaller ones (as in 50MB chunks), and was therefore afraid zip64 was needed for this to work. @malinkb and I just tested with a 5GB randomly generated file and everything worked, so I guess this can be closed for now.

thanks,

roy
