### ISSUE TITLE
Duplicati 2.0.2.4 (2017-09-09) will not start on OSX 10.12.16 (previous version 2017-08-30 OK)

### ISSUE THREAD

**Issue by StevenKSanford** [duplicati/duplicati#2714]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.2.4
- **Operating system**: macOS Sierra 10.12.16
- **Backend**: Google Drive

## Description

Canary version 2.0.2.4 will not run (aborts without messages); I re-installed v.2.0.2.2 (2017-08-30) and it runs OK

## Steps to reproduce

1. download Canary 2.0.2.4
2. install
3. attempt to start Duplicati app (note: macOS asks for permission to run "downloaded app" as usual, selected "Open" as usual)
4. nothing happens
5. note: rebooting macOS made no difference, still could not start duplicati app; uninstall of Canary 2.0.2.4 and reinstall made no difference
6. note: reinstall of Canary 2.0.2.2, and start Duplicati app works OK

- **Actual result**:
nothing happens (no system log entries that I can find)
- **Expected result**:
should create icon-bar icon and start duplicati server which can be accessed from web browser; mono-sgen32 app should be visible in Activity Monitor (it is not found)

## Debug log

no logs found

**Comment by kenkendk** [comment]
Not sure what could be causing it, the only macOS specific change I can think of is also in 2.0.2.2:
cc972289f1b19de7938601d70ee64dd4ddb52bcf

What version of Mono are you using? Can you run it in a terminal, something like:
```
/Applications/Duplicati.app/Contents/MacOS/duplicati
```

That should give some output that might help explain why it does not work.

**Comment by StevenKSanford** [comment]
Stevens-MacBook-Pro-15:~ ssanford11$
/Applications/Duplicati.app/Contents/MacOS/duplicati

Server has started and is listening on 127.0.0.1, port 8200

Unexpected error: System.MissingMethodException: Method
'HttpWebRequest.set_ServerCertificateValidationCallback' not found.

  at Duplicati.GUI.TrayIcon.HttpServerConnection.PerformRequestInternal[T]
(System.String method, System.String endpoint,
System.Collections.Generic.Dictionary`2 queryparams) <0x40d17b0 + 0x004e7>
in <filename unknown>:0

  at Duplicati.GUI.TrayIcon.HttpServerConnection.PerformRequest[T]
(System.String method, System.String urlfragment,
System.Collections.Generic.Dictionary`2 queryparams) <0x40d12d0 + 0x000ab>
in <filename unknown>:0

  at Duplicati.GUI.TrayIcon.HttpServerConnection.UpdateStatus () <0x40d1158
+ 0x0003b> in <filename unknown>:0

  at Duplicati.GUI.TrayIcon.HttpServerConnection..ctor (System.Uri server,
System.String password, Boolean saltedpassword, Boolean
dbPasswordSourceDatabase, System.Collections.Generic.Dictionary`2 options)
<0x40bd608 + 0x00263> in <filename unknown>:0

  at Duplicati.GUI.TrayIcon.Program.RealMain (System.String[] _args)
<0x39d4df8 + 0x00cef> in <filename unknown>:0

Stevens-MacBook-Pro-15:~ ssanford11$

Steven Sanford
*email: *ssanford11@su.edu
*web:*  ssanford11.wordpress.com
*cell #:* 203-543-7222

**Comment by thisweb** [comment]
I get a similar  terminal output using the .deb version on linux mint 18.2 with canary 2.0.2.6 and 2.0.2.4 (there is no .deb file available for 2.0.2.5 ?).   The Duplicati system tray icon does not appear and the server/web GUI does not startup.  The beta loads fine on mint but I am having other upload issues I hope are fixed in canary.

Here my output using 2.0.2.6 linux miint 18.2.  It seems the same as the Mac problem

Server has started and is listening on 127.0.0.1, port 8200
Unexpected error: System.MissingMethodException: Method 'HttpWebRequest.set_ServerCertificateValidationCallback' not found.
  at Duplicati.GUI.TrayIcon.HttpServerConnection.PerformRequestInternal[T] (System.String method, System.String endpoint, System.Collections.Generic.Dictionary`2 queryparams) <0x40254260 + 0x005c7> in <filename unknown>:0 
  at Duplicati.GUI.TrayIcon.HttpServerConnection.PerformRequest[T] (System.String method, System.String urlfragment, System.Collections.Generic.Dictionary`2 queryparams) <0x40253bb0 + 0x00113> in <filename unknown>:0 
  at Duplicati.GUI.TrayIcon.HttpServerConnection.UpdateStatus () <0x40253a10 + 0x0003b> in <filename unknown>:0 
  at Duplicati.GUI.TrayIcon.HttpServerConnection..ctor (System.Uri server, System.String password, Boolean saltedpassword, Boolean dbPasswordSourceDatabase, System.Collections.Generic.Dictionary`2 options) <0x41d77960 + 0x003a3> in <filename unknown>:0 
  at Duplicati.GUI.TrayIcon.Program.RealMain (System.String[] _args) <0x41cb5750 + 0x00f1b> in <filename unknown>:0 

Thanks.

**Comment by kenkendk** [comment]
That seems to indicate a problem with Mono missing a method.
What version of Mono are you using?

**Comment by StevenKSanford** [comment]
Thanks! Seems to work now (2.0.2.8_canary_2017-09-20).

...Steve

Steven Sanford
*email: *ssanford11@su.edu
*web:*  ssanford11.wordpress.com
*cell #:* 203-543-7222

**Comment by thisweb** [comment]
Yep fixed now on linux mint 18.2.  Thanks.
