### ISSUE TITLE
No UI-protection with Mac and Chrome

### ISSUE THREAD

**Issue by warmup72** [duplicati/duplicati#2719]
I´m using Duplicati (2.0.2.1_beta) on my Mac 10.12.6. and i´ve tried to set the password for the user-interface. That works fine.
On Firefox and Safari the UI is protected but for chrome that doesn´t work. After logging out the frontends prompt the pw-request. After restarting chrome i´m logged in without typing the pw! (The password isn´t saved to chrome!)

**Comment by lukasIO** [comment]
Windows and Firefox:
Logging out works (but automatical session time out would be very much appreciated), but if I then open the UI via the Duplicati Icon rightclick->open I am automatically logged in again

**Comment by kenkendk** [comment]
There is a "feature" that might explain this. If you use the tray-icon to open the WebUI, you are logged in automatically. The reason is that the TrayIcon is "trusted" (the browser is not), so before opening the webpage, the trayicon starts a new session for you, and sends the session to the page which opens and you are automatically logged in.

Would this explain what you see? Or do you actually log out, then refresh the page? If so, what is the URL you see at the top?

**Comment by lukasIO** [comment]
just as consideration: I was also wondering about this behaviour before I found in another issue, that it was expected behaviour to "automatically log in" from the tray icon.
but given the fact that once you are logged in you have access to all backup passwords in clear text (export->save in file), it seems a bit of a security concern imo

**Comment by kenkendk** [comment]
For the security concern, the idea is that if someone has access to your machine (and can click the tray icon), they can also just grab the database with the passwords. (This issue is part of #2024).

Other than that I can see a use case for wanting people not to be able to view (or edit) information without a password.

**Comment by lukasIO** [comment]
Thanks for clarifying! It does make sense! I can also imagine cases where an option for enabling/disabling the automatic log in via the tray icon would be benefitial.

**Comment by warmup72** [comment]
Hi,
yes you are right. If I use the Tray Icon I always logged in. If I use the copy the URL and use them after be logged out I get the password prompt.
I must agree lukasIO for me that doesn´t make sense. But seems to work as designed :-)
Maybe it would be nice to add the Feature "Log out" to the Tray Icon.

**Comment by kenkendk** [comment]
The tray-icon itself needs to always be logged in, otherwise it cannot show the state. But it could be made so that this login would not be used to open a browser session.

We have also discussed a "read-only" login option that would allow a user to see only the state of the backup, and possibly allow pause/stop.

**Comment by lukasIO** [comment]
in the idea of the "read-only" login: wouldn't it be possible to solve this via a status api-call to the backend? (if displaying the status is the only issue in that regard) Then you wouldn't have to be logged in at all...

**Comment by warmup72** [comment]
The read-only option seems a good idea to me. Also the password in the general options should not be shown.

**Comment by warmup72** [comment]
The problem is solved with the last beta or maybe some releases before.
Excuse the long opening of the issue, i´ve seen today that it is still open!
Thx
