### ISSUE TITLE
Option to perform one backup after another

### ISSUE THREAD

**Issue by Photographix** [duplicati/duplicati#2758]
[x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info
- **Duplicati version**: 2.0.2.8
- **Operating system**: Windows Svr x64, OSX
- **Backend**: ACD, Jotta

## Description
Option to perform one backup after another.

I have 8 backup jobs running every two hours. Unfortunately, these are not always executed one after the other if the jobs overlap due to the runtime.

It would be nice if the backup jobs would always run in a certain order one after the other (continuous). Independent of the execution time.

**Comment by kenkendk** [comment]
The scheduler works by setting the "next time" for each backup. Whenever "next time" is exceeded, it will put the backup in queue to run. If there is no backup running, the backup will run immediately, otherwise it will run once the other is completed.

The way I read your description, this is what you are requesting?

**Comment by Photographix** [comment]
My backups all run for more than two hours. I wanted the backups to run one at a time (in a circle). 

backup1 - 2 o' clock
backup2 - 4 o' clock
backup3 - 6 o' clock

now runs backup 1 longer than 4 o' clock will not start backup2 but backup3 at 6 o' clock. backup2 runs after 6 o' clock.

I switched from the gui to commandline and built it in a self-calling script.
I have a backup vm that is always on.
