### ISSUE TITLE
Appveyor reports successful build even if tests fail

### ISSUE THREAD

**Issue by warwickmm** [duplicati/duplicati#2777]
- [x] I have searched open and closed issues for duplicates.

## Description

It appears that the Appveyor build will still report a successful build even if there are test failures.  Should we expect a success only if all the tests are passing?

See [this build](https://ci.appveyor.com/project/kenkendk/duplicati/build/1.0.1169#L1487) for an example.

![image](https://user-images.githubusercontent.com/17345532/30998559-6ca87ee6-a484-11e7-9537-7479e1660b70.png)

**Comment by kenkendk** [comment]
Interesting! Yes, all tests should pass.

**Comment by kenkendk** [comment]
The failing purge-tests are caused by the change to FasterHashing, which speed things up. This improved speed makes the backups run back-to-back. The purging needs to write a new filelist after the purge and this is done by adding a second to the previous filelist.
When the backups are too close, there is not a second between the two backups, and this causes the failure.
I have fixed it in master by adding 8 seconds sleep between the tests.

**Comment by warwickmm** [comment]
These build issues were resolved in revisions 640ec634b7eb9f6aa9682f8c7df17122da599154 and f0cfde1cb285d6d5b22195df4d83c7e39f06efab.
