### ISSUE TITLE
Show default values for advanced options

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#2810]
Minor fix should be to add the default value to the text displayed on advanced options.
Some context here:
https://forum.duplicati.com/t/zip-compression-settings/976/6?u=kenkendk

Place to edit:
https://github.com/duplicati/duplicati/blob/master/Duplicati/Server/webroot/ngax/templates/advancedoptionseditor.html#L42

**Comment by Pectojin** [comment]
Are we thinking something like this?
![screen shot 2018-01-27 at 23 43 57](https://user-images.githubusercontent.com/1561484/35477073-06079568-03bc-11e8-8e51-09fbbdca812c.png)

As Magnust noticed `zip-compression-level` has no default value selected. But that's because the default seems to be "BestCompression" while the dropdown uses integers. That has to be fixed in the backend that provides the defaults or alternatively we can make an override in the frontend.

**Comment by kenkendk** [comment]
Yes, we could set the default compression level to "9". It made more sense to have "BestCompression" when it was called `compression-level` (i.e. without the `zip-` prefix, so it fit all compression modules).

**Comment by Pectojin** [comment]
Out of curiosity, where are the default values set?
