### ISSUE TITLE
Log information cut off after prefix

### ISSUE THREAD

**Issue by daylightbrightledlight** [duplicati/duplicati#2812]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.2.1_beta_2017-08-01
- **Operating system**: macOS Sierra 10.12.6
- **Backend**: Google Drive

## Description

When viewing live log information, the backend put event is missing full file name if custom prefix is supplied. This may even happen without a custom prefix (I have not yet tested this). The file name appears to be cut off after the prefix.

## Steps to reproduce

1. Create new backup with `custom` prefix in advanced options
2. Start backup
3. Press "Show log"
4. Press "Live"
5. Select "Information"

- **Actual result**:
Given the prefix is custom-, output only shows the following: `Oct 12, 2017 12:00 PM: Backend event: Put - Started: custom-`. Everything after the prefix appears to be cut off. The missing content can still be copied, indicating that the content is cut off from view.
- **Expected result**:
The hash value should be shown after the prefix. For example: `Oct 12, 2017 12:00 PM: Backend event: Put - Started: custom-c843a9fd24c402e4836af0810a931ea.dblock.zip.aes (49.93 MB)`.

**Comment by kenkendk** [comment]
Ok, this sounds like an UI issue since you can actually copy the contents.

**Comment by Pectojin** [comment]
Heh, I was trying to replicate this in chrome and there were no messages in the live log at all. But strangely the page was getting longer and longer. Turns out all the logs were completely hidden.

It's caused by the `overflow: hidden` attribute. It works as @daylightbrightledlight explained when I switch to Safari, but in chrome it just completely hides all the output on my machine.

I removed the overflow attribute and added a bit more padding and now it looks better:
![screen shot 2018-01-28 at 02 14 26](https://user-images.githubusercontent.com/1561484/35477972-002dfe38-03d1-11e8-8e6d-8df70e060f3f.png)
