### ISSUE TITLE
No encryption in General backup settings

### ISSUE THREAD

**Issue by iBobik** [duplicati/duplicati#2822]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.2.1_beta_2017-08-01
- **Operating system**: macOS High Sierra
- **Backend**: WebDAV (Nextcloud 11)

## Description
In General backup settings there is select box fro Encryption, but only one option is No encryption.

## Steps to reproduce

Open Add backup or config of existing backup.

## Screenshots
<img width="673" alt="snimek obrazovky 2017-10-16 v 11 55 17" src="https://user-images.githubusercontent.com/614232/31606289-f4f40ad0-b268-11e7-96ec-6b29eac630ed.png">

**Comment by warwickmm** [comment]
I occasionally encounter this as well.  For me, refreshing the page eventually enables more encryption options.  I'm not sure what is causing this, though.

**Comment by kenkendk** [comment]
Most likely this is a variant of the XSRF token problem. It fails to contact the server to get the list of installed modules, so you get an empty list.

**Comment by Pectojin** [comment]
@iBobik, can you replicate this consistently or somewhat frequently?
In order to help, I'd need some info because I haven't had this happen on my instance before.

Javascript should throw an error in the console when it fails to get the data for that dropdown, so when it happens you can find the error using your browsers web inspector console. 

Additionally you can check the network section of the inspector, the info in the dropdown is downloaded from `/api/v1/systeminfo` so you should be able to see what happened when your browser tried to download the file there.

**Comment by iBobik** [comment]
Seems solved in canary for me.
