### ISSUE TITLE
Use .NET Core?

### ISSUE THREAD

**Issue by Daniel15** [duplicati/duplicati#2864]
I noticed that Duplicati currently uses Mono. Have you considered switching to .NET Core instead? It's officially supported by Microsoft. .NET Core 2.0 added many more APIs that were missing in prior versions. Targeting `netstandard2.0` for the libraries would allow them to run on .NET Core, .NET Framework, and Mono.

**Comment by kenkendk** [comment]
Yes, I did consider it. Right now it looks like Mono and .NET Core are being developed side-by-side. In the future, maybe .NET Core will be the only one there.

I think most of the Duplicati code can run on .NET Core, but there are a number of support libraries that needs to support it as well. I also seem to recall that the HTTP parts changed, so some rewrite would be needed.

Is there any particular benefit you see in changing to .NET Core?

**Comment by Daniel15** [comment]
> Is there any particular benefit you see in changing to .NET Core?

In the past, I've encountered issues with Mono where their implementation slightly differs from .NET Framework, causing subtle bugs. With .NET Core, you can use the same runtime on both Windows and Linux, so there's fewer differences cross-platform.

I also think that .NET Core is going to be the long-term winner. Now that Microsoft owns Xamarin, they essentially have one team maintaining Mono while another team is building .NET Core. Mono still has a place (such as for running 'full' .NET Framework apps on Linux, or running .NET on phones), but I suspect the desktop use case will eventually be discontinued, particularly since .NET Standard 2.0 greatly increases the API surface available in .NET Core.

Having said all that, if you update as many libraries as possible to target .NET Standard 2.0, they should run fine on .NET Framework, .NET Core and Mono.

**Comment by urbanhusky** [comment]
Pro: you don't even need to install the .NET Core framework, you can distribute the application as a self-contained deployment which includes all used .NET Core libraries - being able to run it as a portable installation (one build per platform though)

Con: There is no UI framework for .NET Core applications

**Comment by mnaiman** [comment]
I think this activity should be splitted to phases:
1) Libraries, targeting netstandard2.0
2) Server migration to core
3) Rest

Lot of dependent libraries are already netstandard2.0 compliant
Biggest advantage - speed (really some operations are MUCH more faster.
Embedded framework - no need to install anything on Duplicati host.

I have already migrated some smaller projects so I could help, if this will be decided way to go.

**Comment by mnaiman** [comment]
I have started work to migrations libraries to .net standard to be usable in .NET/Mono and Core. #3124

**Comment by tygill** [comment]
The recently added MS Graph backends might also require some changes to migrate to .NET Core - rather than Duplicati's standard `JSONWebHelper`, they use `OAuthHttpClient`, which is an extension of the .NET `HttpClient` with a custom `HttpMessageHandler` which provides OAuth authentication. This custom message handler extends `WebRequestHandler` instead of `HttpClientHandler` in order to [configure the settings for read/write timeout and certificate validation](https://github.com/duplicati/duplicati/blob/e0656a22d4da769e52e264e64705f8b5d6d66393/Duplicati/Library/Backend/OAuthHelper/OAuthHttpClient.cs#L89) as they are not exposed in the default `HttpClientHandler`. However, `WebRequestHandler` is defined in `System.Net.Http.WebRequestHandler` (instead of `System.Net.Http`), which is [not currently available in .NET Core](https://github.com/dotnet/corefx/issues/26223).

Technically speaking, we don't actually need `WebRequestHandler` - things would work if it instead extended `HttpClientHandler`. But that would mean that the read/write timeout and SSL certificate override options would not be applied to any backends that use the `OAuthHttpClient`.

**Comment by GSPP** [comment]
The Mega backend makes heavy use of single-block AES encryption. I benchmarked that .NET Core 3.0 improves performance by 2-3x.

Over time more and more performance improvements like this are going to accrue to .NET Core while .NET Framework is now abandoned.

**Comment by kenkendk** [comment]
Duplicati is now on .NETCore8.
