### ISSUE TITLE
list empty while restore from linux to windows

### ISSUE THREAD

**Issue by myB0B** [duplicati/duplicati#2911]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.2.1
- **Operating system**: Debian NAS (openmediavault) / Windows 10 Pro x64
- **Backend**: Backblaze B2

## Description

Save datas on NAS (openmediavault) to backblaze B2 and try to restore datas on a Windows 10 pro x64 but list of files to restore is empty.

## Steps to reproduce

1. create backup task on NAS
2. run backup task
2. export backup config as file
3. import backup config on Win10 Pro x64
4. rebuilt database
5. run restore
6. list of files to restore is empty

- **Actual result**:
list of files to restore is empty (nothing to select) (no error)
(maybe a path problem ? linux path of saved datas not exist on windows system)

- **Expected result**:
just want to get datas back, not matter of path or anything else

**Comment by ts678** [comment]
Not reproducible on current Duplicati, with minor differences. Linux system wasn't a NAS.. Instead of B2, I used a shared drive.
Carrying through after making selection from the GUI tree, I chose original location (despite advice). That worked as expected, meaning the original Linux root became C:\\ and a folder tree was created with Windows backslashes, down to the restored file.

Maybe something got fixed. If issue is still of interest, does it happen for you on a current release? Maybe more info is needed.
