### ISSUE TITLE
How to manually decrypt backup files (default AES encryption)?

### ISSUE THREAD

**Issue by ConradHughes** [duplicati/duplicati#2927]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.2.13_canary_2017-11-22
- **Operating system**: Synology DSM 6.1, Debian 9.3 (stretch)
- **Backend**: n/a

## Description

I wonder could anyone suggest a tool (ideally Linux command line) for decrypting Duplicati's .zip.aes archive files please?  I'm just trying to do a little "due diligence" before committing to Duplicati, and would like to verify both that the backups are correctly encrypted, and that in a worst case situation I could still (albeit extremely laboriously) obtain data from the encrypted backups even without Duplicati.  Looking at the white paper and elsewhere, I couldn't find obvious documentation of the default encryption mechanism, and playing around with a sample backup using a few tools to decrypt AES-256 (openssl, aespipe, gpg) I didn't have much luck: openssl and gpg both expected the encrypted files to have more structure (magic number, etc.) and I could easily believe that the garbage aespipe produced was down to my failure to invoke it correctly.

## Steps to reproduce

1. Make a backup
2. Get hold of the .zip.aes files
3. How to decrypt?

- **Actual result**:
Failed to decrypt using openssl, gpg, aespipe; entirely possible there's an invocation of these that works, but I couldn't find it.
- **Expected result**:
Expect that the encryption is standard/well-defined enough that some third party tool can decrypt it?

**Comment by ConradHughes** [comment]
Hmm, making progress on this: the [developer documentation](https://github.com/duplicati/duplicati/wiki/Developer-Documentation#core-algorithm) mentions AESCrypt, which looks as if it's Windows-originated (not available as part of Debian stretch, anyway), but [source code is available here](https://www.aescrypt.com/download/).  Giving that a try, will report back.

**Comment by ConradHughes** [comment]
Ok, solved: obtained AESCrypt as above and decrypted successfully.  Not entirely trivial, as aescrypt itself wants keyfiles to be in UTF-16LE format for some reason, but it comes with a utility to help with that.  Here are the necessary incantations:

```
aescrypt_keygen -p 'PASSWORD' KEYFILE
aescrypt -d -k KEYFILE DUPLICATI-FILE.zip.aes
```

The first command stores your password in KEYFILE using the correct format; the second command decrypts DUPLICATI-FILE.zip.aes to DUPLICATI-FILE.zip.  AESCrypt was trivial to build: after downloading and extracting, I just `cd`'ed to the source directory and typed `make`.

**Comment by kees-z** [comment]
Alternatively, you can use `SharpAESCrypt.exe`, located in the Duplicati program folder.

**Comment by ConradHughes** [comment]
Thanks @kees-z - in the spirit of "Trust No One", I wanted to decrypt using something not from Duplicati itself!

**Comment by kenkendk** [comment]
Awesome that you got it working. I chose to use AESCrypt because there was an open source implementation, such that there is a good chance you can recover even if Duplicati stops to exist.

Since you are looking at the "restore without Duplicati", you may want to try this as well: https://github.com/duplicati/duplicati/tree/master/Tools/Commandline/RestoreFromPython

**Comment by mrbeandev** [comment]
@kenkendk  i am getting a error as `No .dlist.zip files found`.
actiually i have done a backup of my full pc to a debian server and after i reset my pc i downloaded all the 200GB of files to my pc local HDD and after that i tried to restore it with duplicati and it was giving a error as `No filesets found on remote target`. i havent found any solution to that problem and all the backup are non recoverible so i am trying to decrypto them now and getting another error as  `No .dlist.zip files found`.

**Comment by ts678** [comment]
> i have done a backup of my full pc

What backup completion indications did you see, e.g. did the [job log](https://duplicati.readthedocs.io/en/latest/03-using-the-graphical-user-interface/#viewing-the-log-files-of-a-backup-job) look good, or did some restore tests give some confidence?
This is initially sounding like the backup never finished, and if it was the one-and-only backup (no prior), that's a bad place to be.

> i reset my pc

Are you talking about the below? If so, which option?

![image](https://user-images.githubusercontent.com/40771998/142300756-a6fa50c1-b857-4a6f-87ac-3478f93e6795.png)

Are there any pre-reset Duplicati `sqlite` files in C:\Users\you\AppData\Local\Duplicati? If truly no `dlist`, they might help you.
Did you install as a Windows service via [Duplicati.WindowsService.exe](https://duplicati.readthedocs.io/en/latest/07-other-command-line-utilities/#duplicatiwindowsserviceexe)? That would be a different place, maybe in C:\Windows.old.

> debian server

Do you see any file with `dlist` in the name? If you sort by date, this would be near the end. If not there, the backup didn't finish.
Assuming you have `dblock` files, that's where your data blocks are. `dindex` files make blocks more findable. `dlist` says how to put files together from the blocks. This information is also normally in a `random-letters.sqlite` file in Duplicati's AppData folder.

[Restore Backup with only dblock and dindex files](https://forum.duplicati.com/t/restore-backup-with-only-dblock-and-dindex-files/5766) is where I hope you're not, or if you're there then I hope you kept your database.
Manual decryption of a `dblock` file is easy by the mentioned tools, but then you just get raw blocks not connected to source files.

[How the backup process works](https://duplicati.readthedocs.io/en/latest/appendix-a-how-the-backup-process-works/)
[How the restore process works](https://duplicati.readthedocs.io/en/latest/appendix-b-how-the-restore-process-works/)

**Comment by mrbeandev** [comment]
my windows was given a complete reset just as new pc i used a USB recovery software provided by the manufacturer of the PC (Lenovo) My pc : Lenovo Legion 5
so its all just as new now. !
and the backup was 100% success thats the reason i reset the pc i waited for 3 days to backup to finish !
and i dont find any .dist file in the list of backup files 
is there any way to just decrypto the files without that .dist file ??

**Comment by ts678** [comment]
>so its all just as new now

Such programs typically don't go out of their way to cleanse unused space, so there's a tiny chance there's still old data that an undelete program could get, but there's a better chance that the new files blindly overwrote spots where old data used to be...

Programs also exist that can scan free space to try to reassemble (for example) pictures that now exist only as free space blocks, however these third-party tools (which you can search for) might not be up to reassembling using Duplicati `dblock` file blocks.

> is there any way to just decrypto the files

is not the point, but if you want a bunch of blocks without assembly directions or source file names, tools mentioned here were:

[AES Crypt](https://www.aescrypt.com/) for an easier third-party GUI experience, and `C:\Program Files\Duplicati 2\SharpAESCrypt.exe` if you will do CLI:

```
Usage: SharpAESCrypt e|d[o][1-4] <password> [<fromPath> [<toPath>]]

Use 'e' or 'd' to specify operation: encrypt or decrypt.
Append an 'o' to the operation for optimistic mode. This will skip some tests and leaves partial/invalid files on disk.
Append a single number (up to 4) to the operation to set the number of threads used for crypting. Default is single thread mode (1).

If you ommit the fromPath or toPath, stdin/stdout are used insted, e.g.:
  SharpAESCrypt e 1234 < file.jpg > file.jpg.aes

Abnormal exit will return an errorlevel above 0 (zero):
  4 - Password invalid
  3 - HMAC Mismatch / altered data (also invalid password for version 0 files)
  2 - Missing input stream / input file not found
  1 - Any other cryptographic or IO exception
```

After you decrypt, you'll have a `.zip` file where each file inside is a default-100-KB block from some unknown file. Trying to reassemble will be somewhat like working on a 2 million piece jigsaw puzzle with markings that you frequently can't follow...

You might get lucky on smaller files that are only a single block. If you know what text strings you're after, you can look for a program to help search. I'm not sure if Windows Search is up to this, but there are quite a few alternative programs around.

Although you can try Windows search, block filenames are meaningless to humans or file-format-aware programs. You could
rename everything to `.txt` and file names might be more tool-friendly. or some tools might only know how to text-search.
[SearchMyFiles](https://www.nirsoft.net/utils/search_my_files.html) (which I use on logs) is this way. I can't speak for other tools.



You might get slightly lucky on multi-block files because you have a fresh backup, and blocks are (I think) frequently emitted sequentially from that source file unless the block is already somewhere in the backup, in which case a duplicate isn't written.

[7 Free Advanced Desktop Search With Text Filter For Windows](https://www.geckoandfly.com/32081/advanced-desktop-search/) gives various examples. Paid tools may or may not help more. Something with an index would be faster for repeat queries, if such tool exists. Nothing will be as good as Duplicati tools with database or `dlist`. [Restoring files if your Duplicati installation is lost](https://duplicati.readthedocs.io/en/latest/03-using-the-graphical-user-interface/#restoring-files-if-your-duplicati-installation-is-lost) used beforehand would have noticed the lack of a dlist.

I'm sorry about the loss, but trying to piece anything together is going to be hugely manual, and probably not very effective.

**Comment by mrbeandev** [comment]
how to skip the password ??
while i created backup i choose no encryption i didnt want to put a passwoerd ...

**Comment by ts678** [comment]
> i choose no encryption

Why are you posting to a four-year-old closed thread wanting decryption? That's relevant only if your filenames end in `.aes` (for [Advanced Encryption Standard](https://en.wikipedia.org/wiki/Advanced_Encryption_Standard)) rather than `.zip`. To open a `.zip` file you can double-click it in Windows to get a look at blocks.

So no previous backups to help out, no careful verification of backup completion, and no restore testing before doing reset, right? You're certain that you're looking in the right server folder, and there is no file around with `dlist` anywhere in its name, correct?
Example: `duplicati-20211108T215425Z.dlist.zip`. Using wildcards at a shell prompt, that would be findable with `*.dlist.zip`

Do you happen to program or script in any languages? Python or C# would be good ones because some existing tools use those, which might allow you to reuse code for a custom tool for the very difficult situation of trying to get nameless files without a dlist.

There might be an idea of taking advantage of  `blocklist` information which might be in the `dindex` file to get fewer larger files. This is not something to try by hand, but all those odd filenames for the blocks have mathematical meaning ([Base64](https://en.wikipedia.org/wiki/Base64) of [SHA-256](https://en.wikipedia.org/wiki/SHA-2)).
[The backup process explained](https://duplicati.readthedocs.io/en/latest/01-introduction/#the-backup-process-explained) is a simpler-language explanation of what's going on. [index-file-policy](https://duplicati.readthedocs.io/en/latest/06-advanced-options/#index-file-policy) is a technical clue on the idea. [Expanding blocklists](https://duplicati.readthedocs.io/en/latest/appendix-b-how-the-restore-process-works/#expanding-blocklists) in previously linked article is another. Still lots of work (if possible at all, even theoretically), then you still have nothing for folders or names (those are in `dlist` and database), so you need to identify things using whatever tools you can get.

Because you backed up to a Debian server, are you Linux-proficient to use tools such as the [file](https://linux.die.net/man/1/file) command or something similar to
try to identify things, probably with scripting help? What types of things were there anyway? Any idea how many files there were?

**Comment by ConradHughes** [comment]
Just to say that witnessing your efforts to help here has finally prodded me into becoming a supporter of the project.  Years overdue, that; sorry.
