### ISSUE TITLE
Deleting webdav backup with remote file remove entire content folder

### ISSUE THREAD

**Issue by Salamafet** [duplicati/duplicati#2952]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.2.1_beta_2017-08-01
- **Operating system**: Windows 10 x64
- **Backend**: Firefox Quantum 57.0.4 (64 bits)

## Description

When removing webdav backup with remote file, entire content of remote folder is removed. Not only duplicati file.

## Steps to reproduce

1. Add other file to webdav remote folder backup
2. Remove existent webdav backup
3. Check "Delete remote file"
4. Go to webdav and find empty folder

- **Actual result**:
The webdav backup folder is empty
- **Expected result**:
Find all file that have not been created by duplicati

I don't have make test with other sync method.

Sorry for my bad english

**Comment by Pectojin** [comment]
I think this is _similar_ enough to #2678 that this issue is actually fixed in 451c71ccb1e604e99842c145c2d7c0461e00385c, but I'm afraid it hasn't made it into the beta yet.

@kenkendk Any chance we can push out a beta release with a couple bug fixes? This one seems urgent when it's happening to multiple people.

**Comment by Salamafet** [comment]
Thanks this is exactly my problem.

I think I don't have use the goods words during my research.
