### ISSUE TITLE
Captcha is unreadable

### ISSUE THREAD

**Issue by joshuar** [duplicati/duplicati#2965]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.2.1_beta_2017-08-01
- **Operating system**: Fedora 27
- **Backend**: B2

## Description

I'm trying to delete a backup from the web interface but the captcha is unreadable as it is scaled in the webpage incorrectly.  The rest of the web interface is fine, nothing is unreadable.  Just the captcha:

![image](https://user-images.githubusercontent.com/7401/34936590-1d456708-fa36-11e7-8a34-31b5075356c8.png)

Let me know what additional information, for example, from the browser would be helpful.

To note, I'm on a HiDPI screen with a resolution of 3840x2160 and 162 dpi.  I'm using Firefox 57.0.4.

## Steps to reproduce

1. Create a backup and backup some files
2. Try to delete the backup

**Comment by Pectojin** [comment]
This seems to be an entirely resolution based issue that occurs across browsers and OS'es, I could only replicate the issue when using dev tools to fake a higher resolution than 1920x1080 regardless of browser or OS (Ubuntu + OSX). 

I can take a look at it tomorrow to add some css that'll look good at 4k too.

**Comment by joshuar** [comment]
Thanks @Pectojin yeah likely to just be a resolution oddity.  Will be great to have it fixed!  Thanks muchly for looking into it!

**Comment by Pectojin** [comment]
I was certain I replicated this yesterday, but looking at it today I just can't seem to replicate... 

I did notice that the capcha is sometimes generated so that the text is outside the image, but when I inspect the image it's not cropped in the frontend, it's just _like that_ from the capcha generator. Even happens on 1920x1080 if I reload enough times.

<img width="217" alt="screen shot 2018-01-18 at 23 37 39" src="https://user-images.githubusercontent.com/1561484/35125086-9c841bb2-fca8-11e7-8f8d-5493c6a496c0.png">

Does this happen consistently whenever you load a capcha in the application? 

Additionally, could you try right clicking the capcha and inspecting it in the browser? When you mouse over the `<img>` tag in the inspector it should display the size of the object and should reveal if it's partially hidden below another element or potentially scaled incorrectly.
<img width="946" alt="screen shot 2018-01-18 at 23 41 28" src="https://user-images.githubusercontent.com/1561484/35125245-34012ff2-fca9-11e7-8304-ee99f66c8d7b.png">

**Comment by fouram** [comment]
I am having this same issue except it appears that the wrong font is being used; it looks like wingings or something: 
![image](https://user-images.githubusercontent.com/533951/37635522-684a5c40-2bd2-11e8-8094-da1301698c5f.png)

**Comment by nicolas-t** [comment]
I'm using duplicati on windows, and the captcha seems to be cropped : 

![image](https://user-images.githubusercontent.com/1765930/44618352-78228100-a874-11e8-83e8-df97616d6f4a.png)

returns : incorrect

How can I avoid this issue ? 

Maybe captcha are too strict, why not having an easier confirmation like github does : 
![image](https://user-images.githubusercontent.com/1765930/44618367-bae45900-a874-11e8-9cff-a4d969816bd6.png)

**Comment by oslerw** [comment]
I can repro this as well, using Firefox on Arch Linux with 4k monitors:

![image](https://user-images.githubusercontent.com/1066487/55450917-a7753b00-5585-11e9-81d5-969c871459a2.png)

Though as other commenters have pointed out, it doesn't appear to be related to the browser at all. Instead the captcha generation is just a bit wild. I'd second @nicolas-t's suggestion, I think a catpcha might be the wrong tool here. If the goal is to make sure someone know what they're doing, typing the name or a big scary string like "Yes, please destroy my data forever and ever and ever" would be enough.
