### ISSUE TITLE
Exclude filter ignoring all except last filter

### ISSUE THREAD

**Issue by we9v** [duplicati/duplicati#2976]
- [X] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.2.17_canary_2018-01-23
- **Operating system**: Windows 7
- **Backend**: GUI Command Line

## Description

Filter/exclude is not working properly (using the GUI to populate).  It does seem to work if it's the last line of the advanced options or at least the last filter.  All filters prior to the last filter shown in Advanced options are ignored.

## Steps to reproduce

1. Create a backup set, including a source folder that has a few subdirectories
2. Under Filters, choose "Exclude directories whose name contains" and enter part of a name from a subdirectory in step 1 (in my example, "--exclude=*Previews.lrdata*\".  Finish and save the backup set.
3. Select the backup set, then Commandline...  Choose Test-Filters (removing any Target URL) and run the command.  Note that filter works.  (**Expected result**)
4. Either edit the backup set to add another Filter another subdirectory (Exclude Folder).  Note that this results in a full path, C:\dir\dir2\
5. Run Test-Filters in Commandline... and ensure that the --exclude from step 4 is the after the one from step 2.  Note that the excluded directories whose name contains is now shown as included when running the test.  (**Actual result**)
6.  Run Test-Filters in Commandline... again, but this time edit the advanced options to put the "whose name contains" exclusion last.  The exclusion/filter now works properly again.

Upon further investigation, it seems that all filters are ignored except the last one.  It is not specifically a "directories whose name contains" issue.

**Comment by we9v** [comment]
![capture](https://user-images.githubusercontent.com/35498704/35314310-e30a7fc8-008a-11e8-8f2f-5ae1a368cd5e.PNG)

```
Including source path: C:\Users\we9v\Dropbox\_Trading\
Including folder: C:\Users\we9v\Dropbox\_Trading\
Excluding path due to filter: C:\Users\we9v\Dropbox\_Trading\_TOS Trades\ => (C:\Users\we9v\Dropbox\_Trading\_TOS Trades\)
Including file: C:\Users\we9v\Dropbox\_Trading\C3 M3 Butterfly.doc (37.00 KB)
<<<edit:  SNIP main directory files>>>
Including folder: C:\Users\we9v\Dropbox\_Trading\PosMon Archive\
Including file: C:\Users\we9v\Dropbox\_Trading\PosMon Archive\PosMon 1107 July.ods (111.67 KB)
Including file: C:\Users\we9v\Dropbox\_Trading\PosMon Archive\PosMon 1108 Aug.ods (147.84 KB)
<<<edit:  SNIP \PosMon Archive\ files...that were in the exclude list>>>
Including folder: C:\Users\we9v\Dropbox\_Trading\Bogus2\
<<<edit:  empty directory, but log says it's including directory that's clearly excluded above>>>
Including folder: C:\Users\we9v\Dropbox\_Trading\Bogus1\
<<<edit:  empty directory, but log says it's including directory that's clearly excluded above>>>Matched 99 files (10.79 MB)
Return code: 0
```

**Comment by we9v** [comment]
Downgraded to 2.0.2.15_experimental_2018-01-03 and same bad results.  Only the last filter/exclude is being used.

**Comment by piegamesde** [comment]
This is a quite severe issue that has not received any attention, even though it is more than half a year old. Filters are still broken in `2.0.3.9_canary_2018-06-30`, even if I did not check if the last filter in my list works (since that wouldn't help me anyways).

@tygill please rename this issue into "Exculde filters are broken" to make it easier to find.

**Comment by tygill** [comment]
I just tried to repro this bug, but wasn't able to from the command line - filters seem to be working fine for me with the latest release. (Though admittedly, filters can be a bit touchy and some of their behaviors are unintuitive at first.)

This was my test setup:

`C:\DuplicatiTesting\source\` containing:
- `a\Important.txt`
- `b\Important.txt`
- `c\Important.txt`
- `Image.bmp`
- `Important.txt`
- `Important.txt.bak`
- `Temporary.bak`

```
C:\duplicati-2.0.3.9_canary_2018-06-30>Duplicati.CommandLine.exe test-filters C:\DuplicatiTesting\source --include=*.txt --exclude=*.bak --exclude=C:\DuplicatiTesting\source\a\ --exclude=C:\DuplicatiTesting\source\b\ --exclude=C:\DuplicatiTesting\source\c\
Including source path: C:\DuplicatiTesting\source\
Excluding path due to filter: C:\DuplicatiTesting\source\a\ => (C:\DuplicatiTesting\source\a\)
Excluding path due to filter: C:\DuplicatiTesting\source\b\ => (C:\DuplicatiTesting\source\b\)
Excluding path due to filter: C:\DuplicatiTesting\source\c\ => (C:\DuplicatiTesting\source\c\)
Including path as no filters matched: C:\DuplicatiTesting\source\Image.bmp
Including path due to filter: C:\DuplicatiTesting\source\Important.txt => (*.TXT)
Excluding path due to filter: C:\DuplicatiTesting\source\Important.txt.bak => (*.BAK)
Excluding path due to filter: C:\DuplicatiTesting\source\Temporary.bak => (*.BAK)
Matched 2 files (16 bytes)
```

As can be seen, each filter applied to at least one file or folder - not just the last one in the list.

**Comment by piegamesde** [comment]
So I went into my backup settings and moved a folder to the bottom of the list, still backing it up:

![image](https://user-images.githubusercontent.com/14054505/44712181-7f35d300-aab0-11e8-8c93-df712851fda6.png)

No folder I have tested has been excluded from the backup. I am starting to think this may be a completely separate issue.

![image](https://user-images.githubusercontent.com/14054505/44712500-2ca8e680-aab1-11e8-8efe-0fb0ca7a86c6.png)

I also have not tested the command line options since I don't really know them.

**Comment by adbancroft** [comment]
This issue is still a problem with 2.0.5.1_beta_2020-01-18.

Multiple `--exclude` options work from a command prompt (I use Powershell)
Multiple `--exclude` options do NOT work from the Web UI, as @we9v described in the Steps to Reproduce. 

I worked around this by collapsing the multiple exclusions onto a single regex exclude. E.g.
`--exclude=*\cache*\ --exclude=*\backup*\`
becomes
`[(.*\\cache.*\\)|(.*\\backup.*\\)]`
