### ISSUE TITLE
[Bug] OpenStack AuthAPI value is overridden if you edit configuration in UI

### ISSUE THREAD

**Issue by incyclum** [duplicati/duplicati#2977]
Version : 2.0.2.17_canary_2018-01-23
OS/Browser: Xubuntu 16.04 / Chromium

If you select a custom URL / OpenStack endpoint and go back on edit later the field is
replaced by Rackspace URI.

**Comment by Pectojin** [comment]
I was able to replicate the issue.

There's a typo in the [EditUriBuiltins.js](https://github.com/duplicati/duplicati/blob/b417bfbc521a9bc87bfe292de95b348240b7c771/Duplicati/Server/webroot/ngax/scripts/services/EditUriBuiltins.js), which is responsible for figuring out which item should be selected in the dropdown. In that file it specifies a variable `openstack_server_custom` but in the template, [backends/openstack.html](https://github.com/duplicati/duplicati/blob/b417bfbc521a9bc87bfe292de95b348240b7c771/Duplicati/Server/webroot/ngax/templates/backends/openstack.html), it's looking at the variable `openstack_server`. 

The variable `openstack_server` doesn't exist, so the dropdown falls back to the default selected item. You'll still get your custom URL if you go to the select and change to custom again before saving.

It's an easy "fix", but the issue is caused by inconsistent naming between two files so I'll go through the implementation tomorrow to make sure there aren't any other typos.

I'll probably have a commit in tomorrow to resolve this issue.

**Comment by incyclum** [comment]
Awesome! Thanks :+1:

**Comment by Pectojin** [comment]
Okay, it was a bit more complicated than a typo, but I got it now.

There was some very confusing logic in the method that put data into the `openstack_server` variable. 

I gave up trying to figure it out and just stole the code from the S3 implementation. So it's more or less a search/replace `s3` to `openstack` on the same 14 lines of code :)
