### ISSUE TITLE
Duplicati-server.sqlite reset after Synology DSM update

### ISSUE THREAD

**Issue by Fragrag** [duplicati/duplicati#3004]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.2.1_beta_2017-08-01
- **Operating system**: DSM 6.1.5-15254
- **Backend**:  Local Synology NAS to Backblaze B2

## Description

My Synology NAS executed an update overnight to the new version DSM 6.1.5-15254. When I checked Duplicati this afternoon I noticed all of my backup jobs disappeared and after several reboots they did not return. 

I checked my remote files on Backblaze and they seem intact and present.

I sshed into my NAS and looked for my Duplicati-server.sqlite and noticed that it was a very small size of 25600 if I remember correctly. I then looked if there was another file on the system using `find \ Duplicati-server.sqlite` but I coudn't find any other files.

I decided to re-add the jobs and hope Duplicati is smart enough to pick up from where it ended. While adding the jobs, I got an error message notifying me that the certs were not in order. I then redid the steps in this [wiki entry](https://github.com/duplicati/duplicati/wiki/SSL-TLS-support-in-Mono). 

While looking around, I found this similar ticket:
[Duplicati reset after update #2793](https://github.com/duplicati/duplicati/issues/2793)
As with the above poster, I am reporting this for posterity.

## Steps to reproduce

1. Update Synology DSM to version 6.1.5-15254

## Debug log

No debug log available.

**Comment by Pectojin** [comment]
I still haven't found any evidence that Duplicati would delete those files by itself. I think it's similar in this case that external software (e.g. DSM upgrade) was altering the `.config` folder where Duplicati has it's database. Perhaps it's updating the contents in it's `/root`folder which then overwrites `/root/.config`folder.

Could you see anything in the `/var/log/dsm.log` file after your upgrade? I don't know how detailed the logs are, but it might have written something useful there.

**Comment by Fragrag** [comment]
[Here's the log.](https://pastebin.com/jW78KxjA) I tried to sanitize it from any personal details but if you spot something let me know. I can't find anything particular in there relating to /root or /root/.config.

How does Duplicati react when its config files are unavailable, does it recreate them from scratch?

Yeah I think the DSM upgrade is more to blame here. I've turned off auto-updates so this won't happen again in the future.

**Comment by Pectojin** [comment]
Well, it depends on what was deleted.  

There are 2 types of databases in `/root/.config/Duplicati/` by default: 
- The first is your backup jobs specific db, which will have `some_random_string.sql` as name. It's basically a giant cache of what's on your remote directory. It can be recreated by just selecting your job -> database -> repair.
- The second is the "Duplicati database" which holds information about all your jobs, their logs, etc. When you do an export of your backup job config the output is all from this database. 

In your case the 2nd type of database was deleted, meaning you have to manually set up Duplicati from new because Duplicati basically reset back to a fresh installation.

I couldn't see anything in the logs either. If this can be replicated, and proved to be an issue in DSM upgrade, the best course of action might be to get Synology to not wipe configuration files. 

Alternatively, Duplicati may have to change it's default directory for these databases when running on Synology. The reason it's in `~/.config` on Unix is likely so that normal unprivileged users don't run into permission issues, but when running as privileged you might as well put it somewhere more Unix'y like `/var/lib/Duplicati` which I seriously doubt any updater would touch as `/var/lib/` contains state information on many installed applications.

**Comment by Fragrag** [comment]
ConradHughes seems to have experienced the same issue as well in [Configuration import ignores local database path #3005](https://github.com/duplicati/duplicati/issues/3005). 

I think this is an adequate post-mortem for this issue, so I'm going to close it. Thanks for your time and assistance!

**Comment by Pectojin** [comment]
I've opened a case with Synology to see if they can acknowledge the issue or if we should just start writing code to mitigate the issue :)

**Comment by Pectojin** [comment]
I didn't get a ton out of talking with the support...

>I can confirm our operating system does not take into account extra third party packages installed onto the root folder of your NAS.
>
>Unfortunately, I am not able to provide a complete breakdown on the update steps and why Duplicati was affected as we are unable to assist with third party software.
>
>I can only recommend re-configuring this package manually following the update and / or contacting the Duplicati / Mono developers to check if a workaround exists.
>
>My apologies for the inconvenience caused.

As Kenneth mentioned in #3005 this can be worked around by using the environment variable `DUPLICATI_HOME=/vol/with/space` which would avoid this in the future.
