### ISSUE TITLE
Configuration import ignores local database path

### ISSUE THREAD

**Issue by ConradHughes** [duplicati/duplicati#3005]
- [x ] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.2.17_canary_2018-01-23 [says "unknown" in web front end About text]
- **Operating system**: Synology DSM 6.1.5-15254
- **Backend**: Mono 5.4.1.6-9

## Description

**Duplicati ignores DBPath in configuration backups.**  Synology's latest DSM "upgrade" killed my previous Duplicati install; after getting the above version I imported my saved configuration but discovered that its local database location had moved back to the default, which is a major problem because Synology's root partition is tiny (1GB free) and my backup database is 5GB.

## Steps to reproduce

1.  Select "Add backup", "Import from a file", and import a backup with configured local database location (DBPath field in the .json file).  It doesn't matter whether you "Save immediately" or go through each step of the imported configuration.
2. Select the imported backup in the web UI and look at Advanced/Database to see the local database path.

- **Actual result**:
The local database path had defaulted back to /root/.config/Duplicati/RANDOM.sqlite.
- **Expected result**:
The local database path should have been as configured in the DBPath field in the imported .json file.

**Comment by Pectojin** [comment]
I don't know if this is intentional or not. 

I *think* at once point the config would import the full database path and try to reuse the same database if it existed. But this probably created a lot of trouble with people trying to clone their configs into multiple jobs. An easy fix for that problem was probably to just not use the DB path, falling back to defaults.

At least that would explain why the DB path is there in the JSON but explicitly overwritten on import.  

Let me take a crack at implementing something, then we can see if Kenneth likes it :)

**Comment by kenkendk** [comment]
Yes, it is as @Pectojin  says, people use the export/import to make copies of their backup jobs. When they do this, it makes all kinds of annoying issues when two backups modify the same database, and for that reason the dbpath is ignored on import.

It is also ignore because you can export on one machine, and then import on a different machine. In this case it is possible that the target folder does not exist or is not writeable.

For the problem that @ConradHughes mentions, an easy fix would be to set then environment variable `DUPLICATI_HOME=/vol/with/space`, which will cause Duplicati to use that folder to store everything, including the larger database files.

If we add a new checkbox on the import page with something like "don't ignore dbpath", I am worried that users will be confused. But perhaps that is better than the current method that makes it difficult for experienced users to choose what they want?

**Comment by Pectojin** [comment]
I'm not sure what is the best option. The one i suggested in #3007 basically assumes that if you changed it once you can change it again. But you're right, that doesn't account for configs moved between systems, in which case an inexperienced user might move their database to the wrong place unintentionally.

**Comment by Pectojin** [comment]
I'll close #3007 until I think of a better solution. It's no good to merge like this.

**Comment by ConradHughes** [comment]
Not knowing the details of your UI implementation, it's difficult for me to suggest changes: I don't know how hard they'd be to implement.  My use case was that an "upgrade" had broken Duplicati, so I was reinstalling and restoring the configuration backup to the machine on which it was originally used.  I think my ideal solution here would be to check for existence of the imported DBPath and present a dialogue accordingly:

- "There's already a database at the location specified in this import [PATH]; would you like to use it?  Note that having multiple configurations use the same database file will result in disaster." with options "Use this database" and "No, pick a new location [you can alter this later in the import process]"
- "The import specifies a database location [PATH], but there's no file there; do you want to use that location anyway?" with options "Use the imported location" and "No, pick a new location [you can alter this later in the import process]"

**Comment by ConradHughes** [comment]
As a further note on this, attempts to repair the obsolete database after backing up the file, re-configuring DB path from the UI and copying the backed up database back in repeatedly failed, so I was forced to recreate the database.  This took a month in the end, due to an unfortunately timed machine failure toward the end of the first recreate: successful DB recreation took 14 days for a 1.4TB backup.

A month felt like a long time to be unable to back up, so if you do find a reasonable solution to this I think those affected will be appreciative!

**Comment by Pectojin** [comment]
Hmm, reconfiguring the DB path manually should have worked. At least I'm not aware of any reason it shouldn't.

I haven't sat down to look at this since last time, but perhaps there should just be an advanced option to specify a DB path in the UI

**Comment by ConradHughes** [comment]
So I can't recall the exact circumstances now, but I'm pretty sure that I couldn't change the path to point to my pre-existing non-default-location database file after I'd imported and it had used the default location.  It might have wanted to overwrite the pre-existing database by moving the new blank one it had just created, I forget.  If it's useful I might try to work through the process again at some point.

I'm not sure what repair is supposed to do, but that option definitely didn't work: it failed almost immediately and told me my only option was to re-create.  Some of this could of course be down to Synology/DSM-induced problems, so if I run some tests I'll maybe do them on my Debian desktop, where things should be better behaved.

**Comment by Pectojin** [comment]
Repair is mostly for fixing small differences between the remote and the local, but if a repair fails it won't attempt a repair again because it assumes the DB is broken in a way that makes it easier to recreate.

If you don't know if you can count on the DB then you essentially have to check all the data at which point you may as well just recreate.

**Comment by ConradHughes** [comment]
Just to report that the import capabilities in recent versions (e.g. 2.0.3.2) do pretty much resolve this issue: while “import metadata” didn't pick up the backed-up configuration's database location, manually setting the path to the original database file later on in the backup process now presents appropriate questions and allows successful adoption of the original database (I think — it's still thinking about it, but has definitely picked up the database and registered changes with respect to the backup destination).

Thanks!

**Comment by warwickmm** [comment]
Sounds like this has been resolved.
