### ISSUE TITLE
During restore: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by Germs2004** [duplicati/duplicati#3036]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info
- **Duplicati version**: Duplicati - 2.0.2.19_canary_2018-02-12
- **Operating system**: Windows Server 2016
- **Backend**: Windows Server 2016 shared folder

## Description
A first-time user, I installed the latest Duplicati Canary, created a backup job, ran the backup, then ran a restore. The restore seemed to work fine because I got the file I expected and was able to open it, but the logs show a warning that I assume is a programming bug that ought to be fixed:

Warnings: [
Failed to apply metadata to file: “E:”, message: Object reference not set to an instance of an object. => Object reference not set to an instance of an object.

It’s possible that the problem is failing to apply NTFS permissions. I noticed that I had to give myself permissions on the file before I was able to open it.

Also strange is that the warning says the file is just “E:”. I believe it should say “E:\my file name.pdf”.

**Comment by warwickmm** [comment]
I'm not sure why `E:` by itself is an entry in the collection of metadata records, but that is likely the reason for the warning, as well as the failure to apply permissions.

In the `RestoreHandler.ApplyStoredMetadata` method, the call to `SystemIOWindows.PathGetDirectoryName` will return `null` [if the provided path denotes a root](https://msdn.microsoft.com/en-us/library/system.io.path.getdirectoryname(v=vs.110).aspx) (such as a drive letter).  The subsequent call to `SystemIOWindows.DirectoryExists` calls `SystemIOWindows.IsPathTooLong`, which assumes that the provided path is not `null`.

This null reference exception is caught before the permissions are applied, and the warning is then issued.

I think the real issue is that a root path (e.g. ,`E:`) is showing up in the collection of records.  Can you provide some more detail on how you've specified the source data being backed up?

**Comment by Germs2004** [comment]
I back up several folders from D: that have multiple levels of subfolders.  I tried to restore a random file from those subfolders to the root of E: as a test.  The file restored correctly and opened fine, but I noticed the warning in the log afterward.

Backup job settings export attached.
[BackupJob.json.txt](https://github.com/duplicati/duplicati/files/1740564/BackupJob.json.txt)

**Comment by warwickmm** [comment]
Thanks.  Unfortunately, I don't have a Windows machine to try and replicate this.  If you could list in more detail the steps to reproduce this (e.g., what options you chose for the restore process, etc.), that would really help others who may of better assistance.

**Comment by Germs2004** [comment]
Strangely, I just tested it again several times with various restore settings, and it worked every time without any warnings.  I think the only change I've made since my first test, which got the warning, is installing the C++ Redist files for 2015 and 2017, and rebooted.  I guess if you can't reproduce the error, it's best to mark this issue as closed until someone can reproduce the problem again.  Thanks for looking at it though.

**Comment by warwickmm** [comment]
No problem.  If you encounter the problem again, please feel free to re-open this issue.
