### ISSUE TITLE
2.0.2.19: Setting multiple retention options (--keep-time, --retention-policy) is not permitted

### ISSUE THREAD

**Issue by huste** [duplicati/duplicati#3045]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info
- **Duplicati version**: 2.0.2.19
- **Operating system**: Win10
- **Backend**: local hard drive

## Description
Error "Setting multiple retention options (--keep-time, --retention-policy) is not permitted" after upgrading from previous version to 2.0.2.19 (I think it was the first one introducing smart retention)

## Steps to reproduce
None. It's probably something with my backup.
I changed the retention policy in the old version to a smart custom one:
      {
        "Filter": "",
        "Name": "retention-policy",
        "Value": "1W:1D,4W:1W,3Y:1M",
        "Argument": null
      },

Obsiously, something happened in 2.0.2.19, because it wouldn't want to backup any more with said error message.
I found that the UI showed "keep backups for two years". I then changed it to use my custom one again. To no avail. The UI still showed the "keep backup for two years" option enabled.
I then exported the backup job and noticed that there were both filters in it. The one mentioned above and another one
      {
        "Filter": "",
        "Name": "keep-time",
        "Value": "2Y",
        "Argument": null
      },

I then changed the backup job to the default "smart retention" and saved it.
Then I changed this smart retention to my custom one and the backup job works as expected again.

**Comment by TekkiWuff** [comment]
@huste 
This is somewhat expected. With 2.0.2.18 we made all retention options (`--keep-time`, `--keep-versions`, and `--retention-policy`) mutual exclusive. The GUI is supposed to let you only select one of these and delete the previous selected option when you change your selection. This doesn't seem to work 100% correctly.
According to some people in the forum, you can fix this by selecting `Keep all backups`, saving, going into the options again and then selecting your prefered retention options.

@kenkendk 
Since we are getting a lot error messages like this, I had a look at the commit that added the GUI for the retention policy (https://github.com/duplicati/duplicati/commit/639a7dc892b01e2355bd784f8bb76a8a9b31c73d#diff-dc921566057e1858b10998f97ccbd7f3). If I'm not mistaken, then the following code is supposed to delete all but the selected retention options:
https://github.com/duplicati/duplicati/blob/639a7dc892b01e2355bd784f8bb76a8a9b31c73d/Duplicati/Server/webroot/ngax/scripts/controllers/EditBackupController.js#L318-L333

I noticed that none of these conditions contain the `custom` `KeepType`. So whenever somebody selects `Custom` his or her previously selected retention options stays in place and the `Custom` gets added additionally. Is this intentional?

**Comment by kenkendk** [comment]
No, that is not intentional. That should be cleaned up.

**Comment by kenkendk** [comment]
Fixed with 9297392
