### ISSUE TITLE
Duplicati freezes while compacting remote data

### ISSUE THREAD

**Issue by abrow169** [duplicati/duplicati#3084]
This may be relevant to #2968?
- [X ] I have searched open and closed issues for duplicates.

----------------------------------------
- **Duplicati version**: Canary 2.0.0.7
- **Operating system**: Windows 10
- **Backend**: FTP

Currently we are in the process of backing up all the computers in our lab using duplicati. Most are on the scheduled nightly back ups while a couple are still going through their first run. Most of the computers are Windows 7 and have been running alright. At some point both Windows 10 computers have experienced the following issue.

While performing the scheduled nightly backup, it freezes as it compacts the remote data. This happened to the first computer a week ago and I just ignored it until it unfroze and two days later it was backing up automatically, no problem. Now the second Windows 10 computer has been experiencing this during its schedules nightly backup and I don't know if I should fiddle around with the computer or not. The progress bar is misleading and it doesn't show any progress otherwise so I'm not 100% sure it's even frozen.  

It won't perform repairs and that's as much fiddling as I've done.

![error_frozen](https://user-images.githubusercontent.com/36893503/37045158-45351f78-2133-11e8-9da1-e0e06c6bbb66.png)

**Comment by Scarfmonster** [comment]
I think the issue here is that in general Duplicati doesn't show any progress during compacting at all. It works fine and does not actually freeze, if you look at the Task Manager you should see Duplicati downloading and uploading data, but the only states you ever see in the gui is "in progress" and "done".

**Comment by abrow169** [comment]
I didn't look at the task manager because by the time I read this, the issue resolved itself. Is the progress bar overall for duplicati inaccurate or is it less prone to update on Windows 10  computers specifically?

**Comment by Scarfmonster** [comment]
For compacting, I've seen it do that on Windows 7 as well, so it's most likely not a system specific issue. I've never used Duplicati on anything else but Windows though. Normal backup progress always worked fine as well.

**Comment by Pectojin** [comment]
The progress bar is tricky with many of these operations, because it sometimes displays progress very poorly. Overall there is definitely a need to better show to the end user that progress is being made.

When it appears to be freezing you can often see if it's making progress by looking in the live log (`About` -> `Show log` -> `Live` -> `Profiling`). 

If this is indeed not an issue with freezing, would it make sense to change the title to a request for improved compacting progress? e.g. `[Feature request] Improve progress bar for compacting step`

**Comment by warwickmm** [comment]
This sounds like it was an issue with an uninformative progress bar.  As such, I'm going to close this in favor of #3397.  If anyone thinks this is a separate issue, please feel free to re-open this.
