### ISSUE TITLE
Connect to server not working

### ISSUE THREAD

**Issue by piegamesde** [duplicati/duplicati#3091]
- [ ] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.2.1_beta_2017-08-01
- **Operating system**: Debian Stretch
- **Backend**: Chromium browser

## Description

The "Reconnect to server..." does not work anymore. Neither the automatic one after some delay nor by pressing the button. Only reloading the site will help

## Steps to reproduce

1. Open Duplicati and log in on the web interface
2. Quit Duplicati, wait a while and restart it

- **Actual result**:
The application won't reconnect to Duplicati without reloading the page

- **Expected result**:
The application should connect automatically or after pressing the button after Duplicati has started again.

**Comment by Pectojin** [comment]
I tried to replicate, but it seems to work as intended on my system. I waited 2-4 cycles between each attempt (so 30-60 seconds).

How long did you wait before starting the application again? I know the token expires after 10 minutes of inactivity, so *maybe* it's somehow related to that?

**Comment by piegamesde** [comment]
I tried waiting <1min and >1h between starting the server again, same result. Have you set a password to the web interface?

**Comment by Pectojin** [comment]
Aaaah, I have one with and one without. 

The one without can reconnect within 10 minutes, but the one with a password cannot no matter how quickly the server is started back up.

It's related to how the server authenticates. You never actually send your password to the server, but instead the javascript uses the password and some server provided data to create a response that the server can validate.

The client stores this response token and uses it on each request, but if the server restarts the answer is no longer valid because the server forgot the data it gave you when you logged in.

It's not possible to handle this case and log in again automatically unless the Duplicati server starts storing this data on the disk somewhere. 

But perhaps it should redirect you to the login page instead of just stopping at `connecting`?

**Comment by piegamesde** [comment]
> But perhaps it should redirect you to the login page instead of just stopping at connecting?

Yes, this would be a good solution to the issue.

Just out of interest: how does the client-side authentification work exactly? How is the system secured against malicious clients? And does this require the password to be stored in plain text on the server side?

**Comment by Pectojin** [comment]
The client-side authentication is just salting and noncing the password (basically salting the password twice using sha256). Here is [an example in Python](https://github.com/Pectojin/duplicati_client/blob/1607b755d022d68b89d3b51ad58bdeffaa8302d4/duplicati_client.py#L927). It's more secure than sending the password in plan text, but not a lot more secure.

If your server is available over HTTP a malicious client on the network can snoop the token and the nonced password and do whatever it wants (replay, or new requests using the same token) until your session expires.

The password is stored in plan text in the server database currently, so it's not secure if someone already has access to the database.

There are plans to deal with the database security through encryption, but it's not implemented yet. 
As for connecting to your server, over a network you do not trust, you should definitely have HTTPS, but for local connections it's secure enough.
