### ISSUE TITLE
Unable to restore under Linux

### ISSUE THREAD

**Issue by ethauvin** [duplicati/duplicati#3097]
## Environment info

- **Duplicati version**: 2.0.2.21_canary_2018-03-06
- **Operating system**: CentOS 7.4.1708
- **Backend**: Local or HubiC

## Description

Unable to restore after local or remote (HubiC) backup.

## Steps to reproduce

1. Select `Restore`
2. Select Local or Remote Backup
3. Select `Next`

- **Actual result**: 
Error Dialog: `Not Found`
- **Expected result**:
Restore files list

## Screenshots
![2018-03-10 13_13_27-nix2 thauvin us - duplicati](https://user-images.githubusercontent.com/705618/37246898-ffae111c-2466-11e8-9f52-3d7606daac51.png)

## Debug log
[debug.log](https://github.com/duplicati/duplicati/files/1799818/debug.log)

**Comment by Pectojin** [comment]
Total shot in the dark - Are you using a reverse proxy under nginx or apache?

**Comment by ethauvin** [comment]
@Pectojin Good aim. Using Apache for SSL. Any suggestions?

**Comment by Pectojin** [comment]
Pure luck, I discovered this issue on my apache reverse proxy yesterday :)

On the restore page Duplicati is sending the path to the server to tell it which files to list. So on first load it will send something like "show me files and folders in `/`"

    /api/v1/backup/17/files//?prefix-only=false&folder-contents=true&time=2018-03-10T22:08:07+01:00&filter=/

But that doesn't work for URL's, so it's URL encoding the `/` 

    api/v1/backup/17/files/%2F?prefix-only=false&folder-contents=true&time=2018-03-10T22%3A08%3A07%2B01%3A00&filter=%2F

Turning `/` into `%2F`, but unfortunately Apache reverse proxy is also "smart" like that, so it URL encodes that path once more - Turning `%2F` into `%252F`. So suddenly Duplicati is looking for the path `%2F` instead of `/`.

The easiest thing is to connect directly instead of through the reverse proxy, but if you want to do it right you need to disable the URL encoding in the reverse proxy.

I haven't actually fixed it on my setup yet, but I think it's something like this: https://serverfault.com/questions/524751/apache-reverse-proxy-encodes-characters

**Comment by ethauvin** [comment]
You nailed it @Pectojin. 👍 

I was able to fix it by adding the following to my Apache proxy configuration:

```
    AllowEncodedSlashes On
```

My virtual host configuration now reads something like:

```
    ServerName example.com
    ProxyPreserveHost On
    ProxyRequests off
    ProxyPass / http://127.0.0.1:8200/
    ProxyPassReverse / http://127.0.0.1:8200/
    AllowEncodedSlashes On
```

Thanks!

**Comment by Pectojin** [comment]
Ah, cool! Works like a charm on my system as well now 👍
