### ISSUE TITLE
Office 365 and 2FA?

### ISSUE THREAD

**Issue by zappeee** [duplicati/duplicati#3101]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info
- **Duplicati version**: 2.0.2.1
- **Operating system**: Windows 10
- **Backend**: OneDrive for Business

## Description
We recently got 2FA on our Office365 accounts.
Now when I try to backup I just get the error message of "No sharepoint web could be logged in to at..."
I tried to replace my password with an app password but got the same error.
Have anyone got this to work with 2FA?
Is there anywhere I can see in detail what the issue is?
I know there's been issues with O4B before so I'm not sure if this is 2FA or not

## Steps to reproduce
Activate 2FA on Office365, probably

- **Actual result**:
Error message as above
- **Expected result**:
Successful backup

## Screenshots
.

## Debug log
.

**Comment by xyzlabc** [comment]
Would this have anything to do with #2210 ?

**Comment by tygill** [comment]
Both this and #2210 might be solved with #3024, as using the Microsoft Graph APIs consolidates authentication for both personal and business OneDrive / SharePoint (as well as unifying the file API, so a single backend should be able to provide support for all of them). I've started looking at implementing this, and hopefully will have some more time to work on this in the next few weeks.

**Comment by zappeee** [comment]
I see, thanks for the info!

So currently Duplicati is not compatible with Office 365 2FA?

**Comment by wjansenw** [comment]
Maybe if you use rclone as backend? They haven't moved to the new API yet either I believe. But checking doesn't hurt :).

**Comment by cmthomps** [comment]
I have 2FA authorization enabled for Office 365.  Duplicati will work if you set-up an App Password.  
[https://support.office.com/en-us/article/create-an-app-password-for-office-365-3e7c860f-bda4-4441-a618-b53953ee1183](url).   Obviously bypassing the 2FA auth, but it works.

**Comment by zappeee** [comment]
@cmthomps, I tried that but it still gives me errors unfortunately.

**Comment by tygill** [comment]
FYI, the OAuth service used by Duplicati has been updated to support MS Graph authentication, so I believe you should be able to use OneDrive, OneDrive for Business, or SharePoint sites with 2FA / OAuth tokens if you use the `OneDrive v2` or `SharePoint v2` backends..

(This morning my OneDrive for Business and SharePoint sites aren't actually working, but it appears unrelated to Duplicati since the MS Graph API Explorer tool is also having errors.)

**Comment by zappeee** [comment]
Is it in the latest Canary?

**Comment by tygill** [comment]
Yes, it is.

**Comment by zappeee** [comment]
Which "Storage Type" should I use now?

I tried "Microsoft Office 365 Group" and "Microsoft OneDrive v2", both gave me "Failed to connect: Unwrapped TargetInvocationException"

**Comment by tygill** [comment]
If you want to store in either type of OneDrive account (personal or 'for business'), then the `OneDrive v2` backend should work.

(`SharePoint v2` might work, but it's aimed more at team sites, e.g., `<tenant>.sharepoint.com/teams/<team>/Shared Documents/`. `Office 365 Group` is aimed at Office 365's new style of [groups](https://support.office.com/en-us/article/Learn-about-Office-365-groups-b565caa1-5c40-40ef-9915-60fdb2d97fa2), which have an associated SharePoint library linked to them - unfortunately, they also require the tenant admin to explicitly allow Duplicati to have permission to read group metadata (`Group.Read.All`) to find it, so they likely won't be as useful.)

Which canary are you using? I've tested with the previous (2.0.3.4) and today's (2.0.3.5), and both `OneDrive v2` (personal and 'for business' accounts) and `SharePoint v2` have been working. (Note that when using the `OneDrive v2` backend with a 'for business' account, the path you specify no longer needs to have the full site path - you just need the relative path inside the drive, as the AuthID provides the details about which account to store it in.)

For reference, these are the settings I'm using for `OneDrive v2`:
![image](https://user-images.githubusercontent.com/1046210/38744614-8bd21208-3eff-11e8-9bbe-8a3091d4f85d.png)

And these are what I'm using for `SharePoint v2` (to access a team site instead of my OneDrive for Business):
![image](https://user-images.githubusercontent.com/1046210/38744728-cbd7f16a-3eff-11e8-9f16-1b4020a4fbc2.png)
(I had to stretch the text box to make it all visible in the screenshot.)

There have been some authentication issues (related to which permissions each storage type requires) that kenkendk and I have been working through, so if you generated an AuthID before we made those fixes things might not be working. Can you try again with the latest canary and a new AuthID? 

If you're still hitting issues, you can try running the `Duplicati.CommandLine.BackendTester.exe` tool, which should report the full MS Graph exception (including the request and response if there was an error). These are the settings I've been generally using to quickly test it (you just need to add your AuthID) - just make sure you don't have anything at the `duplicati-test/v2` path that you don't want deleted:
`Duplicati.CommandLine.BackendTester.exe onedrivev2://duplicati-test/v2 --auto-clean --auto-create-folder --force --extended-chars="-_',=)($@! +" --trim-filename-spaces --max-file-size=50mb --reruns=1 --number-of-files=4 --authid=<authid>`

**Comment by tygill** [comment]
Have you tried clearing the cache or forcing it to reload the whole page completely? I've seen a few times where Duplicati hasn't loaded everything fresh after an update, leading to things not being completely in sync. Can you send a screenshot of what you see?

**Comment by zappeee** [comment]
Clearing cache did the trick.
Now the 2FA works.

What path am I supposed to use?
The one I used before, "personal/<myemailaddress>/Documents/Pathto/Backup", didn't work.
Although it works if I browser to it, "https://<nameofsharepoint>.sharepoint.com/personal/<myemailaddress>/Documents/Pathto/Backup"

**Comment by tygill** [comment]
The `OneDrive v2` backend just takes the relative path from the root of the drive (for both personal and 'for business' OneDrive). Since the OAuth token encodes the user account, the `personal/myemailaddress/Documents` part is no longer needed - it should work with just `Pathto/Backup`.

**Comment by zappeee** [comment]
Now that works, thanks!

I only get these warnings while doing the backup

`Warnings: [ 
2018-04-24 15:07:37 +02 - [Warning-Duplicati.Library.Main.Controller-UnsupportedOption]: The supplied option --auth-username is not supported and will be ignored, 
2018-04-24 15:07:37 +02 - [Warning-Duplicati.Library.Main.Controller-UnsupportedOption]: The supplied option --auth-password is not supported and will be ignored ]`

**Comment by tygill** [comment]
It looks like parameters for the old backend aren't being removed from the configuration when switching to the new backend (I think I've seen someone else report this, but don't remember where or when or how that was resolved). A few thoughts on how it might be fixed:

- Do the `--auth-username` or `--auth-password` parameters show up in the advanced options in the final edit step in the UI? If so, try removing them from there.
- You can try switching back to the old backend, clear the values for the parameters, and then switch back to the new backend.
- You can try exporting the config, deleting these parameters from the exported JSON, and then reimporting the backup.

**Comment by zappeee** [comment]
Also, how often do I need to recreate the AuthID?
I'd have to do it twice since the backup stopped working.

**Comment by macmiranda** [comment]
> Now that works, thanks!
> 
> I only get these warnings while doing the backup
> 
> `Warnings: [ 2018-04-24 15:07:37 +02 - [Warning-Duplicati.Library.Main.Controller-UnsupportedOption]: The supplied option --auth-username is not supported and will be ignored, 2018-04-24 15:07:37 +02 - [Warning-Duplicati.Library.Main.Controller-UnsupportedOption]: The supplied option --auth-password is not supported and will be ignored ]`

I have the same here

**Comment by ts678** [comment]
> I have never input any username or password for this config.

[Password saver may autofill too many places, getting --auth-password is not supported #4102](https://github.com/duplicati/duplicati/issues/4102) may explain how it got there if you ever saved a password from any Duplicati screen, including login to GUI. Look in browser settings for whatever URL Duplicati is on.

[Changing backend type leaves invalid backend options #3082](https://github.com/duplicati/duplicati/issues/3082) would explain why these weren't cleared when switching destination. Duplicati's initial destination of `Local folder or drive` accepts these, but some other destination types (such as this one) do not.

[Backup to OneDrive v2 triggers UnsupportedOption: --auth-password every time #4099](https://github.com/duplicati/duplicati/issues/4099#issuecomment-585887760) explains how to clear extras with the GUI.

**Comment by macmiranda** [comment]
Thanks. I believe this can be closed.
