### ISSUE TITLE
Backup concept like grandfather-father-son for having multiple full-backups

### ISSUE THREAD

**Issue by DMW007** [duplicati/duplicati#3182]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.3.3_beta_2018-04-02
- **Operating system**: Debian 8.10 as host OS for duplicati's official docker image
- **Backend**: Local/OneDrive

## Description
I'm evaluating duplicati as main backup-tool with security and OS in mind. In general, I like the software. But it's backup strategy is not really clear to me. In the retention settings (step 5 in edit view), we can choose simple strategies like "Keep a specific number of backups". The [documentation say](https://www.duplicati.com/articles/FactSheet/) that duplicati creates only a single full-backup initially. Afterwards, incremental backups are created.

So my first question is: Lets assume we specify something like _Keep 10 backups_. According to the documentation, i'd assume that this would result in one intial full backup, and 9 incremental backups. But what's done after those 10 backups exists? Deleting the oldest incremental backup isn't possible since all incremental backups depends on the previous one. Does duplicati creates a second full-backup in this case, and delete only the oldest incremental backup from the previous full-backup?

### The goal: Some kind of rotating-concept with multiple full-backups

The approach of incremental backups is a good idea to save storage and in case of cloud-backups also bandwitch. But from a security perspective, I really like to have multiple full-backups. Because if a single incremental backup or even the initial (parent) full-backup is broken for some reasons like i/o or network issues, the hole backup is unusable in the worst case. 

To solve this problem, some rotation-concepts like [grandfather-father-son](https://en.wikipedia.org/wiki/Backup_rotation_scheme#Grandfather-father-son) exists. Here we have several full-backups, also older ones. So we've save from loosing all the data, if a single incremental or full-backup breaks. 

### Configuration of duplicati
In step 5 of the edit-view, I found two interesting options. The first one,_Smart backup retention_, is described like this:
> Over time backups will be deleted automatically. There will remain one backup for each of the last 7 days, each of the last 4 weeks, each of the last 12 months. There will always be at least one remaining backup.

This sounds like some kind of grandfather-father-soon concept. So am I right that this retention would keep

* 7 backups from the last 7 days, where day 1 is a full-backup and day 2-7 are incremental backups on top of the full-backup from day 1
* 4 backups from the last 7 weeks, where all of them are full-backups
* 12 backups from the last 12 months, where all of them are full backups

Or do we have also incremental backups for the weeks and months (e.g.: week 1 is a full-backup, where week 2-4 are incremental ones on top)? 

And is this logic here also applyable to the custom backup rentention? Using the syntax from the docs, I assume that `7D:1D,4W:1W,12M:1M.` would result in the same bevavior than the smart backup retention and also the description from me above. Feel free to correct me, if I understood something wrong.

**Comment by kees-z** [comment]
I have good news for you: **every** backup is a **full** backup.
After a backup job has run 200 times, you have 200 full backups (assuming that every backup run has modified source data since the last backup).

There are no incremental backups. There is no backup that depends on another backup. The term "incremental" is used to point out that only modified data is uploaded, but is a little misplaced. A traditional incremental backup relies on all prior incremental backups and the most recent full backup, but Duplicati backups don't depend on any other backup.

The first time a backup is made, all source data needs to be uploaded to the backup target, so some people call this a full backup. After the first backup operation, only new and modified data is uploaded, unchanged data is already stored at the remote end. This is why some people call it an incremental backup. But the result is a full backup, without any dependancy on the first backup.

The retention policy deletes one or more (full) backups by deleting the restore point (the date and time a particular backup is made) and all blocks of data that are **not** allocated by any other (full) backup. This process thins out the list of available restore points, otherwise the list of backups would keep growing. It also saves some storage space at the backend.
Using a smart or custom retention policy, you can keep a larger amount (full) recent backups and a lower amount of older (full) backups, effectively the same as the GFS policy you describe.

**Comment by ts678** [comment]
> The goal: Some kind of rotating-concept with multiple full-backups

is the polar opposite of what Duplicati intends to do, which is to lower redundant data storage by keeping no block in storage that isn't in use by some file in some backup version. A particular block may appear in multiple files though, which means losing a single destination dblock file (has blocks) may have wide effects. [The AFFECTED command](https://duplicati.readthedocs.io/en/latest/04-using-duplicati-from-the-command-line/#the-affected-command) can answer this question, A lab example is [here](https://duplicati.readthedocs.io/en/latest/08-disaster-recovery/#inventory-of-files-that-are-going-to-be-corrupted).

There are people who rotate plug-in drives through Duplicati, with each backup assigned a drive, and likely both backups the same. This gives you multiple "full" (in the Duplicati sense) backups. You can do similar things to maintain duplicate backups on OneDrive. Personally, I do multiple backups to different destinations. This is good backup practice. Better yet would be using diverse software.

[Allow targeting multiple destinations [$165] #234](https://github.com/duplicati/duplicati/issues/234) is likely seeking easier support of multiple "full" backups to different destinations.

I can see backup rotations of local media with full backups, but would one really want to upload full backups to OneDrive so often? Duplicati's design seems far friendlier to people who are trying to minimize their network and storage utilization, however this does mean that backup files are "processed" data and not your source files. This adds additional ways to fail, and it bothers some people.

**Comment by warwickmm** [comment]
I don't think there's any action to take here.
