### ISSUE TITLE
Backup hangs after laptop sleeps

### ISSUE THREAD

**Issue by Mossop** [duplicati/duplicati#3200]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.3.3_beta_2018-04-02
- **Operating system**: OSX 10.13.4
- **Backend**: Minio S3 Compatible on a server on my local network but visible to the public internet

## Description

I started an initial backup running while I was at my office. I later closed my laptop to put it to sleep, went home and then opened my laptop again. The backup now seems to be stuck. Duplicati says the backup is running but no details about what it is backing up. The last two log messages show that shortly after I woke the laptop up it started trying to send some files but nothing has happened for the 25 minutes since then:

    Apr 30, 2018 4:40 PM: put duplicati-i4053118ec79c4192b43042f26fcfaeda.dindex.zip.aes
    Apr 30, 2018 4:40 PM: put duplicati-b0a49c0fc84e24e8a879b6935edeb02a2.dblock.zip.aes
    Apr 30, 2018 2:59 PM: put duplicati-i3229bef0e3dd46d08ed7df0366b2f966.dindex.zip.aes
    Apr 30, 2018 2:59 PM: put duplicati-b7259b2ba20a64c869627a9d409e56a4c.dblock.zip.aes

## Screenshots
https://screenshots.firefox.com/GdSJ8QchFiqo7SJR/localhost

**Comment by Germs2004** [comment]
Your screenshot has expired.

Is Duplicati using the external IP to your Minio destination at all times, like at work and at home?  If it's using a DNS lookup, make sure that the DNS server at work is returning the external IP address for the Minio because I'd imagine that it would return an internal IP by default, so at home, Duplicati might still be looking for the internal IP.  Either way, this sounds like it still needs addressing by Duplicati devs because it should fail nicely if it can no longer find the backup destination.  Going to sleep should probably just abort any active backup jobs.

**Comment by Mossop** [comment]
It returns the external IP at all times. Anyway I gave up on Duplicati some time ago.

**Comment by warwickmm** [comment]
Unfortunately, this issue is difficult to duplicate.  I am not experiencing any issues with the backup after suspending/resuming my laptop.  Closing this for now, as we can reopen this later if necessary.
