### ISSUE TITLE
Email fails to send with TLS

### ISSUE THREAD

**Issue by Germs2004** [duplicati/duplicati#3232]
- [X ] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info
- **Duplicati version**: 2.0.3.3_beta_2018-04-02
- **Operating system**: Windows Server 2016

## Description
If I prepend SMTPS to my email server connection string, it fails to send with this error appearing in the log:

`{"ClassName":"System.IO.IOException","Message":"The handshake failed due to an unexpected packet format.","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at Duplicati.Library.Modules.Builtin.SendMail.OnFinish(Object result)","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":"8\nOnFinish\nDuplicati.Library.Modules.Builtin, Version=2.0.3.3, Culture=neutral, PublicKeyToken=null\nDuplicati.Library.Modules.Builtin.SendMail\nVoid OnFinish(System.Object)","HResult":-2146232800,"Source":"Duplicati.Library.Modules.Builtin","WatsonBuckets":null}`

I did a packet capture while Duplicati was configured to use the SMTPS server string, and the packet trace looks like this:
1) TCP SYN out to the email server
2) TCP SYN ACK in from the email server
3) TCP ACK out
4) TLS1.2 Client Hello out
5) TCP ACK in
6) SMTP server header in:
`Response: 220 SN1NAM02FT047.mail.protection.outlook.com Microsoft ESMTP MAIL Service ready at Thu, 24 May 2018 02:20:09 +0000\r\n`
7)  TCP RST ACK out, killing the connection

I'm not an email or TLS master, but it seems that Duplicati sent a TLS 1.2 packet in frame 4 and the email server responded in plaintext in frame 6.  Since this is a Microsoft server, I doubt they're doing it wrong, so I'm guessing that Duplicati is somehow not sending the correct TLS packet so Microsoft ignored it and replied in plaintext.

I can send email successfully if I append STARTTLS=ALWAYS to my server string, so this is a good workaround for now, but it would be nice to get regular TLS working correctly.

This server string does NOT work in Duplicati:
smtps://MYDOMAIN-com.mail.protection.outlook.com:25

This server string works in Duplicati:
smtp://MYDOMAIN-com.mail.protection.outlook.com:25/?starttls=always

I am able to successfully send an email using TLS1.2 with the following Powershell command, so it seems the Microsoft email server is working ok with TLS1.2 as long as it's formatted the way Microsoft expects.
```
[System.Net.ServicePointManager]::SecurityProtocol = 'TLS12'
Send-MailMessage -From noreply@MYDOMAIN.com -Subject "test 1" -To MYEMAIL@MYDOMAIN.com -Body "test 111" -Port 25 -SmtpServer MYDOMAIN-com.mail.protection.outlook.com -UseSsl
```

The email server is Office 365 configured with a Relay Connector that authenticates all email by our public IP address.  That way, I don't have to enter a username and password into Duplicati.

**Comment by mnaiman** [comment]
Hi,

It seems that you are combining TLS on STARTTLS port (25).
There is big difference - https://www.fastmail.com/help/technical/ssltlsstarttls.html

**Comment by mnaiman** [comment]
This is expected to be working smtp://MYDOMAIN-com.mail.protection.outlook.com:25/?starttls=always
This NOT on same port smtps://MYDOMAIN-com.mail.protection.outlook.com:25
Its like trying to make HTTPS request to port 80.

**Comment by ts678** [comment]
> I am able to successfully send an email using TLS1.2 with the following Powershell command

Please take a look at its packets, as you did for Duplicati's. When I tested this to outlook.com, it did STARTTLS, then did TLS.

When I used `curl` to try to force TLS directly into port 25, it closed on me because it presumably only uses STARTTLS plan.

[POP, IMAP, and SMTP settings for Outlook.com](https://support.microsoft.com/en-us/office/pop-imap-and-smtp-settings-for-outlook-com-d088b986-291d-42b8-9564-9c414e2aa040) says "SMTP encryption method STARTTLS", and asks for port 587 although port 25 apparently works too. Connecting to either one gives me the 220 Mail service ready. The usual port for TLS without doing STARTTLS process is usually 465. I agree with @mnaiman that you can't push TLS into a non-TLS port, and MS provides no port for direct TLS.

**Comment by ts678** [comment]
> it would be nice to get regular TLS working correctly.

This requires  a port on email server ready to accept it directly. Sometimes 465 is used for implicit TLS, but it's controversial.

[Which SMTP port should I use? Understanding ports 25, 465 & 587](https://www.mailgun.com/blog/email/which-smtp-port-understanding-ports-25-465-587/)

[SMPT Port 465 and Port 587: What’s the Difference?](https://sendgrid.com/blog/whats-the-difference-between-ports-465-and-587/)

[RFC 8314 "Cleartext Considered Obsolete: Use of Transport Layer Security (TLS) for Email Submission and Access", January 2018](https://www.rfc-editor.org/errata/rfc8314)

> so it seems the Microsoft email server is working ok with TLS1.2 as long as it's formatted the way Microsoft expects.

Original post analyzes low-level TCP and TLS which is entirely formatted by Microsoft, because Windows is what's doing TLS.

[TRANSMISSION CONTROL PROTOCOL](https://www.ietf.org/rfc/rfc793.txt)
[The Illustrated TLS 1.2 Connection](https://tls12.xargs.org/)

I'm not seeing anything here that isn't working (or failing) as it should.
