### ISSUE TITLE
Duplicati still uses full CPU after interrupting backup

### ISSUE THREAD

**Issue by piegamesde** [duplicati/duplicati#3268]
- [ ] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.3.6_canary_2018-04-23
- **Operating system**: Arch linux
- **Backend**: SFTP

## Description
Yesterday, I ran the backup and as usual had issue #3205. I let it run for the night and then stopped the still running backup. A few hours later, Duplicati is still using 12% CPU constantly (that's a full core) for seemingly no reason. It does not indicate to be doing things.

## Steps to reproduce
1. Start a backup and abort it during the "Verifying backup" phase
2. Wait a while
3. Have a look at the CPU usage

- **Actual result**: Duplicati still uses 12% CPU
- **Expected result**: It should be 0% since it's doing nothing. Alternatively, it should tell me what it's doing

## Workaround

    systemctl --user restart duplicati

**Comment by ts678** [comment]
> Alternatively, it should tell me what it's doing

It's been awhile, but do you recall what was it telling you on the status bar? If live, try About --> Show log --> Live at some level.
Verbose might be a good blend. Profiling is the last resort, as the output is huge, but it's also the most sensitive logging available.

Using the advanced options for a log file is probably better, as then you're more likely to see the activities leading up to the issue.

There might also be some times when Duplicati can't tell you what it's doing because it's actually `mono` doing work underneath it.

There are several open issues involving mystery CPU use, but I guess here I'll check on the interest level to help gather some data. Presumably a lot of fixes have taken place in both Duplicati and `mono` since 2018, so another question is whether it still happens?

I'll set the labels so this issue won't automatically go stale on no response.

**Comment by piegamesde** [comment]
Yep, it's been a while ^^
