### ISSUE TITLE
Counting of size of file to go

### ISSUE THREAD

**Issue by mnaiman** [duplicati/duplicati#3305]
- [ x] I have searched open and closed issues for duplicates.

----------------------------------------

- **Duplicati version**: 2.0.3.8_canary_2018-06-28
- **Operating system**: Win10
- **Backend**: File storage - local

Remaining file size is jumping in weird jump, sometimes positive, sometime negative.

![image](https://user-images.githubusercontent.com/2264442/42157065-044e08d2-7ded-11e8-9772-7828cf1bd800.png)

**Comment by mnaiman** [comment]
I captured some jsons from which it is calculated:

1 file (-4689821696 bytes) to go

{
  "BackupID": "2",
  "TaskID": 7,
  "BackendAction": "List",
  "BackendPath": null,
  "BackendFileSize": -1,
  "BackendFileProgress": 0,
  "BackendSpeed": -1,
  "BackendIsBlocking": false,
  "CurrentFilename": "some file name",
  "CurrentFilesize": 42786095104,
  "CurrentFileoffset": 31537561600,
  "Phase": "Backup_ProcessingFiles",
  "OverallProgress": 0.0,
  "ProcessedFileCount": 0,
  "ProcessedFileSize": 0,
  "TotalFileCount": 1,
  "TotalFileSize": 26847739904,
  "StillCounting": false
}


1 file (-7621431296 bytes) to go

{
  "BackupID": "2",
  "TaskID": 7,
  "BackendAction": "List",
  "BackendPath": null,
  "BackendFileSize": -1,
  "BackendFileProgress": 0,
  "BackendSpeed": -1,
  "BackendIsBlocking": false,
  "CurrentFilename": "some file name",
  "CurrentFilesize": 42786095104,
  "CurrentFileoffset": 34469171200,
  "Phase": "Backup_ProcessingFiles",
  "OverallProgress": 0.0,
  "ProcessedFileCount": 0,
  "ProcessedFileSize": 0,
  "TotalFileCount": 1,
  "TotalFileSize": 26847739904,
  "StillCounting": false
}

**Comment by mnaiman** [comment]
Pattern is TotalFileSize - CurrentFile offset which gave such weird result.

**Comment by dtgriscom** [comment]
Perhaps this is similar, but I'm near the end of my first full backup, and the web page progress bar says:

`MainBackup: -37 files (1.31 GB) to go at 2.14 MB/s`

The number of files stayed at -37 for quite a while, and then suddenly started decreasing further:

`MainBackup: -70 files (355.36 MB) to go at 1.25 MB/s`

and then

`MainBackup: -96 files (14.31 MB) to go at 1.48 MB/s`

Finally, it seems to be completing the backup, but that display has me a bit worried...

Using Duplicati - 2.0.3.3_beta_2018-04-02. Let me know if there's more info I can provide.

**Comment by tgjohnst** [comment]
I just encountered the same behavior as @dtgriscom , during my first backup the number of files eventually became a negative (currently at -3791 files) and is now slowly approaching zero but appears to be continuing the backup successfully.

**Comment by crazy4chrissi** [comment]
I think what @dtgriscom and @tgjohnst report is more this bug: https://github.com/duplicati/duplicati/issues/2188 (negative number of files instead of negative number of bytes and 1 file)

I think you can get rid of the "negative number of files" bug by updating to the latest canary, and get the "negative number of bytes" bug instead ;)

**Comment by kenkendk** [comment]
@dtgriscom and @tgjohnst : Duplicati does a file scan and computes the number of files it expects to encounter. If you add files after the scan, but before the backup has completed, you can see negative numbers. I think the smartest way to handle this is perhaps to simply display `...` instead of a negative number. What are your thoughts?

@mnaiman It looks like you are making a backup of a single file with size `42786095104`. However, the scanner has finished and only found `26847739904` bytes in that file. It does not look like a 32bit wrap-over, as both numbers are larger than 32bit. Is it perhaps a database file that suddenly expanded? Any other idea as to what is happening?

**Comment by crazy4chrissi** [comment]
@kenkendk My backup almost always shows "1 file to go" and a negative size. This is not a 1-file backup, it is a 2,2 million files backup with about 230 GiB . The backup currently runs for about 15 to 20 hours, most of the time with idle IO-priority (`ionice -c 3`). It may be possible that lots of files come and go while the backup is running. The negative size has lots of different values while the backup runs, but mostly small values for me. My backup runs real slow due to idle IO priority, so it is easy to watch it live what it is doing. Currently, it shows -20 bytes and the current file displayed as "current file" has 20 bytes of size (checked with `ls -lh`). Now it does not change for quite a while, in the live log I see lots of files being skipped as timestamp has not changed. Next, it shows -97 bytes, and the "current file" actually has 97 bytes. Now it is taking a lot of time as no file is updated.

This is definitely not an overflow. And the files it is backing up are mostly small html, php files and such. The negative value happens for all of them, it is very unlikely that they all expand while the backup is running. I think I saw positive values once, and I guess it was when the backup had only started recently. I need to check this again, but it will take its time until the current run finishes.

And regarding the negative number of files: I had the same problem with an older version of Duplicati (can't remember which one).  It is gone now, and instead I have the negative size problem. Maybe both issues have the same root cause, and it just shows differently.

**Comment by kenkendk** [comment]
Can you capture the `json` like @mnaiman  did? Just use the browsers developer tools and look at the network tab, and find the `GET /progressstate` call.

**Comment by crazy4chrissi** [comment]
Sure. Here is the current one:
```

{
  "BackupID": "6",
  "TaskID": 26,
  "BackendAction": "List",
  "BackendPath": null,
  "BackendFileSize": -1,
  "BackendFileProgress": 0,
  "BackendSpeed": -1,
  "BackendIsBlocking": false,
  "CurrentFilename": "/var/[...].htm",
  "CurrentFilesize": 97,
  "CurrentFileoffset": 97,
  "Phase": "Backup_ProcessingFiles",
  "OverallProgress": 0.0,
  "ProcessedFileCount": 0,
  "ProcessedFileSize": 0,
  "TotalFileCount": 1,
  "TotalFileSize": 0,
  "StillCounting": false
}
```

All further ones look same, as it currently does not progress any files (all skipped as not changed).

**Comment by kenkendk** [comment]
@crazy4chrissi Ok, that is certainly wrong. It reports only one file found during scanning (`TotalFileCount`), which version of Duplicati is this?

**Comment by crazy4chrissi** [comment]
Duplicati - 2.0.3.9_canary_2018-06-30

Last backup report said it is 2280494 files.

**Comment by kenkendk** [comment]
Found and fixed the problem, thanks for the quick reporting!

**Comment by crazy4chrissi** [comment]
Great. Thank you for quick fixing!
