### ISSUE TITLE
Processing files which are not in backup sources

### ISSUE THREAD

**Issue by mnaiman** [duplicati/duplicati#3307]
- [x ] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info
- **Duplicati version**: 2.0.3.9
- **Operating system**: WIN
- **Backend**: File storage

During Backup_ProcessingFiles Duplicati process files which are not in sources

![image](https://user-images.githubusercontent.com/2264442/42288233-2bac629c-7fba-11e8-9e1e-31e9fbbb7278.png)

![image](https://user-images.githubusercontent.com/2264442/42288253-4306f4c0-7fba-11e8-9763-367831206147.png)

Profiling log:
2018-07-04 18:28:56 +02 - [Verbose-Duplicati.Library.Main.Operation.Backup.FileEnumerationProcess-IncludingPath]: Including path as no filters matched: D:\Virtual Machines\test\test\
2018-07-04 18:28:56 +02 - [Verbose-Duplicati.Library.Main.Operation.Backup.MetadataPreProcess.FileEntry-AddDirectory]: Adding directory D:\Virtual Machines\test\

Sometimes it processing "System Volume Information folder" on drive root (which is not on source list either).
![image](https://user-images.githubusercontent.com/2264442/42288821-cf5643ac-7fbc-11e8-8880-a1ee487de65d.png)

**Comment by mnaiman** [comment]
It is VSS related.
With --snapshot-policy=off this is not happening.
VSS code was change heavily during concurrent processing merge - @kenkendk do you have idea?

**Comment by mnaiman** [comment]
Ok, first finding, there is some trouble, look at input folder and what is returned.

![image](https://user-images.githubusercontent.com/2264442/42415057-a9e56e16-8243-11e8-8767-7c31366a252e.png)

**Comment by JonMikelV** [comment]
I can confirm this happens on the two Windows machines I've tested and that it only happens when snapshot-policy is in use.

As described at https://forum.duplicati.com/t/processing-files-which-are-not-in-backup-sources/4009/8, replication of the issue can be done with a simple test job such as:
- `C:\Users\` as source
- `--snapshot-policy=Off`
- `--log-file=C:\_Backups\Duplicati\VSSFilterTest-SnapshotOff.log`
- `--log-file-log-filter=+*.Controller*;+*.FileEnumerationProcess*;-*`

Run `test-filters`, change the snapshot policy to `On` and the log file to end with `On.log` and run again.

I have not had a chance to test on any Linux or MacOS systems, but I suspect it will NOT be an issue there due to differences in file system handling.

**Comment by kenkendk** [comment]
The problem is that the assignment _would_ be atomic if `KeyValuePair<>` was a class. In that case `m_lastLookup` would be a reference/pointer (meaning a single int32/int64 value).

But since `KeyValuePair<>` is a struct, with value sematics, the line:
https://github.com/duplicati/duplicati/blob/06d6352aca385fd0d1bfb3dfef6501dc2998478e/Duplicati/Library/Snapshots/WindowsSnapshot.cs#L433

Is translated to something like this(very pseudo IL code):
```
push localPath;
push mappedPath;
new KeyValuePair(); <- pop 2, push 2 (key + value)
m_lastLookup.Value = pop();
m_lastLookup.Key = pop();
```

And that is very non-atomic, as a race can happen between the last two lines, storing a mixed variable. To make it even worse, the compare also copies the variable to start with, adding another potential problem.

A simple way of thinking of it is that a struct is syntatic sugar for multiple local variables.

We could probably re-introduce it simply with `Tuple<string, string>` instead, as that is an object and uses reference semantics, but I think the performance gain from a few string operations is negligible, and would be offset by the need to do value lookups and string compares.

**Comment by mnaiman** [comment]
Aaaah, thx for explanation!
