### ISSUE TITLE
Rsync - server support

### ISSUE THREAD

**Issue by ajtak-angelus** [duplicati/duplicati#3336]
Please, can you add rsync server for remote backup? Thanks!

**Comment by n1trux** [comment]
you can already backup to SSH/SFTP, the rsync protocol itself doesn't use in-transit encryption and as such, IMHO it shouldn't be used for backups.

**Comment by ts678** [comment]
A Duplicati backup destination (a.k.a. backend) is said to need only a few simple functions, specifically GET, PUT, LIST, DELETE per https://github.com/duplicati/duplicati/wiki/Developer-documentation. rsync doesn't seem to be able to do all those (per rsync man page and https://rsync.samba.org/how-rsync-works.html), however the raw protocol looks like it may be theoretically possible to manipulate into this. May be hard.

Basically, I would expect some resistance to this because rsync is so different from the usual destinations.

What is much more reasonable would be to use rsync to remote-sync a local backup Duplicati maintains.
Please read https://forum.duplicati.com/t/backing-up-duplicati-backups-with-rsync-to-remote-drive/1889 and the other discussions in the forum. There are still some potential pitfalls, but people seem to use this.

https://forum.duplicati.com/search?q=rsync

**Comment by ts678** [comment]
Hearing about benefits from this would be worthwhile. I'm not sure if it's better to take that to the forum.

One nice thing one hears about rsync (e.g. in its man page) is its delta-transfer algorithm which sends the changes from an updated file, not the entire file. Duplicati already does this though. Both are block based.

https://www.duplicati.com/articles/Storage-Engine/

https://www.duplicati.com/articles/Backup-Process/

Please feel free to send your input on why rsync should be added. I don't decide that, but input still helps.

Thanks!

**Comment by Pectojin** [comment]
The only way to use rsync as a Duplicati backend is to open a new rsync connection to "sync" each new volume up. And it will never do anything useful because Duplicati will only ask it to upload new volumes. You'll never ever re-upload the same volume with the same name and there will never be a delta. 

It's basically useless compared to other backends.
