### ISSUE TITLE
Couldn't install Duplicati on Synology

### ISSUE THREAD

**Issue by MaximF** [duplicati/duplicati#3356]
## Environment info
- **Duplicati version**: 2.0.3.3 and 2.0.3.10
- **Operating system**: SynologyOS
- **Mono version**: 4.6.2-0096

## Description
I'm trying to install Duplicati on Synology 218+ through CLI, getting an error 289. Any ideas on what could be wrong there?

## Steps to reproduce
```
# whoami
root
# synopkg install duplicati-2.0.3.10_canary_2018-08-30.spk
Failed to install package duplicati-2.0.3.10_canary_2018-08-30.spk, error = [289]
```

**Comment by ts678** [comment]
> Any ideas on what could be wrong there?

We're low on Synology expertise at the moment. Might Synology support have some idea?

`https://github.com/martinorob/plexupdate/issues/1` on error 289 got the suggestion:

> change the settings on Package Manager to allow the installation of packages published by "Any publisher".

but there's a bigger problem which is DSM 7 changed its packaging requirement. Now Duplicati needs Docker.

While it appears that older releases are not yet end of life, the install type of this issue is going away with time.

Any further interest or thoughts?
