### ISSUE TITLE
When a restore fails no error information is available

### ISSUE THREAD

**Issue by GSPP** [duplicati/duplicati#3486]
I just tried restoring directly from the backup files. I got this error and no further information:

![image](https://user-images.githubusercontent.com/12032350/48314519-177d2780-e5cb-11e8-9189-1790bd61de10.png)

I do not believe there is any log that I can open because this operation was not associated with any specific backup configuration. I should be able to see the errors.

**Comment by mikaelmello** [comment]
You can go to "Settings > Show logs" and check either Live and Remote

**Comment by GSPP** [comment]
The "Stored" log at About->Logs does not have entries for this operation. The Live log is empty. Fyi.

**Comment by ts678** [comment]
Not reproducible in 2.0.7.100_canary_2023-12-27. The Show button on the error (which you lack, so not sure when it went in) goes right to the job log even though it's a `Direct restore`. Prior to 2.0.7.100 I suspect it would have too, but I'm not sure if error would be there. Another way (these days, anyway) to get a log is to have screen 2 options ask for a [log-file](https://duplicati.readthedocs.io/en/latest/06-advanced-options/#log-file) at some path.

Things have improved since 2018. Logging has had various changes. I can't test original mystery issue, so I forced some errors.

If there's any news on this, or continued interest or issue presence, feel free to update. Without more, issue will eventually close.
