### ISSUE TITLE
RUMPS issue on High Sierra introduced between 2.0.4.5_beta_2018-11-28 and  2.0.4.6_canary_2018-12-11 

### ISSUE THREAD

**Issue by BrettDikeman** [duplicati/duplicati#3550]
- [x ] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.4.6_canary_2018-12-11 or higher
- **Operating system**: OS X High Sierra
- **Backend**: N/A

## Description
Installing a release newer than 2.0.4.5_beta_2018-11-28 (possibly starting with 2.0.4.6_canary_2018-12-11, I don't have the time to exhaustively nail down which release) results in a Duplicati installation that cannot run on an up-to-date, largely-unmodified OS X High Sierra system.

## Steps to reproduce

1. Install High Sierra
2. Install 2.0.4.6_canary_2018-12-11 or newer (including as-of-writing current canary release v2.0.4.8-2.0.4.8_canary_2018-12-13

## Result

**Actual result**:
- As installer finishes, Dock shimmies as the Duplicati process repeatedly dies & is relaunched by launchctl
- mono consumes a large amount of CPU time

## Debug log

```
$ /Applications/Duplicati.app/Contents/MacOS/duplicati 
Unexpected message: None
Unexpected message: Exception in thread Thread-1:
Unexpected message: Traceback (most recent call last):
Unexpected message: File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
Unexpected message: self.run()
Unexpected message: File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
Unexpected message: self.__target(*self.__args, **self.__kwargs)
Unexpected message: File "/Applications/Duplicati.app/Contents/Resources/OSXTrayHost/osx-trayicon-rumps.py", line 108, in get_input
Unexpected message: app.menu = parsemenus(cfg)
Unexpected message: File "/Applications/Duplicati.app/Contents/Resources/OSXTrayHost/osx-trayicon-rumps.py", line 51, in parsemenus
Unexpected message: mn = rumps.MenuItem(n["Text"])
Unexpected message: KeyError: 'Text'
```

[Forum post](https://forum.duplicati.com/t/high-sierra-client-wont-run-duplicati-repeatedly-crashes-with-keyerror-text/5713)

My ability to help diagnose this will be limited until my restore finishes, although I just tried to do a restore and that's failing as well with the beta version I was able to get running...

**Comment by Pectojin** [comment]
Happens on my macbook too. It seems to be related to specifically the TrayIcon. Everything works as expected if I launch the server independently.

When launching the TrayIcon the mono process will spawn a child python process consuming 100% of a core and using 3-4GB RAM. Killing the Python child process allows the actual server to keep running and being accessible over web UI, but the TrayIcon never appears. 

Beyond the above log trace, I also see the following spammed repeatedly in stdout
`Unexpected message: 2018-12-20 02:18:54.191 Python[1571:19978] -[__NSCFNumber member:]: unrecognized selector sent to instance 0xf`

**Comment by Pectojin** [comment]
@warwickmm could you take a look? You've got the only changes in [Duplicati/GUI/Duplicati.GUI.TrayIcon/](https://github.com/duplicati/duplicati/commits/master/Duplicati/GUI/Duplicati.GUI.TrayIcon) since 2.0.4.5. 

All the commits look fine to me, but I'm fairly unfamiliar with the TrayIcon implementation.

**Comment by warwickmm** [comment]
Unfortunately, I'm unable to reproduce this (I don't have a Mac, and it runs fine on my Arch Linux machine).  Can someone confirm that 2.0.4.5 does not have this issue?

**Comment by warwickmm** [comment]
I'm flying a bit blind here, but I've posted a [branch](https://github.com/duplicati/duplicati/compare/master...warwickmm:debug/rumps_runner) with a potential fix (just a guess).  @Pectojin, would you be able to build and test this locally?

**Comment by Pectojin** [comment]
I've been trying to replicate the issue in debug but I cannot build anything since 94f34ce5a19b542b6b2e63c0f8e1aea9baf2ebe5. I get a stack full of errors that seems unrelated
<img width="1106" alt="screenshot 2018-12-20 at 09 21 23" src="https://user-images.githubusercontent.com/1561484/50272639-a38b3600-0438-11e9-951d-9f6a5d8cf714.png">
Errors happen in https://github.com/duplicati/duplicati/blob/master/Duplicati/Library/Common/IO/SystemIOWindows.cs

**Comment by Pectojin** [comment]
Good news, everyone! I updated Visual Studio and that did away with my build errors. 

When building in debug mode from master I see the exact same issue as when running the canary release, so this issue is reproduced two ways.

@warwickmm, it appears your patch resolves this issue. I'm kinda amazed you managed to fix something you can't replicate 🥇Will you make the PR?

**Comment by Milznike** [comment]
Hi, guys-

New to this project.  I have been looking through the comments over the past day or so and see you have pinpointed High Sierra.  I just wanted to let you know that I have two different Macs (an early 2008 iMac running El Capitan and a 2013 MacBook Air running Mojave) and they both have the same issue.  So just in case you were looking for more data points, it appears to be affecting OS X across hardware and OS versions.  Looks like you have it all squared away, but wanted to give you the data in the event it is helpful.

**Comment by Pectojin** [comment]
2.0.4.9 is out now with the provided fix
