### ISSUE TITLE
Passphrase request on restore

### ISSUE THREAD

**Issue by yfxwardy** [duplicati/duplicati#3615]
I checked out some topics and issues about this and I am worried about it.
1) I can restore my backups without enter passphrase. Is there any way or option to get duplicati require passphrase on any restore? 
2) After login GUI with master password I can reveal all my passphrase from Duplicati-server.sqlite , isnt it?

I pray for doing duplicati more secure in this case. I think nobody have to be possible restore AES256 encrypted files of users

I appreciate any open sourse product very much and Duplicati is the great one. Thank you.

**Comment by Pectojin** [comment]
1. There's no further password protection than the WebUI login.
2. If you're already password protecting the UI, what does an extra password accomplish? Are you actually trying to solve a different problem? e.g. multiple users using the same server?

**Comment by Robespeler** [comment]
Ok, its your choice and politics.
Password protecting the UI - Ok

Where are master password stored? Is it safe or encrypted?

**Comment by Pectojin** [comment]
It's not my choice or policy. I'm trying to understand what you want to achieve.

Adding a passphrase on restore and nothing else is pointless because a user could just edit the backup job to remove or change the passphrase. 

What is the issue you want to solve?

**Comment by Robespeler** [comment]
> What is the issue you want to solve?

I want the system to require passphrase when I try to restore any backup.
I expect that 3rd person come to my house and will detect open duplicati process and can easily to restore my archive files. Other files on my computer are encrypted.

If I close Duplicati process I loose the schedule function

Thank you for your answer and patience

**Comment by Pectojin** [comment]
If you check the setting "Prevent tray icon automatic log-in" you would have to login to reach the web interface. But if they have full access to your computer they can just read the information from the disk directly regardless or whether or not Duplicati is running.

**Comment by Robespeler** [comment]
My files on disk are encrypted

**Comment by kenkendk** [comment]
@Robespeler There is a choice between security and simplicity, and since a backup is intended to run in the background, Duplicati tries to not bother you too much. It is also a general assumption that if an attacker gets full control of your machine, they can read the files you are backing up directly from disk, so there is no need to perform a restore or interact with Duplicati. In this case they will have access to your login credentials, so if you want to guard against this, you need to be think about how to guard against intruders wiping your remote destinations.

As @Pectojin mentions, you can set the "Prevent tray icon automatic login" to always require a password when accessing the UI. Note that this does not add any additional security, as people with access to click the tray icon can simply extract the contents of the database and filesystem anyway.

We do not currently have integration with the system keystore, nor do we have an option to prevent starting Duplicati without entering a password.

**Comment by Robespeler** [comment]
Thank you for your answer




> people with access to click the tray icon can simply extract the contents of the database and filesystem anyway

This is sad. If I see the master password function and prevent tray icon function I expect that it protects me like any normal user. 



> We do not currently have integration with the system keystore

This is the key point I suppose

**Comment by warwickmm** [comment]
Closing this in favor of #2024, which covers integration with system keystores.
