### ISSUE TITLE
Duplicati creates a lot of unnecessary traffic, increasing extremely WAN backup times and reducing drive lifetime

### ISSUE THREAD

**Issue by JsBergbau** [duplicati/duplicati#3674]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.4.5_beta_2018-11-28
- **Operating system**: WIndows 10
- **Backend**: SMB

## Description

a) Just started the first backup of about 2,5 TB size. Now after about 6 hours when I took a look at the progress I've noticed that duplicati is now constantly fetching a lot of data from the backup location. I have no explanation for that.

I verified via RessourceMonitor that this incoming traffic is from the BackupLocation. There are no other processes accessing this location.

b) On my first test with restoring a backup of about 200 GB size to another location duplicati took the files/blocks from the original location and restored almost everything quite fast. Then before it reported completed it generated a lot of network traffic for a long time. I had the impression duplicati was downloading the whole backup and doing what so ever, because files were restored at that point completely. There was no change in this 200 GB files in between!

c) From another about 2,5 GB backup I've deleted the local database and recreated it.
As far as I know the "dindex.zip.aes" files are relevant for the database. Duplicati copied the whole 2,5 GB just to rebuild the database

## Steps to reproduce

Make a big backup with duplicati

- **Actual result**:
Duplicati generated too much network traffic
- **Expected result**:
a) No big incoming network traffic on the first backup
b) No big incoming network traffic when restoring with local blocks
c) Not fetching the whole backup just to rebuild the database

Duplicati is also intented to store data over WAN, this unnecessary traffic massively slows them down. Currently you need 2 drives. One locally the other in the internet and rsycing them to avoid this unnecessary WAN traffic.

This unnecessary traffic causes more load to the drives, making them warmer and thus also reducing lifetime (at least a bit).

## Screenshots

![grafik](https://user-images.githubusercontent.com/37013344/53301043-2e781a80-3846-11e9-934b-cfb2b0613fc2.png)

**Comment by JsBergbau** [comment]
Update:
It gets even worse. Now backupspeed is only about 1/3 as before and network traffic from backup destination doubled 
![grafik](https://user-images.githubusercontent.com/37013344/53356986-a3218680-3924-11e9-9652-4b318b1d3f19.png)

Still about 700 GB to backup. There is almost no CPU usage caused by duplicati anymore. It's wasting time

**Comment by ts678** [comment]
> duplicati is now constantly fetching a lot of data from the backup location. I have no explanation for that.

I don't either. How do you know it's Duplicati and not, for example, an antivirus or some indexing program?

You can see what Duplicati is doing in real-time with About --> Show log --> Live --> Information, or set a
[log-file](https://duplicati.readthedocs.io/en/latest/06-advanced-options/#log-file)=\<path> [log-file-log-level](https://duplicati.readthedocs.io/en/latest/06-advanced-options/#log-file-log-level)=information for a study after the fact. You'll see few Get operations done.
Here's what \<job> --> Show log --> Remote shows for a 300 MB file backup. Log is reverse-chronological:

```
Jan 17, 2024 11:52 AM: get duplicati-bfd2bb2d7610545d79ee2cb8382f64fd2.dblock.zip
Jan 17, 2024 11:52 AM: get duplicati-ib160c642147848098f2c15cd4bbfcfb7.dindex.zip
Jan 17, 2024 11:52 AM: get duplicati-20240117T165155Z.dlist.zip
Jan 17, 2024 11:52 AM: list
Jan 17, 2024 11:52 AM: put duplicati-20240117T165155Z.dlist.zip
Jan 17, 2024 11:52 AM: put duplicati-ib160c642147848098f2c15cd4bbfcfb7.dindex.zip
Jan 17, 2024 11:52 AM: put duplicati-bfd2bb2d7610545d79ee2cb8382f64fd2.dblock.zip
Jan 17, 2024 11:52 AM: put duplicati-ie3af4972acfb4b2587f1d407be23a77b.dindex.zip
Jan 17, 2024 11:52 AM: put duplicati-b56c71a70a3ab4b3c90b908272528e2c4.dblock.zip
Jan 17, 2024 11:52 AM: put duplicati-i08f3ff1af4ed40538d38ab2de642e761.dindex.zip
Jan 17, 2024 11:52 AM: put duplicati-ib3e3c98a1a1c41db96be575bc2a83db4.dindex.zip
Jan 17, 2024 11:52 AM: put duplicati-b586c3e0fa68a4179928144be81a19c42.dblock.zip
Jan 17, 2024 11:52 AM: put duplicati-be2f2cbbd9e23449abaf82094e7295b56.dblock.zip
Jan 17, 2024 11:52 AM: put duplicati-i5e7e34b1b487442c9aa4e524a48eaa91.dindex.zip
Jan 17, 2024 11:52 AM: put duplicati-i98cbb3d9cfe745c99a04180c49d7455c.dindex.zip
```

There are earlier pages, but the bottom here is the primary backup rhythm. It uploads dblock and dindex files.
There's no constant fetching from Duplicati, in fact the only `get` is generally the configurable end verification.

> because files were restored at that point completely. There was no change in this 200 GB files in between!

[How the restore process works](https://duplicati.readthedocs.io/en/latest/appendix-b-how-the-restore-process-works/) explains how files are restored a block at a time, so you can't rely just on seeing file names.
You also can't rely on reading the file contents because metadata such as timestamps gets restored last, so study carefully.

The same distinction applies to `no-local-blocks`. That helps get the file contents, but I think it doesn't get the metadata.
To get a good view of the restore process, you can run a log (live or file) at `verbose` level, and that will show the activities.

> As far as I know the "dindex.zip.aes" files are relevant for the database.

Again, a verbose log will reveal. Ideally, the order is dlist, then dindex, and dblock only if something still needs to be found.
On the GUI progress bar, dblock reading has three 10% phases starting at 70%, and the 90%-100% is the slow last resort.
Possibly you had a damaged backup. If a current release downloads dblocks on a healthy backup, please supply the details.

While I do see a possible enhancement idea, does above explain things enough if this is still of interest and still happening?

**Comment by JsBergbau** [comment]
Thanks for the explanation. 
You assume, that it might me a damaged backup. The hardware I used for this test never made any problems. So this very unlikely. 

Since this issue was so long open without others reporting same problems, it looks like, it only affected me somehow. 

In the meantime I'm now using restic backup, so this is not relevant for me any more. 

This issue can be closed or kept open for reference, as you like.
