### ISSUE TITLE
When restoring a backup with multiple server UNC paths, file browser cannot be navigated until a search is performed.

### ISSUE THREAD

**Issue by sjpt4x** [duplicati/duplicati#3722]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.4.5_beta_2018-11-28
- **Operating system**: Windows Server 2008 R2
- **Backend**: Local

## Description

When restoring a backup with multiple server UNC paths, file browser cannot be navigated. Multiple UNC paths from the same server behave as expected.

## Steps to reproduce

1. Create backup with multiple server UNC paths eg. \\SERVER1\Share and \\SERVER2\Share
2. Open Restore page after performing a backup.
3. File browser drop down doesn't work. Fig1
![image](https://user-images.githubusercontent.com/46354998/55720830-a4e96a00-59f9-11e9-952d-f6c4d3212051.png)
4. Search for a file, the file browser can now be navigated to found files Fig2
![image](https://user-images.githubusercontent.com/46354998/55721090-57213180-59fa-11e9-9ae9-2f546f289986.png)

Due to this issue I will now have to split this job into multiple jobs instead.

**Comment by JonMikelV** [comment]
This issue is described on the forum (https://forum.duplicati.com/t/restore-gui-not-working-correct-with-unc-source/1774) and includes a workaround of using "." (no quotes) for the search term them removing the "." but NOT pressing enter.

Does that workaround work for you?

**Comment by sjpt4x** [comment]
Hi JonMikeIV,

Thank you for pointing me toward the forum post, had not seen this.

Yes this workaround works! But is obviously not ideal.

One problem with this is that if the Duplicati server is managed by multiple people. It would rely on everybody remembering how to use this workaround, potentially under pressure when needing to retrieve a backup quickly.

The second problem with this workaround is that it expands every folder when the search occurs which is a bit of a nightmare on big folder structures.

**Comment by ts678** [comment]
[Restore, UNC path #2906](https://github.com/duplicati/duplicati/issues/2906) on 2.0.2.1 seems similar. There, I reported:

Not reproducible currently. I tested to Local folder Destination. Source was two folders on one share, two files on another.
Quite possibly something was fixed. This issue will close eventually unless some other information becomes available on it.

Here I also tested with `Direct restore from backup files`. 2.0.4.5 had the problem. No surprise, as this issue was on it.
2.0.5.1 lacked the problem. I'll assume that this problem is now fixed, and the issue will close automatically without activity.
