### ISSUE TITLE
dblocks missing SharpAESCrypt header causing multiple other errors

### ISSUE THREAD

**Issue by stargazindreamr** [duplicati/duplicati#3746]
- [x] I have searched open and closed issues for duplicates. Possibly related to or root cause of #3700.

----------------------------------------

## Environment info
- **Duplicati version**: 2.0.4.17
- **Operating system**: Win7, Win10
- **Backend**: OneDrive personal

## Description
On OneDrive personal backups (possibly other backends), the dblock files are missing the SharpAESCrypt header, but only if the dblock size was limited by the max setting (50MB default in my case). The dlist and dindex files have the SharpAESCrypt header. Any dblock file that was created with a size less than the limit has the AES header.

This has resulted in failed hash checks, failed test/verify-all executions, failed restores via GUI.

Downloading entire backup file set to local drive and hex editing revealed missing AES headers.

Same install, same machines, same backup profile but with backend changed to local disk results in successful backups, proper AES headers on dblock files, and no errors, ever, on subsequent backups, database rebuilds, restores, verifications, etc.

I examined files produced by another machine that has been running Duplicati since 2.0.1.51. The last files it uploaded to OneDrive that hit the 50MB dblock size limit were created while running 2.0.4.12 and have proper AES headers. I have not run a backup using 2.0.4.17 that hit the dblock size limit. The small dblock files created with 2.0.4.17 have AES headers. I have suspended backups until I can downgrade or this is fixed.

## Steps to reproduce
1. Install 2.0.4.17
2. Create backup with OneDrive as the backend
3. Run backup
4. Run backup again with at least one small new or changed file
5. Run a verify all --full-remote-verification
6. Try to restore a file that involves a dblock that was size limited due to max dblock size setting

- **Actual result**:
Backup is successful the first time. Backup fails with hash error on dblock during final test phase. Test/verify fails to even decrypt the files despite known-good password (which works to manually decrypt dlist and dindex files). Errors stating "invalid header marker" (verbose logging) when trying to rebuild database downloaded 

- **Expected result**:
All backups run successfully each time with no errors. Verify all or restore completes successfully.

The test/verify phase after backup:
`2019-04-19 21:05:29 -04 - [Retry-Duplicati.Library.Main.BackendManager-RetryGet]: Operation Get with file duplicati-b5f6726e1d7ac4f41aeaf5f02def7e351.dblock.zip.aes attempt 2 of 5 failed with message: Hash mismatch on file "C:\Users\xxxxxx\AppData\Local\Temp\dup-e314876f-177f-4477-83f7-6e1149c6f5e8", recorded hash: joDC7PEC6nKRdW6qOj0jpQu0tDtVwZVlSuEuddZblPc=, actual hash sxVjUlM83kNa/glIOSe9tvTtNfpNlA38BayGYSBaAQA=
Duplicati.Library.Main.BackendManager+HashMismatchException: Hash mismatch on file "C:\Users\xxxxxx\AppData\Local\Temp\dup-e314876f-177f-4477-83f7-6e1149c6f5e8", recorded hash: joDC7PEC6nKRdW6qOj0jpQu0tDtVwZVlSuEuddZblPc=, actual hash sxVjUlM83kNa/glIOSe9tvTtNfpNlA38BayGYSBaAQA=
   at Duplicati.Library.Main.BackendManager.DoGet(FileEntryItem item)
   at Duplicati.Library.Main.BackendManager.ThreadRun()`

When trying to restore:
`2019-04-21 01:53:01 -04 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Started: duplicati-b56acde50f91c43cdbcb7b2a21bab617b.dblock.zip.aes (49.97 MB)
2019-04-21 01:53:57 -04 - [Profiling-Timer.Finished-Duplicati.Library.Main.BackendManager-RemoteOperationGet]: RemoteOperationGet took 0:00:00:56.558
2019-04-21 01:53:57 -04 - [Retry-Duplicati.Library.Main.BackendManager-RetryGet]: Operation Get with file duplicati-b56acde50f91c43cdbcb7b2a21bab617b.dblock.zip.aes attempt 3 of 7 failed with message: Invalid header marker
System.Security.Cryptography.CryptographicException: Invalid header marker ---> System.IO.InvalidDataException: Invalid header marker
   at SharpAESCrypt.SharpAESCrypt.ReadEncryptionHeader(String password, Boolean skipFileSizeCheck)
   at SharpAESCrypt.SharpAESCrypt..ctor(String password, Stream stream, OperationMode mode, Boolean skipFileSizeCheck)
   at Duplicati.Library.Encryption.AESEncryption.Decrypt(Stream input)
   at Duplicati.Library.Encryption.EncryptionBase.Decrypt(Stream input, Stream output)
   at Duplicati.Library.Main.BackendManager.<>c__DisplayClass36_0.<coreDoGetPiping>b__0()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at Duplicati.Library.Main.BackendManager.coreDoGetPiping(FileEntryItem item, IEncryption useDecrypter, Int64& retDownloadSize, String& retHashcode)
   at Duplicati.Library.Main.BackendManager.DoGet(FileEntryItem item)
   at Duplicati.Library.Main.BackendManager.ThreadRun()`

**Comment by stargazindreamr** [comment]
I uninstalled 2.0.4.17 and installed 2.0.4.12. The same situation occurred: the dblock files uploaded to OneDrive do not have the AES headers (except the very first one). I uninstalled 2.0.4.12 and installed 2.0.3.13. **All** dblock files uploaded to OneDrive have AES headers. No errors are encountered during subsequent backups at the test/verify phase. Files can be restored from the GUI with no errors.

A database delete/repair is successful. **However**, as has been observed by others, the database delete/repair downloaded **all** 13GB of dblock files (instead of just using the dindex files). There should be no need for dblock files to recreate the database, considering that the Developer Information page states "This means that the local database can be restored from only the dlist and dindex files." Is there a switch/setting that permits disabling the full download dblock and instead relying on the dindex files?

There were no errors in the log, no missing files, etc. All dlist and dindex files were downloaded successfully... then all the dblock files were downloaded.

**Comment by ts678** [comment]
Using a hex viewer or similar, do the dblock files with the missing AES header also have NULs (0x00) at end? Also are you using any throttling, e.g. by the GUI control near top, or one of the throttle advanced options?

**Comment by ts678** [comment]
Hello @stargazindreamr

Could you please answer the previous questions? I'm looking at some issues when throttling is in effect, but can't get missing headers on 2.0.4.17 per directions, using a 250 MB ISO as initial backup, then a small add. 

Restore is fine (need to use --no-local-blocks to make sure it does this by download). Test is fine (see below).

~~~
  Listing remote folder ...
  Downloading file (909 bytes) ...
  Downloading file (1005 bytes) ...
  Downloading file (18.89 KB) ...
  Downloading file (18.98 KB) ...
  Downloading file (18.03 KB) ...
  Downloading file (106.92 KB) ...
  Downloading file (925 bytes) ...
  Downloading file (17.97 KB) ...
  Downloading file (17.97 KB) ...
  Downloading file (49.91 MB) ...
  Downloading file (49.97 MB) ...
  Downloading file (49.97 MB) ...
  Downloading file (35.54 MB) ...
  Downloading file (1.01 KB) ...
  Downloading file (49.92 MB) ...
  Downloading file (49.94 MB) ...
Examined 16 files and found no errors
Return code: 0
~~~

Is the second backup a necessary part of your process? It's not anywhere near a full 50 MB volume by itself.

I mentioned throttling (please check), but unthrottled upload speed might matter. Mine is 4-6 Mbit/second.

[2.0.4.18](https://github.com/duplicati/duplicati/releases/tag/v2.0.4.18-2.0.4.18_canary_2019-05-12) should do better on avoiding pointless dblock downloads.

**Comment by Tentos** [comment]
I also seem to experience this problem, but have not had the time to investigate further.
> 
> 
> Using a hex viewer or similar, do the dblock files with the missing AES header also have NULs (0x00) at end? Also are you using any throttling, e.g. by the GUI control near top, or one of the throttle advanced options?
I have checked, and the dblock files I have looked at do not have the AES header, but have a large amount of 0x00 at the end.
I have also quickly checked some dblock files on another cloud backup (where Duplicati uses WebDAV), and the files there have the AES header as well as no 0x00 at the end.

**Comment by ts678** [comment]
[v2.0.4.22-2.0.4.22_canary_2019-06-30](https://github.com/duplicati/duplicati/releases/tag/v2.0.4.22-2.0.4.22_canary_2019-06-30) fixes one corruption which I thought only happens with throttling, but maybe I'm wrong, or maybe your problem files arose somehow else. The fixed throttling corruption produces files that are the right size, but the contents are mangled. You can see what the right size is by setting option [--upload-verification-file](https://duplicati.readthedocs.io/en/latest/06-advanced-options/#upload-verification-file)=true then finding the created file to look into, or to run utility-scripts/DuplicatiVerify.* on if you have Windows or Linux access to backend files. Alternatively you could use DB Browser for SQLite to look in RemoteVolume table. BTW, I assume your dblock files have the .aes suffix, otherwise no AES header is normal. A .zip should have a PK header. What backend are you using?

In case the numbering is confusing, [2.0.4.23](https://github.com/duplicati/duplicati/releases/tag/v2.0.4.23-2.0.4.23_beta_2019-07-14) is just 2.0.4.5 plus an urgent warning. 2.0.4.22 is advanced, but that also means returning back to 2.0.4.23 won't work due to DB upgrades. Need to move forward. Ordinarily I'd suggest [v2.0.4.21-2.0.4.21_experimental_2019-06-28](https://github.com/duplicati/duplicati/releases/tag/v2.0.4.21-2.0.4.21_experimental_2019-06-28) as a beta preview, but it lacks this fix.

**Comment by ts678** [comment]
[OneDrive high levels of uploaded file corruption](https://forum.duplicati.com/t/onedrive-high-levels-of-uploaded-file-corruption/13879) was a problem for me in Feb 2022 when I started using OneDrive again.
[OneDrive sync never completes with SHA-1 corrupted transfer with latest rclone](https://forum.rclone.org/t/onedrive-sync-never-completes-with-sha-1-corrupted-transfer-with-latest-rclone/29884) shows it from rclone users in Mar 2022.
Original report here is Apr 2019, so that's a bit of a stretch. Main lesson is sometimes issue is in destination, not the app.

Sometimes it's the app though. We never heard if @stargazindreamr was using throttling, which was a problem until fix.
There have been the [2.0.5.1_beta_2020-01-18](https://github.com/duplicati/duplicati/releases/tag/v2.0.5.1-2.0.5.1_beta_2020-01-18) and [2.0.6.3_beta_2021-06-17](https://github.com/duplicati/duplicati/releases/tag/v2.0.6.3-2.0.6.3_beta_2021-06-17) Beta releases with the cited code changes.

@Tentos was not using throttling, but I'm not 100% sure the buggy code couldn't cause a similar problem even without.
It would also be helpful to know what type of destination was used. Some are troublesome, especially the network drives.

Is anyone still seeing this on current releases? It's possible that there's nothing more that can be investigated. Any news?
