### ISSUE TITLE
Repair does not work over FTP (alternative): Zip archive appears to have a broken Central Record Header, switching to stream mode

### ISSUE THREAD

**Issue by huste** [duplicati/duplicati#3807]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info
- **Duplicati version**: 2.0.4.22
- **Operating system**: Windows 10
- **Backend**: Local and FTP (alternative)

## Description
I tried to create a backup job using the current Duplicati release on a freshly setup Win10 machine. Destination is supposed to be a Synology FTP-Server that is reachable through a VPN. The problem is, that the internet connection is *very* limited and the backup job is quite big (10GB, max upload is about 20KB/s, I had to throttle it to 15KB so that the machine remains usable while the upload is in progress, files change rarely over time). I tried using FTP alternative at first (FTP fails with an error message about improper server responses) directly, but the backup failed frequently - I can't recall the error messages.

So I tried the following...

## Steps to reproduce
1. Create a local backup job and run it
2. Create a remote backup job with the same settings apart from the destination (FTP alternative)
3. Copy all files from the local backup job destination to the destination (I verified they're all the same by using md5sum)
4. restore database from the remote storage

- **Actual result**:
Duplicati starts downloading the files, but frequently fails with 
"Zip archive appears to have a broken Central Record Header, switching to stream mode". The backup job is not usable.
I tried removing the database from the local backup job and repair it from the local source: This worked flawlessly. So I presume, there must be an issue with the FTP connection.

- **Expected result**:
proper rebuild of the database based on all the dindex and dlist files, thus being able to run the smaller diff-jobs directly to the remote storage.

## Debug log
I attached the bug report for the repair command.
[bugreport.zip](https://github.com/duplicati/duplicati/files/3364064/bugreport.zip)

**Comment by ts678** [comment]
> the machine remains usable while the upload is in progress

I assume this refers to the PC needing some of the "_very_ limited" connection for non-Duplicati usage.

>     4. restore database from the remote storage

I assume this means "Repair" without a local database, or "Recreate (delete and repair)" of a database.
BTW, I "think" you could just have just copied the database to the new remote job with uploaded files.

You might be running into a combination of these two open issues if your backup is throttling upload:

[`--throttle-upload` affects restore download performance #3272](https://github.com/duplicati/duplicati/issues/3272)

[Hash mismatch download corruption, likely from throttle buffer offset being reused #3782](https://github.com/duplicati/duplicati/issues/3782)

On ordinary corrupted downloads (if that's what's happening) the file hash won't match the DB record, however in your case there isn't one yet, so (assuming it's unencrypted), ZIP is probably the first choke.

Can your machine remain usable without a download throttle? If so, try turning off the upload throttle.

If you have the recreated or original database that matches the remote, you can try [the test command](https://duplicati.readthedocs.io/en/latest/04-using-duplicati-from-the-command-line/#the-test-command) before removing the upload throttle, to see if you can get occasional hash errors instead of ZIP errors.

If this turns out to be issue #3782, the fix is simple and a field-patch via a debugger might be possible.
More conservative path would be to target next canary. I now suspect we'll need one before next beta.

Or maybe this theory is all wrong. Turning off throttling and still getting an issue would say it's in FTP...

**Comment by huste** [comment]
I will try, but I am on vacation right now. I'll just keep my mail unread...
To clarify: by saying "usable" I don't mean CPU limitations, but really the possibility to connect to that machine from a remote location

**Comment by ts678** [comment]
If this is the download throttle bug (I know you haven't tested yet), please consider testing the next canary under original conditions (including original throttling settings) to see if the code fix resolves the problem.

**Comment by huste** [comment]
Hi!

The machine is not usable without an upload throttle, it is usable without download throttle, though.

Do you think, it's valid to test the next canary with the upload throttle enabled and simply recreate the database? Because if I get it right, the issue with any throttling buffer is (was) that it affects the downloads as well and thus the files downloaded were corrupted?
If so, downloading the remote files to recreate a local database should wok properly and the original issue wouldn't be there as well.

I ask because the original initial backup took about 9 (written in words: nine) days...

**Comment by ts678** [comment]
If original issue had upload throttle, which crept into download, which corrupted, is Recreate a 9 day task?

No need for this to disrupt heavily. You could possibly get it using a larger-than-default-1 [test command](https://duplicati.readthedocs.io/en/latest/04-using-duplicati-from-the-command-line/#the-test-command), perhaps done using [Commandline](https://duplicati.readthedocs.io/en/latest/03-using-the-graphical-user-interface/#using-the-command-line-tools-from-within-the-graphical-user-interface) screen, and I'm surprised that the download problem isn't hitting your backup at the [verifying backend files](https://duplicati.readthedocs.io/en/latest/03-using-the-graphical-user-interface/#verifying-backend-files) step after backup (unless that's been turned off using some option).

Although it wasn't my input, I think the main wish is to just verify bug fix actually fixes something for you, rather than relying completely on theories and  lab tests. Plus, your interesting network may also factor in.

**Comment by huste** [comment]
No, recreation is faster. I am physically at that machine on Sunday (hopefully) and I'copy all lcoal backups that were made in the meantime manually the remote machine. Then I'll try to recreate the DB.

Do you think that a smaller backup job might show the same issues? If so, I could try to create a say 40MB job. That uploads in about 2 hours and wouldn't be much of a pain in the evening. :)

**Comment by ts678** [comment]
40MB might get it. My records are hazy, but I think #3782 used 64MB file and 10KB throttle to local folder.

**Comment by ts678** [comment]
40MB might get it. My records are hazy, but I think #3782 used 64MB file and 10KB throttle to local folder. Results seem somewhat destination-dependent, and possibly yours will show the error on smaller & faster.

**Comment by huste** [comment]
Jsut t clarify: Are we talking about 2.0.4.24 where I should retest with the upload-throttle? Because the whole issue was there in 2.0.4.22 and if I get it right, 2.0.4.23 is just an Amazon Cloud Drive removal release.

I just tried (without looking beforehand) to recreate the database with the original settings (including the upload-throttle) and it failed again - of course, as it's 2.0.4.22.

After that, I tried recreation without the upload throttle: Works like a charm. I just got 1 warning about ftp-passive not being supported, but the recreation process comlpeted successfully. I'll try to have the backup run to the remote location today.

**Comment by ts678** [comment]
> Are we talking about 2.0.4.24

Nobody knows what the number will be when it comes out, but it's not any number released so far.

> I just wonder why the overview page of the backup jobs still shows old data after recreation...

I vaguely recall wondering the same after some operation. I think I found it only updates on backup.

**Comment by huste** [comment]
I downloaded 2.0.4.28 right now and created a new job for 35MB of data and used the upload-throttle filter. The backup jobs fails initially, but this seems to be a different issue, which I just opened: #3900. With the newly created backup job, after running it one, there are 6 files of 19,9MB each at the destination, but there's no dlist file. I don't think this looks right. Does it?

**Comment by ts678** [comment]
> I downloaded 2.0.4.28 right now and created a new job for 35MB of data and used the upload-throttle filter.

It looks like the set of throttling fixes finished in [2.0.4.24_canary_2019-09-02](https://github.com/duplicati/duplicati/releases/tag/v2.0.4.24-2.0.4.24_canary_2019-09-02)

> there are 6 files of 19,9MB each at the destination, but there's no dlist file.

Knowing type of file (dblock, dindex, etc.) would help, but per your other issues, these might be retries of dblock.
Looking at live log can help, or sometimes one can see the upload retries with \<job> --> Show log --> Remote
Click on the `put`. If `Size` and `Hash` stay the same, it's almost certainly a retry of an upload, with a new name.

Is this issue still of interest? One of the later ones reported success finally. If nothing more is said, issue will close.
