### ISSUE TITLE
Update nuget packages?

### ISSUE THREAD

**Issue by BlueBlock** [duplicati/duplicati#3822]
Most nuget packages are fairly old.  I can update them unless there is a compatibility reason they are on older versions?

**Comment by ts678** [comment]
Hmm. Is this offer retracted? I was just about to suggest FluentFTP because it just got a rather important [fix](https://forum.duplicati.com/t/problems-after-upgrade-to-2-0-4-21/7469/18?u=ts678) that may require an update-and-test with some FTP server (FileZilla Server would do if you're on Windows).

Getting more ambitious (and maybe less urgent) there's a Mega.nz [issue](https://forum.duplicati.com/t/mega-nz-error-when-check-connection/5316/8?u=ts678) that an update might help. Nobody on that post seems interested in a DIY test, and recently I'm suspecting a Duplicati rebuild might be needed.

Then there's everything else that's getting old and possibly having issues (e.g. security) that's not so obvious.

If you're still interested, somebody else would have to advise you on the mechanics. I'm not really a dev here.

If you just go ahead on your own and do pull requests, separate ones might be best, in case issues arise. Sometimes compatibility issues aren't apparent until the new package gets into canary for field testing...

Thanks for the offer!

**Comment by BlueBlock** [comment]
Not retracted. I thought my question might be a little too simple so I closed it.

I've updated all the packages and will be submitting them all shortly.

I've also included a fix to a big problem I've been having when trying to stop big backup jobs. I would try using "Stop after upload" but it had no effect in stopping the job. I've changed it so 'Stop after upload' will stop the backup after the current file is complete.
