### ISSUE TITLE
Questions from a new Duplicati developer 

### ISSUE THREAD

**Issue by BlueBlock** [duplicati/duplicati#3855]
I'd like to really commend the coding and structure. Duplicati is far better code than most companies will produce. It is incredibly well thought out. I'm new to the code base and with a decent amount of time I can pretty easily find my way around. It is a very impressive amount of work. Really well done.

Here are my most immediate questions.

1) For submitting PR for big changes in what stage should code be submitted? Is the desire to have an entire completed change submitted or to have it submitted in working subsets so others can review and comment?

2) I've seen comments about limiting code changes to only those needed and to not refactor. I'm trying to limit refactoring. Given the previous question about submitting in-progress work, I'm wanting to understand how best to help testers/reviewers understand the code changes without too much effort; I'm thinking I can explain the changes in the commit to help?

3) Lastly, I have some ideas I'd like to discuss.  It github the preferred place or is the forum and the developer section?

**Comment by Pectojin** [comment]
I think most of it is just about keeping it easy to review and keeping PR/issues on Github to a minimum (since we're currently over 800 issues open). 

We don't have a strict policy at the moment, so anything here is just my opinion (subject to discussion of course :smile: )

1. It's best to have PR's ready for merge, or named at least `[WIP] <title>` so people know not to start reviewing or merging the code yet. Naturally it may make sense to have PR's that are unfinished if you're collaborating with someone on it.
2. Refactoring and cleanup is welcomed, but for reviewability it's best to separate functionality changes from refactorization in different PR's - unless it's tightly coupled. @warwickmm often make small cleanup/refactoring changes, so looking back at his PR's could give an idea of what's easy to review: https://github.com/duplicati/duplicati/pulls?q=is%3Apr+is%3Aclosed+author%3Awarwickmm
3. Forum is often best for dialogs and discussions, then concrete items like bug reports or exact feature descriptions can be posted here and referenced :smile:

**Comment by BlueBlock** [comment]
That makes sense. Thanks.

I'll put a GoogleDrive backend fix as a PR. The subfolder work will be a WIP PR as the backends are updated to handle subfolders.

**Comment by warwickmm** [comment]
I agree with @Pectojin's thoughts.  Regarding question 2, we do have an issue with inconsistent indentations and line endings.  As a result, I often find that making a small change to a file results in changes to every line of the file.  In these cases, I'll revert all the non-functional changes to simplify the review process.  A separate pull request can be submitted to fix the coding style.
