### ISSUE TITLE
Shorten paths in data.zip file used for BulkData tests

### ISSUE THREAD

**Issue by warwickmm** [duplicati/duplicati#3863]
Our AppVeyor configuration currently ignores the `BulkData` tests.  This was intended originally to avoid running into AppVeyor's time limit restriction (currently at 60 minutes).  While this limit now appears to provide ample time for us to run all the tests (including `BulkData`), there are paths inside the `https://s3.amazonaws.com/duplicati-test-file-hosting/data.zip` file that result in test paths longer than what is supported by Windows.  For example:
```
C:\projects\duplicati\testdata\data\Icons\077434-black-inlay-crystal-clear-bubble-icon-business-full-set\077434-black-inlay-crystal-clear-bubble-icon-business-full-set\077238-black-inlay-crystal-clear-bubble-icon-business-currency-british-pound-sc35.png
```

We should modify the data in this file so that the resulting paths satisfy the length requirement.  Once we do so, we should be able to enable the `BulkData` tests in AppVeyor.

**Comment by warwickmm** [comment]
The changes in pull request #4256 should fix the issue with long paths.  However, there is some concern about the S3 bandwidth charges if we enable these tests.  We should look into downloading the files from the DigitalOcean server instead.

**Comment by dferreyra** [comment]
@warwickmm, I'm afraid that even with #4256 I could still get unit test failures under Windows because paths are too long.  For example, the call to `System.IO.Compression.ZipFile.ExtractToDirectory()` throws an exception when long paths are involved, even in .NET 4.6.2.

My workaround for running the unit tests has been to set UNITTEST_BASEFOLDER to something short, like "`C:\td`".

I looked into it and I'll be submitting a pull request that fixes all the long path issues in the unit tests, at least in my experiments, without having to change data.zip.  I'll see what you think.

**Comment by warwickmm** [comment]
Pull request #4352 changes the unit test data host to reduce S3 transfer charges.
