### ISSUE TITLE
improvement request: cloud2cloud

### ISSUE THREAD

**Issue by maravento** [duplicati/duplicati#3952]
Congratulations for duplicati. 
I think it could be better if it can backup cloud2cloud or cloud2PC too (only pc2cloud does)
And it should also have a mirror option (one way system: A to B), without compression. (other backup programs already incorporate this option, such as [FreeFileSync](https://freefilesync.org/) or [retrospect](https://www.retrospect.com))

thanks in advance

**Comment by ts678** [comment]
The Duplicati manual's [Overview](https://duplicati.readthedocs.io/en/latest/01-introduction/#overview) covers some things that it's not, and several are named here. Duplicati does backup from local computer drives, very precisely trying to record all the subtleties of the file such as Windows NTFS permissions. On the destination it asks as little as possible from the provider, so as to allow all sorts. Basically it needs upload, download, list, delete, and sometimes create. Asymmetric is by design. For mirroring (and a lot more), you might also consider [rclone](https://rclone.org/). Duplicati is hugely different than mirroring. It processes your source files to achieve deduplication, compression, security, versioning, etc. [Features](https://duplicati.readthedocs.io/en/latest/01-introduction/#features) describes these, and most rely on NOT just mirroring. [How the backup process works](https://duplicati.readthedocs.io/en/latest/appendix-a-how-the-backup-process-works/) explains.
