### ISSUE TITLE
Windows 10 v1903: Tray app does not launch from Start Menu link after update to v2.0.4.32-2.0.4.32_canary_2019-10-24

### ISSUE THREAD

**Issue by jdrch** [duplicati/duplicati#3968]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.4.32-2.0.4.32_canary_2019-10-24
- **Operating system**: Windows 10 x64 v1903
- **Backend**: OneDrive

## Description

After updating to this release, the Duplicati system tray app does not launch.

## Steps to reproduce

1. Install the new build, upgrading from the previous canary release
2. In the Start menu, click the Duplicati entry

- **Actual result**:
Nothing happens. No Duplicati process is even started.
- **Expected result**:
Duplicati tray app launches.

**Comment by psybustermk2** [comment]
Also happening to me.

**Comment by Epithumia** [comment]
Same issue, and reinstalling a previous version doesn't fix it.

**Comment by cccstein** [comment]
Same over here. After the latest update the Duplicati.Server.exe dies immediately and restarts in a loop.
Same happens by invoking Duplicati.Service.exe. Remove, Reinstall, older versions, cleaning registry, nothing helps. 

Console shows 100s of entries like: 
Attempting to restart server process: C:\ProgramData\Duplicati\updates\2.0.4.32\Duplicati.Server.exe
Starting process C:\ProgramData\Duplicati\updates\2.0.4.32\Duplicati.Server.exe with cmd args --ping-pong-keepalive=true
Attempting to restart server process: C:\ProgramData\Duplicati\updates\2.0.4.32\Duplicati.Server.exe
Starting process C:\ProgramData\Duplicati\updates\2.0.4.32\Duplicati.Server.exe with cmd args --ping-pong-keepalive=true
......

**Comment by cccstein** [comment]
Used the brute force solution. Completely uninstalled Duplicati, deleted the \Program Data\Duplicati directory tree as well, then installed Duplicati latest version again. Works now!

**Comment by jdrch** [comment]
> Completely uninstalled Duplicati, deleted the \Program Data\Duplicati directory tree as well

Did you have to set it up from scratch again afterwards, or did the new installation pick up the previous settings and jobs?

**Comment by ts678** [comment]
[Downgrading / reverting to a lower version](https://forum.duplicati.com/t/downgrading-reverting-to-a-lower-version/3393) discusses some mechanics. One key concept is that upgrades installed using the Duplicati GUI updater (i.e. the Install and Activate buttons) don't change Program Files.

Instead, they go into an updates folder, so can be found and launched by the Program Files version. IIRC uninstall and reinstall acts only on the Program Files version, so if the problem was in the updates folder then it might persist. On `About --> System info` you can see your BaseVersionName and ServerVersion. `Duplicati.CommandLine.exe system-info` writes similar info if it runs, otherwise it's manual investigation. 

Findings like "Nothing happens. No Duplicati process is even started." may not mean exactly what it says (only roughly), as depending on how you did update, you might have a failure in Program Files start, or a good start there then failure in start of child on the updated version. This can be seen using [Sysinternals Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer) more clearly, but Task Manager can also show the processes coming (and maybe going). [Sysinternals Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) can give details (e.g. of all processes of a given name) but is advanced work.

You can also change directories directly to the folder in updates and start programs by hand if you like. This is sort of what I do (with a .bat file) to be running exactly what I want (for testing various versions). This unusual install scheme sort of works with the GUI updater, but I still can't reproduce this problem.

Having Windows do an uninstall should do no damage to settings or jobs, but if you manually delete folders, make sure there aren't .sqlite files in them which represent settings and per-backup data files. 
The location is quite configurable, but default would be in some user profile AppData\Local\Duplicati.

**Comment by cccstein** [comment]
Dell Customer Communication - Confidential

The new install found its previous backup job configurations (to a WebDAV server in my case), even after deleting the Program Data Directory.

**Comment by jdrch** [comment]
OK thanks! Nice to meet another Dell person, BTW. Used to work for them 😛

**Comment by mozart77** [comment]
Same story on W2012r2 when upgrading from 2.0.4.22_canary_2019-06-30 to 2.0.4.33_canary_2019-11-01. Tray app launches and quits immediately.

**Comment by ts678** [comment]
I'd much prefer to solve or understand this, but I can't reproduce it, so need to know your history.
The more the better. Ideally someone will have enough steps to reproduce this that anybody can.

If any of you have done workarounds, knowing what worked and what was there before will help.

How did you install 2.0.4.32 update? Options include Duplicati GUI's Install/Activate, or from .msi.
For any .msi install, did you uninstall Duplicati first? There have been installer bugs, thought fixed.

What previous canary (if any) worked OK? If recent enough canary, you can also try a downgrade.
See previous notes about downgrade. Simply installing an old .msi can still pick up prior upgrade.

What is your base version? You can read C:\Program Files\Duplicati 2\changelog.txt if all else fails.
GUI About --> System info
CLI "C:\Program Files\Duplicati 2\Duplicati.CommandLine.exe" system-info

What browser do you use for Duplicati? On my system, Windows 10 v1903 made "localhost" bugs.
For awhile I was using 127.0.0.1 instead if I needed to get to the Duplicati GUI with Microsoft Edge.

Check for a Duplicati-crashlog.txt file. Try C:\ProgramData\Duplicati\updates for non-service install.

If trying start menu, instead test "C:\Program Files\Duplicati 2\Duplicati.GUI.TrayIcon.exe" by hand.

Launching from the CLI is also an easier way to add a [--log-file](https://duplicati.readthedocs.io/en/latest/06-advanced-options/#log-file) option to catch possible last words.

Watch with Task Manager (or Process Explorer) for one or two Duplicati.GUI.TrayIcon.exe processes. Timing between the two processes can also be significant. How long do the processes stay around? Confirm that no Duplicati processes exist when you think it's down. Leftovers cause future troubles.

Think up an unused path and start by hand with `--server-datafolder=<that path>` to see if it works when .sqlite database folder is empty. It should create the folder for you, and give a  "first run" dialog.
This test is to distinguish between a total can't-start and a start-then-exit-on-past-due-scheduled job.

See if somehow 2.0.4.33 works where 2.0.4.32 didn't. If you have no other way to get it (e.g. GUI fails), [Duplicati.Library.AutoUpdater.exe](https://duplicati.readthedocs.io/en/latest/07-other-command-line-utilities/#duplicatilibraryautoupdaterexe) can check current updates and get any newer ones such as 2.0.4.33.

[Duplicati.Server.exe](Duplicati.Server.exe) is like Duplicati.GUI.TrayIcon without the tray icon. Your browser can talk to it OK, however stopping is harder because you have to kill the processes using Task Manager or something.
This test is to distinguish between an icon problem and a problem with the server that process hosts.

**Comment by mozart77** [comment]
Current version 
> Duplicati - 2.0.4.22_canary_2019-06-30
Works fine as portable or msi installation. 
After automatic update to  2.0.4.33_canary_2019-11-01 Duplicati.GUI.TrayIcon.exe quits right after start. No messages, empty system logs and Duplicati-crashlog.txt. Also tried portable version. Problem persists.

**Comment by goobs1** [comment]
I had to go back to duplicati-2.0.4.30_canary_2019-09-20-x64.msi before I could get the tray icon working again.
When on newer versions the icon never appeared. If from a command prompt I ran "C:\Program Files\Duplicati 2\Duplicati.GUI.TrayIcon.exe" --log-file then  the crash log mentioned:

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: path
at Duplicati.GUI.TrayIcon.HostedInstanceKeeper..ctor(String[] args)
   at Duplicati.GUI.TrayIcon.Program.RealMain(String[] _args)

If I double clicked Duplicati.Service.exe and left the empty window running I could then access Duplicati with https://localghost:8200 and run backups. 

For now I will stick with 2.0.4.30 until it is fixed.

**Comment by ts678** [comment]
Thanks @goobs1 

Coincidentally, my works-here test used an upgrade from a 2.0.4.30 upgrade to a 2.0.4.33 upgrade with Program Files base version of 2.0.4.5 beta. Somewhat oddly, @cccstein ran the same test as you, [above](https://github.com/duplicati/duplicati/issues/3968#issuecomment-548077060), with seemingly successful results, although on Oct 30, the latest version was 2.0.4.32 instead of 2.0.4.33.

The other hints plus stack trace also help (although someone more expert than I am should interpret it).

**Comment by ts678** [comment]
I was able to cause a TrayIcon quick exit in 2.0.4.32 (2.0.4.31 OK) by putting a password on the web UI.
Test was with two folders with a zip file install, so that maybe gets all of the installers out of this issue.
Removing the UI password by starting TrayIcon with `--webservice-password=` removes the quick exit.

**Comment by warwickmm** [comment]
Does everyone here have a password set on the web UI?  Pull request #3978 should fix the startup issue for that situation.

If that's the case, I'm a bit surprised that a reinstall fixes the issue...

**Comment by gillesgagniard** [comment]
Upgrading to Duplicati 2.0.4.32 on macOS also breaks the tray icon for me.

Here is the console output:
```
~> /Applications/Duplicati.app/Contents/MacOS/duplicati
Unexpected error: System.ArgumentNullException: Value cannot be null.
Parameter name: s
  at System.Convert.FromBase64String (System.String s) [0x00003] in <b814b509d4ad406fb40c6c93e38929e7>:0 
  at Duplicati.GUI.TrayIcon.HttpServerConnection.GetAuthToken () [0x00094] in <4e95f350085143d1b0f674e30796dbcc>:0 
  at Duplicati.GUI.TrayIcon.HttpServerConnection.PerformRequest[T] (System.String method, System.String urlfragment, System.Collections.Generic.Dictionary`2[TKey,TValue] queryparams) [0x001ae] in <4e95f350085143d1b0f674e30796dbcc>:0 
  at Duplicati.GUI.TrayIcon.HttpServerConnection.UpdateStatus () [0x00001] in <4e95f350085143d1b0f674e30796dbcc>:0 
  at Duplicati.GUI.TrayIcon.HttpServerConnection..ctor (System.Uri server, System.String password, System.Boolean saltedpassword, Duplicati.GUI.TrayIcon.Program+PasswordSource passwordSource, System.Boolean disableTrayIconLogin, System.Collections.Generic.Dictionary`2[TKey,TValue] options) [0x000cb] in <4e95f350085143d1b0f674e30796dbcc>:0 
  at Duplicati.GUI.TrayIcon.Program.StartTray (System.String[] _args, System.Collections.Generic.Dictionary`2[TKey,TValue] options, System.String toolkit, Duplicati.GUI.TrayIcon.HostedInstanceKeeper hosted, System.String password, System.Boolean saltedpassword) [0x00024] in <4e95f350085143d1b0f674e30796dbcc>:0 
```
Downgrading to 2.0.4.31 fixes the issue and Duplicati can be started again as usual.
Duplicati 2.0.4.33 is also impacted ...

**Comment by ts678** [comment]
[After last update duplicati doesn’t work anymore](https://forum.duplicati.com/t/after-last-update-duplicati-doesnt-work-anymore/8369/3?u=ts678) was narrowing down the problem (or at least one problem -- reports in this issue seem to vary), and the fix.

[Release: 2.0.4.34 (canary) 2019-11-05](https://forum.duplicati.com/t/release-2-0-4-34-canary-2019-11-05/8381) is now available to be tested by anyone who had a UI password and TrayIcon start problems when running 2.0.4.32 or 2.0.4.33.

**Comment by jdrch** [comment]
> available to be tested by anyone who had a UI password and TrayIcon start problems when running 2.0.4.32 or 2.0.4.33.

Fixed on this end. Thanks so much!
