### ISSUE TITLE
delete remote files that  cause errors

### ISSUE THREAD

**Issue by xilutian** [duplicati/duplicati#4004]
I want to do periodic backup, that is to say, the remote files are deleted and the new data is backed up again for a period of time, but the software will report an error and the remote files are deleted. How should I set it?
![image](https://user-images.githubusercontent.com/14370659/69926917-41183200-14f1-11ea-9505-baf1e4375d9b.png)

**Comment by xilutian** [comment]
Does software support filter of the source in time ?

**Comment by drwtsn32x** [comment]
Are you trying to delete remote files yourself?  Don't do that....  let Duplicati manage them automatically.  You can set retention options by editing the backup job and setting it to keep only X versions or backups for X days.

**Comment by xilutian** [comment]
Does software support real-time synchronization, that is to say, when the source file changes, it will be automatically synchronized. If it is supported, how should it be configured

**Comment by drwtsn32x** [comment]
No... Duplicati is not synchronization software. It is backup software that uses deduplication in order to efficiently store many backup versions.  Source files are broken into chunks for deduplication, packaged into volumes, compressed, and encrypted.  You probably noticed that files on the "back end" are definitely NOT in native format.

If you want synchronization software that keeps files in native format, Duplicati is not the right choice.

**Comment by xilutian** [comment]
What I just said is not correct, Does software support real-time backup ，a software can generate millions of photos a day. I want to back up in real time. When generating new photos, I want to back up to the specified directory in real time

**Comment by drwtsn32x** [comment]
Duplicati is not realtime per se, where it actively monitors filesystem activity and does a backup as soon as a file is modified.

The Web UI can schedule jobs to run as frequently as every 6 minutes.  If you use the OS scheduler you can potentially do backups more frequently.  How well Duplicati handles such frequent backups depends on your setup.  If you do backups this often you'll want to set the retention option so that versions are getting pruned otherwise you'll end up with thousands of versions very quickly.

**Comment by warwickmm** [comment]
@drwtsn32x is correct.  If you want true real-time backup, then there might be better tools.

I'm going to close this as there's nothing actionable.  Feel free to reopen this if you think it is unresolved.
