### ISSUE TITLE
On IIS: If allowAnonymousPropfind:"True" and a HTTP ERROR 403 is raised, then no failback to authenticate is performed

### ISSUE THREAD

**Issue by tomtheone** [duplicati/duplicati#4019]
- [ x ] I have searched open and closed issues for duplicates.
----------------------------------------

## Environment info
- **Duplicati version**: 2.0.4.23_beta_2019-07-14
- **Operating system**: Windows 10 1909
- **Backend**: WebDAV: Windows Server 2016

## Description
If allowAnonymousPropfind:"True" and a HTTP ERROR 403 is raised from the webserver, then no failback to authenticate anyways is performed. Duplicati requires to see a 401 to be able to perform an authentication.

## Steps to reproduce
Please read all the details here:
https://forum.duplicati.com/t/webdav-backups-to-windows-2016-iis/8640/21

## Screenshots
Refer you to the Forum

## Debug log
None was required

**Comment by drwtsn32x** [comment]
Very thorough analysis in the discussion thread, thank you for that @tomtheone.

I have been able to reproduce the problem.

**Comment by drwtsn32x** [comment]
From what I can tell, it's the HttpWebRequest .NET class that automatically handles a 401 response. It views it as an authentication challenge and responds by authenticating. It does not do the same for a 403 response.

At first I thought PreAuthentication option may help, but then I saw Duplicati was already setting it to True.  Saw this blog post which has some useful info:

https://weblog.west-wind.com/posts/2010/feb/18/net-webrequestpreauthenticate-not-quite-what-it-sounds-like

If you must have allowAnonymousPropfind = True in your environment, then maybe we need to find another workaround.  I wonder if it's possible to override IIS 403 response code so that it returns 401 instead, at least when accessing the webdav area.

**Comment by tomtheone** [comment]
Ok for me, i do not depend on the allowAnonymousPropfind:"True".

**Comment by ts678** [comment]
> From what I can tell, it's the HttpWebRequest .NET class that automatically handles a 401 response. It views it as an authentication challenge and responds by authenticating. It does not do the same for a 403 response.

suggests that this is beyond our control.

> Ok for me, i do not depend on the allowAnonymousPropfind:"True".

and the lack of other reports in open and closed issues or in the forum suggests that a workaround may be adequate.
All this documentation will continue to exist, if helpful for future reference, but this issue will close if it remains inactive.
