### ISSUE TITLE
Password can be revealed in the backup settings

### ISSUE THREAD

**Issue by akurzawa** [duplicati/duplicati#4062]
- Duplicati 2.0.5.1_beta_2020-01-18
- Windows
- local backup (disk to disk)

Hi, what's the point of using strongpassword/password where it can be revealed by clicking show the password in the backup task settings? why the password of abckup is visible?

![image](https://user-images.githubusercontent.com/20043789/73058542-23819c00-3e94-11ea-9ae1-45c2562d4985.png)

**Comment by drwtsn32x** [comment]
This password is stored on the local Duplicati machine.  Someone would need to have access to your local machine in order to view the password in the Web UI or Duplicati-server.sqlite file.

Encryption is especially important when you don't have physical control of the remote storage media - you are backing up to cloud storage, for instance.  If you are only doing local backups and are not concerned about physical security of your backups, then you probably don't even need encryption.

**Comment by sirius-c** [comment]
Password secrets should still be stored into a system keyring (if available), not in plain text to a configuration file, so that passwords are always encrypted on disk with the login credentials. I believe any program should follow this, no matter how private or public the computer is.

**Comment by drwtsn32x** [comment]
@sirius-c - agree completely. It's just not the current state of things.

Issues/feature requests already exist for this change... I think it's just a matter of finding a dev with time.  More info here:  https://github.com/duplicati/duplicati/issues/2024

**Comment by warwickmm** [comment]
Closing this in favor of #2024.
