### ISSUE TITLE
GUI shows incorrect number of versions

### ISSUE THREAD

**Issue by starik1968** [duplicati/duplicati#4081]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.5.1_beta_2020-01-18
- **Operating system**: Windows 10 x64 Enterprise German
- **Backend**: Local Drivres

## Description

When I backup via command line everything runs well. But the number of versions in tray web gui stay the same, I can access the new backup but the gui says the last backup was when I used the GUI. How can I refresh this information?

**Comment by drwtsn32x** [comment]
Duplicati.CommandLine.exe is independent from the Duplicati Server hosting the Web UI.  This is by design.

In some situations people want to have the Web UI but be able to trigger defined backup jobs from the command line, as if they clicked "Run now" in the Web UI (for example).  If that's what you want to do, then I suggest you use an alternative command line tool:  [duplicati-client](https://github.com/Pectojin/duplicati-client).  It will do what you want and the Web UI will always be up to date.

**Comment by starik1968** [comment]
Thanks for Your great comment! So I close the issue.
