### ISSUE TITLE
Performance issue: Restore with "--overwrite=true" shouldn't calculate hashsums

### ISSUE THREAD

**Issue by ramteid** [duplicati/duplicati#4131]
Restoring a large backup with many files (1,4 TB, 209k files) takes 5 hours on my machine, even when no files changed since the backup and "--overwrite=true" was supplied.

I tracked this issue down to RestoreHandler.ScanForExistingTargetBlocks(). In this method, 99% of the 5 hours are spent. For every file, the event "TargetExistsInCorrectVersion" is logged.

Why are hashsums calculated when the intention is to overwrite all files anyway? Maybe there would be some performance to save.

**Comment by ts678** [comment]
[--overwrite](https://duplicati.readthedocs.io/en/latest/06-advanced-options/#overwrite) says:

> Use this option to overwrite target files when restoring, if this option is not set the files will be restored with a timestamp and a number appended.

but what's not said is that the timestamp and number are only used if necessary because the files are actually different. Similarly an overwrite is not done if the file is all set -- thus the hash check for that.

https://github.com/duplicati/duplicati/blob/c86ca0f38c7edc945e69d291afd63c3eb6d51ee4/Duplicati/Library/Main/Operation/RestoreHandler.cs#L349-L352

Duplicati tries not to do work that doesn't need doing, especially if work is slow, such as remote work.

[--no-local-blocks](https://duplicati.readthedocs.io/en/latest/06-advanced-options/#no-local-blocks)

> --no-local-blocks = false
Duplicati will attempt to use data from source files to minimize the amount of downloaded data. Use this option to skip this optimization and only use remote data.

So if you had restored to a different folder, Duplicati would be using the above shortcut to read blocks from source files if possible for new files, instead of the shortcut you saw which saves writing old ones.

Look at your Restore job's `BackendStatistics`, and I expect you'll see far less than 1.4 TB downloaded.

**Comment by warwickmm** [comment]
As @ts678 mentioned, the hash check is to avoid unnecessary downloads.  I'm going to close this, but feel free to reopen if you think there's work that can be done here.
