### ISSUE TITLE
All files modified

### ISSUE THREAD

**Issue by Squarebro** [duplicati/duplicati#4141]
- [ ] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.5.103
- **Operating system**: Windows

## Description

I have installed new version of Duplicati (2.0.5.103) from (2.0.5.1) and when i run all my Tasks they all got new backup sets even tho most of them didnt had any files added/deleted/modified. When i checked what was going on i saw this:
![changeno](https://user-images.githubusercontent.com/62223861/76713839-cda6d300-6723-11ea-965a-cbc905230df2.png)

So all files got modified but (0 bytes) added. Also there were new dblocks and one new dlist (i thought dblocks were only created if there are some actuall file changes?)

## Steps to reproduce

- Install 2.0.5.103 after using earlier version
- Run any backup

- **Actual result**:
All files get modified
- **Expected result**:
No files modified, no new backup set

**Comment by drwtsn32x** [comment]
It could be due to improved metadata checks.  There was a change recently (I forget if it made it into 2.0.5.1 or if it was later) where NTFS permission breaks were not backed up properly.  Adding this feature did cause all files to be reprocessed.

How did the next backup perform?  It hopefully only "opened" files that were truly changed since the previous backup.

**Comment by Squarebro** [comment]
@drwtsn32x I see two changes between this two versions (both by you - thanks for all the work)

- Fixed issue with USN returning too many results
- Improved USN changes by looking at size and attributes

So this could be the case, but, I dont use usn-policy and i dont even run Duplicati as admin. Would it be still possible for this to be the reason?

**Comment by drwtsn32x** [comment]
No, if you don't use USN policy then these changes wouldn't have affected you. Plus at most those changes may just trigger a full filesystem scan, not a reprocessing of all file contents.

When you ran your next backup did it still reprocess all file contents?

**Comment by Squarebro** [comment]
Next backup didn't modify any files and didnt create new backup set, so no changes were made if this is what you mean by reprocess.

I guess its metadata as you said, but i dont know why would it be triggered if nothing changed and i dont see any other changes between two versions that could trigger it.

Is there some way you know that i could check what really changed?
I could run some querry in SQLli or somehow check in backup files?

Thanks

**Comment by drwtsn32x** [comment]
I did a quick test and confirmed what you saw. Did a backup of some files with 2.0.5.1, upgraded to 2.0.5.103, and ran another backup.  A new backup version was created.

I watched the Verbose Live Log while the backup was running and confirmed that it is due to what Duplicati sees as metadata changes.  The root cause is indeed the change where NTFS permission breaks are now backed up properly.  (See pull request https://github.com/duplicati/duplicati/pull/4031)

The new dblocks that are created contain the saved/updated file metadata.

Here's an example of the metadata difference for a folder backed up by 2.0.5.1 (upper) and one backed up by 2.0.5.103 (lower):
![Capture](https://user-images.githubusercontent.com/39164691/76763581-a1557b80-6750-11ea-86f6-38809eeb4d4d.PNG)

In hindsight it may have been a better idea to only store the `win-ext:accessrulesprotected` property when it is True.  This would have reduced the rescanning of file contents, and eliminated the saving of a new backup version (but only if there were zero files/folders with inheritance broken).

**Comment by Squarebro** [comment]
Thanks for testing this for me. Now I can be calm its not just me, already unexpected differences in fileset is my problem :D 

I guess everything is explained and it is indeed extra data in metada section.
It would be better as you said to save it only if its true, but I dont know if for compatibility reason this should be changed as this is only one new backup version and its only "extra" if nothing else changed. 

Im closing the issue. Thanks again!

**Comment by drwtsn32x** [comment]
@Squarebro - I have submitted a pull request to make this refinement: https://github.com/duplicati/duplicati/pull/4142
