### ISSUE TITLE
'--synchronous-upload' flag has no effect

### ISSUE THREAD

**Issue by cosmopol** [duplicati/duplicati#4207]
- [X] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: duplicati-2.0.5.1_beta_2020-01-18-x64
- **Operating system**: Win 8.1 64 pro
- **Backend**: LTO LTFS

## Description

(main thread: https://github.com/duplicati/duplicati/issues/4200)
--synchronous-upload flag has no effect

## Steps to reproduce

Here is my use case (redacted):
--alternate-destination-marker={GUID]
--alternate-target-paths=*:\_duplicati
--asynchronous-concurrent-upload-limit=1
--dblock-size=16777220KB
--file-hash-algorithm=MD5
--no-auto-compact=true
--no-backend-verification=true
--retry-delay=720s
--snapshot-policy=On
--synchronous-upload=true
--thread-priority=low
--use-background-io-priority=false
--use-block-cache=true
--zip-compression-level=0

- **Actual result**:
function according to testing:
--synchronous-upload=true (tested w/ and w/o --asynchronous-concurrent-upload-limit=1)
Duplicati does not wait for each volume to complete upload and still heavily uses read/write operations to parse source data as can be easily observed in the web GUI and Microsoft process explorer.
- **Expected result**:
function according to manual:
--synchronous-upload = false
Duplicati will upload files while scanning the disk and producing volumes, which usually makes the backup faster.
Use this flag to turn the behavior off, so that Duplicati will wait for each volume to complete.
(https://duplicati.readthedocs.io/en/stable/06-advanced-options/#synchronous-upload)

## Screenshots
N/A

## Debug log
N/A (there is no error entry regarding the issues mentioned above!)

**Comment by ts678** [comment]
I suspect this message was simply carried from the Duplicati 1 help text. Duplicati 2 has an extremely different design internally.
[Block-based storage engine](https://www.duplicati.com/articles/Storage-Engine/) covers some. Other parts likely carried over.

Duplicati 1.3.4 (the last of Duplicati 1 line) help is:

https://github.com/duplicati/duplicati/blob/266bd3e40a655066f5051d8cc187822273fda727/Duplicati/Library/Main/Strings/Options.resx#L486-L488

[Channel Pipeline](https://forum.duplicati.com/t/channel-pipeline/11466) describes the high use of concurrency in the current design, especially since [2.0.3.6_canary_2018-04-23](https://github.com/duplicati/duplicati/releases/tag/v2.0.3.6-2.0.3.6_canary_2018-04-23) change.

The current effect looks like it lowers the asynchronousuploadlimit to 1, but that doesn't directly pause the Source file processing.

Suggest the help text be changed, if anyone can think of a wording. Help then has the chance to flow into the manual (with help).

**Comment by kenkendk** [comment]
This is an old issue, so there is a chance that this was fixed at some point.

Tracking the flag shows that it is used in a few places where it will be more restrictive than settings `--asynchronous-concurrent-upload-limit=1` in that it will wait for an upload before progressing.

I will update the description of the flag to better match what it is doing.

**Comment by kenkendk** [comment]
Another option that is now available is `--cpu-intensity` which will, as a side-effect also reduce the I/O intensity.
