### ISSUE TITLE
"stop now" button gives a "stopping after the current file" response. how do I stop gracefully?

### ISSUE THREAD

**Issue by dorak88783** [duplicati/duplicati#4348]
- [x ] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.5.1_beta_2020-01-18
- **Operating system**: Windows
- **Backend**: Jottacloud

## Description

I'm starting a new backup so it will take some time. I would like to gracefully stop Duplicati when I want to turn off my PC.

However, when I click (in the UI) the cross icon and select 'Stop now', it's not sure what happens. The UI will switch to "Stopping after the current file: " which is exactly not the option chosen. There is also still network activity ongoing. It's also not clear if I lose the progress on the file that is currently uploading - if so it might be better to choose a smaller upload size so there's less waste?

## Steps to reproduce

1. Click stop now

- **Actual result**:
"stopping after the current file"
- **Expected result**:
immediate stop

**Comment by warwickmm** [comment]
Version 2.0.5.1 had several issues with interrupting backups that have since been improved in the canary releases.  If you're willing to try a canary release (which are less stable and can introduce other problems), you can help let us know if this behavior has improved.  Otherwise, you will have to wait for the next beta release to pick up these fixes.
