### ISSUE TITLE
Automatically dismissing errors

### ISSUE THREAD

**Issue by Vaalyn** [duplicati/duplicati#4451]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info
- **Duplicati version**: 2.0.5.1
- **Operating system**: Windows 10
- **Backend**: SMB Share

## Description

Hello, I've got a question that I couldn't find an answer to in the documentation nor in the GitHub issues.

Is it possible to configure duplicati to not show previous errors on the tray icon and in the dashboard if the last attempt to make a backup has been successful?

I have a home server that I use as a backup target via an SMB share that is mounted to windows and sometimes that server is not available. When duplicati tries to backup when the server is not reachable it will show an error on the dashboard and tray icon until the error is manually dismissed which becomes quite annoying to do over time.

**Comment by warwickmm** [comment]
Perhaps a better solution would be to use a [run-script-before](https://duplicati.readthedocs.io/en/latest/06-advanced-options/#run-script-before) script that detects if your server is available and returns [exit code 1](https://github.com/duplicati/duplicati/blob/338f467111f6bdcde971f93b8376daba42827498/Duplicati/Library/Modules/Builtin/run-script-example.bat#L22) if it's not.  That way, you could avoid errors instead of ignoring them.

https://forum.duplicati.com/t/feature-request-start-backup-only-if-some-host-is-available/11169
https://forum.duplicati.com/t/how-to-run-a-backup-job-only-if-storage-server-is-available/8913

**Comment by Vaalyn** [comment]
Thank you for the quick response and the links.

I'll play around with this `run-script-before` option and will post an update. 👍

**Comment by warwickmm** [comment]
No problem.  I'm going to go ahead and close this, since I don't think that automatic dismissal is the right solution here. If you need help with the script, I would recommend posting in the forums to see if other users have had experience with the scenario.

https://forum.duplicati.com/
