### ISSUE TITLE
Backups created outside the GUI cannot be imported

### ISSUE THREAD

**Issue by Hoffenbar** [duplicati/duplicati#4514]
I have created a backup with the command line tool, without using the gui. It´s not visible within the gui. Found no official way to import it. Don't know that the configuration file is - the sqlite DB isn't it. Its not possible to create a config file from a command line! Tried to manipulate the (unencrypted) Duplicati-server.sqlite, but only the first step was successfull.
It's only possible to import a file which was previously already created within the gui.
Don't want to try a direct restore from storage location just to possibly get the backup config into the gui. gui and command line should maintain and share the same configuration basis.

**Comment by ts678** [comment]
> Found no official way to import it.

[Duplicati.CommandLine.ConfigurationImporter.exe](https://duplicati.readthedocs.io/en/latest/07-other-command-line-utilities/#duplicaticommandlineconfigurationimporterexe) is the official way, though it's often easier to [Export As Command-line](https://duplicati.readthedocs.io/en/latest/03-using-the-graphical-user-interface/#exporting-a-backup-job-configuration) from GUI.

> gui and command line should maintain and share the same configuration basis.

[Integration between command line and web interface #2693](https://github.com/duplicati/duplicati/issues/2693#issuecomment-327440337) covers design intent:

> The commandline interface is intentionally separate from the server. The use case is for people who prefer headless commandline tools.

[A command line client for controlling the Duplicati Server ](https://github.com/Pectojin/duplicati-client) is also mentioned there. This is a third-party tool, but appears maintained.

**Comment by warwickmm** [comment]
As @ts678 mentioned, the command-line and web UI backups are separate.

The purpose of the `ConfigurationImporter` is to simply import JSON [configuration files](https://duplicati.readthedocs.io/en/latest/03-using-the-graphical-user-interface/#exporting-a-backup-job-configuration) into the web UI.  The correct syntax should be as described here:
https://github.com/duplicati/duplicati/blob/7b4f475762928ae72575cb96279364f0784de4e4/Duplicati/CommandLine/ConfigurationImporter/Program.cs#L27

The [documentation](https://duplicati.readthedocs.io/en/latest/07-other-command-line-utilities/#duplicaticommandlineconfigurationimporterexe) is probably wrong due to a copy/paste error of mine in the forums.  The first version of this tool allowed for various advanced options, but I removed them in pull request #3595 for some reason that I unfortunately didn't document.  However, I believe it does support anything that is captured by the JSON configuration file (except for the `DBPath`, which I think is always newly generated).  For example, I was recently testing the `auto-cleanup` and`number-of-retries` options, and used the `ConfigurationImporter` to import a JSON configuration that contained the following settings:
```
"Settings": [
    ...,
      {
        "Filter": "",
        "Name": "--number-of-retries",
        "Value": "0",
        "Argument": null
      },
      {
        "Filter": "",
        "Name": "--auto-cleanup",
        "Value": "true",
        "Argument": null
      }
    ],
```

I haven't tried this, but while the DBPath in the JSON file is ignored, after importing you could try recreating the database from the backend files.

**Comment by ts678** [comment]
> for some reason that I unfortunately didn't document.

[Always require server-datafolder option when importing configuration #3622](https://github.com/duplicati/duplicati/pull/3622) looks like the removal, shortly after initial commit.
That might be the high-level reason, but the reason why general advanced option support was removed isn't immediately clear.

**Comment by warwickmm** [comment]
Thanks @ts678, I linked to the wrong pull request in my comment (now fixed).  I'm guessing the reason was that the JSON configuration can accommodate the advanced options and I didn't want to deal with resolving any ambiguities.
