### ISSUE TITLE
Request: Improve error handling and reporting on invalid CLI arguments

### ISSUE THREAD

**Issue by LordMike** [duplicati/duplicati#4565]
- [x] I have searched open and closed issues for duplicates.
- [ ] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.6.3
- **Operating system**: Ubuntu 20.04
- **Backend**: N/A

## Description

I was troubleshooting why my commandline [was not being read](https://github.com/kees-z/DuplicatiDocs/issues/78) and finally found out why. During this, I wanted to increase the log level but [no matter which value I provided](https://github.com/kees-z/DuplicatiDocs/issues/79), I didn't get more logs. 

I was hoping that by providing invalid values, the output could tell me where I went wrong, but there was none.

I've run these commands with `Duplicati.Server.exe`. I imagine the same issue is present for the other utilities.

Note: Duplicati now runs for me, I figured out the proper formats, but I hope that future users would get more feedback on invalid values :).

## Steps to reproduce

1. Provide invalid arguments as linked

- **Actual result**:
*No console output*

- **Expected result**:
Something like:

```
> /usr/bin/mono /usr/lib/duplicati/Duplicati.Server.exe --log-level Debug --webservice-port 8250
Error: Invalid argument provided for "--log-format", expected "Verbose", "Error", ..
Error: Dangling argument provided: "Debug"
Error: Empty argument provided for "--webservice-port", expected a number
Error: Dangling argument provided: "8250"
```

These lines would tell me what Duplicati didn't link arguments like "--webservice-port" and "8250" which would tell me that the delimiter was wrong. Additionally, the error message for log levels would inform me of valid values, so I didn't have to guess. :)

## Screenshots
N/A

## Debug log
*No output*

**Comment by warwickmm** [comment]
Thanks @LordMike.  Our handling of options needs to be improved.  Currently, it's not easy to determine whether an option is expected to have an associated value (`--parameter=value`) or not (`--parameter`).  We will need to enhance our representation of command line arguments in order to better communicate errors to the user.

Issue #1970 is related.

**Comment by LordMike** [comment]
Does #1970 completely cover this? - if so, we can just close this issue :)

**Comment by warwickmm** [comment]
Yes, thanks. I'll add a comment there to mention how we can better communicate these types of errors to the user.

**Comment by ts678** [comment]
> I was hoping that by providing invalid values, the output could tell me where I went wrong, but there was none.

I think the servers do worse than CommandLine option processing and help. For example, Duplicati.CommandLine
tells you (when it's not totally confused). For example, if I give --log-level=Debug (note required = sign) it tells me:

```
The option log-level is deprecated: Use the log-file-log-level and console-log-level options instead
The option --log-level does not support the value "Debug", supported values are: ExplicitOnly, Profiling, Verbose, Retry, Information, DryRun, Warning, Error
```

CommandLine help is also more sophisticated and takes specific options (and other things) that have help text, e.g.

```
C:\ProgramData\Duplicati\duplicati-2.0.5.114_canary_2021-03-10>Duplicati.CommandLine.exe help log-level
  --log-level (Enumeration): Log information level
    [DEPRECATED]: Use the log-file-log-level and console-log-level options
    instead
    Specifies the amount of log information to write into the file specified
    by --log-file
    * values: ExplicitOnly, Profiling, Verbose, Retry, Information, DryRun,
    Warning, Error
    * default value: Warning
 ```

https://github.com/duplicati/duplicati/blob/5af46b6eecc9fe04c140ec5304dabdd50bdaa3af/Duplicati/Library/Main/Strings.cs#L106
https://github.com/duplicati/duplicati/blob/5af46b6eecc9fe04c140ec5304dabdd50bdaa3af/Duplicati/Library/Main/Options.cs#L318

so you can see that it's possible to get "improved" handling without #1970, but maybe that change makes it easier.

It's probably deprecated in CommandLine since [2.0.4.5](https://github.com/duplicati/duplicati/releases/tag/v2.0.4.5-2.0.4.5_beta_2018-11-28) (in Beta), but the [change](https://github.com/duplicati/duplicati/commit/842fd965439c6f1e6aac2d9ecaedfac1981e16c9) doesn't look like it changed server:

https://github.com/duplicati/duplicati/blob/5af46b6eecc9fe04c140ec5304dabdd50bdaa3af/Duplicati/Server/Program.cs#L507-L518
