### ISSUE TITLE
Implement AES-512

### ISSUE THREAD

**Issue by kankadev** [duplicati/duplicati#4581]
Please implement AES-512 for better and future proof encryption.

**Comment by ts678** [comment]
> AES-512

This does not exist, as far as I can tell.  Do you have citations otherwise?
[Advanced Encryption Standard](https://en.wikipedia.org/wiki/Advanced_Encryption_Standard) says NIST chose 128, 192 and 256 bits.
There might be an unofficial method that somebody is calling AES-512.
Stay away from cryptography made up by non-experts. Crypto is hard.

There are  `crypto.stackexchange.com` and other pages that say more.

[Is it common we extended Key size to 512 bit in AES Algorithm? [duplicate]](https://crypto.stackexchange.com/questions/64446/is-it-common-we-extended-key-size-to-512-bit-in-aes-algorithm)
[Why we can't implement AES 512 key size?](https://crypto.stackexchange.com/questions/20253/why-we-cant-implement-aes-512-key-size)
[Will there ever be a 512-bit Advanced Encryption Standard?](https://www.quora.com/Will-there-ever-be-a-512-bit-Advanced-Encryption-Standard)
[AES with bigger keys more secure?](https://crypto.stackexchange.com/questions/72129/aes-with-bigger-keys-more-secure)
