### ISSUE TITLE
Duplicati.Commandline.Backendtool Problem with GET file:// in Version 2.0.6.3_beta_2021-06-17

### ISSUE THREAD

**Issue by Domalar** [duplicati/duplicati#4632]
- [x] I have searched open and closed issues for duplicates.
- [x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info
- **Duplicati version**: 2.0.6.3
- **Operating system**: Windows 10
- **Backend**: file

## Description
A GET with the commandline to a file: Backend does not work with 2.0.6.3. If I execute the same command with my previous version 2.0.5.1 (on same PC to get the same file) the command is successfull.

Compare [https://forum.duplicati.com/t/duplicati-commandline-backendtool-problem-get-file-after-update-to-2-0-6-3-beta-2021-06-17/13264/2](Duplicati Forum) where the user ts678 confirmed the behaviour on an other windows pc.

## Steps to reproduce
1. `Duplicati.CommandLine.BackendTool.exe GET "file://\\hulk\backup_rw\duplicati\local-03_hulk_data" duplicati-b4d2dfe9739124b1292308bcf3e0016d4.dblock.zip.aes`
2. Works with 2.0.5.1 => file is downloaed
3. Switch to 2.0.6.3 and execute again

- **Actual result**:
`Command failed: Die Datei "\\?\duplicati-b4d2dfe9739124b1292308bcf3e0016d4.dblock.zip.aes" konnte nicht gefunden werden.
System.IO.FileNotFoundException: Die Datei "\\?\duplicati-b4d2dfe9739124b1292308bcf3e0016d4.dblock.zip.aes" konnte nicht gefunden werden.
Dateiname: "\\?\duplicati-b4d2dfe9739124b1292308bcf3e0016d4.dblock.zip.aes"
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   bei Duplicati.CommandLine.BackendTool.Program.RealMain(String[] _args)
`
[Englisch: The file ... could not be found. Filename: "\\?\..."]

- **Expected result**:
Should download the file!

## Screenshots
Command output pasted above.

## Debug log
If someone responds how to change the command line to get this output I will add the debug output here.

**Comment by warwickmm** [comment]
Is it possible to just fix the usages in `BackendTool`?

**Comment by dferreyra** [comment]
Sorry it's taken so long to get to this.  I have a fix I'd like to propose.  I'll submit a pull request later today so folks can look at it.

**Comment by dferreyra** [comment]
I've submitted a pull request with my proposed fix.

Like I say in the commit message, the changes I made in #4256 made it so that many methods in SystemIOWindows would no longer work with relative paths (or with absolute paths with relative components like "..").  Specifically, the `\\?\` was prepended to many paths passed in to SystemIOWindows methods, but that can only work when the path is absolute and needs no additional "parsing" from Windows.

My proposed fix changes the code so that `\\?\` is prepended only when it appears safe to do so.  This way, if relative paths are passed in, they get passed on to the basic .NET methods unchanged and behave like they're supposed to.

This bug has been in place for a while now, so it seems like relative paths aren't encountered too often in Duplicati.  Still, before I had a good picture of what was going on, I did look to see if I could find all the places where relative paths could make it through to SystemIOWindows, and I found dozens of places that would need investigating if a fix were to be applied at those sites instead of fixing SystemIOWindows itself -- mostly in Duplicati.CommandLine.* programs.  Restoring relative path handling in SystemIOWindows made the most sense to me, especially since I think anyone looking at the code would expect SystemIOWindows methods (and by extension, ISystemIO methods) to work with relative paths.

**Comment by warwickmm** [comment]
Thanks @dferreyra!  Yes, fixing the code that adds the `\\?\` seems like the right approach.

**Comment by Domalar** [comment]
@warwickmm Sorry I am not a aware of the code. But you write sometimes in your analyse about "relative paths". Just to clearify: My fiven file-Backend path is not relative! It is an absolute path: file://\\hulk\backup_rw\duplicati\local-03_hulk_data

**Comment by dferreyra** [comment]
Hi @Domalar, you're right about the "file://..." part, but the second parameter, "duplicati-b4d2dfe9739124b1292308bcf3e0016d4.dblock.zip.aes" is relative in the sense that the BackendTool is supposed to place "duplicati-b4d2dfe9739124b1292308bcf3e0016d4.dblock.zip.aes" in the current directory for you.  The bug I introduced with #4256 makes it so that that Duplicati can't create that file.  If, instead, you use an absolute path for that second parameter; e.g., "C:\temp\duplicati-b4d2dfe9739124b1292308bcf3e0016d4.dblock.zip.aes", the BackendTool would then be able to create the file, even with this bug in place.
