### ISSUE TITLE
speed up small files backup

### ISSUE THREAD

**Issue by rufengsuixing** [duplicati/duplicati#4637]
- [Y] I have searched open and closed issues for duplicates.
- [Y] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info
- **Duplicati version**: Duplicati - 2.0.6.3_beta_2021-06-17
- **Operating system**: Windows10
- **Backend**: Onedrive

## Description

i have a 3.5gb folder with 58000 files. duplicate spend too much time counting files ,spend 20% of cpu , at about 4.43 file every second. need more than 3.6h to proceed with most time nic card idle.
i have read https://www.duplicati.com/articles/Backup-Process/ and find "Processing similar data" is not always apply to small files,why not pack some kind of small files together to  speed up  or  use muti process  to speed up the  counting data or gave us some config which can backup small files with no check at all. if duplicate spend alot of time to check all the small file in the backup,i think it must need a lot of time to find information to restore. why not just pack small files in a folder and culculate and save at once. i would rather wast a little space to speed up backup process than wait all the time.

**Comment by warwickmm** [comment]
The documentation is a bit behind, but you could try the `disable-file-scanner` option:

> When this flag is enabled, the scanner that computes the size of source files is disabled, and instead the reported size is read from the database. Using this flag can speed up the backup by reducing disk access, but will give a less accurate progress indicator.

**Comment by ts678** [comment]
[usn-policy](https://duplicati.readthedocs.io/en/latest/06-advanced-options/#usn-policy) can avoid scanning for changed files, but it needs Administrator privileges in effect, which means either [install as](https://duplicati.readthedocs.io/en/latest/07-other-command-line-utilities/#duplicatiwindowsserviceexe) or [migrate to](https://forum.duplicati.com/t/migrating-from-user-to-service-install-on-windows/660) a Windows service (cleanest, but needs extra manual steps), or a UAC prompt or workaround to elevate without it.

As for the theory given here, you can also look at [How the backup process works](https://duplicati.readthedocs.io/en/latest/appendix-a-how-the-backup-process-works/) for greater depth, including seeing how the blocks of small files are already packed together into dblock files. [Choosing sizes in Duplicati](https://duplicati.readthedocs.io/en/latest/appendix-c-choosing-sizes-in-duplicati/) gives information on tuning block size and dblock size if you want to do that, however if scanning is the limiter, how the data is packaged doesn't matter much if you're not actually packaging much. Duplicati only uploads file changes, but it has to find them (first clue is modification time).

You can look at your job logs to see how many files you have, how many were seen as modified, and how much was uploaded.
For any Windows performance issue, information from Windows performance tools (e.g. the disk utilization) are very important.

Support (but no miracles) is available at the Duplicati forum. and seemingly you already got the development take on this idea.
[Features](https://duplicati.readthedocs.io/en/latest/01-introduction/#features) describes what Duplicati tries to do, and small files get the same level of service because the contents may matter too.
"no check at all" for small files sounds unappealing (but extremely vague) to me. Duplicati is [not a sync](https://duplicati.readthedocs.io/en/latest/01-introduction/#overview) or file copying program.
