### ISSUE TITLE
Warning Listing confirms file duplicati-20211213T230000Z.dlist.zip.aes was not deleted

### ISSUE THREAD

**Issue by iperov** [duplicati/duplicati#4649]
## Environment info
- **Duplicati version**: 2.0.6.3_beta_2021-06-17
- **Operating system**: Windows 10
- **Backend**: Google Drive

## Description

Getting same warning periodically (every 1-4 month)

2021-12-14 03:01:57 +04 - [Warning-Duplicati.Library.Main.BackendManager-DeleteRemoteFileFailed]: Listing confirms file duplicati-20211213T230000Z.dlist.zip.aes was not deleted

- **Actual result**:

warning

- **Expected result**:

no warning

## Debug log

[log.txt](https://github.com/duplicati/duplicati/files/7708990/log.txt)

seems like deleting the file after renaming
```
...
Renaming \"duplicati-20211213T230000Z.dlist.zip.aes\" to \"duplicati-20211213T230001Z.dlist.zip.aes\""
...
DeleteRemoteFileFailed: 20211213T230000Z.dlist.zip.aes FileNotFound
```

**Comment by warwickmm** [comment]
Can you provide more details about the backend?  Is it on the local filesystem or a network share, etc.?  Are you using the GUI or command-line?

The delete after rename is expected.  Not all backends support a rename operation, so a new file is created and the old one is then deleted.  In your logs, it looks like the delete failed because the backend reported that the file did not exist.  However, later on it is still able to list the file.

**Comment by iperov** [comment]
I am using backup on google drive.
GUI.

**Comment by warwickmm** [comment]
Did you configure Duplicati to back up to Google Drive directly, or to a local folder that is synced with Google Drive?  The latter is not recommended.

**Comment by iperov** [comment]
directly

**Comment by warwickmm** [comment]
Thanks.  It's not clear what happened, but something prevented the file from being deleted properly.  Some cloud storage solutions can have potential inconsistency issues immediately after an operation, but I don't know if that's what happened here.

The warning you encountered was one of the checks performed by Duplicati when a deletion fails.  In your case, the delete failed because something claimed the file didn't exist, but later on the file was claimed to still exist.  It's not clear which of these claims was faulty.  Regardless, I think Duplicati eventually cleans up after itself in these cases. 

I don't think there's any action we can take here, but if there are further reports of this we can reopen this and investigate further.

**Comment by iperov** [comment]
ok i will search another backup software. Duplicati is completelly shit without support.

**Comment by warwickmm** [comment]
The only similar sounding situation I could find is [here](https://forum.duplicati.com/t/delete-dlist-file-not-found-exclude-temporary-files/9768), which also involves Google Drive.

Support is limited since we have a very limited number of volunteers.  There is generally more activity in the [forum](https://forum.duplicati.com/).  I hope you are able to find a suitable solution for your needs.
