### ISSUE TITLE
The date of the last backup is not updated

### ISSUE THREAD

**Issue by 5exi** [duplicati/duplicati#4682]
## Environment info
- **Duplicati version**:  2.0.6.3_beta_2021-06-17
- **Operating system**: Windows Server 2019
- **Backend**: S3 compatible

## Description
The date of the last backup is not updated on main screen http://localhost:8200/

## Steps to reproduce
1. run backup script from cmd or powereshell

- **Actual result**:
I open http://localhost:8200 and see old date or Never in Last successful backup
if I open log, you can see successful log
if I try to restore, you can see last successful current backup
- **Expected result**:
I open http://localhost:8200 and see actual date in Last successful backup

**Comment by drwtsn32x** [comment]
This is by design.  The command line programs included with Duplicati are not linked to the web UI in any way, they are independent.

If you'd like a way to trigger backups from command line but have it integrate with the web  UI, I strongly recommend the excellent [duplicati-client](https://github.com/Pectojin/duplicati-client) tool.
