### ISSUE TITLE
Missing folders in backup to external USB drive

### ISSUE THREAD

**Issue by bambita** [duplicati/duplicati#4718]
- [x] I have searched open and closed issues for duplicates.
- [x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.6.3_beta_2021-06-17
- **Operating system**: Windows 10, all current updates
- **Backend**: USB external drive

## Description

I am taking encrypted daily backup to USB external 1TB drive. Backups are taken without any error reported by Duplicati.
When I tried to recover some files, I was horrified to discover that some folders are missing.

## Steps to reproduce

1. Run scheduled backup as per setting
see selected source
![Image 2467](https://user-images.githubusercontent.com/16983664/168239507-52ac89c6-0c56-42f4-862b-87885aade725.png)

2. Trying to recover folders/files
![Image 2466](https://user-images.githubusercontent.com/16983664/168239557-eea6ba8d-37dc-439a-a685-712fecc0eb3b.png)

As you can see "foto" folder is example of missing folder in successful backup

- **Actual result**:
Folder is missing

- **Expected result**:
Selected folder should be backed up

Please advise.

**Comment by ts678** [comment]
As a long shot, your arrow is pointing to where you expect `foto` based on an alphabetical sorting order, yet I see that sorting looks kind of strange. Source screen looks sorted to me, and its "kluci", "kluci scout", and "kluci skoa" order seems reasonable.

On the restore screen, "kluci scout", "kluci skoa" seems fine, but I don't know why "kluci" follows below. Did you look through every folder (including ones beyond the image) to make sure `foto` isn't somewhere else? Red arrow is assuming alphabetical.

[Sort file and folder listing in web UI #4150](https://github.com/duplicati/duplicati/pull/4150) sounds like the intention was to sort both the source and restore screens, so I'm not sure why they differ but they seem to. Maybe a participant in the enhancement can assist, or maybe I'm misreading something.

Is `foto` an ordinary folder similar to the ones beside it, with same permissions and storage, or is there anything special with it?

Do you happen to use [usn-policy](https://duplicati.readthedocs.io/en/latest/06-advanced-options/#usn-policy) on your Options screen? If so, you can try turning it off to see if it helps get your missing files.
On your Source screen, look at Filters and Exclude to make sure they're not involved with the files that are not being backed up.
Using a [log-file](https://duplicati.readthedocs.io/en/latest/06-advanced-options/#log-file)=\<path> at [log-file-log-level](https://duplicati.readthedocs.io/en/latest/06-advanced-options/#log-file-log-level)=verbose might show  `foto`, or if too short, try longer like `_podnikani_ic_69022739`.

**Comment by bambita** [comment]
Hello,

thanks for the reply.

I run the job again with recommended parameters.

I found this in the log file:
 2022-05-30 14:59:48 +02 - [Verbose-Duplicati.Library.Main.Operation.Backup.FileEnumerationProcess-ExcludingPathFromAttributes]: **Excluding path due to attribute filter**: C:\Users\jarda-hp\Documents\_jarda_\99_private\foto\


I have only default filters:
![obrazek](https://user-images.githubusercontent.com/16983664/171004541-c053fa50-2727-4bd9-9338-fcfc0117647b.png)

Does it mean that the folder is system, hidden or temporary?

Thanks & Regards,
JB

**Comment by ts678** [comment]
> Does it mean that the folder is system, hidden or temporary?

That seems to be what "Excluding path due to attribute filter: C:\Users\jarda-hp\Documents_jarda_\99_private\foto\" says.
 [attrib](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/attrib) and [dir](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/dir) can show system and hidden. An easy way to see temporary (and maybe the others) might be File Explorer.
Right-click --> Properties --> Details to read attributes, or show `Attributes` column and browse. Example of temporary:

![image](https://user-images.githubusercontent.com/40771998/171037719-0e6a25c3-98ad-4d5c-8f8e-a4f24e7369f5.png)

![image](https://user-images.githubusercontent.com/40771998/171039319-6ae6706e-53ed-468d-b6fd-0688475ed7d5.png)

Attributes are largely left up to whatever creates or maintains the folder or file. This makes them somewhat unpredictable.

**Comment by bambita** [comment]
Yes, you are right. The "foto" folder had attribute "S", I removed it and now it is included in the backup.

Thanks for support. You can close this issue.

Regards,
JB

**Comment by ts678** [comment]
I'm glad it worked. There was one other missing folder I thought I saw, and the screenshot didn't show everything everywhere.
You might consider [filtering](https://duplicati.readthedocs.io/en/latest/appendix-d-filters/) on path instead of attribute. Getting syntax right has its own challenges, despite some GUI assists.
There are also some predefined path filtering groups (which may or may not be to your liking). Ask for [help](https://duplicati.readthedocs.io/en/latest/04-using-duplicati-from-the-command-line/#getting-help-from-the-command-line-tools) on `filter-groups`.

Closing issue.
