### ISSUE TITLE
how do i connect to my mega account using duplicati? the documentation ISN'T CLEAR.

### ISSUE THREAD

**Issue by DARKBOW923** [duplicati/duplicati#4736]
Hello guys,

I have a problem, i want to connect to my mega account like the docs says, but its not working, it says that the source path (the mega folder) doesn't exists.

Any idea??? thanks.

**Comment by Xavron** [comment]
Its setup the same as SSH.

That means you put in the folder path as it is on the Mega side. I don't know if they can automatically create it or not so you may need to create the folders first.

Also don't know if Mega has some shared user initial path or not as some remote storage will do that but that's more of a Mega side thing. Though if so then Duplicati could at least mention it with a hint or something. eg something like this: https://webapps.stackexchange.com/questions/47953/where-did-mega-co-nz-store-my-download

Put in the usr and pass. And click test button. If its working then it should say a positive message.

**Comment by JovialJerboa** [comment]
@DARKBOW923 did you manage to sort your connection out? I've tried this recently and managed to get it to work, happy to help if I can.

**Comment by ts678** [comment]
> it says that the source path (the mega folder) doesn't exists.

You're trying to backup with MEGA as source not destination? That's not supported. Possible third-party workaround may exist, however doing anything with MEGA is kind of difficult because they have no published API, and don't like third party software...

If I'm misreading that, you got an offer of help just above (without response). If this gets no more action, it will close, eventually.
