### ISSUE TITLE
Login screen will not appear after hibernation

### ISSUE THREAD

**Issue by Rainmaker52** [duplicati/duplicati#4794]
- [X] I have searched open and closed issues for duplicates.
- [X] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info
- **Duplicati version**: 2.0.6.3_beta_2021-06-17
- **Operating system**: Windows 11
- **Backend**: OneDrive v2

## Description
OK, this is a weird problem. But it does seem to somehow be related to Duplicati.

If I close my laptop, my laptop automatically hibernates. If I open my laptop a little later on, the lock screen is displayed, and I need to type in my password.
When Duplicati is running, the login screen does not appear. The background image is not "blurred", as normally happens during password entry. No matter how long I wait, the password prompt does not appear. It works when I put the laptop in hibernation once more (again, using the laptop lid) and wake it up again.

It does not seem to matter whether a backup is actively running during hibernation, or whether it is just idling. However, if I fully stop Duplicati (remove all configurations), the problem does not appear.

I've had this problem on 2 _different_ laptops (a HP Elitebook 840 g3, running Windows 10 and a HP Elitebook x360 g4 running Windows 11). Both laptops do have Bitlocker enabled on the system drive. Both of the times, it works when I fully remove Duplicati, but they "freeze" on resume.

I know how impossible this may sound to be related to Duplicati. But I can reproduce this with almost 100% accuracy.

## Steps to reproduce
1. Configure a backup
2. Close the lid
3. Open the lid

- **Actual result**:
No password prompt appears.

- **Expected result**:
Windows allows me to login

## Screenshots
I can't screenshot the login screen. It's just my desktop background picture, unblurred.

## Debug log
Not sure whether this is applicable here.

**Comment by ts678** [comment]
FWIW I've just begun having a similar problem, although I've been running Duplicati a long time. Control-Alt-Delete helps me.

**Comment by Rainmaker52** [comment]
Wow. Wasn't expecting that.

Ctrl-Alt-Delete does sometimes work on Windows 10, but not on Windows 11.

Any similarity in hardware? Also HP notebooks?

**Comment by ts678** [comment]
> Wasn't expecting that.

It also surprised me, but I thought it was worth a try before using the power button and losing the things that I had open.

> Any similarity in hardware? Also HP notebooks?

This is a ten year old HP Compaq desktop on Windows 10. The problem began days after installing another VSS using app.
I'm not using hibernate, but I do sleep it overnight. I haven't attempted any troubleshooting or research into this problem.

My problem seems a bit intermittent, and the workaround has worked so far. I just tested a short sleep and it woke up OK.
Duplicati was not just running-as-in-up, but running-as-in-mid-backup at the time. I'll try to see if I can notice any pattern.

**Comment by ts678** [comment]
Next short sleep got the typical (when it happens) misbehavior. It wakes, gives me a pretty random photo with a clock and sometimes some other textual commentary. I click that, the text goes away and I'm staring at a photo and a mouse cursor.
Screen times out and goes dark. Mouse wiggle brings it back, but I have to Control-Alt-Delete to get blur and login ability.

**Comment by ts678** [comment]
Do you by any chance have multiple accounts on your computer? I found that a sleep from one account sees this problem.
Two other accounts that were signed in do not. I then found that I didn't even need sleep, just a Windows-L to lock screen.

There's a LockApp.exe process for each account. Killing the one for the troubled account saw it restart, but issue remained.
If I turn off "Show lock screen background picture on the sign-in screen" in the Settings for Lock Screen, I can enjoy a blue
blank screen (plus cursor) while I'm wondering where sign in icon is. This is account-specific, so it can predict this problem.

At that point, I'd shut down Duplicati and lots of other things (looking at foreground processes and even in Task Manager).
Seemingly the next step was sign out and sign in to see if somehow that fixes whatever seems to be stuck inside Windows.

I tried that yesterday, and the problem went away, testing repeatedly with Windows-L. I rebooted and went back to normal (restarting some Windows services and some other automatically run things). Still fine. Slept system overnight, and still fine.

> Ctrl-Alt-Delete does sometimes work on Windows 10, but not on Windows 11.

It turns out that this can be set as a security requirement. For me, while issue existed, it bypassed it without a second usage.
[How to Enable or Disable Secure Sign-In for Windows 10](https://www.howtogeek.com/443119/how-to-enable-or-disable-secure-sign-in-for-windows-10/)
[Interactive logon: Do not require CTRL+ALT+DEL](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/interactive-logon-do-not-require-ctrl-alt-del)

My system does sometimes have odd Windows glitches, e.g. UAC to an admin account can hang on first use but works after.
Because the problem has gone away for me, for now at least, I don't think there's much I can do, but please test as you wish.

**Comment by Rainmaker52** [comment]
Thanks a lot for taking the time to write such a detailed response.

I fiddled around with the settings you're referring to.

With my main Windows 11 laptop, I'm currently at the point where this happens _every time_ on boot, but never when locking / unlocking. On boot, I can "fix" this by pressing ctrl-alt-delete. So, apart from that oddity, there's not that much of a practical problem anymore.

What I am wondering about (and why I expected this issue to be closed without anyone responding) is how on earth Duplicati, as a user-space app, seems to have an impact (any impact at all) on the Windows login screen after resuming. I can't really imagine Windows would even allow an app to influence the process of opening the Winlogon, as it's running on the secure desktop.

I can't really find any references to power settings that Duplicati may alter in the source code of this repo. I'm not sure whether it does so indirectly. 

Again, thanks for the reply.

**Comment by ts678** [comment]
> power settings

Possible source code starting points related to power and sleep/resume hooks include

https://github.com/duplicati/duplicati/blob/6399ad8c871bdbb23b9415abd4133742be8c143b/Duplicati/Library/Main/ProcessController.cs#L270-L271
https://github.com/duplicati/duplicati/blob/6399ad8c871bdbb23b9415abd4133742be8c143b/Duplicati/Server/Scheduler.cs#L305-L308
https://github.com/duplicati/duplicati/blob/6399ad8c871bdbb23b9415abd4133742be8c143b/Duplicati/Server/LiveControls.cs#L344-L351

> have an impact (any impact at all) on the Windows login screen

I agree it's pretty weird, arguably something Windows should prevent even if Duplicati is doing something weird.
For whatever it's worth, my issue hasn't come back, so whatever was weird in Windows has been behaving lately.

**Comment by Alk2** [comment]
I don't have this problem personally, but I happen to stumble across [this article](https://www.askvg.com/fix-windows-11-stuck-at-lock-screen-now-requires-pressing-ctrl-alt-delete-to-unlock/) today, when I remembered this issue here on github. Hope it helps.

**Comment by ts678** [comment]
My 2022 problem went away by itself. Possibly Microsoft fixed something. I don't know if it would help your situation, but there's

![image](https://github.com/duplicati/duplicati/assets/40771998/cdaf6d0a-f807-4b0b-aa5f-52b56c61d4eb)

in Settings, which is useful to keep Duplicati from competing for resources at the same time as the rest of computer is awakening.

My Windows weirdness of today is I opened a web page in Edge. That struggled, screen went blank for two hours, resisted video driver reset and Ctrl-Alt-Del. Finally I momentarily pushed the power button, and that got the video back. I eventually had to kill Edge and Desktop Window Manager. First time on the latter, and it was attempt to fix weird blurring and window drawing issues.

> So, apart from that oddity, there's not that much of a practical problem anymore.

I also searched the forum and Issues for similar reports, but couldn't find any. Whatever was going on seems to be quite unusual.

As I'm in the middle of some cleaning in GitHub Issues to let actionable remaining bugs stand out, I wonder if this can be closed?

If no more interest, it will close by itself.

**Comment by Alk2** [comment]
I have this problem myself now, where the login screen will not appear after putting the PC to sleep. I have to use ctrl+alt+del to make the login box appear every time my monitor goes to sleep (eg. after 10 minutes) even though the PC is still powered on and has not gone to sleep again. 
The issue can be temporarily resolved by re-launching explorer.exe: If I kill explorer.exe using Task Manager (from the Details tab) and re-launch explorer.exe using Task Manager (File>Run new task). Then when the PC goes to sleep again the login screen will behave normally for the next few days.
If I were to restart/shutdown my PC more often, then the problem would not occur/be noticed.

The question is, what is triggering explorer.exe/the login screen to behave abnormally and is it Duplicati? When it next occurs, I will try stopping Duplicati temporarily and see if my login screen returns to normal. I will report back when the opportunity arises.

**Comment by Alk2** [comment]
I have just noticed that when my backup jobs ran, my login box issue re-appeared (it was fine an hour or two beforehand). The original reporter to this issue stated that the Duplicati configuration has to be removed to make the problem go away, so it is possible that it could be something to do with the Duplicati backup jobs running.
Therefore, to conclusively rule Duplicati out as the cause of the problem, I have stopped/disabled my Duplicati services and closed/disabled the trayicon. I will run my PC without any Duplicati backups for as many days as I can to see if the login box issue re-appears. I will report back my findings.

**Comment by Alk2** [comment]
I should have said that I disabled Duplicati a few days ago, prior to my comment yesterday, so I have been running my PC without any Duplicati backups for a few days now.
Today, my Start Menu won't open again and the login screen issue has re-appeared, so I have to press ctrl+alt+del again to login. 
Therefore, I would say that this is pretty conclusive that it is _not_ Duplicati at fault on my PC, because Duplicati has not been running at all during this time - I verified that the Duplicati service was still stopped, etc. and that there are still no Duplicati processes running using Task Manager (sorted alphabetically): 
![2024-02-20_18h49_24](https://github.com/duplicati/duplicati/assets/29456321/7849f2de-6fde-4c98-9be7-b8004202669f)

I have now tested as much as possible to rule out Duplicati and so I would be satisfied if the task were closed.
