### ISSUE TITLE
Not at all clear how to deal with frequently occuring errors: `remote file duplicati-....dblock.zip.aes is listed as Uploaded with size ... but should be ..., please verify the sha256 hash ...`

### ISSUE THREAD

**Issue by posita** [duplicati/duplicati#4848]
I backup a laptop to an auto-mounted SMB drive. Despite #3626 and #4076 being closed as fixed, I frequently get errors like `remote file duplicati-....dblock.zip.aes is listed as Uploaded with size ... but should be ..., please verify the sha256 hash ...`. When this happens it totally unclear how resolve these warnings. It's not even clear whether or which parts of my backups are at risk, whether a subsequent restore will work, or which backed up files are compromised or not restorable.

The command line documentation is not helpful to a non-expert and offers no helpful guidance (or, if it does, it's very hard to discover).

These are listed as warnings, but sound like data loss. The end user should be presented clear and precise guidance on the specific paths implicated by these warnings, their effects, recommendations for addressing them, and the consequences of inaction. It should not be required that the end user be an expert in Duplicati architecture to understand these things.

**Comment by ts678** [comment]
> It should not be required that the end user be an expert in Duplicati architecture to understand these things.

Generally people open a forum topic seeking expert advice, however it would indeed be nice if self-service were more feasible.

What you ask for is probably deeper than brief built-in help could cover, and the command line manual tends to mimic that...
This also isn't just a command line issue, so should be covered (if in the manual at all, as opposed to forum) in common parts.

[https://github.com/kees-z/DuplicatiDocs](https://github.com/kees-z/DuplicatiDocs) is technically a different project. Care to assist developing the text to see if it's taken?
[Disaster Recovery](https://duplicati.readthedocs.io/en/latest/08-disaster-recovery/) might be a reasonable place for such fixes, however an awful lot of people don't seem to find it, making it a questionable use of time trying to document all possible situations. Recovery varies, and human guidance on forum is helpful.

[Recovering by purging files](https://duplicati.readthedocs.io/en/latest/08-disaster-recovery/#recovering-by-purging-files) is the general path, but there are some things not said (and I don't know what's a code deficiency versus a manual oversight). Open a forum topic if you like. Also consider running Canary (adds risk of a surprise breakage, but you're at risk now), so you can enjoy this pull request which helps detect and retry upload corruptions on unreliable file stores.

[FileBackend file size verification #4691](https://github.com/duplicati/duplicati/pull/4691)

You'd generally take the latest Canary, maybe after a wait-and-watch to see if anything broke. This enhancement was added in
[2.0.6.103_canary_2022-06-12](https://github.com/duplicati/duplicati/releases/tag/v2.0.6.103-2.0.6.103_canary_2022-06-12)

> Added check to detect partially written files on network drives, thanks @dkrahmer

Above is what caused the two issues you cited to be closed as fixed, but "fixed" doesn't mean fixed in old Beta you're running...
Nobody has a forecast for next Beta. Duplicati is short of volunteers in all areas, and doing any releases needs a specific person.

**Comment by Xavron** [comment]
This could also well be an issue on the remote side with bugs in LIST, writing of the file, etc that cannot be known by Duplicati so its not all that easy to actually improve the error as it could make it incorrect.

To me, all that can be done here is simply to create a list of things people have done to successfully solve it. That applies to anything though.

I don't really find this worthy of remaining open due to the nature of it.

**Comment by ts678** [comment]
> To me, all that can be done here is simply to create a list of things people have done to successfully solve it.

How does someone seeing the current message (where my personal dislike is the obscure sha256 text) find it?
There was once an idea of some FAQ writing, but issues are so varied that it would be huge. Would it be used?
One would likely need an ability to search, but forum and Issues already are. Issue template even asks for that.

> That would be the only reason to keep it open

It depends on whether this is a support request. If so, need info, and preferably use forum -- hasn't happened.
Sometimes that gets a support Issue closure. If it's an enhancement request for Manual, that hasn't been filed.
In addition to a potential bug (such as others cited), I think better user guidance is good, but how to get that?
There are lots of challenging issues around that are kept open even though there's no immediate way to solve.

I agree that a lot of different things could be behind any specific failure, and there's a troubleshooting process.
IMO, this particular message should be an Error because (unless a false alarm), part of the backup is gone, and
[Disaster Recovery](https://duplicati.readthedocs.io/en/latest/08-disaster-recovery/) can help. Or ask for human help. Even then, that may need to be tailored to be case specific.

[Restore Hash Failed - How to retry/restore from other backup?](https://forum.duplicati.com/t/restore-hash-failed-how-to-retry-restore-from-other-backup/15616) is the kind of failure that broken files can cause.
I set `pending user feedback` on this. OP has been very quiet. Without interest, less reason to keep this open.

**Comment by ts678** [comment]
My "this particular message" really also meant "in this particular report", as the damage could have been to a dlist or dindex.
Those can be deleted and re-uploaded from an intact database by deleting them then having `Repair` upload another copy.

Typically (and unfortunately) dblock damage (where source data is) reports seem more common than for their paired dindex.
In terms of verified actual loss, see `Disaster Recovery` for how to purge broken files. It forgot to mention delete them first.

A dblock definitely merits `Error` IMO. A dlist or dindex is a little less clear, but they can hurt database recreation from them, including the one that happens in disaster recovery using `Direct restore from backup files`, so it's something best fixed.

"successfully solve it" for a dblock means reading `Disaster Recovery` or an enhanced version of it covering some fine points. Possibly message could say that, but I don't think there's precedent yet. One can say a lot more in a manual than in message. Success is relative. Purging broken files doesn't prevent some destination from losing files again, but that may be beyond us...

Just for fun, one (for some odd sense of fun), one can read what IBM does in their enormous manuals to help with messages.

[System messages reference](https://www.ibm.com/docs/en/zos/2.1.0?topic=log-system-messages-reference) (for z/OS 2.1.0)
There's a somewhat standard format with some explanation and some words on action or response. It may mention manuals.
Even the compact format seems a bit much to put in the message itself, but it would be one way to help users sort issues out provided they have a willingness, and maybe knowledge on where to go, to avoid steering them on every last message made.

Nothing like this will be possible without a lot of help. but if one wishes to daydream about good guidance, what would it be?

Returning from the vast sky to the code details:

https://github.com/duplicati/duplicati/blob/666b2281032460254839fdc3b6e1055fdf7ce1db/Duplicati/Library/Main/Operation/FilelistProcessor.cs#L392-L393

also reveals that the `Uploaded` is a variable, and above that one sees that it might have been `Verified`. That sounds worse if something happened after it looked good once. Somebody who pursues this can look further up in the above-cited source file.

This might be the flaky-SMB-upload problem that the OP cited, leading to PR 4691 awaiting Beta, but available in Canaries per
[2.0.6.103_canary_2022-06-12](https://github.com/duplicati/duplicati/releases/tag/v2.0.6.103-2.0.6.103_canary_2022-06-12)
