### ISSUE TITLE
Add Stop Server Command

### ISSUE THREAD

**Issue by alkaris2** [duplicati/duplicati#4853]
- [ x] I have searched open and closed issues for duplicates.
- [ x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.6.104_canary_2022-06-15
- **Operating system**: Linux tohru 5.15.78-1-MANJARO SMP PREEMPT

## Description

Why is there no `stop` or `kill-server` command for Duplicati CLI ? I look through the entire documentation and NOWHERE does it say how to stop and kill the server from running. It's really confusing why there is no kill server command that can be issued to Duplicati to STOP what it's doing. Not even a Service Unit file to stop it with by issuing; `sudo systemctl stop duplicati-server` Doesn't make any sense how this isn't a default coded into the program itself, or the fact the User Manual doesn't show or have anything at all on how to halt the server. My only option would seem to be to directly issue pkill on the main process `DuplicatiServer` and `mono-sgen` with SIGKILL just to stop the server entirely and then run the `Duplicati.Server.exe` again to start the server again, since that doesn't appear to take any commands to stop, start or restart the server. It's so incredibly unuser-friendly and frustrating that `duplicati-cli help` and duplicati-server --help` shows nothing of the sorts.

What even is the proper way to Start, Shutdown or Restart Duplicati service? Can the User Manual please get updated to include this information. Even having a difficult time searching how to stop Duplicati from running, I see a whole bunch of dead-end posts with the same titles _"How do you completely stop Duplicati?"_ or _"Stop"-ing the Duplicati Synology Package Does Not Stop Duplicati.Server.exe"_

**Comment by gpatel-fr** [comment]
Hello

sudo systemctl stop duplicati has always worked for me.
Under Windows, the normal commands to stop a service do the job as well.

If you don't run it as a service, the toolbar icon gives an option to stop the spawned task.

Am I missing something ?

**Comment by ts678** [comment]
> Why is there no stop or kill-server command for Duplicati CLI ?

Duplicati CLIs (and there can be multiple) have nothing to do with Duplicati servers (and there can be multiple on different ports). Knowing further original reasons would need input from original (unavailable now) author, but the above often confuses people...

[Integration between command line and web interface #2693](https://github.com/duplicati/duplicati/issues/2693#issuecomment-327440337) has a 2017 comment from original author, so we have at least a bit:

> The commandline interface is intentionally separate from the server. The use case is for people who prefer headless commandline tools.

which eventually led to third-party tool [A command line client for controlling the Duplicati Server](https://github.com/Pectojin/duplicati-client) which talks to the server some, but I don't see a command to stop it. That would also cut off talk ... and a server start by talking to stopped server is impossible.

Detail of starting and stopping OS services ultimately depends on the OS. Windows has its way. Linux varies, but systemd use is common. macOS has its way. Documentation seems to be best for the most widely used OS types. OS usage can be found [here](https://usage-reporter.duplicati.com/).

There are many ways to run Duplicati. This makes it flexible but confusing and hard to document. Technically a server isn't an OS service every time. One can start servers from a script or CLI. Linux does nice Control-C death. Windows keeps it running (oops) although it looks like it went down because your CLI prompt returns. Actually, child (which does the work) is still up and running.

[Duplicati User's Manual](https://duplicati.readthedocs.io/en/latest/) home page says how (in theory anyway) updates are done:

> Corrections/changes/additions may be submitted as a pull request at Github: https://github.com/kees-z/DuplicatiDocs

For historical reasons, manual is a separately owned project. I'm not sure how actively it's maintained, but you can try if you wish. There is definitely room for improvement, but needed resources are rare, so unfortunately forum and issues have to pick up slack.

Usually the answer to why there is not \<whatever> is lack of volunteers. Duplicati can only exist and improve through volunteers.

**Comment by ts678** [comment]
> NOWHERE does it say how to stop and kill the server from running.

[Installing Duplicati on Linux](https://duplicati.readthedocs.io/en/latest/02-installation/#installing-duplicati-on-linux) (which could use a tune-up) does say this. Typing `systemctl` in the search box goes to this section.

```
sudo systemctl enable duplicati.service
sudo systemctl daemon-reload
sudo systemctl start duplicati.service  
sudo systemctl status duplicati.service
```

Admittedly it doesn't say there's a `stop` as well.
