### ISSUE TITLE
Any chance for next beta?

### ISSUE THREAD

**Issue by anshibanov** [duplicati/duplicati#4887]
The last beta was released on 2021-06-17 (2.0.6.3_beta). During this time there were changes in the code, including bug fixes. Is there any chance to see a new beta please 🙏

**Comment by Xavron** [comment]
Seems to be the last actual and can be downloaded from here: https://github.com/duplicati/duplicati/releases/tag/v2.0.6.104-2.0.6.104_canary_2022-06-15

So I'd say its basically already done. There's not really be anything worth it since.

Of course, if you want to pull it in directly from inside Duplicati GUI then that would be what you're asking.

**Comment by yaneony** [comment]
Is duplicati still alive?

**Comment by ts678** [comment]
> Is there any chance to see a new beta please

The one person who can do them has no time. If any well-qualified person wants to help, negotiations may be possible.
A Beta release usually follows an Experimental, and that follows Canary that has seemed good for awhile. Got that now.
Turning latest Canary into Beta then pushes the challenge into finding someone to do commits and do another Canary.
If that gets solved, then problem moves to finding developer volunteers to add features and fix problems. PRs welcome.

> Is duplicati still alive?

Everything done happens thanks to volunteers, but Duplicati is currently suffering from lacks, including in key positions.
It's kind of wait-and-see for when and if the main project author and maintainer will have time again. Help might help...

Meanwhile, the forum is doing its best to support the project, and there are Canary and some unofficial releases done...

More here:

[Was worried due to the lack of releases](https://forum.duplicati.com/t/was-worried-due-to-the-lack-of-releases/14422/3?u=ts678)

**Comment by joksik** [comment]
> and there are Canary and some unofficial releases done.

hi i search duplicati board but i cannot find unofficial release. where can i find or download to test this unofficial releases ?

**Comment by Xavron** [comment]
> > and there are Canary and some unofficial releases done.
> 
> hi i search duplicati board but i cannot find unofficial release. where can i find or download to test this unofficial releases ?

I linked the latest one right above your reply here ;)

That actually takes you to the releases page on here and you can click releases near the top left if you want more.

**Comment by ts678** [comment]
> where can i find or download to test this unofficial releases

Note that Canary releases are official test releases. Unofficial releases are third-party contributions from the community.
These are sometimes not full releases, but replacement pieces for very specific issues you can maybe find using a search.

Can you clarify your objective? I can't guess much from past posts that I can find. For anybody who's very adventurous,
community member @tsuckow has a .NET 6 port (and other major changes) in progress that could use some code help.

This represents the long-term direction of Duplicati because it has to follow Microsoft's long-term direction around .NET.
[Kestrel is coming](https://forum.duplicati.com/t/kestrel-is-coming/15527) was one forum post. Maybe testers are desired? I'm not sure how efforts from helpers would get done.

**Comment by alxndr-w** [comment]
I was a huge fan of Duplicati 1.x and 2.x-beta works quite well. If time equals money, I would support a call for donations. 

There should be an Open Source alternative to the bigger players with expensive solutions bundled with adware, snake oil and stuff.

**Comment by yfdyh000** [comment]
> There should be an Open Source alternative to the bigger players with expensive solutions bundled with adware, snake oil and stuff.

I'm sorry if this is digression. I recently tried the software but having some Web UI bugs and slow indexes for a large number of files. Since https://github.com/restic/restic seems to have not yet prepared for MS Windows & build-in UI, I now switch to https://github.com/kopia/kopia.

**Comment by mr-russ** [comment]
@ts678 can this be closed as releases have been made?

**Comment by ts678** [comment]
[2.0.7.1_beta_2023-05-25](https://github.com/duplicati/duplicati/releases/tag/v2.0.7.1-2.0.7.1_beta_2023-05-25) was released. Forum page is [Release: 2.0.7.1 (beta) 2023-05-25](https://forum.duplicati.com/t/release-2-0-7-1-beta-2023-05-25/16303) if you want to see how it's received.
Main site's [download page](https://www.duplicati.com/download) also has it, however autoupdates should be rolling out for existing Beta installs, and may be easier.
