### ISSUE TITLE
Can the system do backup from FTP to local  , if not what changes should I do to cater for that 

### ISSUE THREAD

**Issue by hmephi** [duplicati/duplicati#4909]
Is there a way to make a system to do backup from FTP to local , what changes can be made on the source code to cater for that

**Comment by ts678** [comment]
There are also a whole lot of technical reasons why a file transfer protocol (speaking generically) does not work like a local drive. 

Assuming you want restore too, Duplicati restores blocks to local drives using random-access patches -- harder to do remotely although some programs provide such an option. Speed is also a factor. Duplicati may need to scan lots of files to find changes. Even file metadata changes such as NTFS or Linux permissions are read. On the Source side, it does a lot. Destination does little which is why so many varieties can be supported -- they all can fill the minimal requirements that any destination must handle.

If you like the versioning that Duplicati supports, one option would be to rclone to local drive, then have Duplicati back that up. There's also a `mount` command, but results cannot be guaranteed. I think there are reports around of it working, but YMMV...

[[Feature Request] Cloud providers as source data #2590](https://github.com/duplicati/duplicati/issues/2590) was a similar question, so maybe this one will someday close as a dup.

**Comment by Xavron** [comment]
Something like they said but another way to workaround it and have Duplicati do it would be to use an FTP client script that can pull in all the desired FTP files into a temp folder eg daily such as via WinSCP command line + a script in Windows Tasks or Linux cron maybe. Then run Duplicati backup on that locally.
