### ISSUE TITLE
W11 Smart App Control blocks due to unsigned DLLs

### ISSUE THREAD

**Issue by jonahdami** [duplicati/duplicati#4915]
- [x] I have searched open and closed issues for duplicates.
- [x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info
- **Duplicati version**: 2.0.6.3
- **Operating system**: Windows 11 Pro 22H2

## Description

At app startup, there are a lot of windows defender notifications (See image 1, unfortunately windows does show these in my installation language not display language) that a part of the application duplicati might not work due to DLLs not being signed. Multiple of the DLLs in the duplicati folder are flagged, including for example: uplink.NET.dll, UnixSupport.dll, MonoMac.dll, Minio.dll
[This MS article](https://support.microsoft.com/en-us/topic/smart-app-control-has-blocked-part-of-this-app-0729fff1-48bf-4b25-aa97-632fe55ccca2 ) is linked in the notifications.

When starting Duplicati again after these notifications, duplicati shows this error (see Image 2) and - as expected- creating backups doesn't work.
`Could not load file or assembly 'AWSSDK.S3, Version=3.3.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604' or one of its dependencies. Your organization used Device Guard to block this app. Contact your support person for more info. (Exception from HRESULT: 0x800711C7)`

I "solved" it by shutting off Smart App Control all together, but thats not really viable as it can only once per installation be activated. (Activated it for testing purposes).

## Screenshots
Image1:
![IMG_20230401_113707](https://user-images.githubusercontent.com/105049604/229278839-c883b4c6-2492-4251-ad9c-8c7f6ce5016f.png)

Image 2:
![image](https://user-images.githubusercontent.com/105049604/229277628-304e63f7-675c-4243-9e54-b6ef6282c7f8.png)

**Comment by gpatel-fr** [comment]
Hello

as the DLLs that you are mentioning are not produced by the project but shipped unchanged to support third party providers (are downloaded from the Microsoft approved nuget.org repository, actually), you may consider setting an exclusion as explained here:

https://learn.microsoft.com/en-us/deployedge/microsoft-edge-policies#smartscreenallowlistdomains

because I don't think it's possible for an organization to sign Dlls that it has not compiled itself.

This said, if you use only Microsoft blessed backends, Duplicati will work even if it complains about unloadable libraries. These are not called 'dynamic' loadable libraries for nothing. AFAIK the default FTP Duplicati backend is produced by Microsoft itself,so it 'should' (hopefully) be signed according to Microsoft policy.

**Comment by ts678** [comment]
I think these are different security products, [Microsoft Defender SmartScreen](https://learn.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-overview) versus [What is Smart App Control?](https://support.microsoft.com/en-us/topic/what-is-smart-app-control-285ea03d-fa88-4d56-882e-6698afdb7003) which doesn't allow an app exception, and has a simplistic idea that signing the app is the easy answer. But what about its 3rd party libraries?

One can turn the whole thing off, but it needs Windows 11 reinstall to turn it back on. How crude. If that's done in the name of security because something bad might have come in while it was off, that could have happened while it was in evaluation mode.

I've never signed a DLL, but it looks like one can sign arbitrary ones. Whether or not one _should_ do that is a different question.

[SignTool](https://learn.microsoft.com/en-us/windows/win32/seccrypto/signtool?redirectedfrom=MSDN) from Microsoft is sometimes used, but Duplicati looks like it prefers [osslsigncode](https://github.com/mtrojnar/osslsigncode), which does some of the same things.

**Comment by jonahdami** [comment]
> because I don't think it's possible for an organization to sign Dlls that it has not compiled itself. >

@gpatel-fr  sorry, I didn't get the notification for your comment. Makes sense, that Duplicati cant sign the MS provided DLLs.
"solved" it by turning off App Control.


> I think these are different security products, [Microsoft Defender SmartScreen](https://learn.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-overview) versus [What is Smart App Control?](https://support.microsoft.com/en-us/topic/what-is-smart-app-control-285ea03d-fa88-4d56-882e-6698afdb7003) which doesn't allow an app exception

@ts678 Yeah I didn't find a way to whitelist duplicati either and simple disabled Smart App Control (forever).

**Comment by ts678** [comment]
> Makes sense, that Duplicati cant sign the MS provided DLLs.

The problem packages are not those created by Microsoft but are hosted in their public repository nuget.org.
[The flow of packages between creators, hosts, and consumers](https://learn.microsoft.com/en-us/nuget/what-is-nuget#the-flow-of-packages-between-creators-hosts-and-consumers) talks about it, and shows who does what there.

Looking at that flow, your symptoms sounds like all creators should sign their assemblies (`.dll` for example).
As they claim to have 100,000 packages there (and we use some), this seems a pretty huge hurdle to achieve.
Smart App Control might be expecting too much, unless it wants users of packages to sign for their creators...

You can study your files with right-click --> Properties, and see if there is a `Digital Signatures` tab present.
I'm not very expert in this area and am not sure of the cleanest way to solve this issue. We'll likely see it again.

**Comment by gpatel-fr** [comment]
This is not a problem Duplicati can solve.
