### ISSUE TITLE
Version 2.0.7.1: Windows blocks installation - say its insecure

### ISSUE THREAD

**Issue by georgfranz** [duplicati/duplicati#4965]
Hi,
just downloaded the latest version from the website:
https://updates.duplicati.com/beta/duplicati-2.0.7.1_beta_2023-05-25-x64.msi

Windows Defender blocks the installation and say its insecure.

Best,
Georg.

**Comment by gpatel-fr** [comment]
Hello

You can unblock the installation by clicking on 'More...'
This is not caused by the file being rated insecure. The certificate used to sign the MSI file has been renewed on 9 April 2023 and the so-called 'Smartscreen' builds its opinion on application certification on number of Github downloads signed with a given certificate. As this certificate is young still, the 'Smartscreen' displays its warning. You can safely ignore it.

More info on how to work around Smartscreen 'protection':
https://windowsreport.com/unsafe-download-was-blocked-smartscreen/

You can also just a normal browser to download Duplicati instead of Edge. Edge is the only browser interfacing with Smartscreen to display these warnings.

More info on Smartscreen rating:
https://blog.goodsol.com/2017/10/microsoft-smartscreen-file-not-commonly-downloaded.html

**Comment by georgfranz** [comment]
Hi,

thanks for info!

Best,
Georg.
