### ISSUE TITLE
The request was aborted: Could not create SSL/TLS secure channel.

### ISSUE THREAD

**Issue by fouvry** [duplicati/duplicati#4979]
- [ x] I have searched open and closed issues for duplicates.
- [ x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.7.1_beta_2023-05-25
- **Operating system**: Windows 10 Pro 22H2 B 19045.2965
- **Backend**: WebDAV

## Description

Since a week, I get the error message 
```The request was aborted: Could not create SSL/TLS secure channel.```

Through other applications (Windows app, Android app), the secure connection is working.

## Steps to reproduce
(No idea how)

## Debug log

I'm happy to provide any log info, but I wouldn't know what would help.  On 13 June, there are exceptions in the dynamic address resolution of my nextcloud server, but the ssl/tls issue only started happening on 17 June, and after 13 June, dyndns updates seemed to be happening regularly. I could not find anything that looked relevant in the other log files.

**Comment by gpatel-fr** [comment]
Hello

Thanks for the report, however Nextcloud is not a backend for Duplicati: there is no specific driver for Nextcloud, so you must be using a supported backend (driver) to access your system, but it's not clear which one from your post. Please add this information.

About the SSL/TLS problem, there were already some problem reports with 2.0.7 because it is enabling TLS 1.3 in some cases, while the OS is supporting it but not quite correctly. Normally this only concerns Windows 11, but who knows what Microsoft could throw into updates ? Even if it's a long shot, maybe you could try to force the SSL level to 1.2 in Duplicati (--allowed-ssl-versions).

**Comment by fouvry** [comment]
I've corrected the backend information.

But your suggestion made it work. I'm very happy that the backup is working again. Thank you!
