### ISSUE TITLE
[feature request]  Add Shortcut to Manual to About or Footer of Homepage

### ISSUE THREAD

**Issue by wiewowas** [duplicati/duplicati#4981]
- [x] I have searched open and closed issues for duplicates.
- [x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**:  2.0.7.1_beta_2023-05-25
- **Operating system**: Windows
- **Backend**: not relevant

## Description
I noticed that there is no direct link to the manual in the user interface and I think adding it would improve the usability.

For me I returned to using Duplicati after a 1-2 year break. When starting duplicati again I had to first go to the github page, find README and follow the link to the manual there. Googling probably would have been quicker. I think adding a link to the manual somewhere at the bottom of the page or at least in the about section (which was the second place that I checked) would be a nice improvement, especially for inexperienced users.

**Comment by Jojo-1000** [comment]
This is what I can do without hacking around in the stylesheet:

Mobile:
![Screenshot mobile](https://github.com/duplicati/duplicati/assets/33495614/e2f48584-f650-4b38-9e32-19cf79655792)


Desktop:
![Screenshot desktop](https://github.com/duplicati/duplicati/assets/33495614/6e9cf90e-5601-4421-82b6-f54bbb8b03fc)

The top padding is a bit off on mobile, but otherwise I think it is okay. Still needs translations for other languages.
