### ISSUE TITLE
Why  the backup sources cannot  be  FTP, Cloudfiles, WebDAV, SSH (SFTP), Amazon S3 and others ?

### ISSUE THREAD

**Issue by shyding** [duplicati/duplicati#4986]
- [x] I have searched open and closed issues for duplicates.
- [x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: 0.0.0.0
- **Operating system**: Replace me
- **Backend**: Replace me

## Description

Replace me

## Steps to reproduce

1. Replace me
2. Replace me
3. ...

- **Actual result**:
Replace me
- **Expected result**:
Replace me

**Comment by shyding** [comment]
Just like  rsync  both sources and destions can  be remote or local

**Comment by Jojo-1000** [comment]
The program is meant to be used on the system where the files are. There are considerations for uploading to a remote destination, for example retrying the upload. The source is always assumed to be available, so if there are connection issues this can cause errors or hangups (even for Samba shares over LAN).
The way it is designed, I don't think this will change in the future.

You can search the [forum](https://forum.duplicati.com/) for other people who might have done something similar to your use case, or open a thread there for support and ideas, if you are willing to go into more detail.

**Comment by ts678** [comment]
> Just like rsync

It's not rsync. It's asymmetrical by design, with source examined and recorded in high detail. Destination side has minimal asks:

[Developer documentation](https://github.com/duplicati/duplicati/wiki/Developer-Documentation)

> The backends encapsulate the actual communication with a remote host with a simple abstraction, namely that the backend can perform 4 operations: GET, PUT, LIST, DELETE. All operations performed by Duplicati relies on only these operations, enabling almost any storage to be implemented as a destination. If no verification is required, Duplicati can perform backups with only the PUT method.

This combination allows the widest possible set of destinations. Source side is coded around specifics of Windows and UNIX-like systems. Source side is accessed as files, including sequential backup reads, and [random seeks on restore](https://github.com/duplicati/duplicati/blob/master/Duplicati/Library/Main/Operation/RestoreHandler.cs). Destinations lack that. Duplicati uses them as a single folder level (which unfortunately might hit a destination file limit...), whereas source is multi-level. Duplicati's idea of destination capabilities is more like the minimal set that object storage uses rather than the richer file storage.

[Rclone](https://rclone.org/) would be an even better example of a data-location-flexible file-content sync tool. Duplicati is destination-flexible backup. [rclone mount](https://rclone.org/commands/rclone_mount/) can sort of make a non-file-oriented storage look like local files, but speed and quality might suffer in translation...

**Comment by gpatel-fr** [comment]
Hello

as explained, it's not an issue, it is a feature.

**Comment by ts678** [comment]
History of the Duplicati 2 design approach is found in [Block-based storage engine](https://www.duplicati.com/articles/Storage-Engine/) and
[A block based storage model for remote online backupsin a trust no one environment](https://www.duplicati.com/assets/Block-basedstorageformat.pdf)

[How the backup process works](https://duplicati.readthedocs.io/en/latest/appendix-a-how-the-backup-process-works/) and [How the restore process works](https://duplicati.readthedocs.io/en/latest/appendix-b-how-the-restore-process-works/) explain current very block oriented design, which is awkward at best when what is being backed up and restored is remote BLOBs rather than local files. Sloshing BLOBs back and forth might be a workaround, but you can do that yourself in a more graceful way than Duplicati can, e.g. if you rsync or rclone remote to local, then Duplicati can back up local files, and you enjoy block-based space savings of multiple versions which sync programs don't provide...

[Overview](https://duplicati.readthedocs.io/en/latest/01-introduction/#overview) in the manual introduction says:

Duplicati is **not**:
   **A file synchronization program.**
   Duplicati is a block based backup solution.

The `Features` section below that is also worth a read. That highlights some of the backup-specific features that Duplicati provides. There's enough of a challenge trying to be a decent backup program. Being all possible things one might wish isn't likely to happen because development and runtime resources are finite and a design focus is sometimes a good thing. Use the right tool(s) for a job.

If you have a specific use case, and can't find existing suggestions on the forum, feel free to open a topic there to seek suggestions.
