### ISSUE TITLE
Backup size is not reduced with source size

### ISSUE THREAD

**Issue by fwh-dc** [duplicati/duplicati#5070]
- [x] I have searched open and closed issues for duplicates.
- [x] I have searched the [forum](https://forum.duplicati.com) for related topics.

## Description

I have tried to limit the set of files for a backup to reduce the disk usage. However it seems like the change does not change the backup size:

Duplicati reports:

Source:603.71 MB
Backup:213.35 GB / 22 Versions

The change of the number of source files was made a long time ago so it should not be included in the 22 versions.

Is there a way to cleanup backup of files from folders that are no longer part of the backup job? Alternatively can I somehow reset the full backup and start from scratch without setting up the backup job from scratch?

Please let me know if something is unclear.

**Comment by drwtsn32x** [comment]
A change in retention won't be applied until the next time the backup runs.  Have you kicked off the backup job since then?  There is a way to simply delete versions using the command line but it's more complex than just kicking off a backup job.

If you do want to "start over" without recreating the backup job, simply delete the back end files so that the destination is empty, and then delete the local database for the backup job.  (Click on the backup job name in the web UI to expand options, click the blue "Database" link, then click the "Delete" button.)  Next time you run a backup job, Duplicati will behave as if it's the first backup job since both the database and the back end are empty.  The stats will be updated after the job completes.

**Comment by ts678** [comment]
Is this a change in retention or having less source, for example by unchecking things (GUI) or removing from commandline list?

> The change of the number of source files was made a long time ago so it should not be included in the 22 versions.

Can you confirm the "should" with a look in the oldest version? Was the reduction large, and with files not duplicated in source?

Small amounts of wasted backup space are left alone by default, as compact's threshold is 25%, but [compact has many options](https://duplicati.readthedocs.io/en/latest/04-using-duplicati-from-the-command-line/#the-compact-command).
If you want to see how close you are, you can set up About --> Show log --> Live --> Information and push `Compact` button.

**Comment by fwh-dc** [comment]
>(Click on the backup job name in the web UI to expand options, click the blue "Database" link, then click the "Delete" button.) 

I tried to do run Recreate of the database, but it didn’t fix anything. In general this database stuff is not super user friendly imo. I am missing the "Reset backup" option to delete all remote and local backup files.

> Is this a change in retention or having less source, for example by unchecking things (GUI) or removing from commandline list?

I did the change through the GUI.

So eventually I found a workaround:

Run “Compact now” from the gui. This job will take forever (I’m not sure if it will ever succeed). And after a while restart the computer (to stop duplicati). 
Then on the next backup run Duplicati will fail saying that there are files missing from remote storage (2000 in my case). Then run Repair as the error message suggests.

Now on the next backup run Duplicati reports: 

Source:
1.54 GB
Backup:
4.28 GB / 23 Versions

So to me it seems like there are some sync issues that are not caught until “Compact now” is run.

**Comment by ts678** [comment]
> I tried to do run Recreate of the database, but it didn’t fix anything.

Recreate is not a compact. If the concern is destination space, recreating the database changes database, not the destination.

> Run “Compact now” from the gui.

This is still subject to the documented compact option settings. Please make sure you didn't turn [no-auto-compact](https://duplicati.readthedocs.io/en/latest/06-advanced-options/#no-auto-compact) option on, because that would be consistent with a GUI compact helping while [Compacting files at the backend](https://duplicati.readthedocs.io/en/latest/03-using-the-graphical-user-interface/#compacting-files-at-the-backend) normal behavior did not.

> And after a while restart the computer (to stop duplicati).

This is a bad idea, especially while doing sensitive operations like compact. There's at least one bug fixed in next release where interrupted compact deletes dindex files then loses that information in a database transaction rollback due to the interruption. Possibly this is what you saw, but 2000 files is a lot. Did the recovery Repair have any complaints after it had finished running?

> So to me it seems like there are some sync issues that are not caught until “Compact now” is run.

I wouldn't call it a sync issue, but make sure you didn't disable automatic compact, as that would create a space growth issue.
There are actually log files that can record compact (or lack thereof) status very closely, but most people don't keep such logs.

**Comment by fwh-dc** [comment]
> This is still subject to the documented compact option settings. Please make sure you didn't turn [no-auto-compact](https://duplicati.readthedocs.io/en/latest/06-advanced-options/#no-auto-compact) option on, because that would be consistent with a GUI compact helping while [Compacting files at the backend](https://duplicati.readthedocs.io/en/latest/03-using-the-graphical-user-interface/#compacting-files-at-the-backend) normal behavior did not.

Aha this is interesting. I do have [no-auto-compact] turned on. I'm not sure why tbh. I don't understand why the source and destination size would differ in any case?

> This is a bad idea, especially while doing sensitive operations like compact.

Well it seemed to make no progress (been running for 3-4 hours) so I figured there was no other option. But the Repair didn't complain. Neither have succeeding backups. So I guess that everything is alright.

**Comment by ts678** [comment]
> Aha this is interesting. I do have [no-auto-compact] turned on. I'm not sure why tbh.

I certainly can't say, but some people do complain about the extra time that the compact occasionally throws into a backup run. Disabling auto compact just causes the space usage to grow until finally someone does a manual run and spends the time then.

> Well it seemed to make no progress (been running for 3-4 hours) so I figured there was no other option.

It seems to have done a lot. A good activity check would have been About --> Show log --> Live --> Information. Too late now.

> But the Repair didn't complain. Neither have succeeding backups. So I guess that everything is alright.

Maybe. As always, test your backup too, e.g. with at least some sample Restore work. Even better, simulate [full disaster recovery](https://duplicati.readthedocs.io/en/latest/03-using-the-graphical-user-interface/#restoring-files-if-your-duplicati-installation-is-lost).

[Error during compact forgot a dindex file deletion, getting Missing file error next run. #4129](https://github.com/duplicati/duplicati/issues/4129#issuecomment-1426864874) is what you might have hit. I wrote:

> The good news is that Repair fixes it by uploading both dindex files that it forgot it deleted.
But the bad news is it's a pointless file with only the manifest file in it

So if you can sort your destination files by size, then spot 2000 unusually small (but harmless) dindex files, that's the reason why.

> I don't understand why the source and destination size would differ in any case?

[Introduction](https://duplicati.readthedocs.io/en/latest/01-introduction/) section of User Manual has a variety of reasons. It's not a sync (where size would be the same) or full copies (where size would multiply by the number of versions.). It uploads changes as necessary (unlike copy). There's also some reduction from compression, but (unlike full copy), deleting old versions can't do full file deletes because new backups reuse data from old ones. People see old files and complain, but if the data in them is still used by source files still in the backup, the old files are still useful.

As files change and get so old that version retention removes them, waste accumulates and is periodically removed by compacts, however disabling automatic compact means you have to do it manually. If you prefer automatic, remove the disable and watch.

To see if your interrupted manual compact had some leftover work, you can set About --> Show log --> Live --> Verbose and request a manual compact to view if it finds any work to do. An example Verbose output (Information level says less) would be:

```
Dec 19, 2023 8:48 AM: The operation Compact has completed
Dec 19, 2023 8:48 AM: Compacting not required
Dec 19, 2023 8:48 AM: Found 25 volume(s) with a total of 9.09% wasted space (1.07 GB of 11.76 GB)
Dec 19, 2023 8:48 AM: Found 1 small volumes(s) with a total size of 2.37 MB
Dec 19, 2023 8:48 AM: Found 0 fully deletable volume(s)
Dec 19, 2023 8:48 AM: The operation Compact has started
```

and per my settings for compact, there's nothing needed. If you want, you can set a log file, but you can also just watch space.

**Comment by fwh-dc** [comment]
Thanks for taking the time to explaining the different concepts. I'll be turning on auto-compress from now on.

I'll close the issue as it seems like it works as intended.
