### ISSUE TITLE
Large uploads of .aes files get flagged as possible ransomware by Microsoft

### ISSUE THREAD

**Issue by cakeforcat** [duplicati/duplicati#5089]
- [x] I have searched open and closed issues for duplicates.
- [x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.7.1_beta_2023-05-25
- **Operating system**: Windows 11 22621.3007
- **Backend**: Onedrive v2

## Description

I am using a university provided Onedrive as a backup and have had my account temporarily suspended recently. This it turns out was caused by a big upload of .aes files (my duplicati backup) under suspicion of ransomware. I had the issue resolve, but an option for maybe alternative extensions for the uploaded files would be beneficial to avoid false positives like this?

## Steps to reproduce

Upload AES encrypted backups to a business Onedrive v2 backend

- **Actual result**:
.aes gets flagged as possible ransomware
- **Expected result**:
no false positive flag

**Comment by ts678** [comment]
> an option for maybe alternative extensions for the uploaded files would be beneficial to avoid false positives like this?

Good question to research. Microsoft probably won't reveal all their methods, but here are some comments about that:

[Handling ransomware in Sharepoint Online](https://learn.microsoft.com/en-us/sharepoint/troubleshoot/security/handling-ransomware-in-sharepoint-online) says ransomware may add an unknown file extension. Will yours get noted?

[OneDrive Signs of Ransomware Detected Email](https://answers.microsoft.com/en-us/msoffice/forum/all/onedrive-signs-of-ransomware-detected-email/def8d72a-1a55-4235-9fca-e77d628f291c) says Cryptomator cryptic names set it off. Below, discussion was cut off:

[Cryptomator files detected as ransomware](https://answers.microsoft.com/en-us/msoffice/forum/all/cryptomator-files-detected-as-ransomware/9e507054-ad77-4c24-8f38-7b8ad7852fdf) but in doing so, it did provide some info on how to reach OneDrive Support.

Microsoft has a lot of products, some document ways around this, but I don't know which pages apply in your situation.
Possibly your university administrators know their systems (one would hope...), and can suggest what works (or doesn't).

I'll label this as `enhancement` even though I'm not certain it helps. Please update if you get any nice information on that.

**Comment by cakeforcat** [comment]
To quote the cybersecurity team member that gave me the details on my situation 
> The behavior in question was specifically the uploading of 96 files with the file extension .aes to your Onedrive
So it seems to be a combination of a large upload and the .aes file extension, at least in my situation.

**Comment by gpatel-fr** [comment]
@ts678 
I don't agree on calling such a change an enhancement. File extensions are in a sane world a normal way of file management, so it's not unreasonable to hard code a AES encrypted file extension as '.aes', while using a file extension as a security measure is not sane. Making a file extension a parameter to cater to this way of thinking is useless work IMO and lead to unnecessary code complexity and options.

@cakeforcat 
It seems that you have 2 possibilities to not use aes extension with current Duplicati:

* not encrypting files
* using the custom encryption as gpg
Note that I don't remember having seen anyone posting on the forum about gpg encryption, so it's not used frequently at all and could be broken. OTOH if gpg does not work for you, this could be considered as a bug since its use is documented.

Is that enough for you ?

**Comment by ts678** [comment]
> I don't agree on calling such a change an enhancement.

I sure wasn't going to label it as a `bug`. Adjust as you like. This seems a rare but real problem (so far -- but I think not the first).

**Comment by ts678** [comment]
Rather than have this become a rejected `enhancement`, I changed label to `question` -- basically a short-lived support question.

> It seems that you have 2 possibilities

Third is rclone crypt. You may have to [install rclone](https://rclone.org/downloads/), but same may hold if you use gpg, plus `.gpg` extension indicates encryption.
The crypt work of rclone is invisible to Duplicati. Here is what Duplicati thinks it sees in a small test backup, then I show Explorer's:

![image](https://github.com/duplicati/duplicati/assets/40771998/15b835cb-85f7-4f6e-b013-7230d36b4943)

![image](https://github.com/duplicati/duplicati/assets/40771998/ca1627db-3e40-4aa6-b0ed-85704d30e3bb)

Explorer isn't certain what it got, and right-click gets an offer from my installed program to `AES Encrypt` it (not knowing it is...).
Duplicati's installed SharpAESCrypt.exe utility doesn't notice the odd extension, and can decrypt file successfully into a `.zip` file.

Having to go through all this stuff to try to bypass some ransomware false positive in OneDrive is annoying, and maybe will fail.
Actual ransomware is very variable in its extensions. Some systems might also try looking inside the file, not just going by name.
[Ransomware encrypted file extension list
File extensions used by various ransomware that rename the original suffix after the files are encrypted.](https://www.file-extensions.org/filetype/extension/name/ransomware-encrypted-files)

[Disguise filename in order to protect from removal by Cloud Providers #3061](https://github.com/rclone/rclone/issues/3061) in rclone forum has comments about the problem.

I used a `crypt` advanced option `Don't encrypt file data, leave it unencrypted`, but you can encrypt (or not) as you like.
There are also more severe filename obfuscation options that make things very unrecognizable, but that may slow support work.
Somebody might start asking about `dlist` `dindex` or `dblock` files, and it would be nice if you could still see that in the name.

```
C:\>\bin\rclone config show cryptlocal
--------------------
[cryptlocal]
type = crypt
remote = local:
filename_encryption = off
directory_name_encryption = false
password = *** ENCRYPTED ***
no_data_encryption = true
password2 = *** ENCRYPTED ***
--------------------
```

This was built on top of an old rclone remote called `local`, but in your use you might [set up OneDrive](https://rclone.org/onedrive/) then wrap it with `crypt`.

![image](https://github.com/duplicati/duplicati/assets/40771998/5d39ecd7-f2b5-4a26-9fa2-b9a6c2a3d041)

and for note at end above, use Advanced options on Options screen.5, because Destination screen 2 is buggy (a PR is in queue).

Easiest solution is if you're willing to put unencrypted files up (if that helps), otherwise there are two awkward workarounds here.

You might also try consulting your IT people further. Maybe they can put you or your filename styles on some sort of a whitelist.

Will one of these several options do?

**Comment by cakeforcat** [comment]
>You might also try consulting your IT people further

This is by far the easiest solution for me, and something I already did. I didn't want this to be just about my situation, but to discuss the potential issue in general.
If we're willing to just accept it as some sort of extremely rare scenario/Microsoft being too overprotective, then that's fine by me.
