### ISSUE TITLE
Not working anymore auth_username ignored OpenStack v3 Infomaniak  (2.0.8.1_beta_2024-05-07)

### ISSUE THREAD

**Issue by ericjamesbye7** [duplicati/duplicati#5188]
- [x] I have searched open and closed issues for duplicates.
- [x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.8.1_beta_2024-05-07
- **Operating system**: Windows 11 23H2
- **Backend**: Infomaniak

## Description
Using Duplicati 2.0.7.1 with Infomaniak without issues.
**Process**: always using the user and password provided by Infomaniak
**After the update**, I wanted to change the filters and now it seems Duplicati is not able to save auth-username and auth-password anymore. Testing connextion displays **_"Failed to connect: Missing required option: auth-username"_**. I've decided to add the missing fields in _Advanced options_ but the test cx replies _(502) invalid gateway_.
**Please note**

- if I use the command line (from a backup config file), everything is OK
- if I use OneDrive with token, everything is OK

## Steps to reproduce
1. upgrade from  2.0.7.1 to 2.0.8.1_beta
2. Just edit the Backup task and go on Test connexion: failed.

- **Actual result**:
The connection is KO (according to the process I've described)
- **Expected result**:
The connection should be OK, ofc

## Debug log
Where are the logs ?
Nothing in %LOCALAPPDATA%\Duplicati

Thank you for your investigation

Best regards
EJB

**Comment by Jojo-1000** [comment]
Can you provide more information about the backend type (what is selected in the GUI)? You can also try to export the URL and see if the options are there. That is in the dot menu for the destination. It should match what you have in your backup config.

This might be related to #4972, but only if your path has backslashes.



> I've decided to add the missing fields in _Advanced options_ but the test cx replies _(502) invalid gateway_.

If you add the advanced options in Step 5, the Step 2 test command doesn't use it. You could still try a verify from the main backup list to see if it works.

**Comment by ericjamesbye7** [comment]
Hello Jan

Please find the 2 ScS below.
Note, on the 2nd one, the input name/id is not auth_username but openstack_username. Is it logical ? (just for my information).
About the export, the main difference between my old working save confFile and the new KO one is in the field **_TargetURL_**.
The url parameters **_&auth-username=blabla_** and _**&auth-password=bla-blabla**_ are missing.

Thanks
Best regards
EJB

![duplicati_issues_5188-00](https://github.com/duplicati/duplicati/assets/58696705/a6d669a2-ea24-49dc-9f64-5368f3b57df1)
![duplicati_issues_5188-01](https://github.com/duplicati/duplicati/assets/58696705/c88c2581-75ab-4140-bcf9-7534f8dc567a)

**Comment by Jojo-1000** [comment]
The input fields are fine. The relevant part is `ng-model="$parent.Username"` which will bind the value to the internal variable.

I see what went wrong. In #4973 I fixed an issue that the username and password were added in backends where there are no input fields for it. So, there is a choice whether it should include them. It seems that I missed that the openstack backend has those fields and put in the wrong type.

https://github.com/duplicati/duplicati/blob/0d6e9487d7d58dc32fce35150c70dafc34ebe2ad/Duplicati/Server/webroot/ngax/scripts/services/EditUriBuiltins.js#L731

should be `true` instead of `false`.

I am not sure how long a fix will take to be released, since there is currently some work on changing the .NET version. For right now, if you are able to use the browser developer tools you can temporarily fix this to save the backup correctly:

- Go to the Sources tab
- Find `ngax/scripts/services/EditUriBuiltins.js`
- Change line 731 (see above) to 
  ```
  EditUriBackendConfig.merge_in_advanced_options(scope, opts, true);
  ```
- Save the file with Ctrl+S. Do not reload the page until you saved the configuration
- Edit the backup and save it. Test connection should also work
