### ISSUE TITLE
how to do full backups？

### ISSUE THREAD

**Issue by xuze1993** [duplicati/duplicati#5228]
Is there a way to perform a full backup instead of an incremental backup? I tried setting the version number to the minimum value of 1, but it's still doing incremental backups. Because I have a large number of files, after the initial full backup is created, the subsequent scheduled automatic backups will inevitably cause the machine to freeze when analyzing files, even if I limit the CPU usage.

**Comment by Jojo-1000** [comment]
All duplicati backups are incremental by design, there is no way to change this.

You can also look at the forum discussion here:
https://forum.duplicati.com/t/full-backups-instead-of-compressed/3113

For the freezes, you don't provide enough information to help you. If you only want one version, a file sync tool might be more what you want.

For help with your setup, rather than bug reports, the forum is preferred.

**Comment by ts678** [comment]
No forum topic AFAIK. Anything else here?

[Introduction](https://docs.duplicati.com/en/latest/01-introduction/) in the manual explains what Duplicati is (and is not).
