### ISSUE TITLE
Source code for MacOs app

### ISSUE THREAD

**Issue by eox2** [duplicati/duplicati#5340]
Hi 

I'm looking for the source code for the Mac OS app. I don't see it in the repository.

Thanks

**Comment by ts678** [comment]
> I don't see it in the repository.

What were you expecting to see?

[https://github.com/duplicati/duplicati](https://github.com/duplicati/duplicati) shows language breakout of:

![image](https://github.com/user-attachments/assets/9c54d557-a73a-47b4-b5d9-40db3e0d4089)

means most of the code is portable between the operating systems.

If there's some special area you're seeking, dev help may be needed.

**Comment by kenkendk** [comment]
@eox2 I am guessing that you are looking for the binaries that are in 2.0.8.1.
Since that version was released, we removed the launchers in favor of .NET8's native binaries.
The launchers that were needed for Mono support are in the branch prior to the .NET8 switch:
https://github.com/duplicati/duplicati/tree/release/v2.0.8.1_beta/Installer/OSX/launchers
