### ISSUE TITLE
Duplicati warns it cannot backup its own lock file(s) when Application Settings backup is enabled

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#635]
_From [dougb...@gmail.com](https://code.google.com/u/116476123202539832050/) on May 30, 2012 06:23:28_

What steps will reproduce the problem? 1. Set up a backup for Application Settings What is the expected output? What do you see instead? A backup What version of Duplicati are you using? On what operating system? 1.3.1.1205 on two Win7 machines and an XP SP3 machine What backend (destination) are you using? SSH Please provide any additional information below. This may not even be a bug, but I have set up Duplicati on these three machines for testing and without any changes to the scan list I always get a warning that it could not backup Duplicati's lock file(s).  In each installation I've had to add "...\Duplicati\control_dir\" to the list of excluded folders to scan.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=635_
##

**Comment by ts678** [comment]
> 1.3.1.1205

Duplicati 1.3.x has been unmaintained for years. There apparently used to be an "Include application settings" config option, by:

https://github.com/duplicati/duplicati/blame/30c7de2e293b3b18a4b439750afa9acaf7993d30/Duplicati/GUI/Wizard%20pages/Add%20backup/SelectFiles.resx#L321-L323

The Duplicati 2 version of this issue seems to be [Duplicati tries, and fails, to backup its own locked files #1757](https://github.com/duplicati/duplicati/issues/1757) which is still open.

This issue will close eventually, if it stays idle.
