### ISSUE TITLE
Mega support

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#806]
_From [arjanmos...@gmail.com](https://code.google.com/u/100174058931254366165/) on January 20, 2013 17:16:02_

The Mega ( https://mega.co.nz ) service recently launched, and support for this hosting would be awesome. Both the 50 GB free version and the pricing of paid packages is very attractive.

Is their storage and client-side encryption model compatible with Duplicati?

Note: "In the near future, we will provide reference client libraries/SDKs for various programming languages. For now, our JavaScript site code is the only sample code available" << https://mega.co.nz/#developers

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=779_

**Comment by kenkendk** [comment]
I found a better API:
https://github.com/gpailler/MegaApiClient

**Comment by HennieRoets** [comment]
Hi kenkendk,

may I ask for your help please. I'm not familiar with github ect. Was using Duplicati with Google docs login, but not working anymore as you know. I still prefer the old version before 2 because it has the test selection feature. You created a way for Duplicati to authenticate, does that work in version 1.3.4 as well? Otherwise can Duplicati 1.3.4 log into mega at this stage?

Here is the whole idea, is to upload backups to a folder online that does NOT sync with your pc. So that when ransomware viruses infect me, the online folder is not infected because it is not synced.

Please help, I would really appreciate it and donate the moment I can.

**Comment by kenkendk** [comment]
"Google Drive" is the name of the Google file storage, you do not have to sync if you don't want to (i.e. it is the same as Google Docs in that regard).

1.3.x does not work with the new stuff because it would require some minor changes which I do not have the time to do. The source is still there if anyone wants to do the build with the new backends.

I have on my TODO list to improve the folder input dialog. It is currently in a "minimally viable" state.

I am looking into the Mega storage method, but it does not work right now. I will not port it to 1.3.x once it works.

**Comment by HennieRoets** [comment]
Hi,

thank you very much for the reply. Your 1.3 is still amazing!!!

Thanks again for your hard work
