### ISSUE TITLE
Unicode file name support

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#81]
_From [Col...@gmail.com](https://code.google.com/u/104596042515694179283/) on June 14, 2009 08:41:23_
- What steps will reproduce the problem?
- Backup files with unicode or non-ASCII characters in the file name.

There are two problems when files have unicode file names. One problem is
that when the file is restored from the backup the file name will be
different from the original file or the file will not be restored at all in
some cases. For example: "João.txt" becomes "Joao.txt". The file "你好
Hello.txt" fails to be restored. 

The other problem is that because the file name stored in the backup does
not match the original file name on the file system Duplicati will treat
the file as a new file at every backup interval. It will delete the file in
the backup and copy the original to the backup as a new file. 
- What version of the product are you using? On what operating system?

Version 1.0 on Windows
- Please provide any additional information below.

Attached is a file with a few sample files that I used to test this. This
zip file was created with 7Zip as many other zip programs do not adequately
support unicode file names.

**Attachment:** [TestFiles.zip](http://code.google.com/p/duplicati/issues/detail?id=81)

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=81_

**Comment by jvandenbroek** [comment]
Sorry to react on this old issue, but I think it's back again? I'm on version 2.0.2.13_canary_2017-11-22. The following warnings (which are actually errors?) occur with filenames like this:
 ```
Error reported while accessing file: /backup/M篥redskaber => Could not find file "/backup/M篥redskaber",
    Failed to process path: /backup/M篥redskaber/ => Path doesn't exist!,
```
All files containing non-ASCII chars fail and there are quite a lot of them unfortunately... The source of these files is Windows, so I guess they need to be encoded in ANSI instead of UTF-8? Maybe an per backup option could be added to set the encoding? Thanks!
