### ISSUE TITLE
Backup should be auto-repaired when files got deleted on target

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#937]
_From [andreas....@gmail.com](https://code.google.com/u/111010105257425906577/) on November 22, 2013 10:26:05_

What steps will reproduce the problem? 1. Do a normal backup [CommandLine 2.0]
Duplicati.CommandLine.exe backup D:\TEMP D:\ImportantData --passphrase=Whhhoho

Everything works fine, second Backup without changes is also fine ,...
1. delete one or more of the *.dblock.zip.aes files 
2. try next backup with same parameters (like it will happen with a cron-job on a NAS)

What is the expected output? 

Duplicati should recognise the missing files and upload/copy the data again.

I think duplicati should do everything possible to guarantee a safe backup (without doing a manual repair or so). In my case, the original data (source) is still there, so a repair-during-backup should be simple. 

What do you see instead?

I got this:

Duplicati.CommandLine.exe backup D:\TEMP D:\ImportantData --passphrase=Whhhoho
Backup started at 22.11.2013 09:31:56
Checking remote backup ...
  Listing remote folder ...
Missing file: duplicati-bab5e5626b2324bd5ba27bc0582ba9dde.dblock.zip.aes
Found 1 files that are missing from the remote storage, please run repair
Fatal error => Found 1 files that are missing from the remote storage, please run repair

Found 1 files that are missing from the remote storage, please run repair

and....

Duplicati.CommandLine.exe repair D:\TEMP

Enter passphrase: *******
  Listing remote folder ...
Repair cannot acquire 230 required blocks for volume duplicati-bab5e5626b2324bd5
ba27bc0582ba9dde.dblock.zip.aes, which are required by the following filesets:
duplicati-20131122T083017Z.dlist.zip.aes
This may be fixed by deleting the filesets and running reapir again
Failed to perform cleanup for missing file: duplicati-bab5e5626b2324bd5ba27bc058
2ba9dde.dblock.zip.aes, message: Repair not possible, missing 230 blocks!!! => Repair not possible, missing 230 blocks!!!

btw: there is a typo "reapir" What version of Duplicati are you using? On what operating system? 2.0 on Windows XP What backend (destination) are you using? all file-based Please provide any additional information below. 1) I didn't manage to reactivate the backup, not even with repair.

2) Isn't this testcase the same as checking the integrity of existing blocks in the destination? 
=> One block is corrupt, so upload it again (the new feature in 2.0)
=> One block is missing (or a whole dblock file), so upload it again.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=910_
##

**Comment by Aaron-Ritter-IDEXX** [comment]
Alerts (email?) when there's any sort of fault with the storage are definitely desirable. I'd hate to think my storage could start failing but I wouldn't be notified. Notifications when backups complete successfully... eh, probably desirable as an option, at least. Ideally I'd rather know if I **don't** get a successful backup on schedule, but if the reason is that the service isn't running, it's hard to send a notification.

Are there any situations in which attempting to repair the backup set by writing more data could make it worse? A failing hard disk or SSD? It probably doesn't matter. In any case it's usually a higher priority to backup the user's current data than to protect the old backup. So let it automatically repair/replace as needed while alerting the user that something's going wrong.

I think I'd prefer that it not try to guess at an appropriate level of redundancy, but if you do have options for the level of redundancy then you can suggest to the user they might want to increase it. If you've got multiple degrees of redundancy to choose from, they should scale from "none" up to whatever's reasonable. What the user should use is partially dependent on their choice of storage. If it's S3 or a well designed ZFS pool, there's really no need to have Duplicati 2 adding its own layer of redundancy. If it's merely an external disk or a friend's computer in another house, a fairly high level would be appropriate.

**Comment by kenkendk** [comment]
The "purge-broken-files" command now fixes this.

@Aaron-Ritter-IDEXX I have another solution waiting for the "backup stops running" situation.
